---
title: "PAM data preliminary"
output: html_notebook
---


```{r}
library("knitr")
require("knitr")
opts_knit$set(root.dir = "C:/Users/carol/Documents/PhD Boston University 2019-/Chapter_2_Ecotox/Summer_2022_N_Ecotox")
setwd("C:/Users/carol/Documents/PhD Boston University 2019-/Chapter_2_Ecotox/Summer_2022_N_Ecotox")
getwd()
pam_all.data <- read.csv("PAM_summer_all_10_24_22_0_20C_outlier_deleted_11_9_22.csv", header=TRUE, sep=",",stringsAsFactors = FALSE)
```


```{r BASIC - Master list of subsets}
# all aposymbiotic
all_apo<-subset(pam_all.data, pam_all.data$sym_state=="A")
# all symbiotic
all_sym<-subset(pam_all.data, pam_all.data$sym_state=="S")
# all fed
all_fed<-subset(pam_all.data, pam_all.data$food=="F")
# all starved
all_starved<-subset(pam_all.data, pam_all.data$food=="S")
# all 20C
all_20<-subset(pam_all.data, pam_all.data$temp=="20")
# all 30C
all_30<-subset(pam_all.data, pam_all.data$temp=="30")
# all nitrate (taking out controls)
all_nitrate<-subset(pam_all.data,pam_all.data$N_species=="N" & pam_all.data$N_dose!="0")
# all ammonium (taking out controls)
all_ammonium<-subset(pam_all.data,pam_all.data$N_species=="A" & pam_all.data$N_dose!="0")
# all controls 30C
control_all_30<-subset(pam_all.data, pam_all.data$N_dose=="0" & pam_all.data$temp=="30")
# all controls 20C
control_all_20<-subset(pam_all.data, pam_all.data$N_dose=="0" & pam_all.data$temp=="20")
```


```{r Nitrate/Ammonium LEVELS - Master list of subsets}
# Ammonium HIGH (10uM) 20C
A_10_20<-subset(pam_all.data, pam_all.data$N_dose=="10" & pam_all.data$temp=="20")
# Ammonium HIGH (10uM) 30C
A_10_30<-subset(pam_all.data, pam_all.data$N_dose=="10" & pam_all.data$temp=="30")
# Nitrate HIGH (18uM) 20C
N_18_20<-subset(pam_all.data, pam_all.data$N_dose=="18" & pam_all.data$temp=="20")
# Nitrate HIGH (18uM) 30C
N_18_30<-subset(pam_all.data, pam_all.data$N_dose=="18" & pam_all.data$temp=="30")
# Nitrate HIGH (18uM) 30C AND control 30C
N_18_and_control_30<-subset(pam_all.data, pam_all.data$N_dose==c(0,18) & pam_all.data$temp=="30" & pam_all.data$N_species=="N")
# Ammonium HIGH (10uM) 30C AND control 30C
A_10_and_control_30<-subset(pam_all.data, pam_all.data$N_dose==c(0,10) & pam_all.data$temp=="30" & pam_all.data$N_species=="A")

```


```{r T tests}
#controls 20 v 30
t.test(control_all_20$PAM_avg_day11, control_all_30$PAM_avg_day11)
#control v N18 30
t.test(control_all_30$PAM_avg_day11, N_18_30$PAM_avg_day11)
#control 20 v N18 30
t.test(control_all_20$PAM_avg_day11, N_18_30$PAM_avg_day11)

#control v N18 20
t.test(control_all_20$PAM_avg_day11, N_18_20$PAM_avg_day11)
#control v A10 30
t.test(control_all_30$PAM_avg_day11, A_10_30$PAM_avg_day11)
#control v A10 20
t.test(control_all_20$PAM_avg_day11, A_10_20$PAM_avg_day11)


#overall fed vs starved
t.test(all_fed$PAM_avg_day11, all_starved$PAM_avg_day11)

#overall nitrate vs. ammonium
t.test(all_nitrate$PAM_avg_day11, all_ammonium$PAM_avg_day11)
```

```{r Comparing results to Laura}
fed_ammonium_high_30<-subset(pam_all.data, pam_all.data$food=="F" & pam_all.data$N_dose=="10" & pam_all.data$temp=="30")
fed_ammonium_high_20<-subset(pam_all.data, pam_all.data$food=="F"&  pam_all.data$N_dose=="10" & pam_all.data$temp=="20")
starve_ammonium_high_30<-subset(pam_all.data, pam_all.data$food=="S" & pam_all.data$N_dose=="10" & pam_all.data$temp=="30")
starve_ammonium_high_20<-subset(pam_all.data, pam_all.data$food=="S"&  pam_all.data$N_dose=="10" & pam_all.data$temp=="20")

fed_ammonium_30<-subset(pam_all.data,pam_all.data$N_species=="A" & pam_all.data$temp=="30")
fed_ammonium_20<-subset(pam_all.data,pam_all.data$N_species=="A" & pam_all.data$temp=="20")

control_all_30<-subset(pam_all.data, pam_all.data$N_dose=="0" & pam_all.data$temp=="30")
N_18_and_control_30<-subset(pam_all.data, pam_all.data$N_dose==c(18,0) & pam_all.data$temp=="30")
N_18_A_10_and_control_30<-subset(pam_all.data, pam_all.data$N_dose==c(18,10,0) & pam_all.data$temp=="30")
N_18_and_control<-subset(pam_all.data, pam_all.data$N_dose==c(18,0))
control_all_20<-subset(pam_all.data, pam_all.data$N_dose=="0" & pam_all.data$temp=="20")

t.test(starve_ammonium_high_20$PAM_avg_day11, fed_ammonium_high_20$PAM_avg_day11)

mean(fed_ammonium_high_30$PAM_avg_day11)
#0.327
mean(control_all_30$PAM_avg_day11)
#0.3983



t.test(control_all_20$PAM_avg_day11, fed_ammonium_20$PAM_avg_day11)


```

```{r PAM Plots}
#packages needed to add jitters
library("hrbrthemes")
#install.packages("viridis")
library("viridis")
#install.packages("Rmisc")
library("Rmisc")
#subsetting what I want
A_10_and_all_control_30<-subset(pam_all.data, pam_all.data$treat_ID_without_sym==c("0_30_S","0_30_F","A_10_30_F", "A_10_30_S"))
write.csv(A_10_and_control_30,"C:/Users/carol/Documents/PhD Boston University 2019-/Chapter_2_Ecotox/Summer_2022_N_Ecotox/N_18_and_control_30.csv")
N_18_and_all_control_30<-subset(pam_all.data, pam_all.data$treat_ID_without_sym==c("0_30_S","0_30_F","N_18_30_F", "N_18_30_S"))
write.csv(N_18_and_control_30,"C:/Users/carol/Documents/PhD Boston University 2019-/Chapter_2_Ecotox/Summer_2022_N_Ecotox/A_10_and_control_30.csv")

#What do you want to do?
  #I want to take the average day 1 PAM from each treat_ID
library(Rmisc)
library(tidyverse)
pam_treatmeans_ammonium <- summarySE(A_10_and_all_control_30, measurevar=c("PAM_delta"),groupvars =c("treat_ID_without_sym"), na.rm=TRUE)

pam_treatmeans_nitrate <- summarySE(N_18_and_all_control_30, measurevar=c("PAM_delta"),groupvars =c("treat_ID_without_sym"), na.rm=TRUE)

#AMMONIUM ONLY
# plot, treatment x axis colored by site data figure
pam_plot_treatment_amm <- ggplot(pam_treatmeans_ammonium, aes(x = treat_ID_without_sym, y= c(PAM_delta), color = treat_ID_without_sym))+
  theme_bw()+
  geom_point(size = 3, position = position_dodge(width=0.3))+
  geom_smooth(aes(group=treat_ID_without_sym), position = position_dodge(width=0.3), size = 0.5, method='lm', se = FALSE)+
  geom_jitter(aes(), size=1.2, alpha=0.9)+
  geom_line(aes(group = treat_ID_without_sym), size = 0.5, linetype="dashed", position = position_dodge(width=0.3))+
  geom_errorbar(aes(x = treat_ID_without_sym, ymax = PAM_delta+se, ymin = PAM_delta-se), width = .2, position = position_dodge(width=0.3)) +
  scale_color_manual(name = "Treatment",
                     labels = c("Control 30C Fed","Control 30C Starved","Ammonium High 30C Fed", "Ammonium High 30C Starved","test"),
                     values = c("orchid1","darkorchid1","royalblue","skyblue","black","gray","brown"))+
 ylab("Change in Fv/Fm Pre vs. Post-experiment")+
  #scale_x_continuous(name = "Time Point", breaks = c(46,55,62,66,71,75,80)) +
  #ylim(0.4,0.7) +
  theme(panel.border = element_rect(colour = "black", fill = NA, size = 1))
pam_plot_treatment_amm  

#NITATE ONLY
# plot, treatment x axis colored by site data figure
pam_plot_treatment <- ggplot(pam_treatmeans_nitrate, aes(x = treat_ID_without_sym, y= c(PAM_delta), color = treat_ID_without_sym))+
  theme_bw()+
  geom_jitter(aes(), size=1.2, alpha=0.9)+
  geom_point(size = 3, position = position_dodge(width=0.3))+
  geom_smooth(aes(group=treat_ID_without_sym), position = position_dodge(width=0.3), size = 0.5, method='lm', se = FALSE)+
  geom_line(aes(group = treat_ID_without_sym), size = 0.5, linetype="dashed", position = position_dodge(width=0.3))+
  geom_errorbar(aes(x = treat_ID_without_sym, ymax = PAM_delta+se, ymin = PAM_delta-se), width = .2, position = position_dodge(width=0.3)) +
  scale_color_manual(name = "Treatment",
                     labels = c("Control 30C Fed","Control 30C Starved","Nitrate High 30C Fed", "Nitrate High 30C Starved"),
                     values = c("orchid1","darkorchid1","orange","maroon","black","gray"))+
 ylab("Change in Fv/Fm Pre vs. Post-experiment")+
  #scale_x_continuous(name = "Time Point", breaks = c(46,55,62,66,71,75,80)) +
  #ylim(0.4,0.7) +
  theme(panel.border = element_rect(colour = "black", fill = NA, size = 1))
pam_plot_treatment  


```

```{r}
all_control_30_fed<-subset(pam_all.data, pam_all.data$treat_ID_without_sym==c("0_30_F"))
all_control_30_starve<-subset(pam_all.data, pam_all.data$treat_ID_without_sym==c("0_30_S"))
A_10_30_Fed<-subset(pam_all.data, pam_all.data$treat_ID_without_sym==c("A_10_30_F"))
A_10_30_Starved<-subset(pam_all.data, pam_all.data$treat_ID_without_sym==c("A_10_30_S"))
N_18_30_Fed<-subset(pam_all.data, pam_all.data$treat_ID_without_sym==c("N_18_30_F"))
N_18_30_Starved<-subset(pam_all.data, pam_all.data$treat_ID_without_sym==c("N_18_30_S"))


#boxplot to check normality
hist(all_control_30_fed$PAM_delta)
hist(N_18_30_Starved$PAM_delta)
hist(pam_all.data$PAM_delta)




#all control 30 FED vs. A 10 30 FED
t.test(all_control_30_fed$PAM_avg_day11, A_10_30_Fed$PAM_avg_day11)

#all control 30 STARVED vs. A 10 30 STARVED
t.test(all_control_30_starve$PAM_avg_day11, A_10_30_Starved$PAM_avg_day11)

#all control 30 FED vs.N 18 30 FED
t.test(all_control_30_fed$PAM_avg_day11, N_18_30_Fed$PAM_avg_day11)

  #all control 30 STARVED vs.N 18 30 STARVED
t.test(all_control_30_starve$PAM_avg_day11, N_18_30_Starved$PAM_avg_day11)




#lets just try an ANOVA

anova_ammonium<- lm(A_10_and_all_control_30$PAM_delta ~ A_10_and_all_control_30$treat_ID_without_sym)
summary(anova_ammonium)
anova(anova_ammonium)
#one way ANOVA
aov_ammonium<- aov(A_10_and_all_control_30$PAM_delta ~ A_10_and_all_control_30$treat_ID_without_sym, data= A_10_and_all_control_30)
summary(aov_ammonium)
posthoc_ammonium <-TukeyHSD(aov_ammonium)
posthoc_ammonium

#ANOVA for nitrate
anova_nitrate<- lm(N_18_and_all_control_30$PAM_delta ~ N_18_and_all_control_30$treat_ID_without_sym)
summary(anova_nitrate)
anova(anova_nitrate)
#one way ANOVA
aov_nitrate<- aov(N_18_and_all_control_30$PAM_delta ~ N_18_and_all_control_30$treat_ID_without_sym, data= N_18_and_all_control_30)
summary(aov_nitrate)
posthoc_nitrate <-TukeyHSD(aov_nitrate)
posthoc_nitrate

boxplot(A_10_and_all_control_30$PAM_delta ~ A_10_and_all_control_30$treat_ID_without_sym)


```
```{r new dataset with simplified controls-- controls not assigned by N or A}
#subsetting but removing the controls assinged to nitrate or ammonium
#did it in excel because I was annoyed
pam_all.data_simplified_controls <- read.csv("PAM_summer_all_outlier_deleted_11_9_22_controls_simplified.csv", header=TRUE, sep=",",stringsAsFactors = FALSE)

```

```{r Dispersion of PAM data}

#ALL
pam_plot_treatment_all <- ggplot(pam_all.data, aes(x = treat_ID_without_sym, y= c(PAM_delta), color = treat_ID_without_sym))+
  theme_bw()+
  geom_point(size = 3, position = position_dodge(width=0.3))+
  geom_smooth(aes(group=treat_ID_without_sym), position = position_dodge(width=0.3), size = 0.5, method='lm', se = FALSE)+
  geom_jitter(aes(), size=1.2, alpha=0.9)+
  geom_line(aes(group = treat_ID_without_sym), size = 0.5, linetype="dashed", position = position_dodge(width=0.3))+
  #geom_errorbar(aes(x = treat_ID_without_sym, ymax = PAM_delta+se, ymin = PAM_delta-se), width = .2, position = position_dodge(width=0.3)) +
  #scale_color_manual(name = "Treatment",
                     #labels = c("Control 30C Fed","Control 30C Starved","Ammonium High 30C Fed", "Ammonium High 30C Starved","test"),
                     #values = c("orchid1","darkorchid1","royalblue","skyblue","black","gray","brown"))+
 ylab("Change in Fv/Fm Pre vs. Post-experiment")+
  ggtitle("All colonies - delta PAM")+
  #scale_x_continuous(name = "Time Point", breaks = c(46,55,62,66,71,75,80)) +
  #ylim(0.4,0.7) +
  theme(panel.border = element_rect(colour = "black", fill = NA, size = 1))
pam_plot_treatment_all

#SYM ONLY
sym_all<-subset(pam_all.data, pam_all.data$sym_state.1=="S")
pam_plot_treatment_SYM_all <- ggplot(sym_all, aes(x = treat_ID_without_sym, y= c(PAM_delta), color = treat_ID_without_sym))+
  theme_bw()+
  geom_point(size = 3, position = position_dodge(width=0.3))+
  geom_smooth(aes(group=treat_ID_without_sym), position = position_dodge(width=0.3), size = 0.5, method='lm', se = FALSE)+
  geom_jitter(aes(), size=1.2, alpha=0.9)+
  geom_line(aes(group = treat_ID_without_sym), size = 0.5, linetype="dashed", position = position_dodge(width=0.3))+
  #geom_errorbar(aes(x = treat_ID_without_sym, ymax = PAM_delta+se, ymin = PAM_delta-se), width = .2, position = position_dodge(width=0.3)) +
  #scale_color_manual(name = "Treatment",
                     #labels = c("Control 30C Fed","Control 30C Starved","Ammonium High 30C Fed", "Ammonium High 30C Starved","test"),
                     #values = c("orchid1","darkorchid1","royalblue","skyblue","black","gray","brown"))+
 ylab("Change in Fv/Fm Pre vs. Post-experiment")+
  ggtitle("All symbiotic colonies - delta PAM")+
  #scale_x_continuous(name = "Time Point", breaks = c(46,55,62,66,71,75,80)) +
  #ylim(0.4,0.7) +
  theme(panel.border = element_rect(colour = "black", fill = NA, size = 1))
pam_plot_treatment_SYM_all

#APO ONLY
apo_all<-subset(pam_all.data, pam_all.data$sym_state.1=="A")
pam_plot_treatment_APO_all <- ggplot(apo_all, aes(x = treat_ID_without_sym, y= c(PAM_delta), color = treat_ID_without_sym))+
  theme_bw()+
  geom_point(size = 3, position = position_dodge(width=0.3))+
  geom_smooth(aes(group=treat_ID_without_sym), position = position_dodge(width=0.3), size = 0.5, method='lm', se = FALSE)+
  geom_jitter(aes(), size=1.2, alpha=0.9)+
  geom_line(aes(group = treat_ID_without_sym), size = 0.5, linetype="dashed", position = position_dodge(width=0.3))+
  #geom_errorbar(aes(x = treat_ID_without_sym, ymax = PAM_delta+se, ymin = PAM_delta-se), width = .2, position = position_dodge(width=0.3)) +
  #scale_color_manual(name = "Treatment",
                     #labels = c("Control 30C Fed","Control 30C Starved","Ammonium High 30C Fed", "Ammonium High 30C Starved","test"),
                     #values = c("orchid1","darkorchid1","royalblue","skyblue","black","gray","brown"))+
 ylab("Change in Fv/Fm Pre vs. Post-experiment")+
  ggtitle("All aposymbiotic colonies - delta PAM")+
  #scale_x_continuous(name = "Time Point", breaks = c(46,55,62,66,71,75,80)) +
  #ylim(0.4,0.7) +
  theme(panel.border = element_rect(colour = "black", fill = NA, size = 1))
pam_plot_treatment_APO_all

```

```{r Apo vs. sym}
#overall apo vs. sym
t.test(all_apo$PAM_avg_day11, all_sym$PAM_avg_day11)


pam_treatmeans_apovsym <- summarySE(pam_all.data, measurevar=c("PAM_delta"),groupvars =c("sym_state.1"), na.rm=TRUE)


#AMMONIUM ONLY
# plot, treatment x axis colored by site data figure
pam_plot_apovsym <- ggplot(pam_treatmeans_apovsym, aes(x = sym_state.1, y= c(PAM_delta), color = sym_state.1))+
  theme_bw()+
  geom_point(size = 3, position = position_dodge(width=0.3))+
  geom_smooth(aes(group=sym_state.1), position = position_dodge(width=0.3), size = 0.5, method='lm', se = FALSE)+
 # geom_jitter(aes(), size=1.2, alpha=0.9)+
  geom_line(aes(group = sym_state.1), size = 0.5, linetype="dashed", position = position_dodge(width=0.3))+
  geom_errorbar(aes(x = sym_state.1, ymax = PAM_delta+se, ymin = PAM_delta-se), width = .2, position = position_dodge(width=0.3)) +
  #scale_color_manual(name = "Treatment",
                    #labels = c("Control 30C Fed","Control 30C Starved","Ammonium High 30C Fed", "Ammonium High 30C Starved","test"),
                    # values = c("orchid1","darkorchid1","royalblue","skyblue","black","gray","brown"))+
 ylab("Change in Fv/Fm Pre vs. Post-experiment")+
  ggtitle("Sym vs. Apo")+
  #scale_x_continuous(name = "Time Point", breaks = c(46,55,62,66,71,75,80)) +
  #ylim(0.4,0.7) +
  theme(panel.border = element_rect(colour = "black", fill = NA, size = 1))
pam_plot_apovsym


```

```{r overall fed vs. starved}
#overall fed vs. starved
t.test(all_fed$PAM_avg_day11, all_starved$PAM_avg_day11)


pam_treatmeans_fedvstarved <- summarySE(pam_all.data, measurevar=c("PAM_delta"),groupvars =c("food"), na.rm=TRUE)


#AMMONIUM ONLY
# plot, treatment x axis colored by site data figure
pam_plot_fedvstarved <- ggplot(pam_treatmeans_fedvstarved, aes(x = food, y= c(PAM_delta), color = food))+
  theme_bw()+
  geom_point(size = 3, position = position_dodge(width=0.3))+
  geom_smooth(aes(group=food), position = position_dodge(width=0.3), size = 0.5, method='lm', se = FALSE)+
 # geom_jitter(aes(), size=1.2, alpha=0.9)+
  geom_line(aes(group = food), size = 0.5, linetype="dashed", position = position_dodge(width=0.3))+
  geom_errorbar(aes(x = food, ymax = PAM_delta+se, ymin = PAM_delta-se), width = .2, position = position_dodge(width=0.3)) +
  #scale_color_manual(name = "Treatment",
                    #labels = c("Control 30C Fed","Control 30C Starved","Ammonium High 30C Fed", "Ammonium High 30C Starved","test"),
                    # values = c("orchid1","darkorchid1","royalblue","skyblue","black","gray","brown"))+
 ylab("Change in Fv/Fm Pre vs. Post-experiment")+
  ggtitle("Fed vs. starved")+
  #scale_x_continuous(name = "Time Point", breaks = c(46,55,62,66,71,75,80)) +
  #ylim(0.4,0.7) +
  theme(panel.border = element_rect(colour = "black", fill = NA, size = 1))
pam_plot_fedvstarved
```
```{r nitrate vs. ammonium overall}

pam_treatmeans_nitratevammonium <- summarySE(pam_all.data_simplified_controls, measurevar=c("PAM_delta"),groupvars =c("N_species"), na.rm=TRUE)

t.test(pam_all.data_simplified_controls$N_species=="N", pam_all.data_simplified_controls$N_species=="A")
# plot, treatment x axis colored by site data figure
pam_plot_nitratevammonium <- ggplot(pam_treatmeans_nitratevammonium, aes(x = N_species, y= c(PAM_delta), color = N_species))+
  theme_bw()+
  geom_point(size = 3, position = position_dodge(width=0.3))+
  geom_smooth(aes(group=N_species), position = position_dodge(width=0.3), size = 0.5, method='lm', se = FALSE)+
 # geom_jitter(aes(), size=1.2, alpha=0.9)+
  geom_line(aes(group = N_species), size = 0.5, linetype="dashed", position = position_dodge(width=0.3))+
  geom_errorbar(aes(x = N_species, ymax = PAM_delta+se, ymin = PAM_delta-se), width = .2, position = position_dodge(width=0.3)) +
  #scale_color_manual(name = "Treatment",
                    #labels = c("Control 30C Fed","Control 30C Starved","Ammonium High 30C Fed", "Ammonium High 30C Starved","test"),
                    # values = c("orchid1","darkorchid1","royalblue","skyblue","black","gray","brown"))+
 ylab("Change in Fv/Fm Pre vs. Post-experiment")+
  ggtitle("Nitrate v. Ammonium")+
  #scale_x_continuous(name = "Time Point", breaks = c(46,55,62,66,71,75,80)) +
  #ylim(0.4,0.7) +
  theme(panel.border = element_rect(colour = "black", fill = NA, size = 1))
pam_plot_nitratevammonium
```
```{r hot vs. ambient overall}
pam_treatmeans_20vs30 <- summarySE(pam_all.data_simplified_controls, measurevar=c("PAM_delta"),groupvars =c("temp.1"), na.rm=TRUE)

t.test(pam_all.data_simplified_controls$temp.1=="20", pam_all.data_simplified_controls$temp.1=="30")
# plot, treatment x axis colored by site data figure
pam_plot_20vs30 <- ggplot(pam_treatmeans_20vs30, aes(x = temp.1, y= c(PAM_delta), color = temp.1))+
  theme_bw()+
  geom_point(size = 3, position = position_dodge(width=0.3))+
  geom_smooth(aes(group=temp.1), position = position_dodge(width=0.3), size = 0.5, method='lm', se = FALSE)+
 # geom_jitter(aes(), size=1.2, alpha=0.9)+
  geom_line(aes(group = temp.1), size = 0.5, linetype="dashed", position = position_dodge(width=0.3))+
  geom_errorbar(aes(x = temp.1, ymax = PAM_delta+se, ymin = PAM_delta-se), width = .2, position = position_dodge(width=0.3)) +
  #scale_color_manual(name = "Treatment",
                    #labels = c("Control 30C Fed","Control 30C Starved","Ammonium High 30C Fed", "Ammonium High 30C Starved","test"),
                    # values = c("orchid1","darkorchid1","royalblue","skyblue","black","gray","brown"))+
 ylab("Change in Fv/Fm Pre vs. Post-experiment")+
  ggtitle("20C vs. 30C")+
  #scale_x_continuous(name = "Time Point", breaks = c(46,55,62,66,71,75,80)) +
  #ylim(0.4,0.7) +
  theme(panel.border = element_rect(colour = "black", fill = NA, size = 1))
pam_plot_20vs30
```

```{r All ammonium}
pam_treatmeans_ammonium <- summarySE(all_ammonium, measurevar=c("PAM_delta"),groupvars =c("treat_ID_without_sym"), na.rm=TRUE)

t.test(all_ammonium$N_dose==0, all_ammonium$N_dose==5)
# plot, treatment x axis colored by site data figure
pam_plot_ammonium <- ggplot(pam_treatmeans_ammonium, aes(x = treat_ID_without_sym, y= c(PAM_delta), color = treat_ID_without_sym))+
  theme_bw()+
  geom_point(size = 3, position = position_dodge(width=0.3))+
  geom_smooth(aes(group=treat_ID_without_sym), position = position_dodge(width=0.3), size = 0.5, method='lm', se = FALSE)+
 # geom_jitter(aes(), size=1.2, alpha=0.9)+
  geom_line(aes(group = treat_ID_without_sym), size = 0.5, linetype="dashed", position = position_dodge(width=0.3))+
  geom_errorbar(aes(x = treat_ID_without_sym, ymax = PAM_delta+se, ymin = PAM_delta-se), width = .2, position = position_dodge(width=0.3)) +
  #scale_color_manual(name = "Treatment",
                    #labels = c("Control 30C Fed","Control 30C Starved","Ammonium High 30C Fed", "Ammonium High 30C Starved","test"),
                    # values = c("orchid1","darkorchid1","royalblue","skyblue","black","gray","brown"))+
 ylab("Change in Fv/Fm Pre vs. Post-experiment")+
  ggtitle("All Ammonium Treatments")+
  #scale_x_continuous(name = "Time Point", breaks = c(46,55,62,66,71,75,80)) +
  #ylim(0.4,0.7) +
  theme(panel.border = element_rect(colour = "black", fill = NA, size = 1))
pam_plot_ammonium

ammonium_jitter <- ggplot(all_ammonium, aes(x = treat_ID_without_sym, y= c(PAM_delta), color = treat_ID_without_sym))+
  theme_bw()+
  geom_point(size = 3, position = position_dodge(width=0.3))+
  geom_smooth(aes(group=treat_ID_without_sym), position = position_dodge(width=0.3), size = 0.5, method='lm', se = FALSE)+
  geom_jitter(aes(), size=1.2, alpha=0.9)+
  geom_line(aes(group = treat_ID_without_sym), size = 0.5, linetype="dashed", position = position_dodge(width=0.3))+
  #geom_errorbar(aes(x = treat_ID_without_sym, ymax = PAM_delta+se, ymin = PAM_delta-se), width = .2, position = position_dodge(width=0.3)) +
  #scale_color_manual(name = "Treatment",
                     #labels = c("Control 30C Fed","Control 30C Starved","Ammonium High 30C Fed", "Ammonium High 30C Starved","test"),
                     #values = c("orchid1","darkorchid1","royalblue","skyblue","black","gray","brown"))+
 ylab("Change in Fv/Fm Pre vs. Post-experiment")+
  ggtitle("All colonies treated with Ammonium - JITTER")+
  #scale_x_continuous(name = "Time Point", breaks = c(46,55,62,66,71,75,80)) +
  #ylim(0.4,0.7) +
  theme(panel.border = element_rect(colour = "black", fill = NA, size = 1))
ammonium_jitter

```

```{r}
pam_treatmeans_nitrate <- summarySE(all_nitrate, measurevar=c("PAM_delta"),groupvars =c("treat_ID_without_sym"), na.rm=TRUE)

t.test(all_ammonium$N_dose==0, all_ammonium$N_dose==5)
# plot, treatment x axis colored by site data figure
pam_plot_nitrate<- ggplot(pam_treatmeans_nitrate, aes(x = treat_ID_without_sym, y= c(PAM_delta), color = treat_ID_without_sym))+
  theme_bw()+
  geom_point(size = 3, position = position_dodge(width=0.3))+
  geom_smooth(aes(group=treat_ID_without_sym), position = position_dodge(width=0.3), size = 0.5, method='lm', se = FALSE)+
 # geom_jitter(aes(), size=1.2, alpha=0.9)+
  geom_line(aes(group = treat_ID_without_sym), size = 0.5, linetype="dashed", position = position_dodge(width=0.3))+
  geom_errorbar(aes(x = treat_ID_without_sym, ymax = PAM_delta+se, ymin = PAM_delta-se), width = .2, position = position_dodge(width=0.3)) +
  #scale_color_manual(name = "Treatment",
                    #labels = c("Control 30C Fed","Control 30C Starved","Ammonium High 30C Fed", "Ammonium High 30C Starved","test"),
                    # values = c("orchid1","darkorchid1","royalblue","skyblue","black","gray","brown"))+
 ylab("Change in Fv/Fm Pre vs. Post-experiment")+
  ggtitle("All Nitrate Treatments")+
  #scale_x_continuous(name = "Time Point", breaks = c(46,55,62,66,71,75,80)) +
  #ylim(0.4,0.7) +
  theme(panel.border = element_rect(colour = "black", fill = NA, size = 1))
pam_plot_nitrate

nitrate_jitter <- ggplot(all_nitrate, aes(x = treat_ID_without_sym, y= c(PAM_delta), color = treat_ID_without_sym))+
  theme_bw()+
  geom_point(size = 3, position = position_dodge(width=0.3))+
  geom_smooth(aes(group=treat_ID_without_sym), position = position_dodge(width=0.3), size = 0.5, method='lm', se = FALSE)+
  geom_jitter(aes(), size=1.2, alpha=0.9)+
  geom_line(aes(group = treat_ID_without_sym), size = 0.5, linetype="dashed", position = position_dodge(width=0.3))+
  #geom_errorbar(aes(x = treat_ID_without_sym, ymax = PAM_delta+se, ymin = PAM_delta-se), width = .2, position = position_dodge(width=0.3)) +
  #scale_color_manual(name = "Treatment",
                     #labels = c("Control 30C Fed","Control 30C Starved","Ammonium High 30C Fed", "Ammonium High 30C Starved","test"),
                     #values = c("orchid1","darkorchid1","royalblue","skyblue","black","gray","brown"))+
 ylab("Change in Fv/Fm Pre vs. Post-experiment")+
  ggtitle("All colonies treated with Nitrate - JITTER")+
  #scale_x_continuous(name = "Time Point", breaks = c(46,55,62,66,71,75,80)) +
  #ylim(0.4,0.7) +
  theme(panel.border = element_rect(colour = "black", fill = NA, size = 1))
nitrate_jitter
```

```{r Loading all packages for lmer}
library("lmerTest")
#install.packages("emmeans")
library("emmeans")
#install.packages("pbkrtest")
library("pbkrtest")

#multiple response variables 
#check model with performance package
  #model tools R markdown
  #check for colinearity
  #r squared figures
#install.packages("performance")
#install.packages(c("rlang", "ggplot2", "performance", "dplyr", "ggrepel", "see"), dependencies = TRUE)
library("performance")
#install.packages("see")
library("see")
#install.packages("ggrepel")
library("ggrepel")
#install.packages("sjPlot") #for visualizing linear models
library("sjPlot")
```

```{r LINEAR MODEL}
#we know everything is normal, so we can proceed to do a mixed linear model

#IMPORTANT#
#Releveling data to compare everything to the control (NOTE, we can change this if we want)
unique(pam_all.data_simplified_controls$treat_ID_without_sym)
pam_all.data_simplified_controls$treat_ID_without_sym <- factor(pam_all.data_simplified_controls$treat_ID_without_sym, levels=c("0_20_F" ,    "0_20_S"  ,   "0_30_F"  ,   "0_30_S"  ,  "N_1.5_20_F", "N_1.5_20_S" ,"N_1.5_30_F", "N_1.5_30_S"  ,"A_5_20_F"  , "A_5_20_S"  , "A_5_30_F"  , "A_5_30_S" ,"N_5_20_F"  , "N_5_20_S"  , "N_5_30_F"  , "N_5_30_S",
"A_7.5_20_F" ,"A_7.5_20_S" ,"A_7.5_30_F", "A_7.5_30_S"  ,"N_18_20_F",  "N_18_20_S" ,"N_18_30_F" , "N_18_30_S" ,
"A_10_20_F",  "A_10_20_S",  "A_10_30_F" , "A_10_30_S"))

#LINEAR MODELS
# null model 
pam_mm_null <- lm(PAM_delta ~ 1 , data=pam_all.data_simplified_controls) #not adding anything random yet, but I probably should
plot(pam_mm_null)
summary(pam_mm_null)

# full model 
#pam_mm_full <- lmer(Score ~ Treatment * Day + (1+Day|Beetag), data=pam_all.data)
#summary(pam_mm_full)
pam_mm_test <- pam_mm_null <- lm(PAM_delta ~ temp * N_species *N_dose *food *sym_state.1, data=pam_all.data_simplified_controls) #not adding anything random yet, but I probably should

#DO AN AIC DROPPING VARIABLE BY VARIABLE
#Lower AIC wins
AIC(pam_mm_null,pam_mm_test)
anova(pam_mm_test) #gives us overall treatment effects (how much they contribute)

emm_pam_overall=emmeans(pam_mm_test, specs=pairwise ~ N_dose) 

summary(emm_pam_overall)


```

```{r}

```

