---
title: "Experiment 3A Recategorization with Bigelow Water Quality Data"
author: "Caroline Fleming"
date: "2023-06-07"
output: html_document
---
```{r add packages}
library("lme4")
#install.packages("lmerTest")
library("lmerTest")
#install.packages("emmeans")
library("emmeans")
#install.packages("pbkrtest")
library("pbkrtest")
#reshape melts our datasets in the way we want
library("reshape2")
library("dplyr")
library("plyr")
library("tidyverse")
library("Rmisc")
library("ggplot2")
#multiple response variables 
#check model with performance package
  #model tools R markdown
  #check for colinearity
  #r squared figures
#install.packages("performance")
#install.packages(c("rlang", "ggplot2", "performance", "dplyr", "ggrepel", "see"), dependencies = TRUE)
library("performance")
#install.packages("see")
library("see")
#install.packages("ggrepel")
library("ggrepel")
#install.packages("sjPlot") #for visualizing linear models
library(sjPlot)
library(car)
#gg effects

#increase the number of results it will show
options(max.print=1000000)
```


```{r upload data }
#upload data
exp3A_bigelow_all.data <- read.csv("3A_resp_PAM_using_bigelow_water_quality_6_7_23.csv", header=TRUE, sep=",",stringsAsFactors = FALSE)
exp3A_bigelow_all.data <- na.omit(exp3A_bigelow_all.data)


#make temp a factor
exp3A_bigelow_all.data$temp <- as.factor(exp3A_bigelow_all.data$temp)

#add an absolute value column 
exp3A_bigelow_all.data$resp_rate_abs <- abs(exp3A_bigelow_all.data$resp_rate)


exp3A_bigelow_all.data$e_coli<- as.factor(exp3A_bigelow_all.data$e_coli)

```

```{r histograms}
hist(exp3A_bigelow_all.data$resp_rate_abs) #not bad
hist(exp3A_bigelow_all.data$PAM_delta) #not great but not horrible

```

```{r RESPIRATION graphing by ammonium / nitrate experienced}

#first lets subset the corals that were supposed to be in the AMMONIUM treatment
expA_ammonium <- subset(exp3A_bigelow_all.data, exp3A_bigelow_all.data$N_species=="A" | exp3A_bigelow_all.data$N_species=="CNTRL")

# Summarize by N_species_dose so we can visualize
sum_ammonium_3A <- summarySE(expA_ammonium, measurevar = "resp_rate_abs", groupvars = c("new_treatID_ammonium", "e_coli"))
sum_ammonium_3A$new_treatID_ammonium<- factor(sum_ammonium_3A$new_treatID_ammonium, levels=c("ambient", "intermediate","high"))
# Visualize
gg_sum_ammonium_3A_resp<-ggplot(data = sum_ammonium_3A,
       aes(x = new_treatID_ammonium,
           y = resp_rate_abs, col=e_coli)) +
    geom_point(size=4) +
    theme (axis.text.x = element_text(size = 20),
   axis.title.x = element_text(size = 24),
  axis.text.y = element_text(size = 20),
   axis.title.y = element_text(size = 18)) +
    geom_errorbar(aes(ymin=resp_rate_abs-se, ymax=resp_rate_abs+se), width=0.3, size = 2) +
   theme(legend.position="none")+
    labs(x = "\n", 
         y = expression(paste("Metabolic rate (umol oxygen*min"^"-1"~"*g"^"-1"~")")), 
         caption = "data represent mean +/- SEM" ) +
   # scale_x_discrete("Dose", labels=c(CNTRL_0="Control", A_5="Ambient", A_7.5="Intermediate", A_10="High"))+
    ggtitle("Resp rate new NH4 dose grouping - E. coli vs. no E. coli (Ammonium experiment + controls only)") + 
    scale_color_manual(labels=c("no E. coli", "E. coli"), values=c("darkgray","darkgreen"))
gg_sum_ammonium_3A_resp
#STATS 
summary(aov_1<-aov(resp_rate_abs ~ e_coli + new_treatID_ammonium, data=expA_ammonium))
TukeyHSD(aov_1, "new_treatID_ammonium")

# Summarize by N_species_dose E coli and TEMP so we can visualize
expA_ammonium <- subset(exp3A_bigelow_all.data, exp3A_bigelow_all.data$N_species=="A" | exp3A_bigelow_all.data$N_species=="CNTRL"& exp3A_bigelow_all.data$temp=="30")
sum_ammonium_3A <- summarySE(expA_ammonium, measurevar = "resp_rate_abs", groupvars = c("new_treatID_ammonium", "e_coli"))
sum_ammonium_3A$new_treatID_ammonium<- factor(sum_ammonium_3A$new_treatID_ammonium, levels=c("ambient", "intermediate","high"))
# Visualize
gg_sum_ammonium_3A_resp<-ggplot(data = sum_ammonium_3A,
       aes(x = new_treatID_ammonium,
           y = resp_rate_abs, col=e_coli)) +
    geom_point(size=4) +
    theme (axis.text.x = element_text(size = 20),
   axis.title.x = element_text(size = 24),
  axis.text.y = element_text(size = 20),
   axis.title.y = element_text(size = 18)) +
    geom_errorbar(aes(ymin=resp_rate_abs-se, ymax=resp_rate_abs+se), width=0.3, size = 2) +
   theme(legend.position="none")+
    labs(x = "\n", 
         y = expression(paste("Metabolic rate (umol oxygen*min"^"-1"~"*g"^"-1"~")")), 
         caption = "data represent mean +/- SEM" ) +
   # scale_x_discrete("Dose", labels=c(CNTRL_0="Control", A_5="Ambient", A_7.5="Intermediate", A_10="High"))+
    ggtitle("Resp rate new NH4 dose grouping - E. coli vs. no E. coli (Ammonium experiment + controls only)") + 
    scale_color_manual(labels=c("no E. coli", "E. coli"), values=c("darkgray","darkgreen"))
gg_sum_ammonium_3A_resp
#STATS 
summary(aov_1<-aov(resp_rate_abs ~ e_coli + new_treatID_ammonium, data=expA_ammonium))
TukeyHSD(aov_1, "new_treatID_ammonium")


#first lets subset the corals that were supposed to be in the NITRATE treatment
expA_nitrate <- subset(exp3A_bigelow_all.data, exp3A_bigelow_all.data$N_species=="N" | exp3A_bigelow_all.data$N_species=="CNTRL" )

# Summarize by N_species_dose so we can visualize
sum_nitrate_3A <- summarySE(expA_nitrate, measurevar = "resp_rate_abs", groupvars = c("new_treatID_nitrate", "e_coli"))
sum_nitrate_3A$new_treatID_nitrate<- factor(sum_nitrate_3A$new_treatID_nitrate, levels=c("ambient", "intermediate","high"))
# Visualize
gg_sum_nitrate_3A_resp<-ggplot(data = sum_nitrate_3A,
       aes(x = new_treatID_nitrate,
           y = resp_rate_abs, col=e_coli)) +
    geom_point(size=4) +
    theme (axis.text.x = element_text(size = 20),
   axis.title.x = element_text(size = 24),
  axis.text.y = element_text(size = 20),
   axis.title.y = element_text(size = 18)) +
    geom_errorbar(aes(ymin=resp_rate_abs-se, ymax=resp_rate_abs+se), width=0.3, size = 2) +
   theme(legend.position="none")+
    labs(x = "\n", 
         y = expression(paste("Metabolic rate (umol oxygen*min"^"-1"~"*g"^"-1"~")")), 
         caption = "data represent mean +/- SEM" ) +
   # scale_x_discrete("Dose", labels=c(CNTRL_0="Control", A_5="Ambient", A_7.5="Intermediate", A_10="High"))+
    ggtitle("Resp rate new NO3 dose grouping - E. coli vs. no E. coli (nitrate experiment + controls only)") + 
    scale_color_manual(labels=c("no E. coli", "E. coli"), values=c("darkgray","darkgreen"))
gg_sum_nitrate_3A_resp
#STATS 
summary(aov_2<-aov(resp_rate_abs ~ e_coli + new_treatID_nitrate, data=expA_nitrate))
TukeyHSD(aov_2, "new_treatID_nitrate")

# by temp
expA_nitrate <- subset(exp3A_bigelow_all.data, exp3A_bigelow_all.data$N_species=="N" | exp3A_bigelow_all.data$N_species=="CNTRL" & exp3A_bigelow_all.data$temp=="30")

# Summarize by N_species_dose so we can visualize
sum_nitrate_3A <- summarySE(expA_nitrate, measurevar = "resp_rate_abs", groupvars = c("new_treatID_nitrate", "e_coli"))
sum_nitrate_3A$new_treatID_nitrate<- factor(sum_nitrate_3A$new_treatID_nitrate, levels=c("ambient", "intermediate","high"))
# Visualize
gg_sum_nitrate_3A_resp<-ggplot(data = sum_nitrate_3A,
       aes(x = new_treatID_nitrate,
           y = resp_rate_abs, col=e_coli)) +
    geom_point(size=4) +
    theme (axis.text.x = element_text(size = 20),
   axis.title.x = element_text(size = 24),
  axis.text.y = element_text(size = 20),
   axis.title.y = element_text(size = 18)) +
    geom_errorbar(aes(ymin=resp_rate_abs-se, ymax=resp_rate_abs+se), width=0.3, size = 2) +
   theme(legend.position="none")+
    labs(x = "\n", 
         y = expression(paste("Metabolic rate (umol oxygen*min"^"-1"~"*g"^"-1"~")")), 
         caption = "data represent mean +/- SEM" ) +
   # scale_x_discrete("Dose", labels=c(CNTRL_0="Control", A_5="Ambient", A_7.5="Intermediate", A_10="High"))+
    ggtitle("Resp rate new NO3 dose grouping - E. coli vs. no E. coli (nitrate experiment + controls only)") + 
    scale_color_manual(labels=c("no E. coli", "E. coli"), values=c("darkgray","darkgreen"))
gg_sum_nitrate_3A_resp
#STATS 
summary(aov_2<-aov(resp_rate_abs ~ e_coli + new_treatID_nitrate, data=expA_nitrate))
TukeyHSD(aov_2, "new_treatID_nitrate")


```

```{r PAM graphing by ammonium / nitrate experienced}
#first lets subset the corals that were supposed to be in the AMMONIUM treatment
expA_ammonium <- subset(exp3A_bigelow_all.data, exp3A_bigelow_all.data$N_species=="A" | exp3A_bigelow_all.data$N_species=="CNTRL")

# Summarize by N_species_dose so we can visualize
sum_ammonium_3A <- summarySE(expA_ammonium, measurevar = "PAM_delta", groupvars = c("new_treatID_ammonium","temp"))
sum_ammonium_3A$new_treatID_ammonium<- factor(sum_ammonium_3A$new_treatID_ammonium, levels=c("ambient", "intermediate","high"))
# Visualize
gg_sum_ammonium_3A_resp<-ggplot(data = sum_ammonium_3A,
       aes(x = new_treatID_ammonium,
           y = PAM_delta, col=temp)) +
    geom_point(size=4) +
    theme (axis.text.x = element_text(size = 20),
   axis.title.x = element_text(size = 24),
  axis.text.y = element_text(size = 20),
   axis.title.y = element_text(size = 18)) +
    geom_errorbar(aes(ymin=PAM_delta-se, ymax=PAM_delta+se), width=0.3, size = 2) +
   theme(legend.position="none")+
    labs(x = "\n", 
         y = expression(paste("Change in Fv/Fm")), 
         caption = "data represent mean +/- SEM" ) +
   # scale_x_discrete("Dose", labels=c(CNTRL_0="Control", A_5="Ambient", A_7.5="Intermediate", A_10="High"))+
    ggtitle("Delta PAM new NH4 dose grouping (Ammonium experiment + controls only)") + 
     scale_color_manual(labels=labels, values=c("dodgerblue","darkred"))
gg_sum_ammonium_3A_resp
#STATS 
summary(aov_1<-aov(PAM_delta ~ new_treatID_ammonium, data=expA_ammonium))
TukeyHSD(aov_1, "new_treatID_ammonium")


#first lets subset the corals that were supposed to be in the NITRATE treatment
expA_nitrate <- subset(exp3A_bigelow_all.data, exp3A_bigelow_all.data$N_species=="N" | exp3A_bigelow_all.data$N_species=="CNTRL")

# Summarize by N_species_dose so we can visualize
sum_nitrate_3A <- summarySE(expA_nitrate, measurevar = "PAM_delta", groupvars = c("new_treatID_nitrate", "temp"))
sum_nitrate_3A$new_treatID_nitrate<- factor(sum_nitrate_3A$new_treatID_nitrate, levels=c("ambient", "intermediate","high"))
# Visualize
gg_sum_nitrate_3A_resp<-ggplot(data = sum_nitrate_3A,
       aes(x = new_treatID_nitrate,
           y = PAM_delta, col=temp)) +
    geom_point(size=4) +
    theme (axis.text.x = element_text(size = 20),
   axis.title.x = element_text(size = 24),
  axis.text.y = element_text(size = 20),
   axis.title.y = element_text(size = 18)) +
    geom_errorbar(aes(ymin=PAM_delta-se, ymax=PAM_delta+se), width=0.3, size = 2) +
   theme(legend.position="none")+
    labs(x = "\n", 
         y = expression(paste("Change in Fv/Fm")), 
         caption = "data represent mean +/- SEM" ) +
    ylim(-.55, 0.12) +
   # scale_x_discrete("Dose", labels=c(CNTRL_0="Control", A_5="Ambient", A_7.5="Intermediate", A_10="High"))+
    ggtitle("Delta PAM new NO3 dose grouping - (nitrate experiment + controls only)") + 
        scale_color_manual(labels=labels, values=c("dodgerblue","darkred"))
gg_sum_nitrate_3A_resp
#STATS 
summary(aov_2<-aov(PAM_delta ~ new_treatID_nitrate, data=expA_nitrate))
TukeyHSD(aov_2, "new_treatID_nitrate")

```

