---
title: "Generating random subset of controls"
author: "Caroline Fleming"
date: "2023-04-19"
output: html_document
---

```{r packages}
library("lme4")
#install.packages("lmerTest")
library("lmerTest")
#install.packages("emmeans")
library("emmeans")
#install.packages("pbkrtest")
library("pbkrtest")
#reshape melts our datasets in the way we want
library("reshape2")
library("dplyr")
library("plyr")
library("tidyverse")
library("Rmisc")
library("ggplot2")
#multiple response variables 
#check model with performance package
  #model tools R markdown
  #check for colinearity
  #r squared figures
#install.packages("performance")
#install.packages(c("rlang", "ggplot2", "performance", "dplyr", "ggrepel", "see"), dependencies = TRUE)
library("performance")
#install.packages("see")
library("see")
#install.packages("ggrepel")
library("ggrepel")
#install.packages("sjPlot") #for visualizing linear models
library(sjPlot)
library(MASS)
library(car)
library(outliers)
#gg effects
library(ggpubr)
#install.packages("ggpmisc")
library("ggpmisc")
library(devtools)
source_gist("524eade46135f6348140") #for the stat_smooth_func()


#increase the number of results it will show
options(max.print=1000000)
```


```{r NITRATE - upload nitrate controls}
pam_controls_nitrate.data <- read.csv("PAM_Control_all_4_19_23_NITRATE.csv", header=TRUE, sep=",",stringsAsFactors = FALSE)
pam_controls_nitrate.data <- na.omit(pam_controls_nitrate.data)
#changing some column names
pam_controls_nitrate.data<-subset(pam_controls_nitrate.data, select = -c(temp))
#renaming columns in base R because dplyr is freaking out
colnames(pam_controls_nitrate.data)[colnames(pam_controls_nitrate.data) == "sym_state"] ="sym_state_full"
colnames(pam_controls_nitrate.data)[colnames(pam_controls_nitrate.data) == "sym_state.1"] ="sym_state"
colnames(pam_controls_nitrate.data)[colnames(pam_controls_nitrate.data) == "temp.1"] ="temp"

```


```{r NITRATE - create a new dataset with 60 random rows}
pam_control_nitrate_random <- pam_controls_nitrate.data %>% sample_n(60)
write.csv(pam_control_nitrate_random, "pam_control_nitrate_random.csv")
```


```{r AMMONIUM - upload ammonium controls}
#uploading the data and fixing it a bit
pam_controls_ammonium.data <- read.csv("PAM_Control_all_4_19_23_AMMONIUM.csv", header=TRUE, sep=",",stringsAsFactors = FALSE)
pam_controls_ammonium.data <- na.omit(pam_controls_ammonium.data)
#changing some column names
pam_controls_ammonium.data<-subset(pam_controls_ammonium.data, select = -c(temp))
#renaming columns in base R because dplyr is freaking out
colnames(pam_controls_ammonium.data)[colnames(pam_controls_ammonium.data) == "sym_state"] ="sym_state_full"
colnames(pam_controls_ammonium.data)[colnames(pam_controls_ammonium.data) == "sym_state.1"] ="sym_state"
colnames(pam_controls_ammonium.data)[colnames(pam_controls_ammonium.data) == "temp.1"] ="temp"
```

```{r AMMONIUM - create a new dataset with 60 random rows}
pam_control_ammonium_random <- pam_controls_ammonium.data %>% sample_n(60)
write.csv(pam_control_ammonium_random, "pam_control_ammonium_random.csv")
```

```{r combine those dataframes}
pam_controls_merged_RANDOM <- rbind(pam_control_nitrate_random, pam_control_ammonium_random)
write.csv(pam_controls_merged_RANDOM, "pam_controls_merged_RANDOM.csv")
```

```{r make a graph of old over new data }

gg_controls <- ggplot() +
 # geom_boxplot(data=pam_controls_merged_RANDOM, aes(x=N_species_dose, y=PAM_delta), color="black")+
  geom_jitter(data=pam_controls_merged_RANDOM, aes(x=N_species_dose, y=PAM_delta), width=0.15, alpha=0.9, color="black") +
   #geom_boxplot(data=pam_controls_ammonium.data, aes(x=N_species_dose, y=PAM_delta), color="darkgreen")+
  geom_jitter(data=pam_controls_ammonium.data, aes(x=N_species_dose, y=PAM_delta), width=0.15, alpha=0.9, color="green") +
    # geom_boxplot(data=pam_controls_nitrate.data, aes(x=N_species_dose, y=PAM_delta), color="dodgerblue")+
  geom_jitter(data=pam_controls_nitrate.data, aes(x=N_species_dose, y=PAM_delta), width=0.15, alpha=0.9, color="dodgerblue") +
  ylab("Delta PAM")+
  xlab("Dose")+
  theme(legend.position="none", plot.title = element_text(size = 9)) +
  theme(axis.text.x = element_text(angle=90, vjust=.5, hjust=1))+ #this makes the x axis labels up and down instead of side to side to prevent overlapping
 annotate("text", x = Inf, y = Inf, label = paste("  "), vjust = 1, hjust = 1, size=3)+
  ggtitle("All controls - random")
gg_controls

#the random subset seems really representative! so let's proceed using it

```

```{r graph the new data by sym state}

gg_pam_plot_apovsym <- ggplot(pam_controls_merged_RANDOM, aes(x = N_species_dose, y= c(PAM_delta), color = sym_state))+
  geom_boxplot(size = .5) +
  geom_jitter() +
   theme(
  axis.text.x = element_text(size = 16),
   axis.title.x = element_text(size = 20),
  axis.text.y = element_text(size = 20),
   axis.title.y = element_text(size = 20)) +
    theme(legend.position = "right",
          legend.text= element_text(size=18),
          legend.background = element_blank())+
    ylim(-.2,0.2) +
 ylab("Change in Fv/Fm")+
  ggtitle("Jittered apo vs. sym - new random controls")+
   scale_x_discrete("Dose", labels=c(CNTRL_0="Control", A_5="Ambient", A_7.5="Intermediate", A_10="High"))+
    scale_color_manual("Sym state", labels=c(A="Aposymbiotic", S="Symbiotic"), values=c("darkgray", "sienna")) #gives you the colors for each point on the graph
gg_pam_plot_apovsym
```


