---
title: "Respirometry data analysis (NITRATE) C. Fleming Last updated: 2/20/23"
output:
  pdf_document: default
  html_notebook: default
authors: Caroline Fleming

#Some resources:
  #https://rstudio-pubs-static.s3.amazonaws.com/63556_e35cc7e2dfb54a5bb551f3fa4b3ec4ae.html

#### NITRATE ####
---

```{r Install required packages}
require("knitr")

#install.packages("lmerTest")
library("lmerTest")
#install.packages("Matrix")
library("Matrix")
#install.packages("lme4")
library("lme4")
#install.packages("emmeans")
library("emmeans")
#install.packages("pbkrtest")
library("pbkrtest")
library("tidyverse")
library("performance")
#install.packages("see")
library("see")
#install.packages("ggrepel")
library("ggrepel")
#install.packages("sjPlot") #for visualizing linear models
library(sjPlot)
#install.packages("MASS")
library(MASS)
#install.packages("glmmTMB") # for visualizing model checks
library(glmmTMB)
#install.packages("relaimpo") #for quantifying the effects of predictor variables
library(relaimpo)
#install.packages("outliers") #for checking out whether a data point is an outlier
library(outliers)
library(Rmisc)
#install.packages("ggeffects")
library(ggeffects)

#turn off scientific notation
options(scipen=999)

#let dplyr print a bunch of numbers
options(dplyr.print_max = 1e9)
options(max.print = 10000)   

```


```{r Set working directory and upload data - NITRATE DATA ONLY}
#opts_knit$set(root.dir = "C:/Users/carol/Documents/PhD Boston University 2019-/Chapter_2_Ecotox/Summer_2022_N_Ecotox/N_Ecotox_Chapter_2_ANALYSIS/Astrangia_nutrient_stressors_Rotjan_lab")
#getwd()
resp_all.data <- read.csv("RESP_ALL_SUMMARY_cleaned_dead_and_broken_outlierG28Y65_deleted_2_17_23.csv", header=TRUE, sep=",",stringsAsFactors = FALSE)
resp_all.data<-na.omit(resp_all.data)

resp_all_nitrate.data <- subset(resp_all.data, resp_all.data$N_species=="N" | resp_all.data$N_species=="CNTRL")

hist(resp_all_nitrate.data$resp_rate)
qqnorm(resp_all_nitrate.data$resp_rate)

#make sure treatID is a character
resp_all_nitrate.data$treat_ID_full<-as.character(resp_all_nitrate.data$treat_ID_full)

#adding a log transformed resp rate
resp_all_nitrate.data$log_resp_rate<-abs(resp_all_nitrate.data$resp_rate)
resp_all_nitrate.data$log_resp_rate<-log(resp_all_nitrate.data$log_resp_rate)
resp_all_nitrate.data$arcsin_resp_rate<-asin(resp_all_nitrate.data$resp_rate)

#testing for normality
#TESTING FOR NORMALITY IN PAM_delta
#install new package to see what the best transformation is
#install.packages("bestNormalize")
library("bestNormalize")
bestNormalize(resp_all_nitrate.data$resp_rate)
#in order for this to work I need to change the PAM_delta in to a vector
resp_all_nitrate.data$resp_rate_vector<-as.vector(resp_all_nitrate.data$resp_rate_vector)
#then I run the orderNorm command into a new object
orderNormobj_resp_rate<-orderNorm(resp_all_nitrate.data$resp_rate)
#this object gives us what we want, but we have to index from that object and put it in a new column
resp_all_nitrate.data$ordernorm_resp_rate<-orderNormobj_resp_rate$x.t

# Essential subsets
all_20C<-subset(resp_all_nitrate.data, resp_all_nitrate.data$temp==20)
all_30C<-subset(resp_all_nitrate.data, resp_all_nitrate.data$temp==30)
all_apo<-subset(resp_all_nitrate.data, resp_all_nitrate.data$sym_state=="A")
all_sym<-subset(resp_all_nitrate.data, resp_all_nitrate.data$sym_state=="S")
e_coli<-subset(resp_all_nitrate.data, resp_all_nitrate.data$e_coli_plate=="1")
no_e_coli<-subset(resp_all_nitrate.data, resp_all_nitrate.data$e_coli_plate=="0")
```
```{r checking some things out}
#Im on line 1652 of Sarah's code
#https://github.com/speroffs/A.Poculata-Multiple-stressors-thesis-analysis-/blob/main/Respiration/Respiration.RMD
N_species_dose_lm <- lm(resp_rate~N_species_dose, data=resp_all_nitrate.data)
summary(N_species_dose_lm)
# Summarize by N_species_dose
N_species_dose.sum1 <- summarySE(resp_all_nitrate.data, measurevar = "resp_rate", groupvars = c("N_species_dose"))
# Visualize
ggplot(data = N_species_dose.sum1,
       aes(x = N_species_dose,
           y = resp_rate)) +
    geom_point() +
    geom_errorbar(aes(ymin=resp_rate-se, ymax=resp_rate+se), width=0.1, size = 1) +
    #scale_color_manual(values = c("black", "darkgreen")) +
    ggtitle ("Nitrate Dose") +
    theme(legend.position = "right",
          legend.title = element_text(size=12),
          axis.title = element_text(size = 12),
          legend.background = element_blank(),
          panel.grid.major = element_blank(), 
          panel.grid.minor = element_blank(),
          axis.text = element_text(size = 12)) +
    labs(x = "\n", 
         y = expression(paste("Rate O2 Consumption (umol*min"^"-1"~"*g"^"-1"~")")), 
         caption = "data represent mean +/- SEM" ) +
    theme_classic()
```


```{r All subsets and some preliminary t tests}
control_all_20<-subset(resp_all_nitrate.data, resp_all_nitrate.data$N_dose=="0" & resp_all_nitrate.data$temp=="20")
control_ecoli_20<-subset(resp_all_nitrate.data, resp_all_nitrate.data$N_dose=="0" & resp_all_nitrate.data$temp=="20" & resp_all_nitrate.data$e_coli=="1")
control_no_ecoli_20<-subset(resp_all_nitrate.data, resp_all_nitrate.data$N_dose=="0" & resp_all_nitrate.data$temp=="20" & resp_all_nitrate.data$e_coli=="0")
control_all_30<-subset(resp_all_nitrate.data, resp_all_nitrate.data$N_dose=="0" & resp_all_nitrate.data$temp=="30")
control_ecoli_30<-subset(resp_all_nitrate.data, resp_all_nitrate.data$N_dose=="0" & resp_all_nitrate.data$temp=="30" & resp_all_nitrate.data$e_coli=="1")
control_no_ecoli_30<-subset(resp_all_nitrate.data, resp_all_nitrate.data$N_dose=="0" & resp_all_nitrate.data$temp=="30" & resp_all_nitrate.data$e_coli=="0")
A_5_20 <-subset(resp_all_nitrate.data, resp_all_nitrate.data$N_species=="A"& resp_all_nitrate.data$N_dose=="5" & resp_all_nitrate.data$temp=="20")
A_5_30 <- A_5_20 <-subset(resp_all_nitrate.data, resp_all_nitrate.data$N_species=="A"& resp_all_nitrate.data$N_dose=="5" & resp_all_nitrate.data$temp=="30")
A_7.5_20 <-subset(resp_all_nitrate.data, resp_all_nitrate.data$N_species=="A"& resp_all_nitrate.data$N_dose=="7.5" & resp_all_nitrate.data$temp=="20")
A_7.5_30 <- A_5_20 <-subset(resp_all_nitrate.data, resp_all_nitrate.data$N_species=="A"& resp_all_nitrate.data$N_dose=="7.5" & resp_all_nitrate.data$temp=="30")
A_10_20 <-subset(resp_all_nitrate.data, resp_all_nitrate.data$N_species=="A"& resp_all_nitrate.data$N_dose=="10" & resp_all_nitrate.data$temp=="20")
A_10_30 <- A_5_20 <-subset(resp_all_nitrate.data, resp_all_nitrate.data$N_species=="A"& resp_all_nitrate.data$N_dose=="10" & resp_all_nitrate.data$temp=="30")
N_1.5_20 <-subset(resp_all_nitrate.data, resp_all_nitrate.data$N_species=="N"& resp_all_nitrate.data$N_dose=="1.5" & resp_all_nitrate.data$temp=="20")
N_1.5_30 <- A_5_20 <-subset(resp_all_nitrate.data, resp_all_nitrate.data$N_species=="N"& resp_all_nitrate.data$N_dose=="1.5" & resp_all_nitrate.data$temp=="30")
N_5_20 <-subset(resp_all_nitrate.data, resp_all_nitrate.data$N_species=="N"& resp_all_nitrate.data$N_dose=="5" & resp_all_nitrate.data$temp=="20")
N_5_30 <- A_5_20 <-subset(resp_all_nitrate.data, resp_all_nitrate.data$N_species=="N"& resp_all_nitrate.data$N_dose=="5" & resp_all_nitrate.data$temp=="30")
N_18_20 <-subset(resp_all_nitrate.data, resp_all_nitrate.data$N_dose=="18" & resp_all_nitrate.data$temp=="20")
N_18_30 <-subset(resp_all_nitrate.data, resp_all_nitrate.data$N_dose=="18" & resp_all_nitrate.data$temp=="30")
e_coli<-subset(resp_all_nitrate.data, resp_all_nitrate.data$e_coli==1)
no_e_coli<-subset(resp_all_nitrate.data, resp_all_nitrate.data$e_coli==0)
N_18_30_e_coli <-subset(resp_all_nitrate.data, resp_all_nitrate.data$N_dose=="18" & resp_all_nitrate.data$temp=="30" & resp_all_nitrate.data$e_coli==1)

#e coli controls
t.test(control_ecoli_30$resp_rate, control_no_ecoli_20$resp_rate) #no difference

# Control 20 v control 30
t.test(control_all_20$resp_rate, control_all_30$resp_rate)
# A 5 20 v A 5 30
t.test(A_5_20$resp_rate, A_5_30$resp_rate)
# A 7.5 20 v A 7.5 30
t.test(A_7.5_20$resp_rate, A_7.5_30$resp_rate)
# Control 20 v. A10 20
t.test(control_all_20$resp_rate, A_10_20$resp_rate)
# Control 30 v. A10 30
t.test(control_all_30$resp_rate, A_10_30$resp_rate)
# A10 20 v A10 30
t.test(A_10_20$resp_rate, A_10_30$resp_rate)
# N 1.5 20 v N 1.5 30
t.test(N_1.5_20$resp_rate, N_1.5_30$resp_rate)
# N 5 20 v N 5 30
t.test(N_5_20$resp_rate, N_5_30$resp_rate)
# Control 20 v. N18 20
t.test(control_all_20$resp_rate, N_18_20$resp_rate)
# Control 30 v. Control N18 30
t.test(control_all_30$resp_rate, N_18_30$resp_rate)

# e coli vs. no ecoli 
t.test(e_coli$resp_rate, no_e_coli$resp_rate)
# N 18 e coli 30 vs. control 30
t.test(control_all_30$resp_rate, N_18_30_e_coli$resp_rate)
       
```



#Linear models

```{r linear models - ALL NITRATE DATA}
mm_resp_null <- lmer(resp_rate ~ 1 + (1|vial_ID) + (1|col_num) + (1|exp_num) +(1|exp_subrun) +(1|jar_unique_ID) + (1|resp_run) , data= resp_all_nitrate.data)
summary(mm_resp_null)
#that null looks good

#full model with all interactions possible
mm_resp_1 <- lmer(resp_rate ~  N_species_dose + temp + food + sym_state + e_coli_plate + N_species_dose*temp + N_species_dose*food + N_species_dose*sym_state + N_species_dose*e_coli_plate + temp*food + temp*sym_state + temp*e_coli_plate + food*sym_state + food*e_coli_plate + sym_state*e_coli_plate + (1|vial_ID) +  (1|col_num) + (1|exp_num) + (1|exp_subrun), data= resp_all_nitrate.data)
#summary(mm_resp_1)
#WARNING:
# boundary (singular) fit: see help('isSingular')
help('isSingular')

# OKAY NOW LETS TRY TO DO A STEPWISE LINEAR REGRESSION A LA RANDI's SUGGESTION
# This stepwise function includes random effects, but does not like random effects that cause singularity so I had to get rid of a bunch of them
full.model <- lmer(resp_rate ~  N_species_dose + temp + food + sym_state + e_coli_plate + N_species_dose*temp + N_species_dose*food + N_species_dose*sym_state + N_species_dose*e_coli_plate + temp*food + temp*sym_state + temp*e_coli_plate + food*sym_state + food*e_coli_plate + sym_state*e_coli_plate +  + (1|vial_ID) +  (1|col_num) + (1|exp_num) + (1|exp_subrun), data= resp_all_nitrate.data)
print(step.model<- step(full.model))

#The model did NOT select sym_state as informative, but because it is marginally significant (p value of 0.054) we should keep it in

# here is the model that it recommends
mm_resp_2 <- lmer(resp_rate ~ N_species_dose + temp + sym_state + e_coli_plate + (1 | col_num) + (1 | exp_num), data=resp_all_nitrate.data)
summary(mm_resp_2)

#it says to get rid of sym state, but it has a p value of 0.054 and we know it is biologically significant so we will keep it in
mm_resp_2_changing_randoms <- lmer(resp_rate ~ temp + sym_state + e_coli_plate +  (1|exp_subrun) , data= resp_all_nitrate.data)
summary(mm_resp_changing_randoms)
#it looks like exp_subrun is causing the singularity
AIC(mm_resp_2,mm_resp_2_changing_randoms)

    # Question: is there a dose of nitrate where we see a statistically significant effect on respiration?
#Pairwise for N_species_dose
emm_resp_2_N_species_dose=emmeans(mm_resp_2, specs=pairwise ~ N_species_dose)
summary(emm_resp_2_N_species_dose)
# contrast         estimate       SE  df t.ratio p.value
# CNTRL_0 - N_1.5 -0.000317 0.000200 394  -1.584  0.3890
# CNTRL_0 - N_18   0.000423 0.000220 400   1.926  0.2187
# CNTRL_0 - N_5    0.000146 0.000208 400   0.705  0.8952
# N_1.5 - N_18     0.000740 0.000245 379   3.019  0.0143
# N_1.5 - N_5      0.000463 0.000234 376   1.983  0.1963
# N_18 - N_5      -0.000277 0.000248 374  -1.117  0.6792
# Not really -- potentially there is a difference between N1.5 and N18 but there is no difference between N0 and N18

    # Question: do corals that experienced heat stress have statistically significant different respiration?
#pairwise for temp
emm_resp_2_temp=emmeans(mm_resp_2, specs=pairwise ~ temp)
summary(emm_resp_2_temp)
# contrast         estimate       SE  df t.ratio p.value
# temp20 - temp30 -0.000394 0.000154 406  -2.561  0.0108
    # Answer: Yes! Corals at 30C respired less than those at 20C.
mean(all_20C$resp_rate, na.rm=TRUE)
#-0.004391691 #respired more than 30C
mean(all_30C$resp_rate, na.rm=TRUE)
#-0.004115614

# Question: do sym versus apo have statistically significant different respiration?
#pairwise for sym state
emm_resp_2_sym_state=emmeans(mm_resp_2, specs=pairwise ~ sym_state)
summary(emm_resp_2_sym_state)
# contrast estimate       SE  df t.ratio p.value
# A - S    0.000361 0.000188 260   1.915  0.0566
  #Answer: symbiotic colonies respired marginally more than aposymbiotic colonies.
mean(all_apo$resp_rate, na.rm=TRUE)
#-0.004043973
mean(all_sym$resp_rate, na.rm=TRUE)
# -0.004452824 #respired more than apo

# Question: do E. coli versus no e coli have statistically significant different respiration?
#pairwise for e coli
emm_resp_2_e_coli=emmeans(mm_resp_2, specs=pairwise ~ e_coli_plate)
summary(emm_resp_2_e_coli)
# contrast                      estimate       SE  df t.ratio p.value
# e_coli_plate0 - e_coli_plate1 0.000371 0.000169 400   2.196  0.0286
  #Answer: E. coli plates respired more than plates without e coli.
mean(e_coli$resp_rate, na.rm=TRUE)
# -0.00441 #respired more than no_e_coli
mean(no_e_coli$resp_rate, na.rm=TRUE)
# -0.004084725




#  CHECKING MODEL FITNESS AND VISUALIZING MODEL for our winning model mm_resp_2
#checking for model fit
plot(mm_resp_2) #homogeneity of variance,looks okay--they are relatively distributed around 0
r2(mm_resp_2) #marginal id variance just by fixed factors, conditional includes variance explained by random factor
  # treatment explains 5% of variation
  # Random effects 27.3% genetic effect 
# !!!!!!!!!!!!! WEE WOO LOOK INTO THIS !!!!!!!!!!!!!!!!!!
check_collinearity(mm_resp_2) #check for predictor variables are correlated #Low correllation
check_outliers(mm_resp_2) #it looks like there might be an outlier so let's look into this
grubbs.test(resp_all_nitrate.data$resp_rate) #we fixed this and got rid of G28Y65_exp1A, no more outlier :)

check_heteroscedasticity(mm_resp_2) #heteroscadasticity detected
check_homogeneity(mm_resp_2) #variances different between groups
check_autocorrelation(mm_resp_2) #all good, there is independence
#Now this command will plot all of our model diagnostics to visualize them
plot_model(mm_resp_2, type="diag") #everything looks pretty good
#lowest value -0.0125 is an outlier, this is polyp G28Y65_exp1A

#checking out the contribution of each variable to the mode
summary(mm_resp_2)$coef
#we can just interpret t as an index of how important the effect is without trying to use some p-value to describe it

#looking at just the random effect part of the model
VarCorr(mm_resp_2) #not really sure how to interpret this

plot_model(mm_resp_2, "eff") # plots the predicted effects of each variable on respiration rate 
plot_model(mm_resp_2, type="re") # plots random effects

plot_model(mm_resp_2)
tab_model(mm_resp_2, digits=7) #adding digits tells it to include more decimal places

#let's try using the package relaimpo to give us a sense of the relative contribution of each variable to the model
# link for info on this package: https://advstats.psychstat.org/book/mregression/importance.php
library(relaimpo)
lm_resp_2_relimp <- lm(resp_rate ~ factor(N_species_dose) + factor(sym_state) + factor(temp) + 
    factor(e_coli_plate), data = resp_all_nitrate.data) #for some reason this code would not run unless I treated them as factors
calc.relimp(lm_resp_2_relimp, type="lmg", rela=TRUE)
#need to identify exactly what lmg means
```




```{r linear models - E. COLI NITRATE DATA}

mm_resp_e_coli_null <- lmer(resp_rate ~ 1 + (1|vial_ID) + (1|col_num) + (1|exp_num) +(1|exp_subrun) +(1|jar_unique_ID) + (1|resp_run) , data= e_coli)
summary(mm_resp_e_coli_null)

#full model with all interactions possible
mm_resp_e_coli_1 <- lmer(resp_rate ~  N_species_dose + temp + food + sym_state + N_species_dose*temp + N_species_dose*food + N_species_dose*sym_state + temp*food + temp*sym_state + food*sym_state + (1|vial_ID) +  (1|col_num) + (1|exp_num) + (1|exp_subrun), data= e_coli)
summary(mm_resp_1)
#WARNING:
# boundary (singular) fit: see help('isSingular')
help('isSingular')

# OKAY NOW LETS TRY TO DO A STEPWISE LINEAR REGRESSION A LA RANDI's SUGGESTION
# This stepwise function includes random effects, but does not like random effects that cause singularity so I had to get rid of a bunch of them
full.model <- lmer(resp_rate ~  N_species_dose + temp + food + sym_state + N_species_dose*temp + N_species_dose*food + N_species_dose*sym_state + temp*food + temp*sym_state + food*sym_state + (1|vial_ID) +  (1|col_num) + (1|exp_num) + (1|exp_subrun), data= e_coli)
print(step.model<- step(full.model))

#The model did NOT select sym_state as informative, but because it is marginally significant (p value of 0.067) we should keep it in

# here is the model that it recommends
mm_resp_e_coli_2 <- lmer(resp_rate ~ N_species_dose + temp + sym_state + (1 | col_num) + (1 | exp_num), data=e_coli)
summary(mm_resp_e_coli_2)

#Model Interaction plot - NITRATE
int<-lmer(resp_rate~N_species_dose*temp*food*sym_state+(1|col_num), data=e_coli)
summary(int)
int_pred <- ggemmeans(int, terms=c("N_species_dose", "temp","sym_state","food")) # I cannot do more than 4 interactions 
pred <- ggplot(int_pred, aes(facet,predicted, colour = group)) +
  geom_point(aes(shape = x)) +
  geom_errorbar(aes(ymin = conf.low, ymax = conf.high), width = 0.3) +
  labs(x = "Symbiotic State", y = "Rate O2 Consumption (umol*min-1*g-1)",
       color = "temp") +
  facet_grid(~panel) +
  ggtitle("test") +
  theme_classic() +
  theme(axis.title.x = element_text(color="black", size=12),
axis.title.y = element_text(color="black", size=12))+
  theme(axis.text.x = element_text(size=12),
          axis.text.y = element_text(size=12)) +
  scale_color_manual(values=c("black", "goldenrod"))
pred

# Question: is there a dose of nitrate where we see a statistically significant effect on respiration?
#Pairwise for N_species_dose
mm_resp_e_coli_2_N_species_dose=emmeans(mm_resp_e_coli_2, specs=pairwise ~ N_species_dose*sym_state)
summary(mm_resp_e_coli_2_N_species_dose)
# $contrasts
#  contrast         estimate       SE  df t.ratio p.value
#  CNTRL_0 - N_1.5  0.000169 0.000266 200   0.634  0.9208
#  CNTRL_0 - N_18   0.000872 0.000284 198   3.074  0.0128
#  CNTRL_0 - N_5    0.000460 0.000274 195   1.676  0.3390
#  N_1.5 - N_18     0.000704 0.000319 184   2.207  0.1252
#  N_1.5 - N_5      0.000291 0.000313 186   0.932  0.7877
#  N_18 - N_5      -0.000412 0.000322 175  -1.282  0.5756

#Interesting! There N_18 corals respired MORE than controls. Perhaps metabolic stress?
# Summarize by N_species_dose so we can visualize
e_coli_sum_N_species_dose <- summarySE(e_coli, measurevar = "resp_rate", groupvars = c("N_species_dose"))
e_coli_sum_N_species_dose
# Visualize
ggplot(data = e_coli_sum_N_species_dose,
       aes(x = N_species_dose,
           y = resp_rate)) +
    geom_point() +
    geom_errorbar(aes(ymin=resp_rate-se, ymax=resp_rate+se), width=0.1, size = 1) +
    #scale_color_manual(values = c("black", "darkgreen")) +
    ggtitle ("Nitrate E. Coli - N Species Dose") +
    theme(legend.position = "right",
          legend.title = element_text(size=12),
          axis.title = element_text(size = 12),
          legend.background = element_blank(),
          panel.grid.major = element_blank(), 
          panel.grid.minor = element_blank(),
          axis.text = element_text(size = 12)) +
    labs(x = "\n", 
         y = expression(paste("Rate O2 Consumption (umol*min"^"-1"~"*g"^"-1"~")")), 
         caption = "data represent mean +/- SEM" ) +
    theme_classic()

#Plot model estimate for N_species_dose # I am not sure how interesting this is, but here is the code if we want it
l=plot_model(mm_resp_e_coli_2, 'pred', ci.lvl = 0.95, terms="N_species_dose")
l +
  theme_classic() +
xlab("N species dose")+
  ylab("Rate O2 Consumption (umol*min-1*g-1)")+
  ggtitle("")+
  theme(axis.title.x = element_text(color="black", size=14, face="bold"),
axis.title.y = element_text(color="black", size=14, face="bold"))+
  theme(axis.text.x = element_text(size=14),
          axis.text.y = element_text(size=14))
# plot model estimate for temp
t=plot_model(mm_resp_e_coli_2, 'pred', ci.lvl = 0.95, terms="N_species_dose")
t

    # Question: do corals that experienced heat stress have statistically significant different respiration?
#pairwise for temp
mm_resp_e_coli_2_temp=emmeans(mm_resp_e_coli_2, specs=pairwise ~ temp)
summary(mm_resp_e_coli_2_temp)
 # contrast         estimate       SE  df t.ratio p.value
 # temp20 - temp30 -0.000445 0.000203 202  -2.196  0.0292
    # Answer: Yes! Corals at 30C respired LESS than those at 20C.
# Summarize by Temperature
e_coli_sum_temp<- summarySE(e_coli, measurevar = "resp_rate", groupvars = c("temp"))
e_coli_sum_temp
# Visualize
ggplot(data = e_coli_sum_temp,
       aes(x = temp,
           y = resp_rate)) +
    geom_point() +
    geom_errorbar(aes(ymin=resp_rate-se, ymax=resp_rate+se), width=0.1, size = 1) +
    #scale_color_manual(values = c("black", "darkgreen")) +
    ggtitle ("Nitrate E. Coli - Temperature") +
    theme(legend.position = "right",
          legend.title = element_text(size=12),
          axis.title = element_text(size = 12),
          legend.background = element_blank(),
          panel.grid.major = element_blank(), 
          panel.grid.minor = element_blank(),
          axis.text = element_text(size = 12)) +
    labs(x = "\n", 
         y = expression(paste("Rate O2 Consumption (umol*min"^"-1"~"*g"^"-1"~")")), 
         caption = "data represent mean +/- SEM" ) +
    theme_classic()


# Question: do sym versus apo have statistically significant different respiration?
#pairwise for sym state
mm_resp_e_coli_2_sym_state=emmeans(mm_resp_e_coli_2, specs=pairwise ~ sym_state)
summary(emm_resp_2_sym_state)
# contrast estimate       SE  df t.ratio p.value
# A - S    0.000361 0.000188 260   1.915  0.0566
  #Answer: symbiotic colonies respired marginally more than aposymbiotic colonies.
# Summarize by Symbiotic State
e_coli_sum_sym_state<- summarySE(e_coli, measurevar = "resp_rate", groupvars = c("sym_state"))
# Visualize
ggplot(data =e_coli_sum_sym_state,
       aes(x = sym_state,
           y = resp_rate)) +
    geom_point() +
    geom_errorbar(aes(ymin=resp_rate-se, ymax=resp_rate+se), width=0.1, size = 1) +
    #scale_color_manual(values = c("black", "darkgreen")) +
    ggtitle ("Nitrate E. Coli - Symbiotic State") +
    theme(legend.position = "right",
          legend.title = element_text(size=12),
          axis.title = element_text(size = 12),
          legend.background = element_blank(),
          panel.grid.major = element_blank(), 
          panel.grid.minor = element_blank(),
          axis.text = element_text(size = 12)) +
    labs(x = "\n", 
         y = expression(paste("Rate O2 Consumption (umol*min"^"-1"~"*g"^"-1"~")")), 
         caption = "data represent mean +/- SEM" ) +
    theme_classic()


# I THINK WE SHOULD LEAVE IT AT THIS LEVEL AND GET ALL OF OUR TAKE HOMES FROM THIS, BUT I'LL DO SOME MORE ANALYSES FOR KICKS

```

```{r Linear models grouping by food and sym state}

# Overall food and symbiotic state
mm_food_sym<- lmer(resp_rate ~  food_sym_state + (1|vial_ID) +  (1|col_num) + (1|exp_num) + (1|exp_subrun), data= resp_all_nitrate.data)
summary(mm_food_sym)
emm_food_sym<-emmeans(mm_food_sym, pairwise ~ food_sym_state)
summary(emm_e_coli_food_sym)
#No pairwise differences 
print(step.model<- step(mm_e_coli_food_sym))


# E coli food and symbiotic state
mm_e_coli_food_sym<- lmer(resp_rate ~  food_sym_state + (1|vial_ID) +  (1|col_num) + (1|exp_num) + (1|exp_subrun), data= e_coli)
summary(mm_e_coli_food_sym)
emm_e_coli_food_sym<-emmeans(mm_e_coli_food_sym, pairwise ~ food_sym_state)
summary(emm_e_coli_food_sym)
#No pairwise differences 
print(step.model<- step(mm_e_coli_food_sym))
#nothing really significant


# NO E coli food and symbiotic state
mm_no_e_coli_food_sym<- lmer(resp_rate ~  food_sym_state + (1|vial_ID) +  (1|col_num) + (1|exp_num) + (1|exp_subrun), data= no_e_coli)
summary(mm_no_e_coli_food_sym)
emm_no_e_coli_food_sym<-emmeans(mm_no_e_coli_food_sym, pairwise ~ food_sym_state)
summary(emm_no_e_coli_food_sym)
#No pairwise differences 
print(step.model<- step(mm_no_e_coli_food_sym))
#nothing really significant



```



```{r linear models - E. COLI NITRATE BY TEMPERATURE}
e_coli_20C<-subset(resp_all_nitrate.data, resp_all_nitrate.data$temp==20 & resp_all_nitrate.data$e_coli_plate=="1")
e_coli_30C<-subset(resp_all_nitrate.data, resp_all_nitrate.data$temp==30 & resp_all_nitrate.data$e_coli_plate=="1")

# Nitrate E. coli at 20C
full.model_e_coli_20C <- lmer(resp_rate ~  N_species_dose + food + sym_state + N_species_dose*food + N_species_dose*sym_state +  food*sym_state + (1|vial_ID) +  (1|col_num) + (1|exp_num) + (1|exp_subrun), data= e_coli_20C)
summary(full.model_e_coli_20C)
print(step.model<- step(full.model_e_coli_20C))
# The model the program picked: 
mm_e_coli_20C <- lmer(resp_rate ~ (1 | col_num) + (1 | exp_num), data=e_coli_20C) #NO SIGNIFICANT FACTORS

# Nitrate E. coli at 30C
full.model_e_coli_30C <- lmer(resp_rate ~  N_species_dose + food + sym_state + N_species_dose*food + N_species_dose*sym_state +  food*sym_state + (1|vial_ID) +  (1|col_num) + (1|exp_num) + (1|exp_subrun), data= e_coli_30C)
summary(full.model_e_coli_30C)
print(step.model<- step(full.model_e_coli_30C))
# The model the program picked: 
mm_e_coli_30C <- lmer(resp_rate ~ (1 | col_num), data=e_coli_30C) #NO SIGNIFICANCE
mm_e_coli_30C_test <- lmer(resp_rate ~ sym_state + N_species_dose + (1 | col_num), data=e_coli_30C)
summary(mm_e_coli_30C_test)

mm_resp_e_coli_30C_N_species_dose=emmeans(mm_e_coli_30C_test, specs=pairwise ~ N_species_dose)
summary(mm_resp_e_coli_30C_N_species_dose)
```


```{r linear models - NO E. COLI NITRATE DATA}

mm_resp_no_e_coli_null <- lmer(resp_rate ~ 1 + (1|vial_ID) + (1|col_num) + (1|exp_num) +(1|exp_subrun) +(1|jar_unique_ID) + (1|resp_run) , data= no_e_coli)
summary(mm_resp_no_e_coli_null)

#full model with all interactions possible
mm_resp_no_e_coli_1 <- lmer(resp_rate ~  N_species_dose + temp + food + sym_state + N_species_dose*temp + N_species_dose*food + N_species_dose*sym_state + temp*food + temp*sym_state + food*sym_state + (1|vial_ID) +  (1|col_num) + (1|exp_num) + (1|exp_subrun), data= no_e_coli)
summary(mm_resp_no_e_coli_1)
#WARNING:
# boundary (singular) fit: see help('isSingular')
help('isSingular')

# OKAY NOW LETS TRY TO DO A STEPWISE LINEAR REGRESSION A LA RANDI's SUGGESTION
# This stepwise function includes random effects, but does not like random effects that cause singularity so I had to get rid of a bunch of them
full.model <- lmer(resp_rate ~  N_species_dose + temp + food + sym_state + N_species_dose*temp + N_species_dose*food + N_species_dose*sym_state + temp*food + temp*sym_state + food*sym_state + (1|vial_ID) +  (1|col_num) + (1|exp_num) + (1|exp_subrun), data= no_e_coli)
print(step.model<- step(full.model))

#The model did NOT select sym_state as informative, but because it is marginally significant (p value of 0.067) we should keep it in

# here is the model that it recommends
mm_resp_no_e_coli_2 <- lmer(resp_rate ~  (1 | col_num), data=no_e_coli)

## YIKES! NOTHING SIGNIFICANT! INTERESTING

```

```{r Looking at Nitrate 18uM}
# We found in the above analyses that there was a statistically significant difference between Control and 18uM under E. coli. Let's zoom out and look at 18uM and see what might be driving that model 

#QUESTION: For corals at 18uM nitrate, is there a significant difference if you are 1) fed vs starved? NO 2) E. coli vs. no E. coli? No, but it looks close 3) sym vs apo? NO  4) 20 vs. 30C? NO

all_18uM<-subset(resp_all_nitrate.data, resp_all_nitrate.data$N_species_dose=="N_18")

full.model_all_18uM <- lmer(resp_rate ~ e_coli_plate + temp + food + sym_state + e_coli_plate*temp + e_coli_plate*food + e_coli_plate*sym_state + temp*food + temp*sym_state + food*sym_state + (1|vial_ID) +  (1|col_num) + (1|exp_num) + (1|exp_subrun), data= all_18uM)
summary(full.model_all_18uM)
print(step.model<- step(full.model_all_18uM))

#model it recommends:
mm_all_18uM<-lmer(resp_rate ~ e_coli_plate + temp + food + sym_state + (1 | col_num) + e_coli_plate:temp + e_coli_plate:food + e_coli_plate:sym_state, data=all_18uM)
summary(mm_all_18uM) # E. coli seems to be driving the model
#posthocs
emm_all_18uM_sym_state <- emmeans(mm_all_18uM, pairwise ~ sym_state)
summary(emm_all_18uM_sym_state)

#let's try it just on E. coli data at 18uM

e_coli_18uM<-subset(resp_all_nitrate.data, resp_all_nitrate.data$N_species_dose=="N_18" & resp_all_nitrate.data$e_coli_plate==1)
full.model_e_coli_18uM <- lmer(resp_rate ~ temp + food + sym_state + temp*food + temp*sym_state + food*sym_state + (1|vial_ID) +  (1|col_num) + (1|exp_num) + (1|exp_subrun), data= e_coli_18uM)
summary(full.model_e_coli_18uM)
print(step.model<- step((full.model_e_coli_18uM)))

summary(aov(e_coli_18uM$resp_rate ~ e_coli_18uM$temp))


#Maybe let's graph 18uM and see what comes out
lm_all_18uM<- lm(resp_rate~e_coli_plate + temp + food + sym_state, data=all_18uM)
summary(lm_all_18uM)
# Summarize by E. coli -- it looks like there is a difference here, but it just doesn't come out as significant
all_18uM_sum_e_coli <- summarySE(all_18uM, measurevar = "resp_rate", groupvars = c("e_coli_plate"))
# Summarize by food
all_18uM_sum_food <- summarySE(all_18uM, measurevar = "resp_rate", groupvars = c("food"))
# Summarize by sym-state
all_18uM_sum_sym_state <- summarySE(all_18uM, measurevar = "resp_rate", groupvars = c("sym_state"))
# Summarize by temp
all_18uM_sum_temp <- summarySE(all_18uM, measurevar = "resp_rate", groupvars = c("temp"))
# Visualize
ggplot(data = all_18uM_sum_temp,
       aes(x = temp,
           y = resp_rate)) +
    geom_point() +
    geom_errorbar(aes(ymin=resp_rate-se, ymax=resp_rate+se), width=0.1, size = 1) +
    #scale_color_manual(values = c("black", "darkgreen")) +
    ggtitle ("N 18uM - 20C vs. 30C") +
    theme(legend.position = "right",
          legend.title = element_text(size=12),
          axis.title = element_text(size = 12),
          legend.background = element_blank(),
          panel.grid.major = element_blank(), 
          panel.grid.minor = element_blank(),
          axis.text = element_text(size = 12)) +
    labs(x = "\n", 
         y = expression(paste("Rate O2 Consumption (umol*min"^"-1"~"*g"^"-1"~")")), 
         caption = "data represent mean +/- SEM" ) +
    theme_classic()

# What about 18uM treated with E. coli
# Summarize by food
e_coli_18uM_sum_food <- summarySE(e_coli_18uM, measurevar = "resp_rate", groupvars = c("food"))
# Summarize by sym-state
e_coli_18uM_sum_sym_state <- summarySE(e_coli_18uM, measurevar = "resp_rate", groupvars = c("sym_state"))
# Summarize by temp
e_coli_18uM_sum_temp <- summarySE(e_coli_18uM, measurevar = "resp_rate", groupvars = c("temp"))
# Visualize
ggplot(data = e_coli_18uM_sum_temp,
       aes(x = temp,
           y = resp_rate)) +
    geom_point() +
    geom_errorbar(aes(ymin=resp_rate-se, ymax=resp_rate+se), width=0.1, size = 1) +
    #scale_color_manual(values = c("black", "darkgreen")) +
    ggtitle ("N 18uM with E. Coli - 20C vs. 30C") +
    theme(legend.position = "right",
          legend.title = element_text(size=12),
          axis.title = element_text(size = 12),
          legend.background = element_blank(),
          panel.grid.major = element_blank(), 
          panel.grid.minor = element_blank(),
          axis.text = element_text(size = 12)) +
    labs(x = "\n", 
         y = expression(paste("Rate O2 Consumption (umol*min"^"-1"~"*g"^"-1"~")")), 
         caption = "data represent mean +/- SEM" ) +
    theme_classic()

```




```{r playing around with Sarahs code to see if there is an effect of E coli at every treatment}

#Generate a linear model and then use the log function on it
mm_resp_TREAT_ID <- lmer(resp_rate ~ treat_ID_collapsed_controls + (1|exp_num) + (1|col_num), data= resp_all_nitrate.data)
mm_resp_TREAT_ID_log<- Log(mm_resp_TREAT_ID)~e_coli_plate + (1|exp_num) + (1|col_num)
summary(mm_resp_TREAT_ID_log)

# Question: Is there a significant change of resp rate at each treatment ID under E coli?
# create grouping factor to run all linear models for each treatment at once
by_treat_all <- group_by(resp_all_nitrate.data, treat_ID_collapsed_controls)

# Create a df with the parameter coefficients of the linear models  
response.lm_all <- 
  do(by_treat_all, 
   tidy(                     
     lm(resp_rate~e_coli_plate, data= .)))
print(response.lm_all)

# TEMP
#create grouping factor to run all linear models for each treatment at once
by_treat_20C<- group_by(all_20C, treat_ID_collapsed_controls)

# Create a df with the parameter coefficients of the linear models  
response.lm_20C <- 
  do(by_treat_20C, 
   tidy(                     
     lm(resp_rate~e_coli_plate, data= .)))
response.lm_20C

# create grouping factor to run all linear models for each treatment at once
by_treat_30C<- group_by(all_30C, treat_ID_collapsed_controls)

# Create a df with the parameter coefficients of the linear models  
response.lm_30C <- 
  do(by_treat_30C, 
   tidy(                     
     lm(resp_rate~e_coli_plate, data= .)))
response.lm_30C

# SYM STATE
#create grouping factor to run all linear models for each treatment at once
by_treat_sym<- group_by(all_sym, treat_ID_collapsed_controls)

# Create a df with the parameter coefficients of the linear models  
response.lm_sym <- 
  do(by_treat_sym, 
   tidy(                     
     lm(resp_rate~e_coli_plate, data= .)))
response.lm_sym

# create grouping factor to run all linear models for each treatment at once
by_treat_apo<- group_by(all_apo, treat_ID_collapsed_controls)

# Create a df with the parameter coefficients of the linear models  
response.lm_apo <- 
  do(by_treat_apo, 
   tidy(                     
     lm(resp_rate~e_coli_plate, data= .)))
response.lm_apo

```



#Graphs and visualizations

```{r Graphs NITRATE}
#1
gg_resp_all_ecoli<-
  ggplot(e_coli, aes(x=treat_ID_full, y=resp_rate, color=col_num)) +
  geom_boxplot(width=0.8) +
  geom_jitter(width=0.15, alpha=0.9) +
 # geom_line(aes(group=e_coli_plate), col="darkgray")+
  ylab("Respirometry rate")+
  xlab("Treat ID")+
  theme(legend.position="none", plot.title = element_text(size = 9)) +
  #scale_color_manual(name = "Day of experiment",
                     #labels = c("Day 1","Day 11"),
                   # values = c("royalblue","darkorchid1"))+
 # scale_x_discrete(labels=c("Day 1","Day 11")) +
    theme(axis.text.x = element_text(angle=90, vjust=.5, hjust=1))+ #this makes the x axis labels up and down instead of side to side to prevent overlapping
 annotate("text", x = Inf, y = Inf, label = paste("  "), vjust = 1, hjust = 1, size=3)+
  ggtitle("Resp rate by treat ID - E. coli")
gg_resp_all_ecoli

#2
gg_food_sym_state_ecoli<-
  ggplot(e_coli, aes(x=food_sym_state, y=resp_rate, color=col_num)) +
  geom_boxplot(width=0.8) +
  geom_jitter(width=0.15, alpha=0.9) +
 # geom_line(aes(group=e_coli_plate), col="darkgray")+
  ylab("Respirometry rate")+
  xlab("Treat ID")+
  theme(legend.position="none", plot.title = element_text(size = 9)) +
  #scale_color_manual(name = "Day of experiment",
                     #labels = c("Day 1","Day 11"),
                   # values = c("royalblue","darkorchid1"))+
 # scale_x_discrete(labels=c("Day 1","Day 11")) +
    theme(axis.text.x = element_text(angle=90, vjust=.5, hjust=1))+ #this makes the x axis labels up and down instead of side to side to prevent overlapping
 annotate("text", x = Inf, y = Inf, label = paste("  "), vjust = 1, hjust = 1, size=3)+
  ggtitle("Resp rate by Food and Symbiotic State (Food_Symstate) - E. coli")
gg_food_sym_state_ecoli

#3
gg_resp_all_no_ecoli<-
  ggplot(no_e_coli, aes(x=treat_ID_collapsed_controls, y=resp_rate, color=col_num)) +
  geom_boxplot(width=0.8) +
  geom_jitter(width=0.15, alpha=0.9) +
 # geom_line(aes(group=e_coli_plate), col="darkgray")+
  ylab("Respirometry rate")+
  xlab("Treat ID")+
  theme(legend.position="none", plot.title = element_text(size = 9)) +
  #scale_color_manual(name = "Day of experiment",
                     #labels = c("Day 1","Day 11"),
                   # values = c("royalblue","darkorchid1"))+
 # scale_x_discrete(labels=c("Day 1","Day 11")) +
    theme(axis.text.x = element_text(angle=90, vjust=.5, hjust=1))+ #this makes the x axis labels up and down instead of side to side to prevent overlapping
 annotate("text", x = Inf, y = Inf, label = paste("  "), vjust = 1, hjust = 1, size=3)+
  ggtitle("Resp rate by treat ID - No E. coli")
gg_resp_all_no_ecoli

#4
gg_food_sym_state_no_ecoli<-
  ggplot(no_e_coli, aes(x=food_sym_state, y=resp_rate, color=col_num)) +
  geom_boxplot(width=0.8) +
  geom_jitter(width=0.15, alpha=0.9) +
 # geom_line(aes(group=e_coli_plate), col="darkgray")+
  ylab("Respirometry rate")+
  xlab("Treat ID")+
  theme(legend.position="none", plot.title = element_text(size = 9)) +
  #scale_color_manual(name = "Day of experiment",
                     #labels = c("Day 1","Day 11"),
                   # values = c("royalblue","darkorchid1"))+
 # scale_x_discrete(labels=c("Day 1","Day 11")) +
    theme(axis.text.x = element_text(angle=90, vjust=.5, hjust=1))+ #this makes the x axis labels up and down instead of side to side to prevent overlapping
 annotate("text", x = Inf, y = Inf, label = paste("  "), vjust = 1, hjust = 1, size=3)+
  ggtitle("Resp rate by Food and Symbiotic State (Food_Symstate) - No E. coli")
gg_food_sym_state_no_ecoli


#5
gg_N_species_dose_ecoli<-
  ggplot(e_coli, aes(x=N_species_dose, y=resp_rate, color=col_num)) +
  geom_boxplot(width=0.8) +
  geom_jitter(width=0.15, alpha=0.9) +
  geom_label(position="jitter", label=col_num)+
 # geom_line(aes(group=e_coli_plate), col="darkgray")+
  ylab("Respirometry rate")+
  xlab("Treat ID")+
  theme(legend.position="none", plot.title = element_text(size = 9)) +
  #scale_color_manual()+
                     #labels = c("Day 1","Day 11"),
                   # values = c("royalblue","darkorchid1"))+
 # scale_x_discrete(labels=c("Day 1","Day 11")) +
    theme(axis.text.x = element_text(angle=90, vjust=.5, hjust=1))+ #this makes the x axis labels up and down instead of side to side to prevent overlapping
 annotate("text", x = Inf, y = Inf, label = paste("  "), vjust = 1, hjust = 1, size=3)+
  ggtitle("Resp rate by N_species_dose - E. coli")
gg_N_species_dose_ecoli
?geom_label

#6
gg_N_species_dose_no_ecoli<-
  ggplot(no_e_coli, aes(x=N_species_dose, y=resp_rate, color=col_num)) +
  geom_boxplot(width=0.8) +
  geom_jitter(width=0.15, alpha=0.9) +
 # geom_line(aes(group=e_coli_plate), col="darkgray")+
  ylab("Respirometry rate")+
  xlab("Treat ID")+
  theme(legend.position="none", plot.title = element_text(size = 9)) +
  #scale_color_manual(name = "Day of experiment",
                     #labels = c("Day 1","Day 11"),
                   # values = c("royalblue","darkorchid1"))+
 # scale_x_discrete(labels=c("Day 1","Day 11")) +
    theme(axis.text.x = element_text(angle=90, vjust=.5, hjust=1))+ #this makes the x axis labels up and down instead of side to side to prevent overlapping
 annotate("text", x = Inf, y = Inf, label = paste("  "), vjust = 1, hjust = 1, size=3)+
  ggtitle("Resp rate by N_species_dose - No E. coli")
gg_N_species_dose_no_ecoli


#7
e_coli$temp<-as.factor(e_coli$temp)
gg_temp_ecoli<-
  ggplot(e_coli, aes(x=temp, y=resp_rate)) +
  geom_boxplot(width=0.8) +
  geom_jitter(width=0.15, alpha=0.9) +
 # geom_line(aes(group=e_coli_plate), col="darkgray")+
  ylab("Respirometry rate")+
  xlab("Temperature")+
  theme(legend.position="none", plot.title = element_text(size = 9)) +
  #scale_color_manual(name = "Day of experiment",
                     #labels = c("Day 1","Day 11"),
                   # values = c("royalblue","darkorchid1"))+
 # scale_x_discrete(labels=c("Day 1","Day 11")) +
    theme(axis.text.x = element_text(angle=90, vjust=.5, hjust=1))+ #this makes the x axis labels up and down instead of side to side to prevent overlapping
 annotate("text", x = Inf, y = Inf, label = paste("  "), vjust = 1, hjust = 1, size=3)+
  ggtitle("Resp rate by Temp - E. coli")
gg_temp_ecoli

#8
no_e_coli$temp<-as.factor(no_e_coli$temp)
gg_temp_no_ecoli<-
  ggplot(no_e_coli, aes(x=temp, y=resp_rate, color=col_num)) +
  geom_boxplot(width=0.8) +
  geom_jitter(width=0.15, alpha=0.9) +
 # geom_line(aes(group=e_coli_plate), col="darkgray")+
  ylab("Respirometry rate")+
  xlab("Treat ID")+
  theme(legend.position="none", plot.title = element_text(size = 9)) +
  #scale_color_manual(name = "Day of experiment",
                     #labels = c("Day 1","Day 11"),
                   # values = c("royalblue","darkorchid1"))+
 # scale_x_discrete(labels=c("Day 1","Day 11")) +
    theme(axis.text.x = element_text(angle=90, vjust=.5, hjust=1))+ #this makes the x axis labels up and down instead of side to side to prevent overlapping
 annotate("text", x = Inf, y = Inf, label = paste("  "), vjust = 1, hjust = 1, size=3)+
  ggtitle("Resp rate by Temp - No E. coli")
gg_temp_no_ecoli

#9
no_e_coli$sym_state<-as.factor(no_e_coli$sym_state)
gg_sym_state_no_ecoli<-
  ggplot(no_e_coli, aes(x=sym_state, y=resp_rate)) +
  geom_boxplot(width=0.8) +
  geom_jitter(width=0.15, alpha=0.9) +
 # geom_line(aes(group=e_coli_plate), col="darkgray")+
  ylab("Respirometry rate")+
  xlab("Treat ID")+
  theme(legend.position="none", plot.title = element_text(size = 9)) +
  #scale_color_manual(name = "Day of experiment",
                     #labels = c("Day 1","Day 11"),
                   # values = c("royalblue","darkorchid1"))+
 # scale_x_discrete(labels=c("Day 1","Day 11")) +
    theme(axis.text.x = element_text(angle=90, vjust=.5, hjust=1))+ #this makes the x axis labels up and down instead of side to side to prevent overlapping
 annotate("text", x = Inf, y = Inf, label = paste("  "), vjust = 1, hjust = 1, size=3)+
  ggtitle("Resp rate by Sym state - No E. coli")
gg_sym_state_no_ecoli

#10
e_coli$sym_state<-as.factor(e_coli$sym_state)
gg_sym_state_ecoli<-
  ggplot(e_coli, aes(x=sym_state, y=resp_rate)) +
  geom_boxplot(width=0.8) +
  geom_jitter(width=0.15, alpha=0.9) +
 # geom_line(aes(group=e_coli_plate), col="darkgray")+
  ylab("Respirometry rate")+
  xlab("Treat ID")+
  theme(legend.position="none", plot.title = element_text(size = 9)) +
  #scale_color_manual(name = "Day of experiment",
                     #labels = c("Day 1","Day 11"),
                   # values = c("royalblue","darkorchid1"))+
 # scale_x_discrete(labels=c("Day 1","Day 11")) +
    theme(axis.text.x = element_text(angle=90, vjust=.5, hjust=1))+ #this makes the x axis labels up and down instead of side to side to prevent overlapping
 annotate("text", x = Inf, y = Inf, label = paste("  "), vjust = 1, hjust = 1, size=3)+
  ggtitle("Resp rate by Sym state - No E. coli")
gg_sym_state_ecoli

```

```{r SUBSETS NO E COLI for t tests verus the control for that group}
#ammonium high 20C
sym_fed_ammonium_high_20C_no_ecoli <-subset(resp_all_nitrate.data, resp_all_nitrate.data$sym_state=="S" & resp_all_nitrate.data$food=="F" & resp_all_nitrate.data$N_dose=="10" & resp_all_nitrate.data$temp=="20"& resp_all_nitrate.data$e_coli_plate=="0"& resp_all_nitrate.data$e_coli_plate=="0")
apo_fed_ammonium_high_20C_no_ecoli <-subset(resp_all_nitrate.data, resp_all_nitrate.data$sym_state=="A" & resp_all_nitrate.data$food=="F" & resp_all_nitrate.data$N_dose=="10" & resp_all_nitrate.data$temp=="20"& resp_all_nitrate.data$e_coli_plate=="0")
sym_starved_ammonium_high_20C_no_ecoli <-subset(resp_all_nitrate.data, resp_all_nitrate.data$sym_state=="S" & resp_all_nitrate.data$food=="S" & resp_all_nitrate.data$N_dose=="10" & resp_all_nitrate.data$temp=="20"& resp_all_nitrate.data$e_coli_plate=="0")
apo_starved_ammonium_high_20C_no_ecoli <-subset(resp_all_nitrate.data, resp_all_nitrate.data$sym_state=="A" & resp_all_nitrate.data$food=="S" & resp_all_nitrate.data$N_dose=="10" & resp_all_nitrate.data$temp=="20"& resp_all_nitrate.data$e_coli_plate=="0")
#nitrate high 20C
sym_fed_nitrate_high_20C_no_ecoli <-subset(resp_all_nitrate.data, resp_all_nitrate.data$sym_state=="S" & resp_all_nitrate.data$food=="F" & resp_all_nitrate.data$N_dose=="18" & resp_all_nitrate.data$temp=="20"& resp_all_nitrate.data$e_coli_plate=="0")
apo_fed_nitrate_high_20C_no_ecoli <-subset(resp_all_nitrate.data, resp_all_nitrate.data$sym_state=="A" & resp_all_nitrate.data$food=="F" & resp_all_nitrate.data$N_dose=="18" & resp_all_nitrate.data$temp=="20"& resp_all_nitrate.data$e_coli_plate=="0")
sym_starved_nitrate_high_20C_no_ecoli <-subset(resp_all_nitrate.data, resp_all_nitrate.data$sym_state=="S" & resp_all_nitrate.data$food=="S" & resp_all_nitrate.data$N_dose=="18" & resp_all_nitrate.data$temp=="20"& resp_all_nitrate.data$e_coli_plate=="0")
apo_starved_nitrate_high_20C_no_ecoli <-subset(resp_all_nitrate.data, resp_all_nitrate.data$sym_state=="A" & resp_all_nitrate.data$food=="S" & resp_all_nitrate.data$N_dose=="18" & resp_all_nitrate.data$temp=="20"& resp_all_nitrate.data$e_coli_plate=="0")

#control 20C
sym_fed_control_20C_no_ecoli <-subset(resp_all_nitrate.data, resp_all_nitrate.data$sym_state=="S" & resp_all_nitrate.data$food=="F" & resp_all_nitrate.data$N_dose=="0" & resp_all_nitrate.data$temp=="20"& resp_all_nitrate.data$e_coli_plate=="0")
apo_fed_control_20C_no_ecoli <-subset(resp_all_nitrate.data, resp_all_nitrate.data$sym_state=="A" & resp_all_nitrate.data$food=="F" & resp_all_nitrate.data$N_dose=="0" & resp_all_nitrate.data$temp=="20"& resp_all_nitrate.data$e_coli_plate=="0")
sym_starved_control_20C_no_ecoli <-subset(resp_all_nitrate.data, resp_all_nitrate.data$sym_state=="S" & resp_all_nitrate.data$food=="S" & resp_all_nitrate.data$N_dose=="0" & resp_all_nitrate.data$temp=="20"& resp_all_nitrate.data$e_coli_plate=="0")
apo_starved_control_20C_no_ecoli <-subset(resp_all_nitrate.data, resp_all_nitrate.data$sym_state=="A" & resp_all_nitrate.data$food=="S" & resp_all_nitrate.data$N_dose=="0" & resp_all_nitrate.data$temp=="20"& resp_all_nitrate.data$e_coli_plate=="0")

#ammonium 5uM 20C
sym_fed_ammonium_5um_20C_no_ecoli <-subset(resp_all_nitrate.data, resp_all_nitrate.data$N_species=="A" & resp_all_nitrate.data$sym_state=="S"& resp_all_nitrate.data$food=="F" & resp_all_nitrate.data$N_dose=="5" & resp_all_nitrate.data$temp=="20"& resp_all_nitrate.data$e_coli_plate=="0")
apo_fed_ammonium_5um_20C_no_ecoli <-subset(resp_all_nitrate.data, resp_all_nitrate.data$N_species=="A" & resp_all_nitrate.data$sym_state=="A" & resp_all_nitrate.data$food=="F" & resp_all_nitrate.data$N_dose=="5" & resp_all_nitrate.data$temp=="20"& resp_all_nitrate.data$e_coli_plate=="0")
sym_starved_ammonium_5um_20C_no_ecoli <-subset(resp_all_nitrate.data, resp_all_nitrate.data$N_species=="A" & resp_all_nitrate.data$sym_state=="S" & resp_all_nitrate.data$food=="S" & resp_all_nitrate.data$N_dose=="5" & resp_all_nitrate.data$temp=="20"& resp_all_nitrate.data$e_coli_plate=="0")
apo_starved_ammonium_5um_20C_no_ecoli <-subset(resp_all_nitrate.data, resp_all_nitrate.data$N_species=="A" & resp_all_nitrate.data$sym_state=="A" & resp_all_nitrate.data$food=="S" & resp_all_nitrate.data$N_dose=="5" & resp_all_nitrate.data$temp=="20"& resp_all_nitrate.data$e_coli_plate=="0")
#nitrate 5um 20C
sym_fed_nitrate_5um_20C_no_ecoli <-subset(resp_all_nitrate.data, resp_all_nitrate.data$N_species=="N" & resp_all_nitrate.data$sym_state=="S" & resp_all_nitrate.data$food=="F" & resp_all_nitrate.data$N_dose=="5" & resp_all_nitrate.data$temp=="20"& resp_all_nitrate.data$e_coli_plate=="0")
apo_fed_nitrate_5um_20C_no_ecoli <-subset(resp_all_nitrate.data, resp_all_nitrate.data$N_species=="N" & resp_all_nitrate.data$sym_state=="A" & resp_all_nitrate.data$food=="F" & resp_all_nitrate.data$N_dose=="5" & resp_all_nitrate.data$temp=="20"& resp_all_nitrate.data$e_coli_plate=="0")
sym_starved_nitrate_5um_20C_no_ecoli <-subset(resp_all_nitrate.data, resp_all_nitrate.data$N_species=="N" & resp_all_nitrate.data$sym_state=="S" & resp_all_nitrate.data$food=="S" & resp_all_nitrate.data$N_dose=="5" & resp_all_nitrate.data$temp=="20"& resp_all_nitrate.data$e_coli_plate=="0")
apo_starved_nitrate_5um_20C_no_ecoli <-subset(resp_all_nitrate.data, resp_all_nitrate.data$N_species=="N" & resp_all_nitrate.data$sym_state=="A" & resp_all_nitrate.data$food=="S" & resp_all_nitrate.data$N_dose=="5" & resp_all_nitrate.data$temp=="20"& resp_all_nitrate.data$e_coli_plate=="0")

#ammonium high 30C
sym_fed_ammonium_high_30C_no_ecoli <-subset(resp_all_nitrate.data, resp_all_nitrate.data$sym_state=="S" & resp_all_nitrate.data$food=="F" & resp_all_nitrate.data$N_dose=="10" & resp_all_nitrate.data$temp=="30"& resp_all_nitrate.data$e_coli_plate=="0")
apo_fed_ammonium_high_30C_no_ecoli <-subset(resp_all_nitrate.data, resp_all_nitrate.data$sym_state=="A" & resp_all_nitrate.data$food=="F" & resp_all_nitrate.data$N_dose=="10" & resp_all_nitrate.data$temp=="30"& resp_all_nitrate.data$e_coli_plate=="0")
sym_starved_ammonium_high_30C_no_ecoli <-subset(resp_all_nitrate.data, resp_all_nitrate.data$sym_state=="S" & resp_all_nitrate.data$food=="S" & resp_all_nitrate.data$N_dose=="10" & resp_all_nitrate.data$temp=="30"& resp_all_nitrate.data$e_coli_plate=="0")
apo_starved_ammonium_high_30C_no_ecoli <-subset(resp_all_nitrate.data, resp_all_nitrate.data$sym_state=="A" & resp_all_nitrate.data$food=="S" & resp_all_nitrate.data$N_dose=="10" & resp_all_nitrate.data$temp=="30"& resp_all_nitrate.data$e_coli_plate=="0")
#nitrate high 30C
sym_fed_nitrate_high_30C_no_ecoli <-subset(resp_all_nitrate.data, resp_all_nitrate.data$sym_state=="S" & resp_all_nitrate.data$food=="F" & resp_all_nitrate.data$N_dose=="18" & resp_all_nitrate.data$temp=="30"& resp_all_nitrate.data$e_coli_plate=="0")
apo_fed_nitrate_high_30C_no_ecoli <-subset(resp_all_nitrate.data, resp_all_nitrate.data$sym_state=="A" & resp_all_nitrate.data$food=="F" & resp_all_nitrate.data$N_dose=="18" & resp_all_nitrate.data$temp=="30"& resp_all_nitrate.data$e_coli_plate=="0")
sym_starved_nitrate_high_30C_no_ecoli <-subset(resp_all_nitrate.data, resp_all_nitrate.data$sym_state=="S" & resp_all_nitrate.data$food=="S" & resp_all_nitrate.data$N_dose=="18" & resp_all_nitrate.data$temp=="30"& resp_all_nitrate.data$e_coli_plate=="0")
apo_starved_nitrate_high_30C_no_ecoli <-subset(resp_all_nitrate.data, resp_all_nitrate.data$sym_state=="A" & resp_all_nitrate.data$food=="S" & resp_all_nitrate.data$N_dose=="18" & resp_all_nitrate.data$temp=="30"& resp_all_nitrate.data$e_coli_plate=="0")

#control 30C
sym_fed_control_30C_no_ecoli <-subset(resp_all_nitrate.data, resp_all_nitrate.data$sym_state=="S" & resp_all_nitrate.data$food=="F" & resp_all_nitrate.data$N_dose=="0" & resp_all_nitrate.data$temp=="30"& resp_all_nitrate.data$e_coli_plate=="0")
apo_fed_control_30C_no_ecoli <-subset(resp_all_nitrate.data, resp_all_nitrate.data$sym_state=="A" & resp_all_nitrate.data$food=="F" & resp_all_nitrate.data$N_dose=="0" & resp_all_nitrate.data$temp=="30"& resp_all_nitrate.data$e_coli_plate=="0")
sym_starved_control_30C_no_ecoli <-subset(resp_all_nitrate.data, resp_all_nitrate.data$sym_state=="S" & resp_all_nitrate.data$food=="S" & resp_all_nitrate.data$N_dose=="0" & resp_all_nitrate.data$temp=="30"& resp_all_nitrate.data$e_coli_plate=="0")
apo_starved_control_30C_no_ecoli <-subset(resp_all_nitrate.data, resp_all_nitrate.data$sym_state=="A" & resp_all_nitrate.data$food=="S" & resp_all_nitrate.data$N_dose=="0" & resp_all_nitrate.data$temp=="30"& resp_all_nitrate.data$e_coli_plate=="0")

#ammonium 5um 30C
sym_fed_ammonium_5um_30C_no_ecoli <-subset(resp_all_nitrate.data, resp_all_nitrate.data$N_species=="A" & resp_all_nitrate.data$sym_state=="S" & resp_all_nitrate.data$food=="F" & resp_all_nitrate.data$N_dose=="5" & resp_all_nitrate.data$temp=="30"& resp_all_nitrate.data$e_coli_plate=="0")
apo_fed_ammonium_5um_30C_no_ecoli <-subset(resp_all_nitrate.data, resp_all_nitrate.data$N_species=="A" & resp_all_nitrate.data$sym_state=="A" & resp_all_nitrate.data$food=="F" & resp_all_nitrate.data$N_dose=="5" & resp_all_nitrate.data$temp=="30"& resp_all_nitrate.data$e_coli_plate=="0")
sym_starved_ammonium_5um_30C_no_ecoli <-subset(resp_all_nitrate.data, resp_all_nitrate.data$N_species=="A" & resp_all_nitrate.data$sym_state=="S" & resp_all_nitrate.data$food=="S" & resp_all_nitrate.data$N_dose=="5" & resp_all_nitrate.data$temp=="30"& resp_all_nitrate.data$e_coli_plate=="0")
apo_starved_ammonium_5um_30C_no_ecoli <-subset(resp_all_nitrate.data, resp_all_nitrate.data$N_species=="A" & resp_all_nitrate.data$sym_state=="A" & resp_all_nitrate.data$food=="S" & resp_all_nitrate.data$N_dose=="5" & resp_all_nitrate.data$temp=="30"& resp_all_nitrate.data$e_coli_plate=="0")
#nitrate 5um 30C
sym_fed_nitrate_5um_30C_no_ecoli <-subset(resp_all_nitrate.data, resp_all_nitrate.data$N_species=="N" &  resp_all_nitrate.data$sym_state=="S" & resp_all_nitrate.data$food=="F" & resp_all_nitrate.data$N_dose=="5" & resp_all_nitrate.data$temp=="30"& resp_all_nitrate.data$e_coli_plate=="0")
apo_fed_nitrate_5um_30C_no_ecoli <-subset(resp_all_nitrate.data, resp_all_nitrate.data$N_species=="N" & resp_all_nitrate.data$sym_state=="A" & resp_all_nitrate.data$food=="F" & resp_all_nitrate.data$N_dose=="5" & resp_all_nitrate.data$temp=="30"& resp_all_nitrate.data$e_coli_plate=="0")
sym_starved_nitrate_5um_30C_no_ecoli <-subset(resp_all_nitrate.data, resp_all_nitrate.data$N_species=="N" & resp_all_nitrate.data$sym_state=="S" & resp_all_nitrate.data$food=="S" & resp_all_nitrate.data$N_dose=="5" & resp_all_nitrate.data$temp=="30"& resp_all_nitrate.data$e_coli_plate=="0")
apo_starved_nitrate_5um_30C_no_ecoli <-subset(resp_all_nitrate.data, resp_all_nitrate.data$N_species=="N" & resp_all_nitrate.data$sym_state=="A" & resp_all_nitrate.data$food=="S" & resp_all_nitrate.data$N_dose=="5" & resp_all_nitrate.data$temp=="30"& resp_all_nitrate.data$e_coli_plate=="0")

#nitrate 1.5um 30C
sym_fed_nitrate_1.5um_30C_no_ecoli <-subset(resp_all_nitrate.data, resp_all_nitrate.data$N_species=="N" & resp_all_nitrate.data$sym_state=="S" & resp_all_nitrate.data$food=="F" & resp_all_nitrate.data$N_dose=="1.5" & resp_all_nitrate.data$temp=="30"& resp_all_nitrate.data$e_coli_plate=="0")
apo_fed_nitrate_1.5um_30C_no_ecoli <-subset(resp_all_nitrate.data, resp_all_nitrate.data$N_species=="N" & resp_all_nitrate.data$sym_state=="A" & resp_all_nitrate.data$food=="F" & resp_all_nitrate.data$N_dose=="1.5" & resp_all_nitrate.data$temp=="30"& resp_all_nitrate.data$e_coli_plate=="0")
sym_starved_nitrate_1.5um_30C_no_ecoli <-subset(resp_all_nitrate.data, resp_all_nitrate.data$N_species=="N" & resp_all_nitrate.data$sym_state=="S" & resp_all_nitrate.data$food=="S" & resp_all_nitrate.data$N_dose=="1.5" & resp_all_nitrate.data$temp=="30"& resp_all_nitrate.data$e_coli_plate=="0")
apo_starved_nitrate_1.5um_30C_no_ecoli <-subset(resp_all_nitrate.data, resp_all_nitrate.data$N_species=="N" & resp_all_nitrate.data$sym_state=="A" & resp_all_nitrate.data$food=="S" & resp_all_nitrate.data$N_dose=="1.5" & resp_all_nitrate.data$temp=="30"& resp_all_nitrate.data$e_coli_plate=="0")

#nitrate 1.5um 20C
sym_fed_nitrate_1.5um_20C_no_ecoli <-subset(resp_all_nitrate.data, resp_all_nitrate.data$N_species=="N" & resp_all_nitrate.data$sym_state=="S" & resp_all_nitrate.data$food=="F" & resp_all_nitrate.data$N_dose=="1.5" & resp_all_nitrate.data$temp=="20"& resp_all_nitrate.data$e_coli_plate=="0")
apo_fed_nitrate_1.5um_20C_no_ecoli <-subset(resp_all_nitrate.data, resp_all_nitrate.data$N_species=="N" & resp_all_nitrate.data$sym_state=="A" & resp_all_nitrate.data$food=="F" & resp_all_nitrate.data$N_dose=="1.5" & resp_all_nitrate.data$temp=="20"& resp_all_nitrate.data$e_coli_plate=="0")
sym_starved_nitrate_1.5um_20C_no_ecoli <-subset(resp_all_nitrate.data, resp_all_nitrate.data$N_species=="N" & resp_all_nitrate.data$sym_state=="S" & resp_all_nitrate.data$food=="S" & resp_all_nitrate.data$N_dose=="1.5" & resp_all_nitrate.data$temp=="20"& resp_all_nitrate.data$e_coli_plate=="0")
apo_starved_nitrate_1.5um_20C_no_ecoli <-subset(resp_all_nitrate.data, resp_all_nitrate.data$N_species=="N" & resp_all_nitrate.data$sym_state=="A" & resp_all_nitrate.data$food=="S" & resp_all_nitrate.data$N_dose=="1.5" & resp_all_nitrate.data$temp=="20"& resp_all_nitrate.data$e_coli_plate=="0")

#ammonium 7.5um 30C
sym_fed_ammonium_7.5um_30C_no_ecoli <-subset(resp_all_nitrate.data, resp_all_nitrate.data$N_species=="A" & resp_all_nitrate.data$sym_state=="S" & resp_all_nitrate.data$food=="F" & resp_all_nitrate.data$N_dose=="7.5" & resp_all_nitrate.data$temp=="30"& resp_all_nitrate.data$e_coli_plate=="0")
apo_fed_ammonium_7.5um_30C_no_ecoli <-subset(resp_all_nitrate.data, resp_all_nitrate.data$N_species=="A" & resp_all_nitrate.data$sym_state=="A" & resp_all_nitrate.data$food=="F" & resp_all_nitrate.data$N_dose=="7.5" & resp_all_nitrate.data$temp=="30"& resp_all_nitrate.data$e_coli_plate=="0")
sym_starved_ammonium_7.5um_30C_no_ecoli <-subset(resp_all_nitrate.data, resp_all_nitrate.data$N_species=="A" & resp_all_nitrate.data$sym_state=="S" & resp_all_nitrate.data$food=="S" & resp_all_nitrate.data$N_dose=="7.5" & resp_all_nitrate.data$temp=="30"& resp_all_nitrate.data$e_coli_plate=="0")
apo_starved_ammonium_7.5um_30C_no_ecoli <-subset(resp_all_nitrate.data, resp_all_nitrate.data$N_species=="A" & resp_all_nitrate.data$sym_state=="A" & resp_all_nitrate.data$food=="S" & resp_all_nitrate.data$N_dose=="7.5" & resp_all_nitrate.data$temp=="30"& resp_all_nitrate.data$e_coli_plate=="0")

#ammonium 7.5um 20C
sym_fed_ammonium_7.5um_20C_no_ecoli <-subset(resp_all_nitrate.data, resp_all_nitrate.data$N_species=="A" & resp_all_nitrate.data$sym_state=="S" & resp_all_nitrate.data$food=="F" & resp_all_nitrate.data$N_dose=="7.5" & resp_all_nitrate.data$temp=="20"& resp_all_nitrate.data$e_coli_plate=="0")
apo_fed_ammonium_7.5um_20C_no_ecoli <-subset(resp_all_nitrate.data, resp_all_nitrate.data$N_species=="A" & resp_all_nitrate.data$sym_state=="A" & resp_all_nitrate.data$food=="F" & resp_all_nitrate.data$N_dose=="7.5" & resp_all_nitrate.data$temp=="20"& resp_all_nitrate.data$e_coli_plate=="0")
sym_starved_ammonium_7.5um_20C_no_ecoli <-subset(resp_all_nitrate.data, resp_all_nitrate.data$N_species=="A" & resp_all_nitrate.data$sym_state=="S" & resp_all_nitrate.data$food=="S" & resp_all_nitrate.data$N_dose=="7.5" & resp_all_nitrate.data$temp=="20"& resp_all_nitrate.data$e_coli_plate=="0")
apo_starved_ammonium_7.5um_20C_no_ecoli <-subset(resp_all_nitrate.data, resp_all_nitrate.data$N_species=="A" & resp_all_nitrate.data$sym_state=="A" & resp_all_nitrate.data$food=="S" & resp_all_nitrate.data$N_dose=="7.5" & resp_all_nitrate.data$temp=="20"& resp_all_nitrate.data$e_coli_plate=="0")
```

# OVERALL ANOVA
```{r MANOVA or ANOVA}

#What is a MANOVA?
  # A MANOVA is used when there are multiple dependent variables as well as independent variables in the study. MANOVA combines the multiple dependent variables in a linear manner to produce a combination which best separates the independent variable groups. Can only be used when the dependent variable is continuous
      # NOTE: the non parametric version of this is a PERMANOVA

#What is the difference between a MANOVA and a linear model?
  #  MANOVA will give you a very different answer than multiple regression analyses. MANOVA will look for a linear combination of the independent variables that minimizes ordinary least squares for the set of dependent variables. So, if the variables are not related in some way, it doesn't make much sense to combine them. To answer your question about why do a MANOVA, we can simply state that running multiple regressions (or ANOVAs) will inflate your type I error rate. Think about why you run an ANOVA instead of many t-tests.

# I ACTUALLY THINK WE WANT A UNIVARIATE ANALYSIS BECAUSE WE ONLY HAVE ONE OUTPUT -- RESPIRATION RATE

#We should do a seperate ANOVA for e coli and no e coli
aov_resp_e_coli <- aov(resp_rate ~ N_species * N_dose * temp * food * sym_state, data=e_coli)
summary(aov_resp_e_coli)



```


#Subsets and t tests
```{r SUBSETS E COLI for t tests verus the control for that group}

#everything at 20C vs. everything at 30C
all_20C <-subset(resp_all_nitrate.data,  resp_all_nitrate.data$temp=="20")
mean(all_20C$resp_rate, na.rm=TRUE)
# mean = -0.004676263
all_30C <-subset(resp_all_nitrate.data,  resp_all_nitrate.data$temp=="30")
mean(all_30C$resp_rate, na.rm=TRUE)
# mean = -0.004191459

# INTERESTING -- overall corals at 20C respired more

#ammonium high 20C
sym_fed_ammonium_high_20C_e_coli <-subset(resp_all_nitrate.data, resp_all_nitrate.data$sym_state=="S" & resp_all_nitrate.data$food=="F" & resp_all_nitrate.data$N_dose=="10" & resp_all_nitrate.data$temp=="20"& resp_all_nitrate.data$e_coli_plate=="1"& resp_all_nitrate.data$e_coli_plate=="1")
apo_fed_ammonium_high_30C_e_coli <-subset(resp_all_nitrate.data, resp_all_nitrate.data$sym_state=="A" & resp_all_nitrate.data$food=="F" & resp_all_nitrate.data$N_dose=="10" & resp_all_nitrate.data$temp=="20"& resp_all_nitrate.data$e_coli_plate=="1")
sym_starved_ammonium_high_20C_e_coli <-subset(resp_all_nitrate.data, resp_all_nitrate.data$sym_state=="S" & resp_all_nitrate.data$food=="S" & resp_all_nitrate.data$N_dose=="10" & resp_all_nitrate.data$temp=="20"& resp_all_nitrate.data$e_coli_plate=="1")
apo_starved_ammonium_high_20C_e_coli <-subset(resp_all_nitrate.data, resp_all_nitrate.data$sym_state=="A" & resp_all_nitrate.data$food=="S" & resp_all_nitrate.data$N_dose=="10" & resp_all_nitrate.data$temp=="20"& resp_all_nitrate.data$e_coli_plate=="1")
#nitrate high 20C
sym_fed_nitrate_high_20C_e_coli <-subset(resp_all_nitrate.data, resp_all_nitrate.data$sym_state=="S" & resp_all_nitrate.data$food=="F" & resp_all_nitrate.data$N_dose=="18" & resp_all_nitrate.data$temp=="20"& resp_all_nitrate.data$e_coli_plate=="1")
apo_fed_nitrate_high_20C_e_coli <-subset(resp_all_nitrate.data, resp_all_nitrate.data$sym_state=="A" & resp_all_nitrate.data$food=="F" & resp_all_nitrate.data$N_dose=="18" & resp_all_nitrate.data$temp=="20"& resp_all_nitrate.data$e_coli_plate=="1")
sym_starved_nitrate_high_20C_e_coli <-subset(resp_all_nitrate.data, resp_all_nitrate.data$sym_state=="S" & resp_all_nitrate.data$food=="S" & resp_all_nitrate.data$N_dose=="18" & resp_all_nitrate.data$temp=="20"& resp_all_nitrate.data$e_coli_plate=="1")
apo_starved_nitrate_high_20C_e_coli <-subset(resp_all_nitrate.data, resp_all_nitrate.data$sym_state=="A" & resp_all_nitrate.data$food=="S" & resp_all_nitrate.data$N_dose=="18" & resp_all_nitrate.data$temp=="20"& resp_all_nitrate.data$e_coli_plate=="1")

#control 20C
sym_fed_control_20C_e_coli <-subset(resp_all_nitrate.data, resp_all_nitrate.data$sym_state=="S" & resp_all_nitrate.data$food=="F" & resp_all_nitrate.data$N_dose=="0" & resp_all_nitrate.data$temp=="20"& resp_all_nitrate.data$e_coli_plate=="1")
apo_fed_control_20C_e_coli <-subset(resp_all_nitrate.data, resp_all_nitrate.data$sym_state=="A" & resp_all_nitrate.data$food=="F" & resp_all_nitrate.data$N_dose=="0" & resp_all_nitrate.data$temp=="20"& resp_all_nitrate.data$e_coli_plate=="1")
sym_starved_control_20C_e_coli <-subset(resp_all_nitrate.data, resp_all_nitrate.data$sym_state=="S" & resp_all_nitrate.data$food=="S" & resp_all_nitrate.data$N_dose=="0" & resp_all_nitrate.data$temp=="20"& resp_all_nitrate.data$e_coli_plate=="1")
apo_starved_control_20C_e_coli <-subset(resp_all_nitrate.data, resp_all_nitrate.data$sym_state=="A" & resp_all_nitrate.data$food=="S" & resp_all_nitrate.data$N_dose=="0" & resp_all_nitrate.data$temp=="20"& resp_all_nitrate.data$e_coli_plate=="1")

#ammonium 5uM 20C
sym_fed_ammonium_5um_20C_e_coli <-subset(resp_all_nitrate.data, resp_all_nitrate.data$N_species=="A" & resp_all_nitrate.data$sym_state=="S"& resp_all_nitrate.data$food=="F" & resp_all_nitrate.data$N_dose=="5" & resp_all_nitrate.data$temp=="20"& resp_all_nitrate.data$e_coli_plate=="1")
apo_fed_ammonium_5um_20C_e_coli <-subset(resp_all_nitrate.data, resp_all_nitrate.data$N_species=="A" & resp_all_nitrate.data$sym_state=="A" & resp_all_nitrate.data$food=="F" & resp_all_nitrate.data$N_dose=="5" & resp_all_nitrate.data$temp=="20"& resp_all_nitrate.data$e_coli_plate=="1")
sym_starved_ammonium_5um_20C_e_coli <-subset(resp_all_nitrate.data, resp_all_nitrate.data$N_species=="A" & resp_all_nitrate.data$sym_state=="S" & resp_all_nitrate.data$food=="S" & resp_all_nitrate.data$N_dose=="5" & resp_all_nitrate.data$temp=="20"& resp_all_nitrate.data$e_coli_plate=="1")
apo_starved_ammonium_5um_20C_e_coli <-subset(resp_all_nitrate.data, resp_all_nitrate.data$N_species=="A" & resp_all_nitrate.data$sym_state=="A" & resp_all_nitrate.data$food=="S" & resp_all_nitrate.data$N_dose=="5" & resp_all_nitrate.data$temp=="20"& resp_all_nitrate.data$e_coli_plate=="1")
#nitrate 5um 20C
sym_fed_nitrate_5um_20C_e_coli <-subset(resp_all_nitrate.data, resp_all_nitrate.data$N_species=="N" & resp_all_nitrate.data$sym_state=="S" & resp_all_nitrate.data$food=="F" & resp_all_nitrate.data$N_dose=="5" & resp_all_nitrate.data$temp=="20"& resp_all_nitrate.data$e_coli_plate=="1")
apo_fed_nitrate_5um_20C_e_coli <-subset(resp_all_nitrate.data, resp_all_nitrate.data$N_species=="N" & resp_all_nitrate.data$sym_state=="A" & resp_all_nitrate.data$food=="F" & resp_all_nitrate.data$N_dose=="5" & resp_all_nitrate.data$temp=="20"& resp_all_nitrate.data$e_coli_plate=="1")
sym_starved_nitrate_5um_20C_e_coli <-subset(resp_all_nitrate.data, resp_all_nitrate.data$N_species=="N" & resp_all_nitrate.data$sym_state=="S" & resp_all_nitrate.data$food=="S" & resp_all_nitrate.data$N_dose=="5" & resp_all_nitrate.data$temp=="20"& resp_all_nitrate.data$e_coli_plate=="1")
apo_starved_nitrate_5um_20C_e_coli <-subset(resp_all_nitrate.data, resp_all_nitrate.data$N_species=="N" & resp_all_nitrate.data$sym_state=="A" & resp_all_nitrate.data$food=="S" & resp_all_nitrate.data$N_dose=="5" & resp_all_nitrate.data$temp=="20"& resp_all_nitrate.data$e_coli_plate=="1")

#ammonium high 30C
sym_fed_ammonium_high_30C_e_coli <-subset(resp_all_nitrate.data, resp_all_nitrate.data$sym_state=="S" & resp_all_nitrate.data$food=="F" & resp_all_nitrate.data$N_dose=="10" & resp_all_nitrate.data$temp=="30"& resp_all_nitrate.data$e_coli_plate=="1")
apo_fed_ammonium_high_30C_e_coli <-subset(resp_all_nitrate.data, resp_all_nitrate.data$sym_state=="A" & resp_all_nitrate.data$food=="F" & resp_all_nitrate.data$N_dose=="10" & resp_all_nitrate.data$temp=="30"& resp_all_nitrate.data$e_coli_plate=="1")
sym_starved_ammonium_high_30C_e_coli <-subset(resp_all_nitrate.data, resp_all_nitrate.data$sym_state=="S" & resp_all_nitrate.data$food=="S" & resp_all_nitrate.data$N_dose=="10" & resp_all_nitrate.data$temp=="30"& resp_all_nitrate.data$e_coli_plate=="1")
apo_starved_ammonium_high_30C_e_coli <-subset(resp_all_nitrate.data, resp_all_nitrate.data$sym_state=="A" & resp_all_nitrate.data$food=="S" & resp_all_nitrate.data$N_dose=="10" & resp_all_nitrate.data$temp=="30"& resp_all_nitrate.data$e_coli_plate=="1")
#nitrate high 30C
sym_fed_nitrate_high_30C_e_coli <-subset(resp_all_nitrate.data, resp_all_nitrate.data$sym_state=="S" & resp_all_nitrate.data$food=="F" & resp_all_nitrate.data$N_dose=="18" & resp_all_nitrate.data$temp=="30"& resp_all_nitrate.data$e_coli_plate=="1")
apo_fed_nitrate_high_30C_e_coli <-subset(resp_all_nitrate.data, resp_all_nitrate.data$sym_state=="A" & resp_all_nitrate.data$food=="F" & resp_all_nitrate.data$N_dose=="18" & resp_all_nitrate.data$temp=="30"& resp_all_nitrate.data$e_coli_plate=="1")
sym_starved_nitrate_high_30C_e_coli <-subset(resp_all_nitrate.data, resp_all_nitrate.data$sym_state=="S" & resp_all_nitrate.data$food=="S" & resp_all_nitrate.data$N_dose=="18" & resp_all_nitrate.data$temp=="30"& resp_all_nitrate.data$e_coli_plate=="1")
apo_starved_nitrate_high_30C_e_coli <-subset(resp_all_nitrate.data, resp_all_nitrate.data$sym_state=="A" & resp_all_nitrate.data$food=="S" & resp_all_nitrate.data$N_dose=="18" & resp_all_nitrate.data$temp=="30"& resp_all_nitrate.data$e_coli_plate=="1")

#control 30C
sym_fed_control_30C_e_coli <-subset(resp_all_nitrate.data, resp_all_nitrate.data$sym_state=="S" & resp_all_nitrate.data$food=="F" & resp_all_nitrate.data$N_dose=="0" & resp_all_nitrate.data$temp=="30"& resp_all_nitrate.data$e_coli_plate=="1")
apo_fed_control_30C_e_coli <-subset(resp_all_nitrate.data, resp_all_nitrate.data$sym_state=="A" & resp_all_nitrate.data$food=="F" & resp_all_nitrate.data$N_dose=="0" & resp_all_nitrate.data$temp=="30"& resp_all_nitrate.data$e_coli_plate=="1")
sym_starved_control_30C_e_coli <-subset(resp_all_nitrate.data, resp_all_nitrate.data$sym_state=="S" & resp_all_nitrate.data$food=="S" & resp_all_nitrate.data$N_dose=="0" & resp_all_nitrate.data$temp=="30"& resp_all_nitrate.data$e_coli_plate=="1")
apo_starved_control_30C_e_coli <-subset(resp_all_nitrate.data, resp_all_nitrate.data$sym_state=="A" & resp_all_nitrate.data$food=="S" & resp_all_nitrate.data$N_dose=="0" & resp_all_nitrate.data$temp=="30"& resp_all_nitrate.data$e_coli_plate=="1")

#ammonium 5um 30C
sym_fed_ammonium_5um_30C_e_coli <-subset(resp_all_nitrate.data, resp_all_nitrate.data$N_species=="A" & resp_all_nitrate.data$sym_state=="S" & resp_all_nitrate.data$food=="F" & resp_all_nitrate.data$N_dose=="5" & resp_all_nitrate.data$temp=="30"& resp_all_nitrate.data$e_coli_plate=="1")
apo_fed_ammonium_5um_30C_e_coli <-subset(resp_all_nitrate.data, resp_all_nitrate.data$N_species=="A" & resp_all_nitrate.data$sym_state=="A" & resp_all_nitrate.data$food=="F" & resp_all_nitrate.data$N_dose=="5" & resp_all_nitrate.data$temp=="30"& resp_all_nitrate.data$e_coli_plate=="1")
sym_starved_ammonium_5um_30C_e_coli <-subset(resp_all_nitrate.data, resp_all_nitrate.data$N_species=="A" & resp_all_nitrate.data$sym_state=="S" & resp_all_nitrate.data$food=="S" & resp_all_nitrate.data$N_dose=="5" & resp_all_nitrate.data$temp=="30"& resp_all_nitrate.data$e_coli_plate=="1")
apo_starved_ammonium_5um_30C_e_coli <-subset(resp_all_nitrate.data, resp_all_nitrate.data$N_species=="A" & resp_all_nitrate.data$sym_state=="A" & resp_all_nitrate.data$food=="S" & resp_all_nitrate.data$N_dose=="5" & resp_all_nitrate.data$temp=="30"& resp_all_nitrate.data$e_coli_plate=="1")
#nitrate 5um 30C
sym_fed_nitrate_5um_30C_e_coli <-subset(resp_all_nitrate.data, resp_all_nitrate.data$N_species=="N" &  resp_all_nitrate.data$sym_state=="S" & resp_all_nitrate.data$food=="F" & resp_all_nitrate.data$N_dose=="5" & resp_all_nitrate.data$temp=="30"& resp_all_nitrate.data$e_coli_plate=="1")
apo_fed_nitrate_5um_30C_e_coli <-subset(resp_all_nitrate.data, resp_all_nitrate.data$N_species=="N" & resp_all_nitrate.data$sym_state=="A" & resp_all_nitrate.data$food=="F" & resp_all_nitrate.data$N_dose=="5" & resp_all_nitrate.data$temp=="30"& resp_all_nitrate.data$e_coli_plate=="1")
sym_starved_nitrate_5um_30C_e_coli <-subset(resp_all_nitrate.data, resp_all_nitrate.data$N_species=="N" & resp_all_nitrate.data$sym_state=="S" & resp_all_nitrate.data$food=="S" & resp_all_nitrate.data$N_dose=="5" & resp_all_nitrate.data$temp=="30"& resp_all_nitrate.data$e_coli_plate=="1")
apo_starved_nitrate_5um_30C_e_coli <-subset(resp_all_nitrate.data, resp_all_nitrate.data$N_species=="N" & resp_all_nitrate.data$sym_state=="A" & resp_all_nitrate.data$food=="S" & resp_all_nitrate.data$N_dose=="5" & resp_all_nitrate.data$temp=="30"& resp_all_nitrate.data$e_coli_plate=="1")

#nitrate 1.5um 30C
sym_fed_nitrate_1.5um_30C_e_coli <-subset(resp_all_nitrate.data, resp_all_nitrate.data$N_species=="N" & resp_all_nitrate.data$sym_state=="S" & resp_all_nitrate.data$food=="F" & resp_all_nitrate.data$N_dose=="1.5" & resp_all_nitrate.data$temp=="30"& resp_all_nitrate.data$e_coli_plate=="1")
apo_fed_nitrate_1.5um_30C_e_coli <-subset(resp_all_nitrate.data, resp_all_nitrate.data$N_species=="N" & resp_all_nitrate.data$sym_state=="A" & resp_all_nitrate.data$food=="F" & resp_all_nitrate.data$N_dose=="1.5" & resp_all_nitrate.data$temp=="30"& resp_all_nitrate.data$e_coli_plate=="1")
sym_starved_nitrate_1.5um_30C_e_coli <-subset(resp_all_nitrate.data, resp_all_nitrate.data$N_species=="N" & resp_all_nitrate.data$sym_state=="S" & resp_all_nitrate.data$food=="S" & resp_all_nitrate.data$N_dose=="1.5" & resp_all_nitrate.data$temp=="30"& resp_all_nitrate.data$e_coli_plate=="1")
apo_starved_nitrate_1.5um_30C_e_coli <-subset(resp_all_nitrate.data, resp_all_nitrate.data$N_species=="N" & resp_all_nitrate.data$sym_state=="A" & resp_all_nitrate.data$food=="S" & resp_all_nitrate.data$N_dose=="1.5" & resp_all_nitrate.data$temp=="30"& resp_all_nitrate.data$e_coli_plate=="1")

#nitrate 1.5um 20C
sym_fed_nitrate_1.5um_20C_e_coli <-subset(resp_all_nitrate.data, resp_all_nitrate.data$N_species=="N" & resp_all_nitrate.data$sym_state=="S" & resp_all_nitrate.data$food=="F" & resp_all_nitrate.data$N_dose=="1.5" & resp_all_nitrate.data$temp=="20"& resp_all_nitrate.data$e_coli_plate=="1")
apo_fed_nitrate_1.5um_20C_e_coli <-subset(resp_all_nitrate.data, resp_all_nitrate.data$N_species=="N" & resp_all_nitrate.data$sym_state=="A" & resp_all_nitrate.data$food=="F" & resp_all_nitrate.data$N_dose=="1.5" & resp_all_nitrate.data$temp=="20"& resp_all_nitrate.data$e_coli_plate=="1")
sym_starved_nitrate_1.5um_20C_e_coli <-subset(resp_all_nitrate.data, resp_all_nitrate.data$N_species=="N" & resp_all_nitrate.data$sym_state=="S" & resp_all_nitrate.data$food=="S" & resp_all_nitrate.data$N_dose=="1.5" & resp_all_nitrate.data$temp=="20"& resp_all_nitrate.data$e_coli_plate=="1")
apo_starved_nitrate_1.5um_20C_e_coli <-subset(resp_all_nitrate.data, resp_all_nitrate.data$N_species=="N" & resp_all_nitrate.data$sym_state=="A" & resp_all_nitrate.data$food=="S" & resp_all_nitrate.data$N_dose=="1.5" & resp_all_nitrate.data$temp=="20"& resp_all_nitrate.data$e_coli_plate=="1")

#ammonium 7.5um 30C
sym_fed_ammonium_7.5um_30C_e_coli <-subset(resp_all_nitrate.data, resp_all_nitrate.data$N_species=="A" & resp_all_nitrate.data$sym_state=="S" & resp_all_nitrate.data$food=="F" & resp_all_nitrate.data$N_dose=="7.5" & resp_all_nitrate.data$temp=="30"& resp_all_nitrate.data$e_coli_plate=="1")
apo_fed_ammonium_7.5um_30C_e_coli <-subset(resp_all_nitrate.data, resp_all_nitrate.data$N_species=="A" & resp_all_nitrate.data$sym_state=="A" & resp_all_nitrate.data$food=="F" & resp_all_nitrate.data$N_dose=="7.5" & resp_all_nitrate.data$temp=="30"& resp_all_nitrate.data$e_coli_plate=="1")
sym_starved_ammonium_7.5um_30C_e_coli <-subset(resp_all_nitrate.data, resp_all_nitrate.data$N_species=="A" & resp_all_nitrate.data$sym_state=="S" & resp_all_nitrate.data$food=="S" & resp_all_nitrate.data$N_dose=="7.5" & resp_all_nitrate.data$temp=="30"& resp_all_nitrate.data$e_coli_plate=="1")
apo_starved_ammonium_7.5um_30C_e_coli <-subset(resp_all_nitrate.data, resp_all_nitrate.data$N_species=="A" & resp_all_nitrate.data$sym_state=="A" & resp_all_nitrate.data$food=="S" & resp_all_nitrate.data$N_dose=="7.5" & resp_all_nitrate.data$temp=="30"& resp_all_nitrate.data$e_coli_plate=="1")

#ammonium 7.5um 20C
sym_fed_ammonium_7.5um_20C_e_coli <-subset(resp_all_nitrate.data, resp_all_nitrate.data$N_species=="A" & resp_all_nitrate.data$sym_state=="S" & resp_all_nitrate.data$food=="F" & resp_all_nitrate.data$N_dose=="7.5" & resp_all_nitrate.data$temp=="20"& resp_all_nitrate.data$e_coli_plate=="1")
apo_fed_ammonium_7.5um_20C_e_coli <-subset(resp_all_nitrate.data, resp_all_nitrate.data$N_species=="A" & resp_all_nitrate.data$sym_state=="A" & resp_all_nitrate.data$food=="F" & resp_all_nitrate.data$N_dose=="7.5" & resp_all_nitrate.data$temp=="20"& resp_all_nitrate.data$e_coli_plate=="1")
sym_starved_ammonium_7.5um_20C_e_coli <-subset(resp_all_nitrate.data, resp_all_nitrate.data$N_species=="A" & resp_all_nitrate.data$sym_state=="S" & resp_all_nitrate.data$food=="S" & resp_all_nitrate.data$N_dose=="7.5" & resp_all_nitrate.data$temp=="20"& resp_all_nitrate.data$e_coli_plate=="1")
apo_starved_ammonium_7.5um_20C_e_coli <-subset(resp_all_nitrate.data, resp_all_nitrate.data$N_species=="A" & resp_all_nitrate.data$sym_state=="A" & resp_all_nitrate.data$food=="S" & resp_all_nitrate.data$N_dose=="7.5" & resp_all_nitrate.data$temp=="20"& resp_all_nitrate.data$e_coli_plate=="1")
```

```{r t tests compared to relevant control - E. coli}

#sym fed 20C, all compared to control sym fed 20C
t.test(sym_fed_control_20C_e_coli$resp_rate, sym_fed_nitrate_1.5um_20C_e_coli$resp_rate)
#p=0.1042
t.test(sym_fed_control_20C_e_coli$resp_rate, sym_fed_ammonium_5um_20C_e_coli$resp_rate)
#p=0.4771
t.test(sym_fed_control_20C_e_coli$resp_rate, sym_fed_nitrate_5um_20C_e_coli$resp_rate)
#p=0.5502
t.test(sym_fed_control_20C_e_coli$resp_rate, sym_fed_ammonium_7.5um_20C_e_coli$resp_rate)
#p=0.232
t.test(sym_fed_control_20C_e_coli$resp_rate, sym_fed_ammonium_high_20C_e_coli$resp_rate)
#p=0.2024
t.test(sym_fed_control_20C_e_coli$resp_rate, sym_fed_nitrate_high_20C_e_coli$resp_rate)
#p=0.1682

#sym fed 30C, all compared to control sym fed 30C
t.test(sym_fed_control_30C_e_coli$resp_rate, sym_fed_nitrate_1.5um_30C_e_coli$resp_rate)
#p=0.4524
t.test(sym_fed_control_30C_e_coli$resp_rate, sym_fed_ammonium_5um_30C_e_coli$resp_rate)
#p=0.6342
t.test(sym_fed_control_30C_e_coli$resp_rate, sym_fed_nitrate_5um_30C_e_coli$resp_rate)
#p=0.96
t.test(sym_fed_control_30C_e_coli$resp_rate, sym_fed_ammonium_7.5um_30C_e_coli$resp_rate)
#p=0.0127**
mean(sym_fed_control_30C_e_coli$resp_rate) # -0.004670833
mean(sym_fed_ammonium_7.5um_30C_e_coli$resp_rate) #-0.00321
#reduction in metabolic rate compared to the control
t.test(sym_fed_control_30C_e_coli$resp_rate, sym_fed_ammonium_high_30C_e_coli$resp_rate)
#p=0.1383
t.test(sym_fed_control_30C_e_coli$resp_rate, sym_fed_nitrate_high_30C_e_coli$resp_rate)
#p=0.7563

#___ Sym starved 

#sym starved 20C, all compared to control sym fed 20C
t.test(sym_starved_control_20C_e_coli$resp_rate, sym_starved_nitrate_1.5um_20C_e_coli$resp_rate)
#p=0.0556
mean(sym_starved_control_20C_e_coli$resp_rate) #-0.004846667
mean(sym_starved_nitrate_1.5um_20C_e_coli$resp_rate) #-0.006415
#marginally significant increase in rate comared to control
t.test(sym_starved_control_20C_e_coli$resp_rate, sym_starved_ammonium_5um_20C_e_coli$resp_rate)
#p= 0.1202
t.test(sym_starved_control_20C_e_coli$resp_rate, sym_starved_nitrate_5um_20C_e_coli$resp_rate)
#p= 0.7142
t.test(sym_starved_control_20C_e_coli$resp_rate, sym_starved_ammonium_7.5um_20C_e_coli$resp_rate)
#p= 0.3707
t.test(sym_starved_control_20C_e_coli$resp_rate, sym_starved_ammonium_high_20C_e_coli$resp_rate)
#p= 0.4604
t.test(sym_starved_control_20C_e_coli$resp_rate, sym_starved_nitrate_high_20C_e_coli$resp_rate)
#p= 0.7019

#sym starved 30C, all compared to control sym fed 30C
t.test(sym_starved_control_30C_e_coli$resp_rate, sym_starved_nitrate_1.5um_30C_e_coli$resp_rate)
#p=0.1613
t.test(sym_starved_control_30C_e_coli$resp_rate, sym_starved_ammonium_5um_30C_e_coli$resp_rate)
#p=0.6113
t.test(sym_starved_control_30C_e_coli$resp_rate, sym_starved_nitrate_5um_30C_e_coli$resp_rate)
#p=0.9276
t.test(sym_starved_control_30C_e_coli$resp_rate, sym_starved_ammonium_7.5um_30C_e_coli$resp_rate)
#p= 0.05253
mean(sym_starved_control_30C_e_coli$resp_rate) # -0.004903333
mean(sym_starved_ammonium_7.5um_30C_e_coli$resp_rate) #-0.003205
t.test(sym_starved_control_30C_e_coli$resp_rate, sym_starved_ammonium_high_30C_e_coli$resp_rate)
#p= 0.6491
t.test(sym_starved_control_30C_e_coli$resp_rate, sym_starved_nitrate_high_30C_e_coli$resp_rate)
#p= 0.1142

#___ apo fed 

#apo fed 20C
t.test(apo_fed_control_20C_e_coli$resp_rate, apo_fed_nitrate_1.5um_20C_e_coli$resp_rate)
#p= 0.4355
t.test(apo_fed_control_20C_e_coli$resp_rate, apo_fed_ammonium_5um_20C_e_coli$resp_rate)
#p= 0.6995
t.test(apo_fed_control_20C_e_coli$resp_rate, apo_fed_nitrate_5um_20C_e_coli$resp_rate)
#p= 0.9564
t.test(apo_fed_control_20C_e_coli$resp_rate, apo_fed_ammonium_7.5um_20C_e_coli$resp_rate)
#p= 0.6399
t.test(apo_fed_control_20C_e_coli$resp_rate, apo_fed_ammonium_high_20C_e_coli$resp_rate)
#p= 0.4461
t.test(apo_fed_control_20C_e_coli$resp_rate, apo_fed_nitrate_high_20C_e_coli$resp_rate)
#p= 0.3519

#apo fed 30C
t.test(apo_fed_control_30C_e_coli$resp_rate, apo_fed_nitrate_1.5um_30C_e_coli$resp_rate)
#p=0.5267
t.test(apo_fed_control_30C_e_coli$resp_rate, apo_fed_ammonium_5um_30C_e_coli$resp_rate)
#p=0.4213
t.test(apo_fed_control_30C_e_coli$resp_rate, apo_fed_nitrate_5um_30C_e_coli$resp_rate)
#p=0.5673
t.test(apo_fed_control_30C_e_coli$resp_rate, apo_fed_ammonium_7.5um_30C_e_coli$resp_rate)
#p= 0.3054
t.test(apo_fed_control_30C_e_coli$resp_rate, apo_fed_ammonium_high_30C_e_coli$resp_rate)
#p= 0.4159
t.test(apo_fed_control_30C_e_coli$resp_rate, apo_fed_nitrate_high_30C_e_coli$resp_rate)
#p= 0.04549
mean(apo_fed_control_30C_e_coli$resp_rate) # -0.003823333
mean(apo_fed_nitrate_high_30C_e_coli$resp_rate) # -0.005401667
#significant increase in resp rate compared to control

#___ apo starved

t.test(apo_starved_control_20C_e_coli$resp_rate, apo_starved_nitrate_1.5um_20C_e_coli$resp_rate)
#p= 0.748
t.test(apo_starved_control_20C_e_coli$resp_rate, apo_starved_ammonium_5um_20C_e_coli$resp_rate)
#p= 0.9562
t.test(apo_starved_control_20C_e_coli$resp_rate, apo_starved_nitrate_5um_20C_e_coli$resp_rate, na.rm=TRUE)
#p=0.08441
mean(apo_starved_control_20C_e_coli$resp_rate) #-0.0039725
mean(apo_starved_nitrate_5um_20C_e_coli$resp_rate, na.rm=TRUE) #-0.005892

t.test(apo_starved_control_20C_e_coli$resp_rate, apo_starved_ammonium_7.5um_20C_e_coli$resp_rate)
#p= 0.7132
t.test(apo_starved_control_20C_e_coli$resp_rate, apo_starved_ammonium_high_20C_e_coli$resp_rate)
#p=0.1955
t.test(apo_starved_control_20C_e_coli$resp_rate, apo_starved_nitrate_high_20C_e_coli$resp_rate)
#p= 0.06472
mean(apo_starved_control_20C_e_coli$resp_rate) #-0.0039725
mean(apo_starved_nitrate_high_20C_e_coli$resp_rate) #-0.005861667

#apo fed 30C
t.test(apo_starved_control_30C_e_coli$resp_rate, apo_starved_nitrate_1.5um_30C_e_coli$resp_rate)
#p= 0.3879
t.test(apo_starved_control_30C_e_coli$resp_rate, apo_starved_ammonium_5um_30C_e_coli$resp_rate)
#p= 0.714
t.test(apo_starved_control_30C_e_coli$resp_rate, apo_starved_nitrate_5um_30C_e_coli$resp_rate)
#p= 0.2444
t.test(apo_starved_control_30C_e_coli$resp_rate, apo_starved_ammonium_7.5um_30C_e_coli$resp_rate)
#p= 0.9543
t.test(apo_starved_control_30C_e_coli$resp_rate, apo_starved_ammonium_high_30C_e_coli$resp_rate)
#p= 0.2142
t.test(apo_starved_control_30C_e_coli$resp_rate, apo_starved_nitrate_high_30C_e_coli$resp_rate)
#p= 0.1545


```
```{r t tests No e coli}
#TO DO JANUARY 5
#sym fed 20C, all compared to control sym fed 20C
t.test(sym_fed_control_20C_no_ecoli$resp_rate, sym_fed_nitrate_1.5um_20C_no_ecoli$resp_rate)
#p= 0.5939
t.test(sym_fed_control_20C_no_ecoli$resp_rate, sym_fed_ammonium_5um_20C_no_ecoli$resp_rate)
#p= 0.7668
t.test(sym_fed_control_20C_no_ecoli$resp_rate, sym_fed_nitrate_5um_20C_no_ecoli$resp_rate)
#p= 0.6099
t.test(sym_fed_control_20C_no_ecoli$resp_rate, sym_fed_ammonium_7.5um_20C_no_ecoli$resp_rate)
#p= 0.4135
t.test(sym_fed_control_20C_no_ecoli$resp_rate, sym_fed_ammonium_high_20C_no_ecoli$resp_rate)
#p=0.6549
t.test(sym_fed_control_20C_no_ecoli$resp_rate, sym_fed_nitrate_high_20C_no_ecoli$resp_rate)
#p= 0.7044

#sym fed 30C, all compared to control sym fed 30C
t.test(sym_fed_control_30C_no_ecoli$resp_rate, sym_fed_nitrate_1.5um_30C_no_ecoli$resp_rate)
#p= 0.5475
t.test(sym_fed_control_30C_no_ecoli$resp_rate, sym_fed_ammonium_5um_30C_no_ecoli$resp_rate)
#p= 0.4574
t.test(sym_fed_control_30C_no_ecoli$resp_rate, sym_fed_nitrate_5um_30C_no_ecoli$resp_rate)
#p= 0.6833
t.test(sym_fed_control_30C_no_ecoli$resp_rate, sym_fed_ammonium_7.5um_30C_no_ecoli$resp_rate)
#p=  0.2402
t.test(sym_fed_control_30C_no_ecoli$resp_rate, sym_fed_ammonium_high_30C_no_ecoli$resp_rate)
#p=  0.8251
t.test(sym_fed_control_30C_no_ecoli$resp_rate, sym_fed_nitrate_high_30C_no_ecoli$resp_rate)
#p= 0.9937

#___ Sym starved 

#sym starved 20C, all compared to control 
t.test(sym_starved_control_20C_no_ecoli$resp_rate, sym_starved_nitrate_1.5um_20C_no_ecoli$resp_rate)
#p= 0.7133
t.test(sym_starved_control_20C_no_ecoli$resp_rate, sym_starved_ammonium_5um_20C_no_ecoli$resp_rate)
#p=  0.4512
t.test(sym_starved_control_20C_no_ecoli$resp_rate, sym_starved_nitrate_5um_20C_no_ecoli$resp_rate)
#p=  0.6387
t.test(sym_starved_control_20C_no_ecoli$resp_rate, sym_starved_ammonium_7.5um_20C_no_ecoli$resp_rate)
#p=   0.2497
t.test(sym_starved_control_20C_no_ecoli$resp_rate, sym_starved_ammonium_high_20C_no_ecoli$resp_rate)
#p= 0.257
t.test(sym_starved_control_20C_no_ecoli$resp_rate, sym_starved_nitrate_high_20C_no_ecoli$resp_rate)
#p= 0.5483

#sym starved 30C, all compared to control 
t.test(sym_starved_control_30C_no_ecoli$resp_rate, sym_starved_nitrate_1.5um_30C_no_ecoli$resp_rate)
#p= 0.03202 ***
#looking at what the difference is 
mean(sym_starved_control_30C_no_ecoli$resp_rate) # avg = -0.00492
mean(sym_starved_nitrate_1.5um_30C_no_ecoli$resp_rate) # avg = -0.00307
#This means that the control respired MORE than the nitrate 1.5, metabolic depression
t.test(sym_starved_control_30C_no_ecoli$resp_rate, sym_starved_ammonium_5um_30C_no_ecoli$resp_rate)
#p=0.6934
t.test(sym_starved_control_30C_no_ecoli$resp_rate, sym_starved_nitrate_5um_30C_no_ecoli$resp_rate)
#p= 0.2712
t.test(sym_starved_control_30C_no_ecoli$resp_rate, sym_starved_ammonium_7.5um_30C_no_ecoli$resp_rate)
#p= 0.1486
t.test(sym_starved_control_30C_no_ecoli$resp_rate, sym_starved_ammonium_high_30C_no_ecoli$resp_rate)
#p= 0.2506
t.test(sym_starved_control_30C_no_ecoli$resp_rate, sym_starved_nitrate_high_30C_no_ecoli$resp_rate)
#p= 0.8016

#___ apo fed 

#apo fed 20C
t.test(apo_fed_control_20C_no_ecoli$resp_rate, apo_fed_nitrate_1.5um_20C_no_ecoli$resp_rate)
#p= 0.987
t.test(apo_fed_control_20C_no_ecoli$resp_rate, apo_fed_ammonium_5um_20C_no_ecoli$resp_rate)
#p= 0.4447
t.test(apo_fed_control_20C_no_ecoli$resp_rate, apo_fed_nitrate_5um_20C_no_ecoli$resp_rate)
#p= 0.8832
t.test(apo_fed_control_20C_no_ecoli$resp_rate, apo_fed_ammonium_7.5um_20C_no_ecoli$resp_rate)
#p= 0.07457 * marginally significant
mean(apo_fed_control_20C_no_ecoli$resp_rate) #-0.0044275
mean(apo_fed_ammonium_7.5um_20C_no_ecoli$resp_rate) # -0.003235
t.test(apo_fed_control_20C_no_ecoli$resp_rate, apo_fed_ammonium_high_20C_no_ecoli$resp_rate)
#p=  0.6497
t.test(apo_fed_control_20C_no_ecoli$resp_rate, apo_fed_nitrate_high_20C_no_ecoli$resp_rate)
#p= 0.9887

#apo fed 30C
t.test(apo_fed_control_30C_no_ecoli$resp_rate, apo_fed_nitrate_1.5um_30C_no_ecoli$resp_rate)
#p= 0.07359
mean(apo_fed_control_30C_no_ecoli$resp_rate) #-0.003946667
mean(apo_fed_nitrate_1.5um_30C_no_ecoli$resp_rate) #-0.002713333
t.test(apo_fed_control_30C_no_ecoli$resp_rate, apo_fed_ammonium_5um_30C_no_ecoli$resp_rate)
#p=0.1096
t.test(apo_fed_control_30C_no_ecoli$resp_rate, apo_fed_nitrate_5um_30C_no_ecoli$resp_rate)
#p=0.8034
t.test(apo_fed_control_30C_no_ecoli$resp_rate, apo_fed_ammonium_7.5um_30C_no_ecoli$resp_rate)
#p= 0.08376
mean(apo_fed_control_30C_no_ecoli$resp_rate) #-0.003946667
mean(apo_fed_ammonium_7.5um_30C_no_ecoli$resp_rate) #-0.002761667
t.test(apo_fed_control_30C_no_ecoli$resp_rate, apo_fed_ammonium_high_30C_no_ecoli$resp_rate)
#p= 0.5962
t.test(apo_fed_control_30C_no_ecoli$resp_rate, apo_fed_nitrate_high_30C_no_ecoli$resp_rate)
#p= 0.8624

#___ apo starved

#apo fed 20C
t.test(apo_starved_control_20C_no_ecoli$resp_rate, apo_starved_nitrate_1.5um_20C_no_ecoli$resp_rate)
#p= 0.6904
t.test(apo_starved_control_20C_no_ecoli$resp_rate, apo_starved_ammonium_5um_20C_no_ecoli$resp_rate)
#p=0.6018
t.test(apo_starved_control_20C_no_ecoli$resp_rate, apo_starved_nitrate_5um_20C_no_ecoli$resp_rate)
#p= 0.2128
t.test(apo_starved_control_20C_no_ecoli$resp_rate, apo_starved_ammonium_7.5um_20C_no_ecoli$resp_rate)
#p= 0.5757
t.test(apo_starved_control_20C_no_ecoli$resp_rate, apo_starved_ammonium_high_20C_no_ecoli$resp_rate)
#p= 0.7744
t.test(apo_starved_control_20C_no_ecoli$resp_rate, apo_starved_nitrate_high_20C_no_ecoli$resp_rate)
#p= 0.6394

#apo fed 30C
t.test(apo_starved_control_30C_no_ecoli$resp_rate, apo_starved_nitrate_1.5um_30C_no_ecoli$resp_rate)
#p= 0.8124
t.test(apo_starved_control_30C_no_ecoli$resp_rate, apo_starved_ammonium_5um_30C_no_ecoli$resp_rate)
#p= 0.545
t.test(apo_starved_control_30C_no_ecoli$resp_rate, apo_starved_nitrate_5um_30C_no_ecoli$resp_rate)
#p= 0.8734
t.test(apo_starved_control_30C_no_ecoli$resp_rate, apo_starved_ammonium_7.5um_30C_no_ecoli$resp_rate)
#p= 0.3203
t.test(apo_starved_control_30C_no_ecoli$resp_rate, apo_starved_ammonium_high_30C_no_ecoli$resp_rate)
#p=  0.62
t.test(apo_starved_control_30C_no_ecoli$resp_rate, apo_starved_nitrate_high_30C_no_ecoli$resp_rate)
#p= 0.657
```

```{r ANOVAs and visualizations - SYM FED E. COLI}
#first lets subset what we want
sym_fed_ecoli <-subset(resp_all_nitrate.data, resp_all_nitrate.data$sym_state=="S" & resp_all_nitrate.data$food=="F" & resp_all_nitrate.data$e_coli_plate=="1")

#then lets look at the histogram to make sure its not egregious
hist(sym_fed_ecoli$resp_rate)
#eh its not great, pretty right skewed
#but we have been taught about the robustness of ANOVAs and t tests so lets ride

#plut it in to make an anova object
aov_sym_fed_ecoli <-aov(resp_rate ~ treat_ID_collapsed_controls, data=sym_fed_ecoli)
#need to summarize the anova object
summary(aov_sym_fed_ecoli)
#now we will do a pairwise Tukey
TukeyHSD(aov_sym_fed_ecoli)

gg_sym_fed_ecoli<-
  ggplot(sym_fed_ecoli, aes(x=treat_ID_collapsed_controls, y=resp_rate, color=temp)) +
  geom_boxplot(width=0.8) +
  geom_jitter(width=0.15, alpha=0.9) +
 # geom_line(aes(group=e_coli_plate), col="darkgray")+
  ylab("Respirometry rate")+
  xlab("Treat ID")+
  theme(legend.position="none", plot.title = element_text(size = 9)) +
  #scale_color_manual(name = "Day of experiment",
                     #labels = c("Day 1","Day 11"),
                   # values = c("royalblue","darkorchid1"))+
 # scale_x_discrete(labels=c("Day 1","Day 11")) +
    theme(axis.text.x = element_text(angle=90, vjust=.5, hjust=1))+ #this makes the x axis labels up and down instead of side to side to prevent overlapping
 annotate("text", x = Inf, y = Inf, label = paste("  "), vjust = 1, hjust = 1, size=3)+
  ggtitle("Resp rate by treat ID - Sym Fed E. coli")
gg_sym_fed_ecoli

all_by_e_coli<-
  ggplot(resp_all_nitrate.data, aes(x=treat_ID_collapsed_controls, y=resp_rate, color=e_coli_plate)) +
  geom_boxplot(width=0.8) +
  geom_jitter(width=0.15, alpha=0.9) +
 # geom_line(aes(group=e_coli_plate), col="darkgray")+
  ylab("Respirometry rate")+
  xlab("Treat ID")+
  theme(legend.position="none", plot.title = element_text(size = 9)) +
  #scale_color_manual(name = "Day of experiment",
                     #labels = c("Day 1","Day 11"),
                   # values = c("royalblue","darkorchid1"))+
 # scale_x_discrete(labels=c("Day 1","Day 11")) +
    theme(axis.text.x = element_text(angle=90, vjust=.5, hjust=1))+ #this makes the x axis labels up and down instead of side to side to prevent overlapping
 annotate("text", x = Inf, y = Inf, label = paste("  "), vjust = 1, hjust = 1, size=3)+
  ggtitle("ALL - color = e. coli")
all_by_e_coli

boxplot(resp_all_nitrate.data$resp_rate ~ resp_all_nitrate.data$e_coli_plate)
```

```{r ANOVAs and visualizations - SYM FED NO E. COLI}
#first lets subset what we want
sym_fed_no_ecoli <-subset(resp_all_nitrate.data, resp_all_nitrate.data$sym_state=="S" & resp_all_nitrate.data$food=="F" & resp_all_nitrate.data$e_coli_plate=="0")

#then lets look at the histogram to make sure its not egregious
hist(sym_fed_no_ecoli$resp_rate)
#eh its not great, pretty right skewed
#but we have been taught about the robustness of ANOVAs and t tests so lets ride

#plut it in to make an anova object
aov_sym_fed_no_ecoli <-aov(resp_rate ~ treat_ID_collapsed_controls, data=sym_fed_no_ecoli)
#need to summarize the anova object
summary(aov_sym_fed_no_ecoli)
#now we will do a pairwise Tukey
TukeyHSD(aov_sym_fed_no_ecoli)

gg_sym_fed_no_ecoli<-
  ggplot(sym_fed_no_ecoli, aes(x=treat_ID_collapsed_controls, y=resp_rate, color=temp)) +
  geom_boxplot(width=0.8) +
  geom_jitter(width=0.15, alpha=0.9) +
 # geom_line(aes(group=e_coli_plate), col="darkgray")+
  ylab("Respirometry rate")+
  xlab("Treat ID")+
  theme(legend.position="none", plot.title = element_text(size = 9)) +
  #scale_color_manual(name = "Day of experiment",
                     #labels = c("Day 1","Day 11"),
                   # values = c("royalblue","darkorchid1"))+
 # scale_x_discrete(labels=c("Day 1","Day 11")) +
    theme(axis.text.x = element_text(angle=90, vjust=.5, hjust=1))+ #this makes the x axis labels up and down instead of side to side to prevent overlapping
 annotate("text", x = Inf, y = Inf, label = paste("  "), vjust = 1, hjust = 1, size=3)+
  ggtitle("Resp rate by treat ID - Sym Fed NO E. coli")
gg_sym_fed_no_ecoli
```
```{r ANOVAs and visualizations - SYM STARVED E. COLI}
#first lets subset what we want
sym_starved_ecoli <-subset(resp_all_nitrate.data, resp_all_nitrate.data$sym_state=="S" & resp_all_nitrate.data$food=="S" & resp_all_nitrate.data$e_coli_plate=="1")

#then lets look at the histogram to make sure its not egregious
hist(sym_starved_ecoli$resp_rate)
#eh its not great, pretty right skewed
#but we have been taught about the robustness of ANOVAs and t tests so lets ride

#plut it in to make an anova object
aov_sym_starved_ecoli <-aov(resp_rate ~ treat_ID_collapsed_controls, data=sym_starved_ecoli)
#need to summarize the anova object
summary(aov_sym_starved_ecoli)
#now we will do a pairwise Tukey
TukeyHSD(aov_sym_starved_ecoli)

gg_sym_starved_ecoli<-
  ggplot(sym_starved_ecoli, aes(x=treat_ID_collapsed_controls, y=resp_rate, color=temp)) +
  geom_boxplot(width=0.8) +
  geom_jitter(width=0.15, alpha=0.9) +
 # geom_line(aes(group=e_coli_plate), col="darkgray")+
  ylab("Respirometry rate")+
  xlab("Treat ID")+
  theme(legend.position="none", plot.title = element_text(size = 9)) +
  #scale_color_manual(name = "Day of experiment",
                     #labels = c("Day 1","Day 11"),
                   # values = c("royalblue","darkorchid1"))+
 # scale_x_discrete(labels=c("Day 1","Day 11")) +
    theme(axis.text.x = element_text(angle=90, vjust=.5, hjust=1))+ #this makes the x axis labels up and down instead of side to side to prevent overlapping
 annotate("text", x = Inf, y = Inf, label = paste("  "), vjust = 1, hjust = 1, size=3)+
  ggtitle("Resp rate by treat ID - Sym starved E. coli")
gg_sym_starved_ecoli


```

```{r ANOVAs and visualizations - SYM STARVED NO E. COLI}
#first lets subset what we want
sym_starved_no_ecoli <-subset(resp_all_nitrate.data, resp_all_nitrate.data$sym_state=="S" & resp_all_nitrate.data$food=="S" & resp_all_nitrate.data$e_coli_plate=="0")

#then lets look at the histogram to make sure its not egregious
hist(sym_starved_no_ecoli$resp_rate)
#eh its not great, pretty right skewed
#but we have been taught about the robustness of ANOVAs and t tests so lets ride

#plut it in to make an anova object
aov_sym_starved_no_ecoli <-aov(resp_rate ~ treat_ID_collapsed_controls, data=sym_starved_no_ecoli)
#need to summarize the anova object
summary(aov_sym_starved_no_ecoli)
#now we will do a pairwise Tukey
TukeyHSD(aov_sym_starved_no_ecoli)

gg_sym_starved_no_ecoli<-
  ggplot(sym_starved_no_ecoli, aes(x=treat_ID_collapsed_controls, y=resp_rate, color=temp)) +
  geom_boxplot(width=0.8) +
  geom_jitter(width=0.15, alpha=0.9) +
 # geom_line(aes(group=e_coli_plate), col="darkgray")+
  ylab("Respirometry rate")+
  xlab("Treat ID")+
  theme(legend.position="none", plot.title = element_text(size = 9)) +
  #scale_color_manual(name = "Day of experiment",
                     #labels = c("Day 1","Day 11"),
                   # values = c("royalblue","darkorchid1"))+
 # scale_x_discrete(labels=c("Day 1","Day 11")) +
    theme(axis.text.x = element_text(angle=90, vjust=.5, hjust=1))+ #this makes the x axis labels up and down instead of side to side to prevent overlapping
 annotate("text", x = Inf, y = Inf, label = paste("  "), vjust = 1, hjust = 1, size=3)+
  ggtitle("Resp rate by treat ID - Sym Starved NO E. coli")
gg_sym_starved_no_ecoli
```

# Apo
```{r ANOVAs and visualizations - apo FED E. COLI}
#first lets subset what we want
apo_fed_ecoli <-subset(resp_all_nitrate.data, resp_all_nitrate.data$sym_state=="A" & resp_all_nitrate.data$food=="F" & resp_all_nitrate.data$e_coli_plate=="1")

#then lets look at the histogram to make sure its not egregious
hist(apo_fed_ecoli$resp_rate)
#eh its not great, pretty right skewed
#but we have been taught about the robustness of ANOVAs and t tests so lets ride

#plut it in to make an anova object
aov_apo_fed_ecoli <-aov(resp_rate ~ treat_ID_collapsed_controls, data=apo_fed_ecoli)
#need to summarize the anova object
summary(aov_apo_fed_ecoli)
#now we will do a pairwise Tukey
TukeyHSD(aov_apo_fed_ecoli)

gg_apo_fed_ecoli<-
  ggplot(apo_fed_ecoli, aes(x=treat_ID_collapsed_controls, y=resp_rate, color=temp)) +
  geom_boxplot(width=0.8) +
  geom_jitter(width=0.15, alpha=0.9) +
 # geom_line(aes(group=e_coli_plate), col="darkgray")+
  ylab("Respirometry rate")+
  xlab("Treat ID")+
  theme(legend.position="none", plot.title = element_text(size = 9)) +
  #scale_color_manual(name = "Day of experiment",
                     #labels = c("Day 1","Day 11"),
                   # values = c("royalblue","darkorchid1"))+
 # scale_x_discrete(labels=c("Day 1","Day 11")) +
    theme(axis.text.x = element_text(angle=90, vjust=.5, hjust=1))+ #this makes the x axis labels up and down instead of side to side to prevent overlapping
 annotate("text", x = Inf, y = Inf, label = paste("  "), vjust = 1, hjust = 1, size=3)+
  ggtitle("Resp rate by treat ID - apo Fed E. coli")
gg_apo_fed_ecoli


```

```{r ANOVAs and visualizations - apo FED NO E. COLI}
#first lets subset what we want
apo_fed_no_ecoli <-subset(resp_all_nitrate.data, resp_all_nitrate.data$sym_state=="A" & resp_all_nitrate.data$food=="F" & resp_all_nitrate.data$e_coli_plate=="0")

#then lets look at the histogram to make sure its not egregious
hist(apo_fed_no_ecoli$resp_rate)
#eh its not great, pretty right skewed
#but we have been taught about the robustness of ANOVAs and t tests so lets ride

#plut it in to make an anova object
aov_apo_fed_no_ecoli <-aov(resp_rate ~ treat_ID_collapsed_controls, data=apo_fed_no_ecoli)
#need to summarize the anova object
summary(aov_apo_fed_no_ecoli)
#now we will do a pairwise Tukey
TukeyHSD(aov_apo_fed_no_ecoli)

gg_apo_fed_no_ecoli<-
  ggplot(apo_fed_no_ecoli, aes(x=treat_ID_collapsed_controls, y=resp_rate, color=temp)) +
  geom_boxplot(width=0.8) +
  geom_jitter(width=0.15, alpha=0.9) +
 # geom_line(aes(group=e_coli_plate), col="darkgray")+
  ylab("Respirometry rate")+
  xlab("Treat ID")+
  theme(legend.position="none", plot.title = element_text(size = 9)) +
  #scale_color_manual(name = "Day of experiment",
                     #labels = c("Day 1","Day 11"),
                   # values = c("royalblue","darkorchid1"))+
 # scale_x_discrete(labels=c("Day 1","Day 11")) +
    theme(axis.text.x = element_text(angle=90, vjust=.5, hjust=1))+ #this makes the x axis labels up and down instead of side to side to prevent overlapping
 annotate("text", x = Inf, y = Inf, label = paste("  "), vjust = 1, hjust = 1, size=3)+
  ggtitle("Resp rate by treat ID - apo Fed NO E. coli")
gg_apo_fed_no_ecoli
```

```{r ANOVAs and visualizations - apo STARVED E. COLI}
#first lets subset what we want
apo_starved_ecoli <-subset(resp_all_nitrate.data, resp_all_nitrate.data$sym_state=="A" & resp_all_nitrate.data$food=="S" & resp_all_nitrate.data$e_coli_plate=="1")

#then lets look at the histogram to make sure its not egregious
hist(apo_starved_ecoli$resp_rate)
#eh its not great, pretty right skewed
#but we have been taught about the robustness of ANOVAs and t tests so lets ride

#plut it in to make an anova object
aov_apo_starved_ecoli <-aov(resp_rate ~ treat_ID_collapsed_controls, data=apo_starved_ecoli)
#need to summarize the anova object
summary(aov_apo_starved_ecoli)
#now we will do a pairwise Tukey
TukeyHSD(aov_apo_starved_ecoli)

gg_apo_starved_ecoli<-
  ggplot(apo_starved_ecoli, aes(x=treat_ID_collapsed_controls, y=resp_rate, color=temp)) +
  geom_boxplot(width=0.8) +
  geom_jitter(width=0.15, alpha=0.9) +
 # geom_line(aes(group=e_coli_plate), col="darkgray")+
  ylab("Respirometry rate")+
  xlab("Treat ID")+
  theme(legend.position="none", plot.title = element_text(size = 9)) +
  #scale_color_manual(name = "Day of experiment",
                     #labels = c("Day 1","Day 11"),
                   # values = c("royalblue","darkorchid1"))+
 # scale_x_discrete(labels=c("Day 1","Day 11")) +
    theme(axis.text.x = element_text(angle=90, vjust=.5, hjust=1))+ #this makes the x axis labels up and down instead of side to side to prevent overlapping
 annotate("text", x = Inf, y = Inf, label = paste("  "), vjust = 1, hjust = 1, size=3)+
  ggtitle("Resp rate by treat ID - apo starved E. coli")
gg_apo_starved_ecoli


```

```{r ANOVAs and visualizations - apo STARVED NO E. COLI}
#first lets subset what we want
apo_starved_no_ecoli <-subset(resp_all_nitrate.data, resp_all_nitrate.data$sym_state=="A" & resp_all_nitrate.data$food=="S" & resp_all_nitrate.data$e_coli_plate=="0")

#then lets look at the histogram to make sure its not egregious
hist(apo_starved_no_ecoli$resp_rate)
#eh its not great, pretty right skewed
#but we have been taught about the robustness of ANOVAs and t tests so lets ride

#plut it in to make an anova object
aov_apo_starved_no_ecoli <-aov(resp_rate ~ treat_ID_collapsed_controls, data=apo_starved_no_ecoli)
#need to summarize the anova object
summary(aov_apo_starved_no_ecoli)
#now we will do a pairwise Tukey
TukeyHSD(aov_apo_starved_no_ecoli)

gg_apo_starved_no_ecoli<-
  ggplot(apo_starved_no_ecoli, aes(x=treat_ID_collapsed_controls, y=resp_rate, color=temp)) +
  geom_boxplot(width=0.8) +
  geom_jitter(width=0.15, alpha=0.9) +
 # geom_line(aes(group=e_coli_plate), col="darkgray")+
  ylab("Respirometry rate")+
  xlab("Treat ID")+
  theme(legend.position="none", plot.title = element_text(size = 9)) +
  #scale_color_manual(name = "Day of experiment",
                     #labels = c("Day 1","Day 11"),
                   # values = c("royalblue","darkorchid1"))+
 # scale_x_discrete(labels=c("Day 1","Day 11")) +
    theme(axis.text.x = element_text(angle=90, vjust=.5, hjust=1))+ #this makes the x axis labels up and down instead of side to side to prevent overlapping
 annotate("text", x = Inf, y = Inf, label = paste("  "), vjust = 1, hjust = 1, size=3)+
  ggtitle("Resp rate by treat ID - apo Starved NO E. coli")
gg_apo_starved_no_ecoli
```
