---
title: "PAM data NITRATE: last updated 04/04/22 C. Fleming"
output: html_notebook
---
#NITRATE ONLY

```{r Loading all necessary packages}
# library("knitr")
# require("knitr")
# opts_knit$set(root.dir = "C:/Users/carol/Documents/PhD Boston University 2019-/Chapter_2_Ecotox/Summer_2022_N_Ecotox")
# setwd("C:/Users/carol/Documents/PhD Boston University 2019-/Chapter_2_Ecotox/Summer_2022_N_Ecotox")
# getwd()
#install.packages("lme4")
#compare with and without predictor
library("lme4")
#install.packages("lmerTest")
library("lmerTest")
#install.packages("emmeans")
library("emmeans")
#install.packages("pbkrtest")
library("pbkrtest")
#reshape melts our datasets in the way we want
library("reshape2")
library("dplyr")
library("plyr")
library("tidyverse")
library("Rmisc")
library("ggplot2")
#multiple response variables 
#check model with performance package
  #model tools R markdown
  #check for colinearity
  #r squared figures
#install.packages("performance")
#install.packages(c("rlang", "ggplot2", "performance", "dplyr", "ggrepel", "see"), dependencies = TRUE)
library("performance")
#install.packages("see")
library("see")
#install.packages("ggrepel")
library("ggrepel")
#install.packages("sjPlot") #for visualizing linear models
library(sjPlot)
#gg effects
library(MASS)
library(car)
library(outliers)

#increase the number of results it will show
options(max.print=1000000)
```


```{r Inputting data & making sure everything is organized correctly}
pam_all_nitrate.data <- read.csv("PAM_nitrate_only_4_4_23_dead_deleted.csv", header=TRUE, sep=",",stringsAsFactors = FALSE)

#getting rid of all the extra data at the bottom-- we only want rows 1:959 OR 1:639 if only looking at exp 2 and 3 (remember we got rid of the outlier!)
pam_all_nitrate.data <- na.omit(pam_all_nitrate.data)


#changing some column names
pam_all_nitrate.data<-subset(pam_all_nitrate.data, select = -c(temp))
#renaming columns in base R because dplyr is freaking out
colnames(pam_all_nitrate.data)[colnames(pam_all_nitrate.data) == "sym_state"] ="sym_state_full"
colnames(pam_all_nitrate.data)[colnames(pam_all_nitrate.data) == "sym_state.1"] ="sym_state"
colnames(pam_all_nitrate.data)[colnames(pam_all_nitrate.data) == "temp.1"] ="temp"

#Setting everything I need as factors for linear model and stats
pam_all_nitrate.data$N_species<-as.factor(pam_all_nitrate.data$N_species)
pam_all_nitrate.data$N_dose<-as.factor(pam_all_nitrate.data$N_dose)
pam_all_nitrate.data$N_species_dose<-as.factor(pam_all_nitrate.data$N_species_dose)
pam_all_nitrate.data$temp<-as.factor(pam_all_nitrate.data$temp)
pam_all_nitrate.data$food<-as.factor(pam_all_nitrate.data$food)
pam_all_nitrate.data$sym_state<-as.character(pam_all_nitrate.data$sym_state)
pam_all_nitrate.data$food_sym_state<-as.factor(pam_all_nitrate.data$food_sym_state)
pam_all_nitrate.data$control_or_nutrient<-as.factor(pam_all_nitrate.data$control_or_nutrient)
pam_all_nitrate.data$pam_percent_change<-as.numeric(pam_all_nitrate.data$pam_percent_change)

#LETS LOOK AT OUTLIERS
grubbs.test(pam_all_nitrate.data$pam_percent_change) 
#take out the outlier 33.35
pam_all_nitrate.data<-subset(pam_all_nitrate.data, pam_all_nitrate.data$pam_percent_change!=33.53846154)
grubbs.test(pam_all_nitrate.data$pam_percent_change) 
#take out the outlier 33.11
pam_all_nitrate.data<-subset(pam_all_nitrate.data, pam_all_nitrate.data$pam_percent_change!=31.11111111)
grubbs.test(pam_all_nitrate.data$pam_percent_change) 
#take out the outlier 25.79
pam_all_nitrate.data<-subset(pam_all_nitrate.data, pam_all_nitrate.data$pam_percent_change!=25.78947368)
grubbs.test(pam_all_nitrate.data$pam_percent_change) 
#take out the outlier 14
pam_all_nitrate.data<-subset(pam_all_nitrate.data, pam_all_nitrate.data$pam_percent_change!=14)
grubbs.test(pam_all_nitrate.data$pam_percent_change)
#take out the outlier 10.95121951 
pam_all_nitrate.data<-subset(pam_all_nitrate.data, pam_all_nitrate.data$pam_percent_change!=10.95121951)
grubbs.test(pam_all_nitrate.data$pam_percent_change)
#take out the outlier 10
pam_all_nitrate.data<-subset(pam_all_nitrate.data, pam_all_nitrate.data$pam_percent_change!=10)
grubbs.test(pam_all_nitrate.data$pam_percent_change)
#take out the outlier 7.170212766
pam_all_nitrate.data<-subset(pam_all_nitrate.data, pam_all_nitrate.data$pam_percent_change!=7.170212766)
grubbs.test(pam_all_nitrate.data$pam_percent_change)
#take out the outlier 4.282608696
pam_all_nitrate.data<-subset(pam_all_nitrate.data, pam_all_nitrate.data$pam_percent_change!=4.282608696)
grubbs.test(pam_all_nitrate.data$pam_percent_change, type=10)
#take out the outlier 3.866071429
pam_all_nitrate.data<-subset(pam_all_nitrate.data, pam_all_nitrate.data$pam_percent_change!=3.866071429)
grubbs.test(pam_all_nitrate.data$pam_percent_change, type=10)
#take out the outlier 3.439252336 
pam_all_nitrate.data<-subset(pam_all_nitrate.data, pam_all_nitrate.data$pam_percent_change!=3.439252336 )
grubbs.test(pam_all_nitrate.data$pam_percent_change, type=10)
#take out the outlier 3.208633094
pam_all_nitrate.data<-subset(pam_all_nitrate.data, pam_all_nitrate.data$pam_percent_change!=3.208633094 )
grubbs.test(pam_all_nitrate.data$pam_percent_change, type=10)
#take out the outlier 2.846715328
pam_all_nitrate.data<-subset(pam_all_nitrate.data, pam_all_nitrate.data$pam_percent_change!=2.846715328 )
grubbs.test(pam_all_nitrate.data$pam_percent_change, type=10)
#take out the outlier 2.81147541
pam_all_nitrate.data<-subset(pam_all_nitrate.data, pam_all_nitrate.data$pam_percent_change!=2.81147541 )
grubbs.test(pam_all_nitrate.data$pam_percent_change, type=10)
#take out the outlier 2.718954248 
pam_all_nitrate.data<-subset(pam_all_nitrate.data, pam_all_nitrate.data$pam_percent_change!=2.718954248  )
grubbs.test(pam_all_nitrate.data$pam_percent_change, type=10)
#take out the outlier 2.575
pam_all_nitrate.data<-subset(pam_all_nitrate.data, pam_all_nitrate.data$pam_percent_change!=2.575 )
grubbs.test(pam_all_nitrate.data$pam_percent_change, type=10)
#take out the outlier 2.464285714 
pam_all_nitrate.data<-subset(pam_all_nitrate.data, pam_all_nitrate.data$pam_percent_change!=2.464285714 )
grubbs.test(pam_all_nitrate.data$pam_percent_change, type=10)
#take out the outlier 2.408653846 
pam_all_nitrate.data<-subset(pam_all_nitrate.data, pam_all_nitrate.data$pam_percent_change!=2.408653846  )
grubbs.test(pam_all_nitrate.data$pam_percent_change, type=10)
#take out the outlier 2.404109589
pam_all_nitrate.data<-subset(pam_all_nitrate.data, pam_all_nitrate.data$pam_percent_change!=2.404109589  )
grubbs.test(pam_all_nitrate.data$pam_percent_change, type=10)
#take out the outlier 2.38 
pam_all_nitrate.data<-subset(pam_all_nitrate.data, pam_all_nitrate.data$pam_percent_change!=2.38  )
grubbs.test(pam_all_nitrate.data$pam_percent_change, type=10)
#take out the outlier 2.376470588
pam_all_nitrate.data<-subset(pam_all_nitrate.data, pam_all_nitrate.data$pam_percent_change!=2.376470588  )
grubbs.test(pam_all_nitrate.data$pam_percent_change, type=10)
#take out the outlier 2.272108844 
pam_all_nitrate.data<-subset(pam_all_nitrate.data, pam_all_nitrate.data$pam_percent_change!=2.272108844  )
grubbs.test(pam_all_nitrate.data$pam_percent_change, type=10)
#take out the outlier 2.133802817
pam_all_nitrate.data<-subset(pam_all_nitrate.data, pam_all_nitrate.data$pam_percent_change!=2.133802817  )
grubbs.test(pam_all_nitrate.data$pam_percent_change, type=10)
#take out the outlier 2.127659574
pam_all_nitrate.data<-subset(pam_all_nitrate.data, pam_all_nitrate.data$pam_percent_change!=2.127659574 )
grubbs.test(pam_all_nitrate.data$pam_percent_change, type=10)

#HUZZAH! THOSE ARE ALL OF THE OUTLIERS! JESUUUUUUUS

#lets check for normality in PAM_delta
hist(pam_all_nitrate.data$PAM_delta)
qqnorm(pam_all_nitrate.data$PAM_delta, main = NULL)
#not bad

#lets check for normality in percent_change
hist(pam_all_nitrate.data$pam_percent_change)
qqnorm(pam_all_nitrate.data$pam_percent_change, main = NULL)
# WOW! after we take out all the outliers it looks like we don't actually need to log

hist(pam_all_nitrate.data$PAM_avg_day1) # a little funky but it's probably okay
qqnorm(pam_all_nitrate.data$PAM_avg_day1, main = NULL)

hist(pam_all_nitrate.data$PAM_avg_day11) # a little funky but it's probably okay
qqnorm(pam_all_nitrate.data$PAM_avg_day11, main = NULL)



#change the one with negative infinity to 0
pam_all_nitrate.data[pam_all_nitrate.data$log_pam_percent_change=="-Inf", "log_pam_percent_change"] <- 0 #yay that worked! That was messing up all of our linear models
```


```{r Basic list of subsets}
# all aposymbiotic
all_apo<-subset(pam_all_nitrate.data, pam_all_nitrate.data$sym_state=="A")
# all symbiotic
all_sym<-subset(pam_all_nitrate.data, pam_all_nitrate.data$sym_state=="S")
# all fed
all_fed<-subset(pam_all_nitrate.data, pam_all_nitrate.data$food=="F")
# all starved
all_starved<-subset(pam_all_nitrate.data, pam_all_nitrate.data$food=="S")
# all 20C
all_20<-subset(pam_all_nitrate.data, pam_all_nitrate.data$temp=="20")
# all 30C
all_30<-subset(pam_all_nitrate.data, pam_all_nitrate.data$temp=="30")

#without controls
no_controls <- subset(pam_all_nitrate.data, pam_all_nitrate.data$N_dose!=0)
```


#DELTA models
```{r DELTA Model selection }
#were not going to look at genetic ID so let's do an lm

#stepAIC is from the MASS package
fullModel = lm(PAM_delta ~   N_species_dose + temp + sym_state  + N_species_dose*temp + N_species_dose*sym_state + temp*sym_state, data= pam_all_nitrate.data) # model with all variables and possible combinations

nullModel = lm(PAM_delta ~  1, data= pam_all_nitrate.data) # model with the intercept only

summary(stepAIC(nullModel, # start with a model containing no variables
                direction = 'forward', # run forward selection
                scope = list(upper = fullModel, # the maximum to consider is a model with all variables
                             lower = nullModel), # the minimum to consider is a model with no variables
                trace = 1)) # do not show the step-by-step process of model selection

summary(fullModel)
#model it selected for:
lm_pam_1 <- lm(formula = PAM_delta ~ sym_state + N_species_dose, data = pam_all_nitrate.data)
summary(lm_pam_1)

#lets check out some other models
lm_pam_2 <- lm(formula = PAM_delta ~ sym_state + N_species_dose + sym_state*N_species_dose, data = pam_all_nitrate.data)
summary(lm_pam_2)

summary(emmeans(lm_pam_3, pairwise ~ N_species_dose*temp))
#interaction of temp at n 5? Nothing pairwise
#WINNER OUT OF ALL COMBINATIONS
lm_pam_4 <- lm(formula = PAM_delta ~  N_species_dose, data = pam_all_nitrate.data)
summary(lm_pam_4)
#nothing going on
lm_pam_5 <- lm(formula = PAM_delta ~  temp + N_species_dose, data = pam_all_nitrate.data)
summary(lm_pam_5)

AIC(lm_pam_1, lm_pam_2)

#lets go with 1


plot_model(lm_pam_1, type="diag") #data fitness looks decent
r2(lm_pam_3)

```

```{r DELTA SYM linear model}
#stepAIC is from the MASS package
fullModel = lm(PAM_delta ~   N_species_dose + temp  + N_species_dose*temp, data= all_sym) # model with all 9 variables and possible combinations

nullModel = lm(PAM_delta ~  1, data= all_sym) # model with the intercept only

summary(stepAIC(nullModel, # start with a model containing no variables
                direction = 'forward', # run forward selection
                scope = list(upper = fullModel, # the maximum to consider is a model with all variables
                             lower = nullModel), # the minimum to consider is a model with no variables
                trace = 1)) # do not show the step-by-step process of model selection

summary(fullModel)
# it only selected for:
lm_sym_1 <- lm(PAM_delta ~  temp, data= all_sym)
summary(lm_sym_1)
emm_sym_pam=emmeans(lm_sym_1, specs=pairwise ~ temp)
summary(emm_sym_pam)

#lets see if we add the N_species_dose  what happens
lm_sym_2 <- lm(PAM_delta ~  N_species_dose + temp, data= all_sym)
summary(lm_sym_2)
#nope


AIC(lm_sym_1, lm_sym_2)

emm_sym_pam_N_species_dose_temp=emmeans(lm_sym_2, specs=pairwise ~ N_species_dose*temp)
summary(emm_sym_pam_N_species_dose_temp)

#really no effect of dose or sym state

#graph sym only by N species dose and temperature

# Summarize by temp and N species dose so we can visualize
sum_N_species_dose_temp_nitrate <- summarySE(all_sym, measurevar = "PAM_delta", groupvars = c("temp","N_species_dose"))
sum_N_species_dose_temp_nitrate$N_species_dose <- factor(sum_N_species_dose_temp_nitrate$N_species_dose, levels=c("CNTRL_0", "N_1.5", "N_5","N_18"))
# Visualize
gg_N_species_dose_temp_nitrate<-ggplot(data = sum_N_species_dose_temp_nitrate,
       aes(x = N_species_dose,
           y = PAM_delta, col=temp)) +
    geom_point() +
    geom_errorbar(aes(ymin=PAM_delta-se, ymax=PAM_delta+se), width=0.1, size = 1) +
    #scale_color_manual(values = c("black", "darkgreen")) +
    ggtitle ("SYM CORALS nitrate rgb - Delta R channel value") +
    labs(x = "nitrate dose", 
         y = expression(paste("Delta R channel value")), 
         caption = "data represent mean +/- SEM" ) +
    scale_x_discrete("nitrate dose", labels=c(CNTRL_0="Control", N_1.5="1.5uM", N_5="5uM", N_18="18uM"))+
    scale_color_manual("Temperature",labels=c("20C","30C"), values=c("blue", "red"))
gg_N_species_dose_temp_nitrate


# generating ptemp and pdose:
summary(aov_temp<-aov(PAM_delta ~ temp, data=all_sym))
Anova(aov_temp, type="III")
summary(emmeans(aov_temp, specs=pairwise ~ temp))

#ptemp=0.126740

summary(aov_temp<-aov(PAM_delta ~ N_species_dose, data=all_sym))
Anova(aov_temp, type="III")
summary(emmeans(aov_temp, specs=pairwise ~ N_species_dose))

#pdose=0.2416
  
#food for funsies
summary(aov_food<-aov(PAM_delta ~ food, data=all_sym))
Anova(aov_food, type="III")

#pfood=0.542

#food doesnt seem to matter at all

summary(aov_temp<-aov(pam_percent_change ~ N_species_dose*temp, data=all_sym))
Anova(aov_temp, type="III")
summary(emmeans(aov_temp, specs=pairwise ~ N_species_dose*temp))
  
```

```{r DELTA APO linear model}
#stepAIC is from the MASS package
fullModel = lm(PAM_delta ~   N_species_dose + temp  + N_species_dose*temp, data= all_apo) # model with all 9 variables and possible combinations

nullModel = lm(PAM_delta ~  1, data= all_apo) # model with the intercept only

summary(stepAIC(nullModel, # start with a model containing no variables
                direction = 'forward', # run forward selection
                scope = list(upper = fullModel, # the maximum to consider is a model with all variables
                             lower = nullModel), # the minimum to consider is a model with no variables
                trace = 1)) # do not show the step-by-step process of model selection

summary(fullModel)
#selected for -
lm_apo_1 <- lm(formula = PAM_delta ~ temp, data = all_apo)
summary(lm_apo_1)

lm_apo_2 <- lm(formula = PAM_delta ~ N_species_dose*temp, data = all_apo)
summary(lm_apo_2)

AIC(lm_apo_1, lm_apo_2)

#lets go with 1

#posthocs
emm_apo_N_species_dose=emmeans(lm_apo_1, specs=pairwise ~ temp)
summary(emm_apo_N_species_dose)
# nothing really going on


# Summarize by temp and N species dose so we can visualize
sum_N_species_dose_temp_nitrate <- summarySE(all_apo, measurevar = "PAM_delta", groupvars = c("temp","N_species_dose"))
sum_N_species_dose_temp_nitrate$N_species_dose <- factor(sum_N_species_dose_temp_nitrate$N_species_dose, levels=c("CNTRL_0", "N_1.5", "N_5","N_18"))
# Visualize
gg_N_species_dose_temp_nitrate<-ggplot(data = sum_N_species_dose_temp_nitrate,
       aes(x = N_species_dose,
           y = PAM_delta, col=temp)) +
    geom_point() +
    geom_errorbar(aes(ymin=PAM_delta-se, ymax=PAM_delta+se), width=0.1, size = 1) +
    #scale_color_manual(values = c("black", "darkgreen")) +
    ggtitle ("APO CORALS nitrate rgb - Delta Red channel value") +
    labs(x = "nitrate dose", 
         y = expression(paste("Delta Red channel value")), 
         caption = "data represent mean +/- SEM" ) +
    scale_x_discrete("nitrate dose", labels=c(CNTRL_0="Control", N_1.5="1.5uM", N_5="5uM", N_18="18uM"))+
    scale_color_manual("Temperature",labels=c("20C","30C"), values=c("blue", "red"))
gg_N_species_dose_temp_nitrate

# generating ptemp and pdose:
summary(aov_temp<-aov(PAM_delta ~ temp, data=all_apo))
Anova(aov_temp, type="III")
summary(emmeans(aov_temp, specs=pairwise ~ temp))

#ptemp=0.138

summary(aov_temp<-aov(PAM_delta ~ N_species_dose, data=all_apo))
Anova(aov_temp, type="III")
summary(emmeans(aov_temp, specs=pairwise ~ N_species_dose))

#pdose=0.3758
summary(aov_temp<-aov(PAM_delta ~ N_species_dose*temp, data=all_apo))
Anova(aov_temp, type="III")
summary(emmeans(aov_temp, specs=pairwise ~ N_species_dose*temp))

```

# LINEAR MODELS

```{r getting data ready for lmer}
pam_all_nitrate.data$N_species<-as.factor(pam_all_nitrate.data$N_species)
pam_all_nitrate.data$N_dose<-as.factor(pam_all_nitrate.data$N_dose)
pam_all_nitrate.data$N_species_dose<-as.factor(pam_all_nitrate.data$N_species_dose)
pam_all_nitrate.data$temp<-as.factor(pam_all_nitrate.data$temp)
pam_all_nitrate.data$food<-as.factor(pam_all_nitrate.data$food)
pam_all_nitrate.data$sym_state<-as.factor(pam_all_nitrate.data$sym_state)
pam_all_nitrate.data$N_species_dosee <- factor(pam_all_nitrate.data$N_species_dose, levels=c("CNTRL_0", "N_1.5", "N_5","N_18"))


summary(pam_all_nitrate.data$sym_state)
```


```{r PAM delta Model selection }
#were not going to look at genetic ID so let's do an lm

#stepAIC is from the MASS package
fullModel = lm(pam_percent_change ~   N_species_dose + temp + sym_state  + N_species_dose*temp + N_species_dose*sym_state + temp*sym_state, data= pam_all_nitrate.data) # model with all 9 variables and possible combinations

nullModel = lm(pam_percent_change ~  1, data= pam_all_nitrate.data) # model with the intercept only

summary(stepAIC(nullModel, # start with a model containing no variables
                direction = 'forward', # run forward selection
                scope = list(upper = fullModel, # the maximum to consider is a model with all variables
                             lower = nullModel), # the minimum to consider is a model with no variables
                trace = 1)) # do not show the step-by-step process of model selection

summary(fullModel)
#model it selected for:
lm_pam_1 <- lm(formula = pam_percent_change ~ temp + sym_state + sym_state*temp, data = pam_all_nitrate.data)
summary(lm_pam_1)

#lets check out some other models
lm_pam_2 <- lm(formula = pam_percent_change ~ sym_state + temp +sym_state*temp + N_species_dose*temp, data = pam_all_nitrate.data)
summary(lm_pam_2)

AIC(lm_pam_1, lm_pam_2)
#Theyre SO close in AIC, but let's go with #2 cause it is more informative :)

summary(emmeans(lm_pam_2, specs=pairwise ~ temp))
#0.0031
summary(emmeans(lm_pam_2, specs=pairwise ~ N_species_dose))
#nothing sig
summary(emmeans(lm_pam_2, specs=pairwise ~ sym_state))
#<0.0001
summary(emmeans(lm_pam_2, specs=pairwise ~ temp*sym_state))
 # contrast                estimate     SE  df t.ratio p.value
 # temp20 APO - temp30 APO   0.2366 0.0736 417   3.214  0.0077
 # temp20 APO - temp20 SYM   0.3834 0.0751 417   5.102  <.0001
 # temp20 APO - temp30 SYM   0.4530 0.0739 417   6.130  <.0001
 # temp30 APO - temp20 SYM   0.1468 0.0716 417   2.051  0.1712
 # temp30 APO - temp30 SYM   0.2164 0.0701 417   3.088  0.0115
 # temp20 SYM - temp30 SYM   0.0696 0.0718 417   0.969  0.7672
summary(emmeans(lm_pam_2, specs=pairwise ~ temp*N_species_dose))
 # temp20 N_5 - temp30 N_5          0.34741 0.1035 417   3.358  0.0192
 # temp30 N_18 - temp20 N_5        -0.37411 0.1035 417  -3.616  0.0080
 
plot_model(lm_pam_2, type="diag") #data fitness looks decent
r2(lm_pam_2) 

```

```{r SYM linear model}
#stepAIC is from the MASS package
fullModel = lm(pam_percent_change ~  N_species_dose + temp  + N_species_dose*temp, data= all_sym) # model with all 9 variables and possible combinations

nullModel = lm(pam_percent_change ~  1, data= all_sym) # model with the intercept only

summary(stepAIC(nullModel, # start with a model containing no variables
                direction = 'forward', # run forward selection
                scope = list(upper = fullModel, # the maximum to consider is a model with all variables
                             lower = nullModel), # the minimum to consider is a model with no variables
                trace = 1)) # do not show the step-by-step process of model selection

summary(fullModel)
#damn! it only selected for:
lm_sym_1 <- lm(pam_percent_change ~  1, data= all_sym)
#temp does not matter but dose does! Interesting
#WINNER
lm_sym_2 <- lm(pam_percent_change ~  N_species_dose*temp, data= all_sym)
summary(lm_sym_2)

lm_sym_3 <- lm(pam_percent_change ~  control_or_nutrient, data= all_sym)
summary(lm_sym_3)

AIC(lm_sym_2, lm_sym_1)

# they are SO close in AIC and #2 is way more informative so let's go with that

emm_sym_pam_N_species_dose_temp=emmeans(lm_sym_2, specs=pairwise ~ N_species_dose*temp)
summary(emm_sym_pam_N_species_dose_temp)

#results
 # contrast                         estimate     SE  df t.ratio p.value
 # CNTRL_0 temp30 - N_18 temp30     0.175286 0.0576 219   3.042  0.0527

#technically lm_sym_1 has a higher AIC, but its interesting to see that N species dose and temp seem to matter, so let's go with lm_sym_2


#graph sym only by N species dose and temperature

# Summarize by temp and N species dose so we can visualize
sum_N_species_dose_temp_nitrate <- summarySE(all_sym, measurevar = "pam_percent_change", groupvars = c("temp","N_species_dose"))
sum_N_species_dose_temp_nitrate$N_species_dose <- factor(sum_N_species_dose_temp_nitrate$N_species_dose, levels=c("CNTRL_0", "N_1.5", "N_5","N_18"))
# Visualize
gg_N_species_dose_temp_nitrate<-ggplot(data = sum_N_species_dose_temp_nitrate,
       aes(x = N_species_dose,
           y = pam_percent_change, col=temp)) +
    geom_point() +
    geom_errorbar(aes(ymin=pam_percent_change-se, ymax=pam_percent_change+se), width=0.1, size = 1) +
    #scale_color_manual(values = c("black", "darkgreen")) +
    ggtitle ("SYM CORALS Nitrate PAM - Change in Fv/Fm") +
    labs(x = "Nitrate dose", 
         y = expression(paste("Change in Fv/Fm")), 
         caption = "data represent mean +/- SEM" ) +
    scale_x_discrete("Nitrate dose", labels=c(CNTRL_0="Control", N_1.5="1.5uM", N_5="5uM", N_18="18uM"))+
    scale_color_manual("Temperature",labels=c("20C","30C"), values=c("blue", "red"))
gg_N_species_dose_temp_nitrate


# generating ptemp and pdose:
summary(aov_temp<-aov(pam_percent_change ~ temp, data=all_sym))
Anova(aov_temp, type="III")
summary(emmeans(aov_temp, specs=pairwise ~ temp))

#ptemp=0.33

summary(aov_temp<-aov(pam_percent_change ~ N_species_dose, data=all_sym))
Anova(aov_temp, type="III")
summary(emmeans(aov_temp, specs=pairwise ~ N_species_dose))

#pdose=0.2354

  
```

```{r APO linear model}
#stepAIC is from the MASS package
fullModel = lm(pam_percent_change ~   N_species_dose + temp  + N_species_dose*temp, data= all_apo) # model with all 9 variables and possible combinations

nullModel = lm(pam_percent_change ~  1, data= all_apo) # model with the intercept only

summary(stepAIC(nullModel, # start with a model containing no variables
                direction = 'forward', # run forward selection
                scope = list(upper = fullModel, # the maximum to consider is a model with all variables
                             lower = nullModel), # the minimum to consider is a model with no variables
                trace = 1)) # do not show the step-by-step process of model selection

summary(fullModel)
#selected for temperature ONLY
lm_apo_1 <- lm(pam_percent_change ~  temp, data= all_apo)
summary(lm_apo_1)

#lets see if we add the N_species_dose * temp what happens
lm_apo_2 <- lm(pam_percent_change ~  N_species_dose*temp, data= all_apo)
summary(lm_apo_2)
#nothing really going on

lm_apo_3 <- lm(pam_percent_change ~  control_or_nutrient, data= all_apo)
summary(lm_apo_3)


AIC(lm_apo_1, lm_apo_2)

#posthocs
emm_apo_temp=emmeans(lm_apo_1, specs=pairwise ~ temp)
summary(emm_apo_temp)
#0.0041, those at 20C had a more positive % change in PAM overall vs. 30C

emm_apo_pam_N_species_dose_temp=emmeans(lm_apo_2, specs=pairwise ~ N_species_dose*temp)
summary(emm_apo_pam_N_species_dose_temp)

#results
# NO SIGNIFICANT COMPARISIONS


# Summarize by temp and N species dose so we can visualize
sum_N_species_dose_temp_nitrate <- summarySE(all_apo, measurevar = "pam_percent_change", groupvars = c("temp","N_species_dose"))
sum_N_species_dose_temp_nitrate$N_species_dose <- factor(sum_N_species_dose_temp_nitrate$N_species_dose, levels=c("CNTRL_0", "N_1.5", "N_5","N_18"))
# Visualize
gg_N_species_dose_temp_nitrate<-ggplot(data = sum_N_species_dose_temp_nitrate,
       aes(x = N_species_dose,
           y = pam_percent_change, col=temp)) +
    geom_point() +
    geom_errorbar(aes(ymin=pam_percent_change-se, ymax=pam_percent_change+se), width=0.1, size = 1) +
    #scale_color_manual(values = c("black", "darkgreen")) +
    ggtitle ("APO CORALS Nitrate PAM - Change in Fv/Fm") +
    labs(x = "Nitrate dose", 
         y = expression(paste("Change in Fv/Fm")), 
         caption = "data represent mean +/- SEM" ) +
    scale_x_discrete("Nitrate dose", labels=c(CNTRL_0="Control", N_1.5="1.5uM", N_5="5uM", N_18="18uM"))+
    scale_color_manual("Temperature",labels=c("20C","30C"), values=c("blue", "red"))
gg_N_species_dose_temp_nitrate

# generating ptemp and pdose:
summary(aov_temp<-aov(pam_percent_change ~ temp, data=all_apo))
Anova(aov_temp, type="III")
summary(emmeans(aov_temp, specs=pairwise ~ temp))

#ptemp=0.004109

summary(aov_temp<-aov(pam_percent_change ~ N_species_dose, data=all_apo))
Anova(aov_temp, type="III")
summary(emmeans(aov_temp, specs=pairwise ~ N_species_dose))

#pdose=0.49


```

```{r ANOVAs}
# Nitrate
summary(aov_temp<-aov(PAM_delta ~ temp, data=pam_all_nitrate.data))
Anova(aov_temp, type="III")
?Anova()
summary(emmeans(aov_temp, specs=pairwise ~ temp))

```

```{r PAM delta Model posthocs}
#Really no effect of nitrate dose

# Sym state posthoc
emm_pam_sym_state=emmeans(lm_pam_1, specs=pairwise ~ sym_state)
summary(emm_pam_sym_state)
# p=<0.001

#Temperature from the whole model I dont get why there are so many NAs!
emm_pam_temp=emmeans(lm_pam_1, specs=pairwise ~ temp)
summary(emm_pam_temp)
# p=0.07, where corals under 20C had a marginally higher PAM value than those under 30C

# Sym state by N species dose
emm_pam_N_species_dose_sym_state=emmeans(lm_pam_2, specs=pairwise ~ N_species_dose*sym_state)
summary(emm_pam_N_species_dose_sym_state)
 # contrast              estimate     SE  df t.ratio p.value
 # N_1.5 A - N_1.5 S      0.13612 0.0373 462   3.650  0.0070
 # N_1.5 A - N_18 S       0.11661 0.0369 466   3.164  0.0352
 # N_1.5 A - N_5 S        0.11772 0.0370 467   3.179  0.0335
 # N_18 A - N_1.5 S       0.10468 0.0373 454   2.808  0.0956
 # CNTRL_0 S - N_1.5 S    0.10682 0.0343 425   3.118  0.0405


# temp by N species dose
emm_pam_N_species_dose_temp=emmeans(mm_pam_2, specs=pairwise ~ N_species_dose*temp)
summary(emm_pam_N_species_dose_temp)

# food by N species dose
emm_pam_N_species_dose_food=emmeans(mm_pam_3, specs=pairwise ~ N_species_dose*food)
summary(emm_pam_N_species_dose_food)
```


```{r PAM PAM day 11 Model selection }
full.model_pam_day_11_nitrate <- lmer(PAM_avg_day11 ~  N_species_dose + temp + food + sym_state + N_species_dose*temp + N_species_dose*food + N_species_dose*sym_state + temp*food + temp*sym_state + food*sym_state +  (1|col_num) + (1|exp_num) , data= pam_all_nitrate.data)
print(step.model<- step(full.model_pam_day_11_nitrate ))
#Model found:
# nothing? lmao
mm_pam_day_11_nitrate <- lmer(PAM_avg_day11 ~ (1|col_num), data= pam_all_nitrate.data) #winning model, bummer lol
r2(mm_pam_day_11_nitrate)

summary(mm_2_pam_day_11_nitrate <- lmer(PAM_avg_day11 ~  N_species_dose + temp + food + sym_state + (1|col_num), data= pam_all_nitrate.data))
emm_2_pam_day_11_nitrate =emmeans(mm_2_pam_day_11_nitrate , specs=pairwise ~ N_species_dose)
summary(emm_2_pam_day_11_nitrate ) #nope nothing significant


summary(mm_pam_day_11_nitrate <- lmer(PAM_avg_day11 ~  N_species_dose + temp + food + sym_state + (1|col_num) + (1|exp_num) , data= pam_all_nitrate.data))

# THIS TELLS ME WE REALLY SHOULD PROCEED WITH DELTA RATHER THAN DAY 11

```

```{r PAM day 11 Model posthocs}
# Nitrate dose posthoc
emm_pam_day_11_nitrate=emmeans(mm_pam_day_11_nitrate, specs=pairwise ~ N_species_dose)
summary(emm_pam_day_11_nitrate)
 # contrast        estimate     SE  df t.ratio p.value
 # CNTRL_0 - N_1.5  0.02742 0.0209 426   1.314  0.5545
 # CNTRL_0 - N_5    0.02389 0.0209 436   1.141  0.6642
 # CNTRL_0 - N_18   0.03869 0.0209 440   1.853  0.2501
 # N_1.5 - N_5     -0.00354 0.0209 433  -0.169  0.9983

 # N_1.5 - N_18     0.01127 0.0209 440   0.538  0.9496
 # N_5 - N_18       0.01481 0.0207 420   0.716  0.8907

```

```{r Exploratory t tests}
t.test(all_20$PAM_delta, all_30$PAM_delta) #no difference

t.test(all_fed$PAM_delta, all_starved$PAM_delta) #no difference

t.test(all_sym$PAM_delta, all_apo$PAM_delta) #p-value = 0.0000002325
```



```{r CHALK TALK Linear models -- nutrient or control & sym (ONLY ON SYMBIOTIC CORALS) }



#sym full model -- not including genetic data

fullModel = lm(PAM_delta ~   N_species_dose + temp + food +  N_species_dose*temp + N_species_dose*food  + temp*food, data= all_sym) # model with all 9 variables and possible combinations

nullModel = lm(PAM_delta ~  1, data= all_sym) # model with the intercept only

summary(stepAIC(nullModel, # start with a model containing no variables
                direction = 'forward', # run forward selection
                scope = list(upper = fullModel, # the maximum to consider is a model with all variables
                             lower = nullModel), # the minimum to consider is a model with no variables
                trace = 1)) # do not show the step-by-step process of model selection


mm_sym<- lm(PAM_delta ~  N_species_dose, data= all_sym)
summary(full.model_sym)

emm_sym=emmeans(mm_sym , specs=pairwise ~ N_species_dose)
summary(emm_sym)

summary(aov_sym<-aov(PAM_delta ~ N_species_dose, data=all_sym))
TukeyHSD(aov_sym, "N_species_dose")

all_sym$N_species_dose <- factor(all_sym$N_species_dose, levels=c("CNTRL_0", "N_1.5", "N_5","N_18"))
#now plot sym corals by N species dose
# Summarize by N_species_dose so we can visualize
sum_sym_N_species_dose_nitrate <- summarySE(all_sym, measurevar = "PAM_delta", groupvars = c("N_species_dose"))
# Visualize
gg_sym_N_species_dose_nitrate<-ggplot(data = sum_sym_N_species_dose_nitrate,
       aes(x = N_species_dose,
           y = PAM_delta, col=N_species_dose)) +
    geom_point(size=4) +
   theme(
  axis.text.x = element_text(size = 22),
   axis.title.x = element_text(size = 30),
  axis.text.y = element_text(size = 24),
   axis.title.y = element_text(size = 30)) +
 ylim(-.18, 0.015) +
    geom_errorbar(aes(ymin=PAM_delta-se, ymax=PAM_delta+se), width=0.3, size = 2) +
    #scale_color_manual(values = c("black", "darkgreen")) +
  #  ggtitle ("Nitrate - N Species Dose summary for sym corals") +
   theme(legend.position="none")+
    labs(x = "\n", 
         y = expression(paste("Change in Fv/Fm"))) +
    scale_x_discrete("Dose", labels=c(CNTRL_0="Control", N_1.5="Ambient", N_5="Intermediate", N_18="High"))+
    scale_color_manual(labels=labels, values=c("blue", "#9DCE9D","#359C35","darkgreen"))
gg_sym_N_species_dose_nitrate


# Summarize by N_species_dose so we can visualize
sum_sym_temp <- summarySE(all_sym, measurevar = "PAM_delta", groupvars = c("temp", "control_or_nutrient"))
# Visualize
gg_sum_sym_temp<-ggplot(data = sum_sym_temp,
       aes(x =control_or_nutrient,
           y = PAM_delta, col=temp)) +
    geom_point(size=4) +
   theme(
  axis.text.x = element_text(size = 22),
   axis.title.x = element_text(size = 30),
  axis.text.y = element_text(size = 24),
   axis.title.y = element_text(size = 28)) +
 ylim(-.2, 0.1) +
    geom_errorbar(aes(ymin=PAM_delta-se, ymax=PAM_delta+se), width=0.3, size = 2) +
    #scale_color_manual(values = c("black", "darkgreen")) +
  #  ggtitle ("Nitrate - N Species Dose summary for sym corals") +
   theme( legend.title = element_text(size=20), legend.text = element_text(size=20))+
    labs(x = "\n", 
         y = expression(paste("Change in Fv/Fm"))) +
     scale_color_manual(" Temperature ", labels=c("20C","30C"), values=c("blue", "darkred"))
gg_sum_sym_temp

#nutrient or control

full.model_pam_nutrient_or_control<- lmer(PAM_delta ~  control_or_nutrient + temp + food + control_or_nutrient*temp + control_or_nutrient*food +  temp*food +  (1|col_num) + (1|exp_num) , data= all_sym)
summary(full.model_pam_nutrient_or_control)
print(step.model<- step(full.model_pam_nutrient_or_control))

#CONTROL OR NUTRIENT -- 
mm_pam_control_or_nutrient <- lmer(PAM_delta ~  control_or_nutrient + (1 | col_num) + (1 | exp_num), data=pam_all_nitrate.data)
summary(mm_pam_control_or_nutrient)

emm_test=emmeans(mm_pam_control_or_nutrient , specs=pairwise ~ control_or_nutrient)
summary(emm_test)

tab_model(mm_pam_control_or_nutrient)
```




```{r Subsetting by sym state with visualizations}
#We're interested to see how sym state drives reaction to dose and temperature seperately

#Symbiotic corals
full.model_pam_nitrate_sym <- lmer(PAM_delta ~  N_species_dose + temp + food +  N_species_dose*temp + N_species_dose*food + temp*food + (1|col_num) + (1|exp_num) , data= all_sym)
summary(full.model_pam_nitrate_sym )
print(step.model<- step(full.model_pam_nitrate_sym ))
#lets just add N species dose and temperature cause thats what were interested in
summary(mm_nitrate_sym <- lmer(PAM_delta ~  N_species_dose + temp + (1|col_num) + (1|exp_num) , data= all_sym))
#posthoc to see differences
emm_temp_dose_sym=emmeans(mm_nitrate_sym, specs=pairwise ~ temp*N_species_dose)
summary(emm_temp_dose_sym)
 # NO SIGNIFICANT COMPARISONS

#now plot
sum_temp_dose_nitrate_sym <- summarySE(all_sym, measurevar = "PAM_delta", groupvars = c("temp", "N_species_dose"))
sum_temp_dose_nitrate_sym$N_species_dose <- factor(sum_temp_dose_nitrate_sym$N_species_dose, levels=c("CNTRL_0", "N_1.5", "N_5","N_18"))
gg_sum_temp_dose_nitrate_sym<-ggplot(data = sum_temp_dose_nitrate_sym,
       aes(x = N_species_dose,
           y = PAM_delta, col=temp)) +
    geom_point() +
    geom_errorbar(aes(ymin=PAM_delta-se, ymax=PAM_delta+se), width=0.1, size = 1) +
    #scale_color_manual(values = c("black", "darkgreen")) +
    ggtitle ("Nitrate- Temperature and dose summary - Sym corals") +
  theme(legend.position="none")+
    labs(x = "Nitrate dose", 
         y = expression(paste("Change in Fv/Fm")), 
         caption = "data represent mean +/- SEM" ) +
      scale_x_discrete("nitrate dose", labels=c(CNTRL_0="Control", N_1.5="1.5uM", N_5="5uM", N_18="18uM"))+
    scale_color_manual(labels=labels, values=c("blue", "red"))
gg_sum_temp_dose_nitrate_sym

#Aposymbiotic corals
full.model_pam_nitrate_apo <- lmer(PAM_delta ~  N_species_dose + temp + food +  N_species_dose*temp + N_species_dose*food + temp*food + (1|col_num) + (1|exp_num) , data= all_apo)
summary(full.model_pam_nitrate_apo )
print(step.model<- step(full.model_pam_nitrate_apo ))
#lets just add N species dose and temperature cause thats what were interested in
summary(mm_nitrate_apo <- lmer(PAM_delta ~  N_species_dose + temp + (1|col_num) + (1|exp_num) , data= all_apo))
#posthoc to see differences
emm_temp_dose_apo=emmeans(mm_nitrate_apo, specs=pairwise ~ temp*N_species_dose)
summary(emm_temp_dose_apo)
 # NO STAT DIFFERENCES!

#now plot
sum_temp_dose_nitrate_apo <- summarySE(all_apo, measurevar = "PAM_delta", groupvars = c("temp", "N_species_dose"))
sum_temp_dose_nitrate_apo$N_species_dose <- factor(sum_temp_dose_nitrate_apo$N_species_dose, levels=c("CNTRL_0", "N_1.5", "N_5","N_18"))
gg_sum_temp_dose_nitrate_apo<-ggplot(data = sum_temp_dose_nitrate_apo,
       aes(x = N_species_dose,
           y = PAM_delta, col=temp)) +
    geom_point() +
    geom_errorbar(aes(ymin=PAM_delta-se, ymax=PAM_delta+se), width=0.1, size = 1) +
    #scale_color_manual(values = c("black", "darkgreen")) +
    ggtitle ("nitrate- Temperature and dose summary - Apo corals") +
  theme(legend.position="none")+
    labs(x = "nitrate dose", 
         y = expression(paste("Change in Fv/Fm")), 
         caption = "data represent mean +/- SEM" ) +
  scale_x_discrete("nitrate dose", labels=c(CNTRL_0="Control", N_1.5="1.5uM", N_5="5uM", N_18="18uM"))+
    scale_color_manual(labels=labels, values=c("blue", "red"))
gg_sum_temp_dose_nitrate_apo



```

# VISUALIZATIONS
```{r Prepping for visualizations}
pam_all_nitrate.data$N_species_dose <- factor(pam_all_nitrate.data$N_species_dose, levels=c("CNTRL_0", "N_1.5", "N_5","N_18"))
pam_all_nitrate.data$N_species_dose<-as.character(pam_all_nitrate.data$N_species_dose)
pam_all_nitrate.data$sym_state<-as.character(pam_all_nitrate.data$sym_state)
pam_all_nitrate.data$temp <- as.character(pam_all_nitrate.data$temp)
```


```{r Symbiotic State - PAM_delta}
#overall apo vs. sym
t.test(all_apo$PAM_avg_day11, all_sym$PAM_avg_day11)


pam_treatmeans_apovsym <- summarySE(pam_all_nitrate.data, measurevar=c("PAM_delta"),groupvars =c("sym_state"), na.rm=TRUE)

#NITRATE ONLY 
# plot, treatment x axis colored by site data figure
gg_pam_plot_apovsym <- ggplot(pam_treatmeans_apovsym, aes(x = sym_state, y= c(PAM_delta), color = sym_state))+
  theme_bw()+
  geom_point(size = 3, position = position_dodge(width=0.3))+
  geom_smooth(aes(group=sym_state), position = position_dodge(width=0.3), size = 0.5, method='lm', se = FALSE)+
 # geom_jitter(aes(), size=1.2, alpha=0.9)+
  geom_line(aes(group = sym_state), size = 0.5, linetype="dashed", position = position_dodge(width=0.3))+
  geom_errorbar(aes(x = sym_state, ymax = PAM_delta+se, ymin = PAM_delta-se), width = .2, position = position_dodge(width=0.3)) +
  #scale_color_manual(name = "Treatment",
                    #labels = c("Control 30C Fed","Control 30C Starved","Ammonium High 30C Fed", "Ammonium High 30C Starved","test"),
                    # values = c("orchid1","darkorchid1","royalblue","skyblue","black","gray","brown"))+
 ylab("Change in Fv/Fm Pre vs. Post-experiment")+
  ggtitle("Change in Fv/Fm Sym vs. Apo")+
 labs(caption = "data represent mean +/- SEM, p=0.0006***")+
  scale_x_discrete("Symboitic State", labels=c(A="Aposymbiotic", S="Symbiotic"))+ #relabels the x axis to the values in quotations
    scale_color_manual("Symboitic State", labels=c(A="Aposymbiotic", S="Symbiotic"), values=c("gray", "brown")) #gives you the colors for each point on the graph
gg_pam_plot_apovsym

# Summarize by temp and N species dose so we can visualize
sum_N_species_dose_sym_state_nitrate <- summarySE(pam_all_nitrate.data, measurevar = "PAM_delta", groupvars = c("sym_state","N_species_dose"))
sum_N_species_dose_sym_state_nitrate$N_species_dose <- factor(sum_N_species_dose_sym_state_nitrate$N_species_dose, levels=c("CNTRL_0", "N_1.5", "N_5","N_18"))
# Visualize
gg_N_species_dose_sym_state_nitrate<-ggplot(data = sum_N_species_dose_sym_state_nitrate,
       aes(x = N_species_dose,
           y = PAM_delta, colour=sym_state)) +
    geom_point() +
    geom_errorbar(aes(ymin=PAM_delta-se, ymax=PAM_delta+se), width=0.1, size = 1) +
    #scale_color_manual(values = c("black", "darkgreen")) +
    ggtitle ("Nitrate - Change in Fv/Fm by sym state and dose") +
    
   # scale_x_discrete(labels=c("20C","30C"))+
    labs(x = "Nitrate dose", 
         y = expression(paste("Change in Photosynthetic Efficiency Fv/Fm")), 
         caption = "data represent mean +/- SEM" ) +
    scale_x_discrete("Nitrate dose", labels=c(CNTRL_0="Control", N_1.5="1.5uM", N_5="5uM", N_18="18uM"))+
    scale_color_manual("Sym State", labels=c("Aposymbiotic","Symbiotic"), values=c("gray", "brown"))
gg_N_species_dose_sym_state_nitrate
# Summarize by food and sym state so we can visualize
sum_food_sym_state_nitrate <- summarySE(pam_all_nitrate.data, measurevar = "PAM_delta", groupvars = c("sym_state","food"))
# Visualize
gg_food_sym_state_nitrate<-ggplot(data = sum_food_sym_state_nitrate,
       aes(x = sym_state,
           y = PAM_delta, col=food)) + #use fill here or the legends will be really hard to work with
    geom_point() +
    geom_errorbar(aes(ymin=PAM_delta-se, ymax=PAM_delta+se), width=0.1, size = 1) +
    ggtitle ("PAM delta Fv/Fm Sym vs. Apo at various nitrate doses") +
   #scale_fill_manual(name="Feeding Regime", labels=c('Fed', 'Starved'))+
 # scale_fill_manual(values=c("brown", "darkgray"))+
    labs(x = "Symbiotic state", 
         y = expression(paste("Change in Photosynthetic Efficiency Fv/Fm")), 
         caption = "data represent mean +/- SEM" ) +
      scale_x_discrete(name="Symboitic state", labels=c("A"="Aposymbiotic", "S"="Symbiotic")) +
  # scale_fill_manual(values=c("brown", "darkgray"))
 scale_color_manual(values=c("orange", "black"))
gg_food_sym_state_nitrate 

 
# WITHOUT CONTROLS #
# plot, treatment x axis colored by site data figure
pam_treatmeans_apovsym <- summarySE(no_controls, measurevar=c("PAM_delta"),groupvars =c("sym_state"), na.rm=TRUE)
gg_pam_plot_apovsym <- ggplot(pam_treatmeans_apovsym, aes(x = sym_state, y= c(PAM_delta), color = sym_state))+
  theme_bw()+
  geom_point(size = 3, position = position_dodge(width=0.3))+
  geom_smooth(aes(group=sym_state), position = position_dodge(width=0.3), size = 0.5, method='lm', se = FALSE)+
 # geom_jitter(aes(), size=1.2, alpha=0.9)+
  geom_line(aes(group = sym_state), size = 0.5, linetype="dashed", position = position_dodge(width=0.3))+
  geom_errorbar(aes(x = sym_state, ymax = PAM_delta+se, ymin = PAM_delta-se), width = .2, position = position_dodge(width=0.3)) +
  #scale_color_manual(name = "Treatment",
                    #labels = c("Control 30C Fed","Control 30C Starved","Ammonium High 30C Fed", "Ammonium High 30C Starved","test"),
                    # values = c("orchid1","darkorchid1","royalblue","skyblue","black","gray","brown"))+
 ylab("Change in Photosynthetic Efficiency Fv/Fm")+
  ggtitle("No Controls PAM delta Fv/Fm Sym vs. Apo")+
 labs(caption = "data represent mean +/- SEM, p=")+
  scale_x_discrete("Symboitic State", labels=c(A="Aposymbiotic", S="Symbiotic"))+ #relabels the x axis to the values in quotations
    scale_color_manual("Symboitic State", labels=c(A="Aposymbiotic", S="Symbiotic"), values=c("gray", "brown")) #gives you the colors for each point on the graph
gg_pam_plot_apovsym

# Summarize by food and sym state so we can visualize
sum_food_sym_state_nitrate <- summarySE(no_controls, measurevar = "PAM_delta", groupvars = c("sym_state","food"))
# Visualize
gg_food_sym_state_nitrate<-ggplot(data = sum_food_sym_state_nitrate,
       aes(x = sym_state,
           y = PAM_delta, col=food)) + #use fill here or the legends will be really hard to work with
    geom_point() +
    geom_errorbar(aes(ymin=PAM_delta-se, ymax=PAM_delta+se), width=0.1, size = 1) +
    ggtitle ("No Controls PAM delta Fv/Fm Sym vs. Apo at various nitrate doses") +
   #scale_fill_manual(name="Feeding Regime", labels=c('Fed', 'Starved'))+
 # scale_fill_manual(values=c("brown", "darkgray"))+
    labs(x = "Symbiotic state", 
         y = expression(paste("Change in Photosynthetic Efficiency Fv/Fm")), 
         caption = "data represent mean +/- SEM" ) +
      scale_x_discrete(name="Symboitic state", labels=c("A"="Aposymbiotic", "S"="Symbiotic")) +
  # scale_fill_manual(values=c("brown", "darkgray"))
 scale_color_manual(values=c("orange", "black"))
gg_food_sym_state_nitrate #seems obvious that food doesnt matter

```


```{r Symbiotic State - PAM_avg_day11}
#overall apo vs. sym
t.test(all_apo$PAM_avg_day11, all_sym$PAM_avg_day11)


pam_treatmeans_apovsym <- summarySE(pam_all_nitrate.data, measurevar=c("PAM_avg_day11"),groupvars =c("sym_state"), na.rm=TRUE)

#NITRATE ONLY 
# plot, treatment x axis colored by site data figure
gg_pam_plot_apovsym <- ggplot(pam_treatmeans_apovsym, aes(x = sym_state, y= c(PAM_avg_day11), color = sym_state))+
  theme_bw()+
  geom_point(size = 3, position = position_dodge(width=0.3))+
  geom_smooth(aes(group=sym_state), position = position_dodge(width=0.3), size = 0.5, method='lm', se = FALSE)+
 # geom_jitter(aes(), size=1.2, alpha=0.9)+
  geom_line(aes(group = sym_state), size = 0.5, linetype="dashed", position = position_dodge(width=0.3))+
  geom_errorbar(aes(x = sym_state, ymax = PAM_avg_day11+se, ymin = PAM_avg_day11-se), width = .2, position = position_dodge(width=0.3)) +
  #scale_color_manual(name = "Treatment",
                    #labels = c("Control 30C Fed","Control 30C Starved","Ammonium High 30C Fed", "Ammonium High 30C Starved","test"),
                    # values = c("orchid1","darkorchid1","royalblue","skyblue","black","gray","brown"))+
 ylab("Day 11 Fv/Fm")+
  ggtitle("Day 11 Fv/Fm Sym vs. Apo")+
 labs(caption = "data represent mean +/- SEM, p=")+
  scale_x_discrete("Symboitic State", labels=c(A="Aposymbiotic", S="Symbiotic"))+ #relabels the x axis to the values in quotations
    scale_color_manual("Symboitic State", labels=c(A="Aposymbiotic", S="Symbiotic"), values=c("gray", "brown")) #gives you the colors for each point on the graph
gg_pam_plot_apovsym

# Summarize by food and sym state so we can visualize
sum_food_sym_state_nitrate <- summarySE(pam_all_nitrate.data, measurevar = "PAM_avg_day11", groupvars = c("sym_state","food"))
# Visualize
gg_food_sym_state_nitrate<-ggplot(data = sum_food_sym_state_nitrate,
       aes(x = sym_state,
           y = PAM_avg_day11, col=food)) + #use fill here or the legends will be really hard to work with
    geom_point() +
    geom_errorbar(aes(ymin=PAM_avg_day11-se, ymax=PAM_avg_day11+se), width=0.1, size = 1) +
    ggtitle ("Day 11 Fv/Fm Sym vs. Apo at various nitrate doses") +
   #scale_fill_manual(name="Feeding Regime", labels=c('Fed', 'Starved'))+
 # scale_fill_manual(values=c("brown", "darkgray"))+
    labs(x = "Symbiotic state", 
         y = expression(paste("Day 11 Fv/Fm")), 
         caption = "data represent mean +/- SEM" ) +
      scale_x_discrete(name="Symboitic state", labels=c("A"="Aposymbiotic", "S"="Symbiotic")) +
  # scale_fill_manual(values=c("brown", "darkgray"))
 scale_color_manual(values=c("orange", "black"))
gg_food_sym_state_nitrate #seems obvious that food doesnt matter

# Summarize by temp and N species dose so we can visualize
sum_N_species_dose_sym_state_nitrate <- summarySE(pam_all_nitrate.data, measurevar = "PAM_avg_day11", groupvars = c("sym_state","N_species_dose"))
# Visualize
gg_N_species_dose_sym_state_nitrate<-ggplot(data = sum_N_species_dose_sym_state_nitrate,
       aes(x = N_species_dose,
           y = PAM_avg_day11, colour=sym_state)) +
    geom_point() +
    geom_errorbar(aes(ymin=PAM_avg_day11-se, ymax=PAM_avg_day11+se), width=0.1, size = 1) +
    #scale_color_manual(values = c("black", "darkgreen")) +
    ggtitle ("Day 11 Fv/Fm Sym state and N species dose") +
   # scale_x_discrete(labels=c("20C","30C"))+
    labs(x = "Nitrate dose", 
         y = expression(paste("Day 11 Fv/Fm")), 
         caption = "data represent mean +/- SEM" ) +
    scale_x_discrete("Nitrate dose", labels=c(CNTRL_0="Control", N_1.5="1.5uM", N_5="5uM", N_18="18uM"))+
    scale_color_manual("Sym State", labels=c("Aposymbiotic","Symbiotic"), values=c("gray", "brown"))
gg_N_species_dose_sym_state_nitrate


# WITHOUT CONTROLS #
# plot, treatment x axis colored by site data figure
pam_treatmeans_apovsym <- summarySE(no_controls, measurevar=c("PAM_avg_day11"),groupvars =c("sym_state"), na.rm=TRUE)
gg_pam_plot_apovsym <- ggplot(pam_treatmeans_apovsym, aes(x = sym_state, y= c(PAM_avg_day11), color = sym_state))+
  theme_bw()+
  geom_point(size = 3, position = position_dodge(width=0.3))+
  geom_smooth(aes(group=sym_state), position = position_dodge(width=0.3), size = 0.5, method='lm', se = FALSE)+
 # geom_jitter(aes(), size=1.2, alpha=0.9)+
  geom_line(aes(group = sym_state), size = 0.5, linetype="dashed", position = position_dodge(width=0.3))+
  geom_errorbar(aes(x = sym_state, ymax = PAM_avg_day11+se, ymin = PAM_avg_day11-se), width = .2, position = position_dodge(width=0.3)) +
  #scale_color_manual(name = "Treatment",
                    #labels = c("Control 30C Fed","Control 30C Starved","Ammonium High 30C Fed", "Ammonium High 30C Starved","test"),
                    # values = c("orchid1","darkorchid1","royalblue","skyblue","black","gray","brown"))+
 ylab("Day 11 Fv/Fm")+
  ggtitle("No Controls Day 11 Fv/Fm Sym vs. Apo")+
 labs(caption = "data represent mean +/- SEM, p=")+
  scale_x_discrete("Symboitic State", labels=c(A="Aposymbiotic", S="Symbiotic"))+ #relabels the x axis to the values in quotations
    scale_color_manual("Symboitic State", labels=c(A="Aposymbiotic", S="Symbiotic"), values=c("gray", "brown")) #gives you the colors for each point on the graph
gg_pam_plot_apovsym

# Summarize by food and sym state so we can visualize
sum_food_sym_state_nitrate <- summarySE(no_controls, measurevar = "PAM_avg_day11", groupvars = c("sym_state","food"))
# Visualize
gg_food_sym_state_nitrate<-ggplot(data = sum_food_sym_state_nitrate,
       aes(x = sym_state,
           y = PAM_avg_day11, col=food)) + #use fill here or the legends will be really hard to work with
    geom_point() +
    geom_errorbar(aes(ymin=PAM_avg_day11-se, ymax=PAM_avg_day11+se), width=0.1, size = 1) +
    ggtitle ("No Controls Day 11 Fv/Fm Sym vs. Apo at various nitrate doses") +
   #scale_fill_manual(name="Feeding Regime", labels=c('Fed', 'Starved'))+
 # scale_fill_manual(values=c("brown", "darkgray"))+
    labs(x = "Symbiotic state", 
         y = expression(paste("Day 11 Fv/Fm")), 
         caption = "data represent mean +/- SEM" ) +
      scale_x_discrete(name="Symboitic state", labels=c("A"="Aposymbiotic", "S"="Symbiotic")) +
  # scale_fill_manual(values=c("brown", "darkgray"))
 scale_color_manual(values=c("orange", "black"))
gg_food_sym_state_nitrate #seems obvious that food doesnt matter


```


```{r Fed vs. Starved - Pam delta and day 11}
#Don't think theres anything going on here

# Pam Delta Fed vs. starved
pam_treatmeans_fedvstarved_delta <- summarySE(pam_all_nitrate.data, measurevar=c("PAM_delta"),groupvars =c("food"), na.rm=TRUE)
# plot, treatment x axis colored by site data figure
pam_plot_fedvstarved_delta <-ggplot(pam_treatmeans_fedvstarved_delta, aes(x = food, y= c(PAM_delta), color = food))+
  theme_bw()+
  geom_point(size = 3, position = position_dodge(width=0.3))+
  geom_smooth(aes(group=food), position = position_dodge(width=0.3), size = 0.5, method='lm', se = FALSE)+
 # geom_jitter(aes(), size=1.2, alpha=0.9)+
  geom_line(aes(group = food), size = 0.5, linetype="dashed", position = position_dodge(width=0.3))+
  geom_errorbar(aes(x = food, ymax = PAM_delta+se, ymin = PAM_delta-se), width = .2, position = position_dodge(width=0.3)) +
 ylab("PAMdelta Fv/Fm")+
  ggtitle("Fed vs. starved PAM delta")
pam_plot_fedvstarved_delta

# Day 11 Fed vs. starved
pam_treatmeans_fedvstarved_day11 <- summarySE(pam_all_nitrate.data, measurevar=c("PAM_avg_day11"),groupvars =c("food"), na.rm=TRUE)
# plot, treatment x axis colored by site data figure
pam_plot_fedvstarved_day11 <- ggplot(pam_treatmeans_fedvstarved_day11, aes(x = food, y= c(PAM_avg_day11), color = food))+
  theme_bw()+
  geom_point(size = 3, position = position_dodge(width=0.3))+
  geom_smooth(aes(group=food), position = position_dodge(width=0.3), size = 0.5, method='lm', se = FALSE)+
 # geom_jitter(aes(), size=1.2, alpha=0.9)+
  geom_line(aes(group = food), size = 0.5, linetype="dashed", position = position_dodge(width=0.3))+
  geom_errorbar(aes(x = food, ymax = PAM_avg_day11+se, ymin = PAM_avg_day11-se), width = .2, position = position_dodge(width=0.3)) +
  #scale_color_manual(name = "Treatment",
                    #labels = c("Control 30C Fed","Control 30C Starved","Ammonium High 30C Fed", "Ammonium High 30C Starved","test"),
                    # values = c("orchid1","darkorchid1","royalblue","skyblue","black","gray","brown"))+
 ylab("PAM_avg_day11 Fv/Fm")+
  ggtitle("Fed vs. starved PAM day 11")+
pam_plot_fedvstarved_day11


```


```{r PAM delta hot vs. ambient overall}

# Temp on its own doesnt seem to matter but sym and apo are driving the models so much we will separate them below
pam_treatmeans_20vs30 <- summarySE(pam_all_nitrate.data, measurevar=c("PAM_delta"),groupvars =c("temp"), na.rm=TRUE)

t.test(pam_all_nitrate.data_simplified_controls$temp=="20", pam_all_nitrate.data_simplified_controls$temp=="30")

# Summarize by temperature so we can visualize
sum_temp_nitrate <- summarySE(pam_all_nitrate.data, measurevar = "PAM_delta", groupvars = c("temp"))
# Visualize
gg_temp_nitrate<-ggplot(data = sum_temp_nitrate,
       aes(x = temp,
           y = PAM_delta, col=temp)) +
    geom_point() +
    geom_errorbar(aes(ymin=PAM_delta-se, ymax=PAM_delta+se), width=0.1, size = 1) +
    #scale_color_manual(values = c("black", "darkgreen")) +
    ggtitle ("Nitrate PAM Delta Temperature summary") +
  theme(legend.position="none")+
    labs(x = "Temperature", 
         y = expression(paste("Change in Photosynthetic Efficiency Fv/Fm")), 
         caption = "data represent mean +/- SEM" ) +
    scale_x_discrete("Temperature", labels=c("20"="Control 20C", "30"="Elevated 30C")) +
    scale_color_manual("Temperature",labels=c("20C", "30C"), values=c("blue", "red"))
gg_temp_nitrate

#Let's try this on data without controls
pam_treatmeans_20vs30 <- summarySE(no_controls, measurevar=c("PAM_delta"),groupvars =c("temp"), na.rm=TRUE)
# Summarize by temperature so we can visualize
sum_temp_nitrate <- summarySE(pam_all_nitrate.data, measurevar = "PAM_delta", groupvars = c("temp"))
# Visualize
gg_temp_nitrate<-ggplot(data = sum_temp_nitrate,
       aes(x = temp,
           y = PAM_delta, col=temp)) +
    geom_point() +
    geom_errorbar(aes(ymin=PAM_delta-se, ymax=PAM_delta+se), width=0.1, size = 1) +
    #scale_color_manual(values = c("black", "darkgreen")) +
    ggtitle ("No controls Nitrate PAM Delta Temperature summary") +
  theme(legend.position="none")+
    labs(x = "Temperature", 
         y = expression(paste("Change in Photosynthetic Efficiency Fv/Fm")), 
         caption = "data represent mean +/- SEM" ) +
    scale_x_discrete("Temperature", labels=c("20"="Control 20C", "30"="Elevated 30C")) +
    scale_color_manual("Temperature",labels=c("20C", "30C"), values=c("blue", "red"))
gg_temp_nitrate

#summarize by temp and sym state with and without controls
pam_treatmeans_temp_sym <- summarySE(pam_all_nitrate.data, measurevar=c("PAM_delta"),groupvars =c("temp", "sym_state"), na.rm=TRUE)
# Visualize
gg_pam_treatmeans_temp_sym<-ggplot(data = pam_treatmeans_temp_sym,
       aes(x = sym_state,
           y = PAM_delta, col=temp)) +
    geom_point() +
    geom_errorbar(aes(ymin=PAM_delta-se, ymax=PAM_delta+se), width=0.1, size = 1) +
    #scale_color_manual(values = c("black", "darkgreen")) +
    ggtitle ("Nitrate PAM Delta sym state Temperature summary") +
  theme(legend.position="none")+
    labs(x = "Temperature", 
         y = expression(paste("Change in Photosynthetic Efficiency Fv/Fm")), 
         caption = "data represent mean +/- SEM" ) +
    scale_x_discrete("Sym State", labels=c("A"="Apo", "S"="Sym")) +
    scale_color_manual("Temp",labels=c("20", "30"), values=c("blue", "red"))
gg_pam_treatmeans_temp_sym
#Let's try this on data without controls
pam_treatmeans_temp_sym <- summarySE(no_controls, measurevar=c("PAM_delta"),groupvars =c("temp", "sym_state"), na.rm=TRUE)
# Visualize
gg_pam_treatmeans_temp_sym<-ggplot(data = pam_treatmeans_temp_sym,
       aes(x = sym_state,
           y = PAM_delta, col=temp)) +
    geom_point() +
    geom_errorbar(aes(ymin=PAM_delta-se, ymax=PAM_delta+se), width=0.1, size = 1) +
    #scale_color_manual(values = c("black", "darkgreen")) +
    ggtitle ("No controls Nitrate PAM Delta sym state Temperature summary") +
  theme(legend.position="none")+
    labs(x = "Temperature", 
         y = expression(paste("Change in Photosynthetic Efficiency Fv/Fm")), 
         caption = "data represent mean +/- SEM" ) +
    scale_x_discrete("Sym State", labels=c("A"="Apo", "S"="Sym")) +
    scale_color_manual("Temp",labels=c("20", "30"), values=c("blue", "red"))
gg_pam_treatmeans_temp_sym

# Summarize by temp and N species dose so we can visualize
sum_N_species_dose_temp_nitrate <- summarySE(pam_all_nitrate.data, measurevar = "PAM_delta", groupvars = c("temp","N_species_dose"))
# Visualize
gg_N_species_dose_temp_nitrate<-ggplot(data = sum_N_species_dose_temp_nitrate,
       aes(x = N_species_dose,
           y = PAM_delta, col=temp)) +
    geom_point() +
    geom_errorbar(aes(ymin=PAM_delta-se, ymax=PAM_delta+se), width=0.1, size = 1) +
    #scale_color_manual(values = c("black", "darkgreen")) +
    ggtitle ("Nitrate PAM Delta Dose and Temperature summary") +
    labs(x = "Nitrate dose", 
         y = expression(paste("Change in Photosynthetic Efficiency Fv/Fm")), 
         caption = "data represent mean +/- SEM" ) +
    scale_x_discrete("Nitrate dose", labels=c(CNTRL_0="Control", N_1.5="1.5uM", N_5="5uM", N_18="18uM"))+
    scale_color_manual("Temperature",labels=c("20C","30C"), values=c("blue", "red"))
gg_N_species_dose_temp_nitrate

# Separate by sym state - temp x N species dose

# Sym corals
sum_N_species_dose_temp_nitrate_sym <- summarySE(all_sym, measurevar = "PAM_delta", groupvars = c("temp","N_species_dose"))
# Visualize
gg_N_species_dose_temp_nitrate_sym<-ggplot(data = sum_N_species_dose_temp_nitrate_sym,
       aes(x = N_species_dose,
           y = PAM_delta, col=temp)) +
    geom_point() +
    geom_errorbar(aes(ymin=PAM_delta-se, ymax=PAM_delta+se), width=0.1, size = 1) +
    #scale_color_manual(values = c("black", "darkgreen")) +
    ggtitle ("Symbiotic Corals - Nitrate PAM Delta Dose and Temperature summary") +
    labs(x = "Nitrate dose", 
         y = expression(paste("Change in Photosynthetic Efficiency Fv/Fm")), 
         caption = "data represent mean +/- SEM" ) +
    scale_x_discrete("Nitrate dose", labels=c(CNTRL_0="Control", N_1.5="1.5uM", N_5="5uM", N_18="18uM"))+
    scale_color_manual("Temperature",labels=c("20C","30C"), values=c("blue", "red"))
gg_N_species_dose_temp_nitrate_sym


# apo corals
sum_N_species_dose_temp_nitrate_apo <- summarySE(all_apo, measurevar = "PAM_delta", groupvars = c("temp","N_species_dose"))
# Visualize
gg_N_species_dose_temp_nitrate_apo<-ggplot(data = sum_N_species_dose_temp_nitrate_apo,
       aes(x = N_species_dose,
           y = PAM_delta, col=temp)) +
    geom_point() +
    geom_errorbar(aes(ymin=PAM_delta-se, ymax=PAM_delta+se), width=0.1, size = 1) +
    #scale_color_manual(values = c("black", "darkgreen")) +
    ggtitle ("Aposymbiotic Corals - Nitrate PAM Delta Dose and Temperature summary") +
    labs(x = "Nitrate dose", 
         y = expression(paste("Change in Photosynthetic Efficiency Fv/Fm")), 
         caption = "data represent mean +/- SEM" ) +
    scale_x_discrete("Nitrate dose", labels=c(CNTRL_0="Control", N_1.5="1.5uM", N_5="5uM", N_18="18uM"))+
    scale_color_manual("Temperature",labels=c("20C","30C"), values=c("blue", "red"))
gg_N_species_dose_temp_nitrate_apo
```

```{r N species dose graphs}
#Make N species dose a factor and give it levels so it will display in this order
pam_all_nitrate.data$N_species_dose <- factor(pam_all_nitrate.data$N_species_dose, levels=c("CNTRL_0", "N_1.5", "N_5","N_18"))

#Make everything else a character so they graph nicely 
pam_all_nitrate.data$treat_ID_full<-as.character(pam_all_nitrate.data$treat_ID_full)
pam_all_nitrate.data$temp <- as.character(pam_all_nitrate.data$temp)

# Summarize by N_species_dose so we can visualize
sum_N_species_dose_nitrate <- summarySE(pam_all_nitrate.data, measurevar = "PAM_delta", groupvars = c("N_species_dose"))
# Visualize
gg_N_species_dose_nitrate<-ggplot(data = sum_N_species_dose_nitrate,
       aes(x = N_species_dose,
           y = PAM_delta, col=N_species_dose)) +
    geom_point() +
 ylim(-0.078, 0.015) +
    geom_errorbar(aes(ymin=PAM_delta-se, ymax=PAM_delta+se), width=0.1, size = 1) +
    #scale_color_manual(values = c("black", "darkgreen")) +
    ggtitle ("Nitrate - N Species Dose summary") +
   theme(legend.position="none")+
    labs(x = "\n", 
         y = expression(paste("Change in Fv/Fm")), 
         caption = "data represent mean +/- SEM" ) +
    scale_x_discrete("Nitrate dose", labels=c(CNTRL_0="Control", N_1.5="Ambient", N_5="Intermediate", N_18="High"))+
    scale_color_manual(labels=labels, values=c("blue", "#9DCE9D","#359C35","darkgreen"))
gg_N_species_dose_nitrate

# Summarize by N_species_dose at PAM day 11 so we can visualize
sum_N_species_dose_nitrate_day11 <- summarySE(pam_all_nitrate.data, measurevar = "PAM_avg_day11", groupvars = c("N_species_dose"))
# Visualize
gg_N_species_dose_nitrate_day11<-ggplot(data = sum_N_species_dose_nitrate_day11,
       aes(x = N_species_dose,
           y = PAM_avg_day11, col=N_species_dose)) +
    geom_point() +
    geom_errorbar(aes(ymin=PAM_avg_day11-se, ymax=PAM_avg_day11+se), width=0.1, size = 1) +
    #scale_color_manual(values = c("black", "darkgreen")) +
    ggtitle ("Nitrate - N Species Dose summary") +
   theme(legend.position="none")+
    labs(x = "\n", 
         y = expression(paste("Day 11 Photosynthetic Efficiency Fv/Fm")), 
         caption = "data represent mean +/- SEM" ) +
    scale_x_discrete("Nitrate dose", labels=c(CNTRL_0="Control", N_1.5="1.5uM", N_5="5uM", N_18="18uM"))+
    scale_color_manual(labels=labels, values=c("blue", "#9DCE9D","#359C35","darkgreen","black"))
gg_N_species_dose_nitrate_day11

#Jitter day 11 data
gg_N_species_dose_nitrate_day11_jitter<-ggplot(data = pam_all_nitrate.data,
       aes(x = N_species_dose,
           y = PAM_avg_day11, col=N_species_dose)) +
    geom_boxplot() + 
   geom_jitter() +
    #scale_color_manual(values = c("black", "darkgreen")) +
    ggtitle ("Nitrate - N Species Dose summary") +
   theme(legend.position="none")+
    labs(x = "\n", 
         y = expression(paste("Day 11 Photosynthetic Efficiency Fv/Fm")), 
         caption = "data represent mean +/- SEM" ) +
    scale_x_discrete("Nitrate dose", labels=c(CNTRL_0="Control", N_1.5="1.5uM", N_5="5uM", N_18="18uM"))+
    scale_color_manual(labels=labels, values=c("blue", "#9DCE9D","#359C35","darkgreen","black"))
gg_N_species_dose_nitrate_day11_jitter



```


```{r Controls vs. Nutrient - CHALK TALK}

#I added a column called "control_or_nutrient"

# let's do temperature for control vs. nutrient FOR SYM CORALS ONLY

# Summarize by N_species_dose so we can visualize
sum_sym_temp <- summarySE(all_sym, measurevar = "PAM_delta", groupvars = c("temp", "control_or_nutrient"))
# Visualize
gg_sum_sym_temp<-ggplot(data = sum_sym_temp,
       aes(x =control_or_nutrient,
           y = PAM_delta, col=temp)) +
    geom_point(size=4) +
   theme(
  axis.text.x = element_text(size = 22),
   axis.title.x = element_text(size = 30),
  axis.text.y = element_text(size = 24),
   axis.title.y = element_text(size = 28)) +
 ylim(-.18, 0.1) +
    geom_errorbar(aes(ymin=PAM_delta-se, ymax=PAM_delta+se), width=0.3, size = 2) +
    #scale_color_manual(values = c("black", "darkgreen")) +
  #  ggtitle ("Nitrate - N Species Dose summary for sym corals") +
   theme( legend.title = element_text(size=20), legend.text = element_text(size=20))+
    labs(x = "\n", 
         y = expression(paste("Change in Fv/Fm"))) +
     scale_color_manual(" Temperature ", labels=c("20C","30C"), values=c("blue", "darkred"))
gg_sum_sym_temp

#now let's do sym state for control vs. nutrient

sum_sym_state_control_nutrient <- summarySE(PAM_delta_all_ammonium.data, measurevar = "PAM_delta", groupvars = c("sym_state", "control_or_nutrient"))
gg_sym_state_ammonium<-ggplot(data = sum_sym_state_control_nutrient,
       aes(x = control_or_nutrient,
           y = PAM_delta, col=sym_state)) +
    geom_point() +
    ylim(-0.0049, -0.0039) +
    geom_errorbar(aes(ymin=PAM_delta-se, ymax=PAM_delta+se), width=0.1, size = 1) +
    #scale_color_manual(values = c("black", "darkgreen")) +
    ggtitle ("ammonium with & without control - Sym state summary") +
    labs(x = " ", 
         y = expression(paste("Rate O2 Consumption (umol*min"^"-1"~"*g"^"-1"~")")), 
         caption = "data represent mean +/- SEM" ) +
    scale_color_manual(" Symbiotic State ", labels=c("Aposymbiotic","Symbiotic"), values=c("darkgray", "tan4"))
gg_sym_state_ammonium



# STATS STATS STATS
mm_PAM_delta_control_v_nutrient <- lmer(PAM_delta ~  temp + control_or_nutrient + (1 | col_num), data=pam_all_nitrate.data)
summary(mm_PAM_delta_control_v_nutrient)

# Summarize by control_or_nutrient * e_coli
emm_control_v_nutrient=emmeans(mm_PAM_delta_control_v_nutrient, specs=pairwise ~ control_or_nutrient*e_coli_plate)
summary(emm_control_v_nutrient)

# Summarize by control_or_nutrient * temp
emm_control_v_nutrient=emmeans(mm_PAM_delta_control_v_nutrient, specs=pairwise ~ control_or_nutrient*temp)
summary(emm_control_v_nutrient)

# Summarize by control_or_nutrient * symbiotic state
emm_control_v_nutrient=emmeans(mm_PAM_delta_control_v_nutrient, specs=pairwise ~ control_or_nutrient*sym_state)
summary(emm_control_v_nutrient)


```



