---
title: "Respirometry data analysis (NITRATE) C. Fleming Last updated: 2/24/23"
output:
  pdf_document: default
  html_notebook: default
authors: Caroline Fleming

#Some resources:
  #https://rstudio-pubs-static.s3.amazonaws.com/63556_e35cc7e2dfb54a5bb551f3fa4b3ec4ae.html

#### NITRATE ### New & improved! With updated nitrate only controls
---

```{r Install required packages}
require("knitr")

library("tidyverse")
#install.packages("lmTest")
library("lmTest")
#install.packages("Matrix")
library("Matrix")
#install.packages("lme4")
library("lme4")
#install.packages("emmeans")
library("emmeans")
#install.packages("pbkrtest")
library("pbkrtest")
library("performance")
#install.packages("see")
library("see")
#install.packages("ggrepel")
library("ggrepel")
#install.packages("sjPlot") #for visualizing linear models
library(sjPlot)
#install.packages("MASS")
library(MASS)
#install.packages("glmmTMB") # for visualizing model checks
library(glmmTMB)
#install.packages("relaimpo") #for quantifying the effects of predictor variables
library(relaimpo)
#install.packages("outliers") #for checking out whether a data point is an outlier
library(outliers)
library(Rmisc)
#install.packages("ggeffects")
library(ggeffects)
library(car)
#install.packages("forestmodel")
library(forestmodel)
#turn off scientific notation
options(scipen=999)

#let dplyr print a bunch of numbers
options(dplyr.print_max = 1e9)
options(max.print = 10000)   

```


```{r Set working directory and upload data - NITRATE DATA ONLY}

#FILE: 
#RESP_NITRATE_cleaned_dead_and_broken_outlierG28Y65_deleted_random_controls_7_5_23
#What I did to the above file is took all the cleaned nitrate respirometry data, deleted all controls, and replaced them with the randomized controls consistent with those used for the PAM analysis, so that nitrate and ammonium have the same controls.

# We made a separate Nitrate excel file now so we're all set to upload & go
resp_all_nitrate.data <- read.csv("RESP_NITRATE_cleaned_dead_and_broken_outlierG28Y65_deleted_random_controls_7_5_23.csv", header=TRUE, sep=",",stringsAsFactors = FALSE) #I added a new column called "control_or_nutrient" to make some plotting easier
resp_all_nitrate.data<-na.omit(resp_all_nitrate.data)
#create a column for inverted resp rate for visuals
resp_all_nitrate.data$resp_rate_inverted<- abs(resp_all_nitrate.data$resp_rate)
hist(resp_all_nitrate.data$resp_rate) #slight skew but we're okay let's keep using it
qqnorm(resp_all_nitrate.data$resp_rate) #this looks really nice

#make sure treatID is a character
resp_all_nitrate.data$treat_ID_full<-as.character(resp_all_nitrate.data$treat_ID_full)

#make sure everything else is a factor
resp_all_nitrate.data$e_coli_plate <-as.factor(resp_all_nitrate.data$e_coli_plate)
resp_all_nitrate.data$N_species_dose <-as.factor(resp_all_nitrate.data$N_species_dose)
resp_all_nitrate.data$food <-as.factor(resp_all_nitrate.data$food)
resp_all_nitrate.data$temp <-as.factor(resp_all_nitrate.data$temp)
resp_all_nitrate.data$control_or_nutrient<-as.factor(resp_all_nitrate.data$control_or_nutrient)
resp_all_nitrate.data$sym_state<-as.factor(resp_all_nitrate.data$sym_state)
resp_all_nitrate.data$N_species_dose <- factor(resp_all_nitrate.data$N_species_dose, levels=c("CNTRL_0", "N_1.5", "N_5","N_18"))


# #adding a log transformed resp rate
# resp_all_nitrate.data$log_resp_rate<-abs(resp_all_nitrate.data$resp_rate)
# resp_all_nitrate.data$log_resp_rate<-log(resp_all_nitrate.data$log_resp_rate)
# resp_all_nitrate.data$arcsin_resp_rate<-asin(resp_all_nitrate.data$resp_rate)
# 
# #testing for normality
# #TESTING FOR NORMALITY IN PAM_delta
# #install new package to see what the best transformation is
# #install.packages("bestNormalize")
# library("bestNormalize")
# bestNormalize(resp_all_nitrate.data$resp_rate)
# #in order for this to work I need to change the PAM_delta in to a vector
# resp_all_nitrate.data$resp_rate_vector<-as.vector(resp_all_nitrate.data$resp_rate_vector)
# #then I run the orderNorm command into a new object
# orderNormobj_resp_rate<-orderNorm(resp_all_nitrate.data$resp_rate)
# #this object gives us what we want, but we have to index from that object and put it in a new column
# resp_all_nitrate.data$ordernorm_resp_rate<-orderNormobj_resp_rate$x.t
# 
# Essential subsets
all_20C<-subset(resp_all_nitrate.data, resp_all_nitrate.data$temp==20)
all_30C<-subset(resp_all_nitrate.data, resp_all_nitrate.data$temp==30)
all_apo<-subset(resp_all_nitrate.data, resp_all_nitrate.data$sym_state=="A")
all_sym<-subset(resp_all_nitrate.data, resp_all_nitrate.data$sym_state=="S")
e_coli<-subset(resp_all_nitrate.data, resp_all_nitrate.data$e_coli_plate=="1")
no_e_coli<-subset(resp_all_nitrate.data, resp_all_nitrate.data$e_coli_plate=="0")
```


#Linear models - let's do it the full random way we were taught

```{r linear models - ALL NITRATE DATA}
full.model <- lmer(resp_rate ~  N_species_dose + temp + food + sym_state + e_coli_plate + N_species_dose*temp + N_species_dose*food + N_species_dose*sym_state + N_species_dose*e_coli_plate + temp*food + temp*sym_state + temp*e_coli_plate + food*sym_state + food*e_coli_plate + sym_state*e_coli_plate + (1|col_num) + (1|exp_run_full), data= resp_all_nitrate.data)
print(step.model<- step(full.model))

#model it selected for;

nitrate_resp_model <- lmer(resp_rate ~ N_species_dose + temp + food + e_coli_plate + sym_state + (1 | col_num) + N_species_dose:e_coli_plate + food:e_coli_plate, data= resp_all_nitrate.data)
#sym state was marginal but we added it

summary(nitrate_resp_model)
plot_model(nitrate_resp_model, type="diag")
#Model actually looks decent! Let's go with this one

(summary(emmeans(nitrate_resp_model, specs=pairwise ~ N_species_dose*temp*sym_state*e_coli_plate*food)))

#A negative coefficient suggests that as the independent variable increases, the dependent variable tends to decrease.

```






```{r ANOVAs}
# Nitrate
summary(aov_EC<-aov(resp_rate ~ N_species_dose, data=resp_all_nitrate.data))
Anova(aov_EC, type="III")
summary(emmeans(aov_EC, specs=pairwise ~ N_species_dose))


# E. coli by temperature - nutrient vs control
summary(aov_EC<-aov(resp_rate ~ temp + control_or_nutrient, data=e_coli))
summary(emmeans(aov_EC, specs=pairwise ~ temp*control_or_nutrient))

# No E. coli by temperature - nutrient vs. control
summary(aov_no_EC<-aov(resp_rate ~ temp + control_or_nutrient, data=no_e_coli))
summary(emmeans(aov_no_EC, specs=pairwise ~ temp*control_or_nutrient))

```



```{r Looking at E. coli subsets}
# STATS - E. COLI  SUBSET
#stepAIC is from the MASS package
fullModel_EC = lm(resp_rate ~   control_or_nutrient + temp + sym_state + control_or_nutrient*temp + control_or_nutrient*sym_state  + temp*sym_state, data= e_coli) # model with all 9 variables and possible combinations

nullModel_EC = lm(resp_rate ~  1, data= e_coli) # model with the intercept only

summary(stepAIC(nullModel_EC, # start with a model containing no variables
                direction = 'forward', # run forward selection
                scope = list(upper = fullModel_EC, # the maximum to consider is a model with all variables
                             lower = nullModel_EC), # the minimum to consider is a model with no variables
                trace = 1)) # do not show the step-by-step process of model selection

#this is the model it selected for
lm_EC <- lm(formula = resp_rate ~ temp + control_or_nutrient + sym_state, data = e_coli)
summary(lm_EC)
summary(emmeans(lm_EC, specs=pairwise ~ temp*control_or_nutrient))

#replacing control or nutrient with dose
lm_EC <- lm(formula = resp_rate ~ sym_state + temp + N_species_dose + temp*N_species_dose, data = e_coli)
summary(lm_EC)
summary(emmeans(lm_EC, specs=pairwise ~ temp*N_species_dose))


lm_EC<-lm(resp_rate ~ temp + N_species_dose, data=e_coli)
summary(lm_EC)


summary(aov_EC<-aov(resp_rate ~ temp + N_species_dose, data=e_coli))

summary(emmeans(aov_EC, specs=pairwise ~ temp*N_species_dose))


# STATS - NO E. COLI  SUBSET
#stepAIC is from the MASS package
fullModel_no_EC = lm(resp_rate ~   N_species_dose + temp + sym_state + N_species_dose*temp + N_species_dose*sym_state  + temp*sym_state, data= no_e_coli) # model with all 9 variables and possible combinations

nullModel_no_EC = lm(resp_rate ~  1, data= no_e_coli) # model with the intercept only

summary(stepAIC(nullModel_no_EC, # start with a model containing no variables
                direction = 'forward', # run forward selection
                scope = list(upper = fullModel_no_EC, # the maximum to consider is a model with all variables
                             lower = nullModel_no_EC), # the minimum to consider is a model with no variables
                trace = 1)) # do not show the step-by-step process of model selection

#this is the model it selected for
lm_no_EC <- lm(formula = resp_rate ~ control_or_nutrient + temp, data = no_e_coli)
summary(lm_no_EC)
#replacing control or nutrient with dose
lm_no_EC <- lm(formula = resp_rate ~  N_species_dose + temp, data = no_e_coli)
summary(lm_no_EC)
summary(emmeans(lm_no_EC, specs=pairwise ~ N_species_dose*temp))
```

```{r Nutrient or control linear model}


full.model_control_or_nutrient <- lm(resp_rate ~  control_or_nutrient + temp + food + sym_state + e_coli_plate + control_or_nutrient*temp + control_or_nutrient*food + control_or_nutrient*sym_state + control_or_nutrient*e_coli_plate + temp*food + temp*sym_state + temp*e_coli_plate + food*sym_state + food*e_coli_plate + sym_state*e_coli_plate +  + (1|vial_ID) +  (1|col_num) + (1|exp_num) + (1|exp_subrun), data= resp_all_nitrate.data)
print(step.model<- step(full.model_control_or_nutrient))

#CONTROL OR NUTRIENT -- IT IS SIGNIFICANT
lm_resp_control_or_nutrient <- lm(resp_rate ~ control_or_nutrient + temp + e_coli_plate + (1 | col_num) + control_or_nutrient*e_coli_plate, data=resp_all_nitrate.data)
summary(lm_resp_control_or_nutrient)

elm_test=emmeans(lm_resp_control_or_nutrient, specs=pairwise ~ control_or_nutrient*e_coli_plate)
summary(elm_test)

tab_model(lm_resp_control_or_nutrient)
```


```{r What is the effect of genet on respiration rate}
#just doing this for fun because I'm curious
lm_resp_genet <- lm(resp_rate ~ col_num, data= resp_all_nitrate.data)
summary(lm_resp_genet)
r2(lm_resp_genet)

resp_all_nitrate.data$col_num<-as.character(resp_all_nitrate.data$col_num)

#let's plot genets to check it out
gg_genet_nitrate<-ggplot(data = resp_all_nitrate.data,
       aes(x = col_num,
           y = resp_rate, col=col_num)) +
    geom_point() +
    #geom_errorbar(aes(ymin=resp_rate-se, ymax=resp_rate+se), width=0.1, size = 1) +
    #scale_color_manual(values = c("black", "darkgreen")) +
    ggtitle ("Nitrate - Genet summary") +
   # theme(legend.position = "right",
          # legend.title = element_text(size=12),
          # axis.title = element_text(size = 12),
          # legend.background = element_blank(),
          # panel.grid.major = element_blank(), 
          # panel.grid.minor = element_blank(),
          # axis.text = element_text(size = 12)) +
   legend.position="none" +
    labs(x = "Genet", 
         y = expression(paste("Rate O2 Consumption (umol*min"^"-1"~"*g"^"-1"~")")), 
         caption = "data represent mean +/- SEM" ) +
    theme_classic()
gg_genet_nitrate

```

```{r Model interaction plots}
# Reminder: this is our model
lm_resp_2 <- lm(resp_rate ~ N_species_dose + temp + e_coli_plate + sym_state + N_species_dose*e_coli_plate, data=resp_all_nitrate.data)
summary(lm_resp_2)

#Model Interaction plot - NITRATE
# WHY WONT YOU WORK? BOBBBBBBBBB!
int_nitrate<-lm(resp_rate~N_species_dose*temp*e_coli_plate+(1|col_num), data=resp_all_nitrate.data)
summary(int_nitrate)
int_pred_nitrate <- ggemmeans(int_nitrate, terms=c("N_species_dose", "temp","e_coli_plate")) # I cannot do more than 4 interactions 
pred_nitrate <- ggplot(int_pred_nitrate, aes(facet,predicted, colour = group)) +
  geom_point(aes(shape = x)) +
  geom_errorbar(aes(ymin = conf.low, ymax = conf.high), width = 0.3) +
  labs(x = "temp", y = "Rate O2 Consumption (umol*min-1*g-1)",
       color = "temp") +
  facet_grid(~panel) +
  ggtitle("test") +
  theme_classic() +
  theme(axis.title.x = element_text(color="black", size=12),
axis.title.y = element_text(color="black", size=12))+
  theme(axis.text.x = element_text(size=12),
          axis.text.y = element_text(size=12)) +
  scale_color_manual(values=c("black", "goldenrod"))
pred_nitrate
pred_nitrate <- ggplot(int_pred_nitrate, aes(facet,predicted, colour = group))

```

#Graphs  and visuals
```{r Graphs - Fix data so they plot nicely}
#Make N species dose a factor and give it levels so it will display in this order
resp_all_nitrate.data$N_species_dose <- factor(resp_all_nitrate.data$N_species_dose, levels=c("CNTRL_0", "N_1.5", "N_5","N_18"))

#Make everything else a character so they graph nicely 
resp_all_nitrate.data$treat_ID_full<-as.character(resp_all_nitrate.data$treat_ID_full)
resp_all_nitrate.data$e_coli_plate<-as.character(resp_all_nitrate.data$e_coli_plate)
resp_all_nitrate.data$temp <- as.character(resp_all_nitrate.data$temp)
```


```{r Graphs - Summarizing by each variable}
# Summarize by N_species_dose so we can visualize
sum_N_species_dose_nitrate <- summarySE(resp_all_nitrate.data, measurevar = "resp_rate_inverted", groupvars = c("N_species_dose"))
# Visualize
gg_N_species_dose_nitrate<-ggplot(data = sum_N_species_dose_nitrate,
       aes(x = N_species_dose,
           y = resp_rate_inverted, col=N_species_dose)) +
    geom_point() +
    geom_errorbar(aes(ymin=resp_rate_inverted-se, ymax=resp_rate_inverted+se), width=0.5, size = 1) +
  geom_jitter(data=resp_all_nitrate.data, aes(x=N_species_dose, y=resp_rate_inverted), size=0.2) +
    #scale_color_manual(values = c("black", "darkgreen")) +
    ggtitle ("Nitrate - N Species Dose summary") +
   theme(legend.position="none")+
    labs(x = "\n", 
         y = expression(paste("Rate O2 Consumption (umol*min"^"-1"~"*g"^"-1"~")")), 
         caption = "data represent mean +/- SEM" ) +
    scale_x_discrete("Nitrate dose", labels=c(CNTRL_0="Control", N_1.5="1.5uM", N_5="5uM", N_18="18uM"))+
    scale_color_manual(labels=labels, values=c("blue", "turquoise4","#359C35","darkgreen"))
gg_N_species_dose_nitrate

# Summarize by temperature so we can visualize
sum_temp_nitrate <- summarySE(resp_all_nitrate.data, measurevar = "resp_rate_inverted", groupvars = c("temp"))
# Visualize
gg_temp_nitrate<-ggplot(data = sum_temp_nitrate,
       aes(x = temp,
           y = resp_rate_inverted, col=temp)) +
    geom_point() +
    geom_errorbar(aes(ymin=resp_rate_inverted-se, ymax=resp_rate_inverted+se), width=0.1, size = 1) +
    #scale_color_manual(values = c("black", "darkgreen")) +
    ggtitle ("Nitrate- Temperature summary") +
  theme(legend.position="none")+
    labs(x = "Temperature", 
         y = expression(paste("Rate O2 Consumption (umol*min"^"-1"~"*g"^"-1"~")")), 
         caption = "data represent mean +/- SEM" ) +
    scale_x_discrete("Temperature", labels=c("20"="Control 20C", "30"="Elevated 30C")) +
    scale_color_manual(labels=labels, values=c("blue", "red"))
gg_temp_nitrate

# Summarize by E. coli so we can visualize
sum_e_coli_nitrate <- summarySE(resp_all_nitrate.data, measurevar = "resp_rate_inverted", groupvars = c("e_coli_plate"))
# Visualize
gg_e_coli_nitrate<-ggplot(data = sum_e_coli_nitrate,
       aes(x = e_coli_plate,
           y = resp_rate_inverted, col=e_coli_plate)) +
    geom_point() +
    geom_errorbar(aes(ymin=resp_rate_inverted-se, ymax=resp_rate_inverted+se), width=0.1, size = 1) +
    #scale_color_manual(values = c("black", "darkgreen")) +
    ggtitle ("Nitrate- E. coli summary") +
    theme(legend.position = "right",
          legend.title = element_text(size=12),
          axis.title = element_text(size = 12),
          legend.background = element_blank(),
          panel.grid.major = element_blank(), 
          panel.grid.minor = element_blank(),
          axis.text = element_text(size = 12)) +
   # scale_x_discrete(labels=c("20C","30C"))+
    theme(legend.position="none")+
    labs(x = "E. coli presence", 
         y = expression(paste("Rate O2 Consumption (umol*min"^"-1"~"*g"^"-1"~")")), 
         caption = "data represent mean +/- SEM" ) +
        scale_x_discrete("E. coli presence", labels=c("0"="No E. coli", "1"="E. coli")) +
    scale_color_manual(labels=labels, values=c("gray", "darkgreen"))
gg_e_coli_nitrate

# Summarize by sym state so we can visualize
sum_sym_state_nitrate <- summarySE(resp_all_nitrate.data, measurevar = "resp_rate_inverted", groupvars = c("sym_state"))
# Visualize
gg_sym_state_nitrate<-ggplot(data = sum_sym_state_nitrate,
       aes(x = sym_state,
           y = resp_rate_inverted, col=sym_state)) +
    geom_point() +
    geom_errorbar(aes(ymin=resp_rate_inverted-se, ymax=resp_rate_inverted+se), width=0.1, size = 1) +
    #scale_color_manual(values = c("black", "darkgreen")) +
    ggtitle ("Nitrate- Sym state summary") +
    theme(legend.position = "right",
          legend.title = element_text(size=12),
          axis.title = element_text(size = 12),
          legend.background = element_blank(),
          panel.grid.major = element_blank(), 
          panel.grid.minor = element_blank(),
          axis.text = element_text(size = 12)) +
   # scale_x_discrete(labels=c("20C","30C"))+
    labs(x = "Symbiotic state", 
         y = expression(paste("Rate O2 Consumption (umol*min"^"-1"~"*g"^"-1"~")")), 
         caption = "data represent mean +/- SEM" ) +
        theme(legend.position="none")+
        scale_x_discrete("Symbiotic State", labels=c("A"="Apo", "S"="Symbiotic")) +
        scale_color_manual(labels=labels, values=c("gray", "brown"))
gg_sym_state_nitrate
summary(aov(resp_rate_inverted ~ sym_state, data=resp_all_nitrate.data))
# UGH THEY ARE DIFFERENT! But it doesnt  come up in the overall model
#Let's jitter to check this out
gg_sym_state_nitrate_jitter<-ggplot(data = resp_all_nitrate.data,
       aes(x = sym_state,
           y = resp_rate_inverted, col=sym_state)) +
  geom_boxplot(width=0.8) +
  geom_jitter(width=0.15, alpha=0.9) + #this overlays the raw data  
    #scale_color_manual(values = c("black", "darkgreen")) +
    ggtitle ("Nitrate- Sym state summary") +
   # scale_x_discrete(labels=c("20C","30C"))+
    labs(x = "Symbiotic state", 
         y = expression(paste("Rate O2 Consumption (umol*min"^"-1"~"*g"^"-1"~")")), 
         caption = "data represent mean +/- SEM" ) +
        theme(legend.position="none")+
        scale_x_discrete("Symbiotic State", labels=c("A"="Apo", "S"="Symbiotic")) +
        scale_color_manual(labels=labels, values=c("gray", "brown"))
gg_sym_state_nitrate_jitter
summary(lm(resp_rate_inverted ~ sym_state, data=resp_all_nitrate.data))

# Summarize by food so we can visualize
sum_food_nitrate <- summarySE(resp_all_nitrate.data, measurevar = "resp_rate_inverted", groupvars = c("food"))
# Visualize
gg_food_nitrate<-ggplot(data = sum_food_nitrate,
       aes(x = food,
           y = resp_rate_inverted, col=food)) +
    geom_point() +
    geom_errorbar(aes(ymin=resp_rate_inverted-se, ymax=resp_rate_inverted+se), width=0.1, size = 1) +
    #scale_color_manual(values = c("black", "darkgreen")) +
    ggtitle ("Nitrate- Food summary") +
    theme(legend.position = "right",
          legend.title = element_text(size=12),
          axis.title = element_text(size = 12),
          legend.background = element_blank(),
          panel.grid.major = element_blank(), 
          panel.grid.minor = element_blank(),
          axis.text = element_text(size = 12)) +
   # scale_x_discrete(labels=c("20C","30C"))+
    labs(x = "Symbiotic state", 
         y = expression(paste("Rate O2 Consumption (umol*min"^"-1"~"*g"^"-1"~")")), 
         caption = "data represent mean +/- SEM" ) +
    theme(legend.position="none")+
   scale_x_discrete("Food presence", labels=c("F"="Fed", "S"="Starved")) +
   scale_color_manual(labels=labels, values=c("orange", "black"))
gg_food_nitrate
summary(lm(resp_rate_inverted ~ sym_state, data=resp_all_nitrate.data))


# Summarize by food and sym state so we can visualize
sum_food_sym_state_nitrate <- summarySE(resp_all_nitrate.data, measurevar = "resp_rate_inverted", groupvars = c("e_coli_plate","food"))
# Visualize
gg_food_sym_state_nitrate<-ggplot(data = sum_food_sym_state_nitrate,
       aes(x = e_coli_plate,
           y = resp_rate_inverted, col=food)) + #use fill here or the legends will be really hard to work with
    geom_point() +
    geom_errorbar(aes(ymin=resp_rate_inverted-se, ymax=resp_rate_inverted+se), width=0.5, size = 1) +
  geom_jitter(data = resp_all_nitrate.data,
       aes(x = e_coli_plate,
           y = resp_rate_inverted, colour=food), size=0.1) +
    ggtitle ("Nitrate- E coli and food summary") +
   #scale_fill_manual(name="Feeding Regime", labels=c('Fed', 'Starved'))+
 # scale_fill_manual(values=c("brown", "darkgray"))+
    labs(x = "E coli plate", 
         y = expression(paste("Rate O2 Consumption (umol*min"^"-1"~"*g"^"-1"~")")), 
         caption = "data represent mean +/- SEM" ) +
      scale_x_discrete(name="E coli presence", labels=c("A"="Aposymbiotic", "S"="Symbiotic")) +
  # scale_fill_manual(values=c("brown", "darkgray"))
 scale_color_manual(values=c("salmon3", "cornsilk4"))
gg_food_sym_state_nitrate #seems obvious that food doesnt matter

# Summarize by temp and N species dose so we can visualize
sum_N_species_dose_temp_nitrate <- summarySE(resp_all_nitrate.data, measurevar = "resp_rate_inverted", groupvars = c("temp","N_species_dose"))
# Visualize
gg_N_species_dose_temp_nitrate<-ggplot(data = sum_N_species_dose_temp_nitrate,
       aes(x = N_species_dose,
           y = resp_rate_inverted, colour=temp)) +
    geom_point() +
    geom_errorbar(aes(ymin=resp_rate_inverted-se, ymax=resp_rate_inverted+se), width=0.1, size = 1) +
  geom_jitter(data = resp_all_nitrate.data,
       aes(x = N_species_dose,
           y = resp_rate_inverted, colour=temp), size=0.1) +
    #scale_color_manual(values = c("black", "darkgreen")) +
    ggtitle ("Nitrate - N species dose and temperature summary") +
     
   # scale_x_discrete(labels=c("20C","30C"))+
    labs(x = "Nitrate dose", 
         y = expression(paste("Rate O2 Consumption (umol*min"^"-1"~"*g"^"-1"~")")), 
         caption = "data represent mean +/- SEM" ) +
  scale_x_discrete("Dose", labels=c("20"="Ambient", "30"="Elevated")) +
    scale_color_manual(labels=c("20C","30C"), values=c("blue", "hotpink"))
gg_N_species_dose_temp_nitrate 

# Summarize by e_coli and N species dose so we can visualize
sum_N_species_dose_e_coli_nitrate <- summarySE(resp_all_nitrate.data, measurevar = "resp_rate_inverted", groupvars = c("e_coli_plate","N_species_dose"))
# Visualize
gg_N_species_dose_e_coli_nitrate<-ggplot(data = sum_N_species_dose_e_coli_nitrate,
       aes(x = N_species_dose,
           y = resp_rate_inverted, colour=e_coli_plate)) +
    geom_point() +
    geom_errorbar(aes(ymin=resp_rate_inverted-se, ymax=resp_rate_inverted+se), width=0.5, size = 1) +
  geom_jitter(data = resp_all_nitrate.data,
       aes(x = N_species_dose,
           y = resp_rate_inverted, colour=e_coli_plate), size=0.1) +
    #scale_color_manual(values = c("black", "darkgreen")) +
    ggtitle ("Nitrate- N species dose and e coli summary") +
   # scale_x_discrete(labels=c("20C","30C"))+
    labs(x = "Nitrate dose", 
         y = expression(paste("Rate O2 Consumption (umol*min"^"-1"~"*g"^"-1"~")")), 
         caption = "data represent mean +/- SEM" ) +
   scale_x_discrete("Nitrate dose", labels=c(CNTRL_0="Control", N_1.5="1.5uM", N_5="5uM", N_18="18uM"))+
     scale_color_manual("E. coli presence", labels=c("1"="E. coli", "0"="No E. coli"), values=c("gray25", "green4"))
gg_N_species_dose_e_coli_nitrate

# Summarize by e_coli and temp so we can visualize
sum_temp_e_coli_nitrate <- summarySE(resp_all_nitrate.data, measurevar = "resp_rate_inverted", groupvars = c("e_coli_plate","temp"))
# Visualize
gg_temp_e_coli_nitrate<-ggplot(data = sum_temp_e_coli_nitrate,
       aes(x = e_coli_plate,
           y = resp_rate_inverted, colour=temp)) +
    geom_point() +
    geom_errorbar(aes(ymin=resp_rate_inverted-se, ymax=resp_rate_inverted+se), width=0.1, size = 1) +
    #scale_color_manual(values = c("black", "darkgreen")) +
    ggtitle ("Nitrate- temperature and e coli summary") +
    theme(legend.position = "right",
          legend.title = element_text(size=12),
          axis.title = element_text(size = 12),
          legend.background = element_blank(),
          panel.grid.major = element_blank(), 
          panel.grid.minor = element_blank(),
          axis.text = element_text(size = 12)) +
   # scale_x_discrete(labels=c("20C","30C"))+
    labs(x = "E. coli", 
         y = expression(paste("Rate O2 Consumption (umol*min"^"-1"~"*g"^"-1"~")")), 
         caption = "data represent mean +/- SEM" ) +
     scale_x_discrete("E. coli presence", labels=c("0"="No E. coli", "1"="E coli"))+
     scale_color_manual(labels=labels, values=c("blue", "red"))
gg_temp_e_coli_nitrate

# Summarize by temp and N species dose so we can visualize
sum_N_species_dose_temp_nitrate <- summarySE(resp_all_nitrate.data, measurevar = "resp_rate_inverted", groupvars = c("temp","N_species_dose"))
# Visualize
gg_N_species_dose_temp_nitrate<-ggplot(data = sum_N_species_dose_temp_nitrate,
       aes(x = N_species_dose,
           y = resp_rate_inverted, col=temp)) +
    geom_point() +
    geom_errorbar(aes(ymin=resp_rate_inverted-se, ymax=resp_rate_inverted+se), width=0.1, size = 1) +
    #scale_color_manual(values = c("black", "darkgreen")) +
    ggtitle ("Nitrate - N species dose and temperature summary") +
    labs(x = "Nitrate dose", 
         y = expression(paste("Rate O2 Consumption (umol*min"^"-1"~"*g"^"-1"~")")), 
         caption = "data represent mean +/- SEM" ) +
    scale_x_discrete("Nitrate dose", labels=c(CNTRL_0="Control", N_1.5="1.5uM", N_5="5uM", N_18="18uM"))+
    scale_color_manual("Temperature",labels=c("20C","30C"), values=c("blue", "red"))
gg_N_species_dose_temp_nitrate

# Summarize by N_species_dose and sym state so we can visualize
sum_N_species_dose_nitrate_sym_state <- summarySE(resp_all_nitrate.data, measurevar = "resp_rate_inverted", groupvars = c("N_species_dose", "sym_state"))
# Visualize
sum_N_species_dose_nitrate_sym_state <-ggplot(data = sum_N_species_dose_nitrate_sym_state,
       aes(x = N_species_dose,
           y = resp_rate_inverted, col=sym_state)) +
    geom_point() +
    geom_errorbar(aes(ymin=resp_rate_inverted-se, ymax=resp_rate_inverted+se), width=0.1, size = 1) +
    ggtitle ("Nitrate - N Species Dose and sym state summary") +
   #theme(legend.position="none")+
    labs(x = "\n", 
         y = expression(paste("Rate O2 Consumption (umol*min"^"-1"~"*g"^"-1"~")")), 
         caption = "data represent mean +/- SEM" ) +
    scale_x_discrete("Nitrate dose", labels=c(CNTRL_0="Control", N_1.5="1.5uM", N_5="5uM", N_18="18uM"))+
    scale_color_manual(labels=c("Apo","Sym"), values=c("gray", "brown"))
sum_N_species_dose_nitrate_sym_state
```


```{r Graphs - Plotting model estimates}
#Plot model estimate for N_species_dose # I am not sure how interesting this is, but here is the code if we want it
l=plot_model(lm_resp_2, 'pred', ci.lvl = 0.95, terms="N_species_dose")
l +
  theme_classic() +
xlab("N species dose")+
  ylab("Rate O2 Consumption (umol*min-1*g-1)")+
  ggtitle("")+
  theme(axis.title.x = element_text(color="black", size=14, face="bold"),
axis.title.y = element_text(color="black", size=14, face="bold"))+
  theme(axis.text.x = element_text(size=14),
          axis.text.y = element_text(size=14))
# plot model estimate for temp


```


```{r WITHOUT controls}

nitrate_without_control <- read.csv("RESP_Nitrate_no_controls.csv", header=TRUE, sep=",",stringsAsFactors = FALSE)
nitrate_without_control <- na.omit(nitrate_without_control)
#make sure treatID is a character
nitrate_without_control$treat_ID_full<-as.character(nitrate_without_control$treat_ID_full)
nitrate_without_control$e_coli_plate<-as.character(nitrate_without_control$e_coli_plate)
nitrate_without_control$temp <- as.character(nitrate_without_control$temp)

nitrate_controls <- subset(resp_all_nitrate.data, resp_all_nitrate.data$N_dose==0)


full.model <- lm(resp_rate ~  N_species_dose + temp + food + sym_state + e_coli_plate + N_species_dose*temp + N_species_dose*food + N_species_dose*sym_state + N_species_dose*e_coli_plate + temp*food + temp*sym_state + temp*e_coli_plate + food*sym_state + food*e_coli_plate + sym_state*e_coli_plate +  (1|col_num) + (1|exp_num) , data= nitrate_without_control)
print(step.model<- step(full.model))


lm_without_controls <-lm(resp_rate ~ N_species_dose + sym_state + e_coli_plate + temp + (1 | col_num), data=nitrate_without_control)

summary(lm_without_controls)

# Summarize by temperature
elm_temp=emmeans(lm_without_controls, specs=pairwise ~ sym_state)
summary(elm_temp)

#Pairwise by 
elm_N_species_dose=emmeans(lm_without_controls, specs=pairwise ~ N_species_dose)
summary(elm_N_species_dose)

#Pairwise by 
elm_e_coli=emmeans(lm_without_controls, specs=pairwise ~ temp*e_coli_plate)
summary(elm_e_coli)

# Visualize by sym state
sum_sym_state <- summarySE(nitrate_without_control, measurevar = "resp_rate", groupvars = c("e_coli_plate"))
gg_sym_state_nitrate<-ggplot(data = sum_sym_state,
       aes(x = e_coli_plate,
           y = resp_rate, col=e_coli_plate)) +
    geom_point() +
    geom_errorbar(aes(ymin=resp_rate-se, ymax=resp_rate+se), width=0.1, size = 1) +
    #scale_color_manual(values = c("black", "darkgreen")) +
    ggtitle ("Nitrate without control - E. coli summary") +
  theme(legend.position="none")+
    labs(x = "E. coli presence", 
         y = expression(paste("Rate O2 Consumption (umol*min"^"-1"~"*g"^"-1"~")")), 
         caption = "data represent mean +/- SEM" ) +
   # scale_x_discrete("Sym", labels=c("20"="Control 20C", "30"="Elevated 30C")) +
    scale_color_manual(labels=labels, values=c("black", "darkgreen"))
gg_sym_state_nitrate


# Visualize by temperature
sum_sym_state <- summarySE(nitrate_without_control, measurevar = "resp_rate", groupvars = c("temp"))
gg_sym_state_nitrate<-ggplot(data = sum_sym_state, 
          aes(x=temp, y = resp_rate, col=temp)) +
    geom_point() +
    geom_errorbar(aes(ymin=resp_rate-se, ymax=resp_rate+se), width=0.1, size = 1) +
    #scale_color_manual(values = c("black", "darkgreen")) +
    ggtitle ("Nitrate without control - Sym state summary") +
  theme(legend.position="none")+
    labs(x = "Temperature", 
         y = expression(paste("Rate O2 Consumption (umol*min"^"-1"~"*g"^"-1"~")")), 
         caption = "data represent mean +/- SEM" ) +
   # scale_x_discrete("Sym", labels=c("20"="Control 20C", "30"="Elevated 30C")) +
    scale_color_manual(labels=labels, values=c("blue", "red"))
gg_sym_state_nitrate


# Visualize temperature * E. coli
sum_e_coli_temp <- summarySE(nitrate_without_contro, measurevar = "resp_rate", groupvars = c("temp","e_coli_plate"))
gg_e_coli_temp_nitrate<-ggplot(data = sum_e_coli_temp, 
          aes(x=e_coli_plate, y = resp_rate, col=temp)) +
    geom_point() +
    geom_errorbar(aes(ymin=resp_rate-se, ymax=resp_rate+se), width=0.1, size = 1) +
    #scale_color_manual(values = c("black", "darkgreen")) +
    ggtitle ("Nitrate without control - e. coli and temp summary") +
    labs(x = "E. coli presence", 
         y = expression(paste("Rate O2 Consumption (umol*min"^"-1"~"*g"^"-1"~")")), 
         caption = "data represent mean +/- SEM" ) +
   scale_x_discrete("E. coli presence", labels=c("0"="No E. coli", "1"="E. coli")) +
    scale_color_manual("Temperature", labels=c("20C","30C"), values=c("blue", "darkred"))
gg_e_coli_temp_nitrate

```

```{r Without E. coli for chalk talk}
# Summarize by N_species_dose WITHOUT E. coli so we can visualize
sum_N_species_dose_nitrate_no_e_coli <- summarySE(no_e_coli, measurevar = "resp_rate", groupvars = c("N_species_dose"))
sum_N_species_dose_nitrate_e_coli$N_species_dose <- factor(sum_N_species_dose_nitrate_e_coli$N_species_dose, levels=c("CNTRL_0", "N_1.5", "N_5","N_18"))
# Visualize
gg_N_species_dose_nitrate<-ggplot(data = sum_N_species_dose_nitrate_no_e_coli,
       aes(x = N_species_dose,
           y = resp_rate, col=N_species_dose)) +
    geom_point() +
   ylim(-0.005, -0.0032) +
    geom_errorbar(aes(ymin=resp_rate-se, ymax=resp_rate+se), width=0.1, size = 1) +
    #scale_color_manual(values = c("black", "darkgreen")) +
    ggtitle ("nitrate - N Species Dose summary NO E. Coli") +
   theme(legend.position="none")+
    labs(x = "\n", 
         y = expression(paste("Rate O2 Consumption (umol*min"^"-1"~"*g"^"-1"~")")), 
         caption = "data represent mean +/- SEM" ) +
  scale_x_discrete("Nitrate dose", labels=c(CNTRL_0="Control", N_1.5="Ambient", N_5="Intermediate", N_18="High"))+
    scale_color_manual(labels=labels, values=c("blue", "#9DCE9D","#359C35","darkgreen"))
gg_N_species_dose_nitrate

no_e_coli$treat_ID_full<-as.factor(no_e_coli$treat_ID_full)
no_e_coli$e_coli_plate<-as.factor(no_e_coli$e_coli_plate)
no_e_coli$temp <- as.factor(no_e_coli$temp)
no_e_coli$N_species_dose <- as.factor(no_e_coli$N_species_dose)
no_e_coli$food <- as.factor(no_e_coli$food)


```


```{r Controls vs. Nutrient - CHALK TALK}
#CHALK TALK DOSE MODEL not including genetic data

fullModel = lm(resp_rate ~  N_species_dose + temp + food + sym_state + e_coli_plate + N_species_dose*temp + N_species_dose*food + N_species_dose*sym_state + N_species_dose*e_coli_plate + temp*food + temp*sym_state + temp*e_coli_plate + food*sym_state + food*e_coli_plate + sym_state*e_coli_plate, data= resp_all_nitrate.data) # model with all 9 variables and possible combinations
summary(fullModel)

nullModel = lm(resp_rate ~  1, data= all_sym) # model with the intercept only

summary(stepAIC(nullModel, # start with a model containing no variables
                direction = 'forward', # run forward selection
                scope = list(upper = fullModel, # the maximum to consider is a model with all variables
                             lower = nullModel), # the minimum to consider is a model with no variables
                trace = 1)) # do not show the step-by-step process of model selection


lm_chalktalk<- lm(resp_rate ~  N_species_dose , data= all_sym)
summary(lm_chalktalk)

elm_chalktalk=emmeans(lm_sym , specs=pairwise ~ N_species_dose)
summary(elm_chalktalk)

summary(aov_no_EC<-aov(resp_rate ~ N_species_dose, data=no_e_coli))
TukeyHSD(aov_no_EC, "N_species_dose")


summary(nutrient_control_model_nitrate <- lm(resp_rate ~control_or_nutrient, data=no_e_coli))
elm_chalktalk=emmeans(nutrient_control_model_nitrate, specs=pairwise ~ control_or_nutrient)
summary(elm_chalktalk)



#I added a column called "control_or_nutrient"

#first let's do E. coli for control vs. nutrient

sum_e_coli_control_nutrient <- summarySE(resp_all_nitrate.data, measurevar = "resp_rate", groupvars = c("e_coli_plate", "control_or_nutrient"))
gg_e_coli_nitrate<-ggplot(data = sum_e_coli_control_nutrient,
       aes(x = control_or_nutrient,
           y = resp_rate, col=e_coli_plate)) +
    geom_point() +
 ylim(-0.0050, -0.0036) +
    geom_errorbar(aes(ymin=resp_rate-se, ymax=resp_rate+se), width=0.1, size = 1) +
    #scale_color_manual(values = c("black", "darkgreen")) +
    ggtitle ("Nitrate with & without control - E. coli summary") +
    labs(x = " ", 
         y = expression(paste("Rate O2 Consumption (umol*min"^"-1"~"*g"^"-1"~")")), 
         caption = "data represent mean +/- SEM" ) +
    scale_color_manual(" ", labels=c("Control","E. coli"), values=c("blue", "orange"))
gg_e_coli_nitrate


#now let's do temperature for control vs. nutrient

sum_temp_control_nutrient <- summarySE(resp_all_nitrate.data, measurevar = "resp_rate", groupvars = c("temp", "control_or_nutrient"))
gg_temp_nitrate<-ggplot(data = sum_temp_control_nutrient,
       aes(x = control_or_nutrient,
           y = resp_rate, col=temp)) +
    geom_point() +
    ylim(-0.005, -0.0038) +
    geom_errorbar(aes(ymin=resp_rate-se, ymax=resp_rate+se), width=0.1, size = 1) +
    #scale_color_manual(values = c("black", "darkgreen")) +
    ggtitle ("Nitrate with & without control - Temperature summary") +
    labs(x = " ", 
         y = expression(paste("Rate O2 Consumption (umol*min"^"-1"~"*g"^"-1"~")")), 
         caption = "data represent mean +/- SEM" ) +
    scale_color_manual(" Temperature ", labels=c("20C","30C"), values=c("blue", "darkred"))

# Summarize by e_coli and temp so we can visualize
sum_temp_e_coli_nitrate <- summarySE(resp_all_nitrate.data, measurevar = "resp_rate", groupvars = c("e_coli_plate","temp"))
# Visualize
gg_temp_e_coli_nitrate<-ggplot(data = sum_temp_e_coli_nitrate,
       aes(x = e_coli_plate,
           y = resp_rate, colour=temp)) +
    geom_point() +
  ylim(-0.0053, -0.0037) +
    geom_errorbar(aes(ymin=resp_rate-se, ymax=resp_rate+se), width=0.1, size = 1) +
    #scale_color_manual(values = c("black", "darkgreen")) +
    ggtitle ("nitrate- temperature and e coli summary") +
   # scale_x_discrete(labels=c("20C","30C"))+
    labs(x = "E. coli", 
         y = expression(paste("Rate O2 Consumption (umol*min"^"-1"~"*g"^"-1"~")")), 
         caption = "data represent mean +/- SEM" ) +
     scale_x_discrete("E. coli presence", labels=c("0"="No E. coli", "1"="E coli"))+
     scale_color_manual("Temperature",labels=c("20C","30C"), values=c("blue", "darkred"))
gg_temp_e_coli_nitrate

gg_temp_nitrate

#now let's do sym state for control vs. nutrient

sum_sym_state_control_nutrient <- summarySE(resp_all_nitrate.data, measurevar = "resp_rate", groupvars = c("sym_state", "control_or_nutrient"))
gg_sym_state_nitrate<-ggplot(data = sum_sym_state_control_nutrient,
       aes(x = control_or_nutrient,
           y = resp_rate, col=sym_state)) +
    geom_point() +
    ylim(-0.0049, -0.0039) +
    geom_errorbar(aes(ymin=resp_rate-se, ymax=resp_rate+se), width=0.1, size = 1) +
    #scale_color_manual(values = c("black", "darkgreen")) +
    ggtitle ("Nitrate with & without control - Sym state summary") +
    labs(x = " ", 
         y = expression(paste("Rate O2 Consumption (umol*min"^"-1"~"*g"^"-1"~")")), 
         caption = "data represent mean +/- SEM" ) +
    scale_color_manual(" Symbiotic State ", labels=c("Aposymbiotic","Symbiotic"), values=c("darkgray", "tan4"))
gg_sym_state_nitrate



# STATS STATS STATS
lm_resp_control_v_nutrient <- lm(resp_rate ~  temp + e_coli_plate + control_or_nutrient + (1 | col_num), data=resp_all_ammonium.data)
summary(lm_resp_control_v_nutrient)

# Summarize by control_or_nutrient * e_coli
elm_control_v_nutrient=emmeans(lm_resp_control_v_nutrient, specs=pairwise ~ control_or_nutrient*e_coli_plate)
summary(elm_control_v_nutrient)

# Summarize by control_or_nutrient * temp
elm_control_v_nutrient=emmeans(lm_resp_control_v_nutrient, specs=pairwise ~ control_or_nutrient*temp)
summary(elm_control_v_nutrient)

# Summarize by control_or_nutrient * symbiotic state
elm_control_v_nutrient=emmeans(lm_resp_control_v_nutrient, specs=pairwise ~ control_or_nutrient*sym_state)
summary(elm_control_v_nutrient)






```

```{r Controls only}
nitrate_controls <- subset(resp_all_nitrate.data, resp_all_nitrate.data$N_dose==0)


#linear model 
nitrate_controls$treat_ID_full<-as.factor(nitrate_controls$treat_ID_full)
nitrate_controls$e_coli_plate<-as.factor(nitrate_controls$e_coli_plate)
nitrate_controls$temp <- as.factor(nitrate_controls$temp)
nitrate_controls$N_species_dose <- as.factor(nitrate_controls$N_species_dose)
nitrate_controls$food <- as.factor(nitrate_controls$food)

full.model <- lm(resp_rate ~  N_species_dose + temp + food + sym_state + e_coli_plate + N_species_dose*temp + N_species_dose*food + N_species_dose*sym_state + N_species_dose*e_coli_plate + temp*food + temp*sym_state + temp*e_coli_plate + food*sym_state + food*e_coli_plate + sym_state*e_coli_plate +  (1|col_num) + (1|exp_num) , data= nitrate_controls)
print(step.model<- step(full.model))


lm_controls <-lm(resp_rate ~ sym_state + e_coli_plate + temp + (1 | col_num), data=nitrate_controls)

elm_control <-emmeans(lm_controls, specs=pairwise ~ sym_state)
summary(elm_control)

summary(lm_without_controls)



#make sure treatID is a character
nitrate_controls$treat_ID_full<-as.character(nitrate_controls$treat_ID_full)
nitrate_controls$e_coli_plate<-as.character(nitrate_controls$e_coli_plate)
nitrate_controls$temp <- as.character(nitrate_controls$temp)

sum_sym_state <- summarySE(nitrate_controls, measurevar = "resp_rate", groupvars = c("sym_state"))
gg_sym_state_nitrate<-ggplot(data = sum_sym_state, 
          aes(x=sym_state, y = resp_rate, col=sym_state)) +
    geom_point() +
    geom_errorbar(aes(ymin=resp_rate-se, ymax=resp_rate+se), width=0.1, size = 1) +
    #scale_color_manual(values = c("black", "darkgreen")) +
    ggtitle ("Nitrate CONTROLS ONLY - Sym state summary") +
  theme(legend.position="none")+
    labs(x = "Sym State", 
         y = expression(paste("Rate O2 Consumption (umol*min"^"-1"~"*g"^"-1"~")")), 
         caption = "data represent mean +/- SEM" ) +
   # scale_x_discrete("Sym", labels=c("20"="Control 20C", "30"="Elevated 30C")) +
    scale_color_manual(labels=labels, values=c("gray", "brown"))
gg_sym_state_nitrate

```


```{r By dose by E. coli by temp}
# Summarize by temperature so we can visualize
sum_temp20_nitrate <- summarySE(all_20C, measurevar = "resp_rate", groupvars = c("temp"))
# Visualize
gg_temp20_nitrate<-ggplot(data = sum_temp20_nitrate,
       aes(x = temp,
           y = resp_rate, col=temp)) +
    geom_point() +
    geom_errorbar(aes(ymin=resp_rate-se, ymax=resp_rate+se), width=0.1, size = 1) +
    #scale_color_manual(values = c("black", "darkgreen")) +
    ggtitle ("Nitrate- Temperature summary") +
  theme(legend.position="none")+
    labs(x = "Temperature", 
         y = expression(paste("Rate O2 Consumption (umol*min"^"-1"~"*g"^"-1"~")")), 
         caption = "data represent mean +/- SEM" ) +
    scale_x_discrete("Temperature", labels=c("20"="Control 20C", "30"="Elevated 30C")) +
    scale_color_manual(labels=labels, values=c("blue", "red"))
gg_temp20_nitrate

```


```{r Looking at Nitrate 18uM}
# We found in the above analyses that there was a statistically significant difference between Control and 18uM under E. coli. Let's zoom out and look at 18uM and see what might be driving that model 

#QUESTION: For corals at 18uM nitrate, is there a significant difference if you are 1) fed vs starved? 2) E. coli vs. no E. coli? 3) sym vs apo?   4) 20 vs. 30C? 

summary(aov(e_coli_18uM$resp_rate ~ e_coli_18uM$temp))


#Maybe let's graph 18uM and see what comes out
lm_all_18uM<- lm(resp_rate~e_coli_plate + temp + food + sym_state, data=all_18uM)
summary(lm_all_18uM)
# Summarize by E. coli -- it looks like there is a difference here, but it just doesn't come out as significant
all_18uM_sum_e_coli <- summarySE(all_18uM, measurevar = "resp_rate", groupvars = c("e_coli_plate"))
# Summarize by food
all_18uM_sum_food <- summarySE(all_18uM, measurevar = "resp_rate", groupvars = c("food"))
# Summarize by sym-state
all_18uM_sum_sym_state <- summarySE(all_18uM, measurevar = "resp_rate", groupvars = c("sym_state"))
# Summarize by temp
all_18uM_sum_temp <- summarySE(all_18uM, measurevar = "resp_rate", groupvars = c("temp"))
# Visualize
ggplot(data = all_18uM_sum_e_coli,
       aes(x = e_coli_plate,
           y = resp_rate)) +
    geom_point() +
    geom_errorbar(aes(ymin=resp_rate-se, ymax=resp_rate+se), width=0.1, size = 1) +
    #scale_color_manual(values = c("black", "darkgreen")) +
    ggtitle ("N 18uM - e. coli vs. no e. coli") +
    theme(legend.position = "right",
          legend.title = element_text(size=12),
          axis.title = element_text(size = 12),
          legend.background = element_blank(),
          panel.grid.major = element_blank(), 
          panel.grid.minor = element_blank(),
          axis.text = element_text(size = 12)) +
    labs(x = "\n", 
         y = expression(paste("Rate O2 Consumption (umol*min"^"-1"~"*g"^"-1"~")")), 
         caption = "data represent mean +/- SEM" ) +
    theme_classic()

# What about 18uM treated with E. coli
e_coli_18uM<-subset(resp_all_nitrate.data, resp_all_nitrate.data$N_species_dose=="N_18" & resp_all_nitrate.data$e_coli_plate==1)

# Summarize by food
e_coli_18uM_sum_food <- summarySE(e_coli_18uM, measurevar = "resp_rate", groupvars = c("food"))
# Summarize by sym-state
e_coli_18uM_sum_sym_state <- summarySE(e_coli_18uM, measurevar = "resp_rate", groupvars = c("sym_state"))
# Summarize by temp
e_coli_18uM_sum_temp <- summarySE(e_coli_18uM, measurevar = "resp_rate", groupvars = c("temp"))
# Visualize
ggplot(data = e_coli_18uM_sum_food,
       aes(x = food,
           y = resp_rate)) +
    geom_point() +
    geom_errorbar(aes(ymin=resp_rate-se, ymax=resp_rate+se), width=0.1, size = 1) +
    #scale_color_manual(values = c("black", "darkgreen")) +
    ggtitle ("N 18uM with E. Coli - fed vs. starved") +
    theme(legend.position = "right",
          legend.title = element_text(size=12),
          axis.title = element_text(size = 12),
          legend.background = element_blank(),
          panel.grid.major = element_blank(), 
          panel.grid.minor = element_blank(),
          axis.text = element_text(size = 12)) +
    labs(x = "\n", 
         y = expression(paste("Rate O2 Consumption (umol*min"^"-1"~"*g"^"-1"~")")), 
         caption = "data represent mean +/- SEM" ) +
    theme_classic()

```




```{r playing around with Sarahs code to see if there is an effect of E coli at every treatment}

#Generate a linear model and then use the log function on it, why are we doing this bestie?
lm_resp_TREAT_ID <- lm(resp_rate ~ treat_ID_collapsed_controls + (1|exp_num) + (1|col_num), data= resp_all_nitrate.data)
lm_resp_TREAT_ID_log<- Log(lm_resp_TREAT_ID)~e_coli_plate + (1|exp_num) + (1|col_num)
summary(lm_resp_TREAT_ID_log)

# Question: Is there a significant change of resp rate at each treatment ID under E coli?
# create grouping factor to run all linear models for each treatment at once
by_treat_all <- group_by(resp_all_nitrate.data, treat_ID_collapsed_controls)

# Create a df with the parameter coefficients of the linear models  
response.lm_all <- 
  do(by_treat_all, 
   tidy(                     
     lm(resp_rate~e_coli_plate, data= .)))
print(response.lm_all)

# TEMP
#create grouping factor to run all linear models for each treatment at once
by_treat_20C<- group_by(all_20C, treat_ID_collapsed_controls)

# Create a df with the parameter coefficients of the linear models  
response.lm_20C <- 
  do(by_treat_20C, 
   tidy(                     
     lm(resp_rate~e_coli_plate, data= .)))
response.lm_20C

# create grouping factor to run all linear models for each treatment at once
by_treat_30C<- group_by(all_30C, treat_ID_collapsed_controls)

# Create a df with the parameter coefficients of the linear models  
response.lm_30C <- 
  do(by_treat_30C, 
   tidy(                     
     lm(resp_rate~e_coli_plate, data= .)))
response.lm_30C

# SYM STATE
#create grouping factor to run all linear models for each treatment at once
by_treat_sym<- group_by(all_sym, treat_ID_collapsed_controls)

# Create a df with the parameter coefficients of the linear models  
response.lm_sym <- 
  do(by_treat_sym, 
   tidy(                     
     lm(resp_rate~e_coli_plate, data= .)))
response.lm_sym

# create grouping factor to run all linear models for each treatment at once
by_treat_apo<- group_by(all_apo, treat_ID_collapsed_controls)

# Create a df with the parameter coefficients of the linear models  
response.lm_apo <- 
  do(by_treat_apo, 
   tidy(                     
     lm(resp_rate~e_coli_plate, data= .)))
response.lm_apo

```

# We are now going to subset just fed and just starved data and do linear models to compare results to the overall model
```{r Fed data}
#first let's subset all of the fed data
all_fed_nitrate<-subset(resp_all_nitrate.data, resp_all_nitrate.data$food=="F")
qqnorm(all_fed_nitrate$resp_rate) #looks good

#now let's do model selection
full.model_fed_nitrate <- lm(resp_rate ~  N_species_dose + temp + sym_state + e_coli_plate + N_species_dose*temp +  N_species_dose*sym_state + N_species_dose*e_coli_plate + temp*sym_state + temp*e_coli_plate +  sym_state*e_coli_plate +  (1|col_num) + (1|exp_num) , data= all_fed_nitrate)
print(step.model<- step(full.model_fed_nitrate))

lm_fed_nitrate <- lm(resp_rate ~  N_species_dose + temp + sym_state + e_coli_plate +  (1|col_num) , data= all_fed_nitrate)
summary(lm_fed_nitrate)
#e coli comes out as significant

```


```{r Starved data}
#first let's subset all of the fed data
all_starved_nitrate<-subset(resp_all_nitrate.data, resp_all_nitrate.data$food=="S")
qqnorm(all_starved_nitrate$resp_rate) #looks good
full.model_starved_nitrate <- lm(resp_rate ~  N_species_dose + temp + sym_state + e_coli_plate + N_species_dose*temp +  N_species_dose*sym_state + N_species_dose*e_coli_plate + temp*sym_state + temp*e_coli_plate +  sym_state*e_coli_plate +  (1|col_num) + (1|exp_num) , data= all_fed_nitrate)
print(step.model<- step(full.model_starved_nitrate))

lm_starved_nitrate <- lm(resp_rate ~ N_species_dose + temp + sym_state + e_coli_plate +  (1|col_num) , data= all_starved_nitrate)
summary(lm_starved_nitrate)

#temperature comes out significant

```

