---
title: "RGB data NITRATE: last updated 03/07/22 C. Fleming"
output: html_notebook
---
#NITRATE ONLY

```{r Loading all necessary packages}
# library("knitr")
# require("knitr")
# opts_knit$set(root.dir = "C:/Users/carol/Documents/PhD Boston University 2019-/Chapter_2_Ecotox/Summer_2022_N_Ecotox")
# setwd("C:/Users/carol/Documents/PhD Boston University 2019-/Chapter_2_Ecotox/Summer_2022_N_Ecotox")
# getwd()
#install.packages("lme4")
#compare with and without predictor
library("lme4")
#install.packages("lmerTest")
library("lmerTest")
#install.packages("emmeans")
library("emmeans")
#install.packages("pbkrtest")
library("pbkrtest")
#reshape melts our datasets in the way we want
library("reshape2")
library("dplyr")
library("plyr")
library("tidyverse")
library("Rmisc")
library("ggplot2")
#multiple response variables 
#check model with performance package
  #model tools R markdown
  #check for colinearity
  #r squared figures
#install.packages("performance")
#install.packages(c("rlang", "ggplot2", "performance", "dplyr", "ggrepel", "see"), dependencies = TRUE)
library("performance")
#install.packages("see")
library("see")
#install.packages("ggrepel")
library("ggrepel")
#install.packages("sjPlot") #for visualizing linear models
library(sjPlot)
#gg effects
library(MASS)
library(outliers)
library(car)

#increase the number of results it will show
options(max.print=1000000)
```


```{r Inputting data & making sure everything is organized correctly}
rgb_all_nitrate.data <- read.csv("Master_RGB_Spreadsheet_NITRATE_Condensed_Red_4_4_23_dead_deleted.csv", header=TRUE, sep=",",stringsAsFactors = FALSE)

rgb_all_nitrate.data <- na.omit(rgb_all_nitrate.data)

#checking for outliers
grubbs.test(rgb_all_nitrate.data$red_percent_change)
#alternative hypothesis: highest value 0.770351789 is an outlier
rgb_all_nitrate.data<-subset(rgb_all_nitrate.data, rgb_all_nitrate.data$red_percent_change!=0.770351789)
grubbs.test(rgb_all_nitrate.data$red_percent_change)
#alternative hypothesis: highest value 0.660635155 is an outlier
rgb_all_nitrate.data<-subset(rgb_all_nitrate.data, rgb_all_nitrate.data$red_percent_change!= 0.660635155)
grubbs.test(rgb_all_nitrate.data$red_percent_change)
#alternative hypothesis: highest value 0.639679451 is an outlier
rgb_all_nitrate.data<-subset(rgb_all_nitrate.data, rgb_all_nitrate.data$red_percent_change!= 0.639679451)
grubbs.test(rgb_all_nitrate.data$red_percent_change)
# YAY! Done


#Setting everything I need as factors for linear model and stats
rgb_all_nitrate.data$N_species<-as.factor(rgb_all_nitrate.data$N_species)
rgb_all_nitrate.data$N_dose<-as.factor(rgb_all_nitrate.data$N_dose)
rgb_all_nitrate.data$N_species_dose<-as.factor(rgb_all_nitrate.data$N_species_dose)
rgb_all_nitrate.data$temp<-as.factor(rgb_all_nitrate.data$temp)
rgb_all_nitrate.data$food<-as.factor(rgb_all_nitrate.data$food)
rgb_all_nitrate.data$sym_state<-as.character(rgb_all_nitrate.data$sym_state)
rgb_all_nitrate.data$food_sym_state<-as.factor(rgb_all_nitrate.data$food_sym_state)


#lets check for normality in red_delta
hist(rgb_all_nitrate.data$red_delta)
#looks really nice
qqnorm(rgb_all_nitrate.data$red_delta)


#lets check for normality in red_percent_change
hist(rgb_all_nitrate.data$red_percent_change)
qqnorm(rgb_all_nitrate.data$red_percent_change, main = NULL)
# looks beaaautiful



```


```{r Basic list of subsets}
# all aposymbiotic
all_apo<-subset(rgb_all_nitrate.data, rgb_all_nitrate.data$sym_state=="A")
# all symbiotic
all_sym<-subset(rgb_all_nitrate.data, rgb_all_nitrate.data$sym_state=="S")
# all fed
all_fed<-subset(rgb_all_nitrate.data, rgb_all_nitrate.data$food=="F")
# all starved
all_starved<-subset(rgb_all_nitrate.data, rgb_all_nitrate.data$food=="S")
# all 20C
all_20<-subset(rgb_all_nitrate.data, rgb_all_nitrate.data$temp=="20")
# all 30C
all_30<-subset(rgb_all_nitrate.data, rgb_all_nitrate.data$temp=="30")

#without controls
no_controls <- subset(rgb_all_nitrate.data, rgb_all_nitrate.data$N_dose!=0)
```


#DELTA models
```{r DELTA Model selection }
#were not going to look at genetic ID so let's do an lm

#stepAIC is from the MASS package
fullModel = lm(red_delta ~   N_species_dose + temp + sym_state  + N_species_dose*temp + N_species_dose*sym_state + temp*sym_state, data= rgb_all_nitrate.data) # model with all variables and possible combinations

nullModel = lm(red_delta ~  1, data= rgb_all_nitrate.data) # model with the intercept only

summary(stepAIC(nullModel, # start with a model containing no variables
                direction = 'forward', # run forward selection
                scope = list(upper = fullModel, # the maximum to consider is a model with all variables
                             lower = nullModel), # the minimum to consider is a model with no variables
                trace = 1)) # do not show the step-by-step process of model selection

summary(fullModel)
#model it selected for:
lm_rgb_1 <- lm(formula = red_delta ~1, data = rgb_all_nitrate.data)
summary(lm_rgb_1)

#lets check out some other models
lm_rgb_2 <- lm(formula = red_delta ~ sym_state + N_species_dose, data = rgb_all_nitrate.data)
summary(lm_rgb_2)
#nothing going on
lm_rgb_3 <- lm(formula = red_delta ~ temp*N_species_dose , data = rgb_all_nitrate.data)
summary(lm_rgb_3)
summary(emmeans(lm_rgb_3, pairwise ~ N_species_dose*temp))
#interaction of temp at n 5? Nothing pairwise
#WINNER OUT OF ALL COMBINATIONS
lm_rgb_4 <- lm(formula = red_delta ~  N_species_dose, data = rgb_all_nitrate.data)
summary(lm_rgb_4)
#nothing going on
lm_rgb_5 <- lm(formula = red_delta ~  temp + N_species_dose, data = rgb_all_nitrate.data)
summary(lm_rgb_5)

AIC(lm_rgb_1, lm_rgb_2, lm_rgb_3, lm_rgb_4, lm_rgb_5)




plot_model(lm_rgb_1, type="diag") #data fitness looks decent
r2(lm_rgb_3)

```

```{r DELTA SYM linear model}
#stepAIC is from the MASS package
fullModel = lm(red_delta ~   N_species_dose + temp  + N_species_dose*temp, data= all_sym) # model with all 9 variables and possible combinations

nullModel = lm(red_delta ~  1, data= all_sym) # model with the intercept only

summary(stepAIC(nullModel, # start with a model containing no variables
                direction = 'forward', # run forward selection
                scope = list(upper = fullModel, # the maximum to consider is a model with all variables
                             lower = nullModel), # the minimum to consider is a model with no variables
                trace = 1)) # do not show the step-by-step process of model selection

summary(fullModel)
# it only selected for:
lm_sym_1 <- lm(red_delta ~  1, data= all_sym)

#lets see if we add the N_species_dose  what happens
lm_sym_2 <- lm(red_delta ~  N_species_dose + temp, data= all_sym)
summary(lm_sym_2)
#nope


AIC(lm_sym_1, lm_sym_2)

emm_sym_rgb_N_species_dose_temp=emmeans(lm_sym_2, specs=pairwise ~ N_species_dose*temp)
summary(emm_sym_rgb_N_species_dose_temp)

#really no effect of dose or sym state

#graph sym only by N species dose and temperature

# Summarize by temp and N species dose so we can visualize
sum_N_species_dose_temp_nitrate <- summarySE(all_sym, measurevar = "red_delta", groupvars = c("temp","N_species_dose"))
sum_N_species_dose_temp_nitrate$N_species_dose <- factor(sum_N_species_dose_temp_nitrate$N_species_dose, levels=c("N_0", "N_1.5", "N_5","N_18"))
# Visualize
gg_N_species_dose_temp_nitrate<-ggplot(data = sum_N_species_dose_temp_nitrate,
       aes(x = N_species_dose,
           y = red_delta, col=temp)) +
    geom_point() +
    geom_errorbar(aes(ymin=red_delta-se, ymax=red_delta+se), width=0.1, size = 1) +
    #scale_color_manual(values = c("black", "darkgreen")) +
    ggtitle ("SYM CORALS nitrate rgb - Delta R channel value") +
    labs(x = "nitrate dose", 
         y = expression(paste("Delta R channel value")), 
         caption = "data represent mean +/- SEM" ) +
    scale_x_discrete("nitrate dose", labels=c(N_0="Control", N_1.5="1.5uM", N_5="5uM", N_18="18uM"))+
    scale_color_manual("Temperature",labels=c("20C","30C"), values=c("blue", "red"))
gg_N_species_dose_temp_nitrate


# generating ptemp and pdose:
summary(aov_temp<-aov(red_delta ~ temp, data=all_sym))
Anova(aov_temp, type="III")
summary(emmeans(aov_temp, specs=pairwise ~ temp))

#ptemp=0.33

summary(aov_temp<-aov(red_delta ~ N_species_dose, data=all_sym))
Anova(aov_temp, type="III")
summary(emmeans(aov_temp, specs=pairwise ~ N_species_dose))

#pdose=0.415
  
#food for funsies
summary(aov_food<-aov(red_delta ~ food, data=all_sym))
Anova(aov_food, type="III")

#pfood=0.484

#food doesnt seem to matter at all

summary(aov_temp<-aov(red_delta ~ N_species_dose*temp, data=all_sym))
Anova(aov_temp, type="III")
summary(emmeans(aov_temp, specs=pairwise ~ N_species_dose*temp))
  
```

```{r DELTA APO linear model}
#stepAIC is from the MASS package
fullModel = lm(red_delta ~   N_species_dose + temp  + N_species_dose*temp, data= all_apo) # model with all 9 variables and possible combinations

nullModel = lm(red_delta ~  1, data= all_apo) # model with the intercept only

summary(stepAIC(nullModel, # start with a model containing no variables
                direction = 'forward', # run forward selection
                scope = list(upper = fullModel, # the maximum to consider is a model with all variables
                             lower = nullModel), # the minimum to consider is a model with no variables
                trace = 1)) # do not show the step-by-step process of model selection

summary(fullModel)
#selected for -
lm_apo_1 <- lm(formula = red_delta ~ 1, data = all_apo)
summary(lm_apo_1)

lm_apo_2 <- lm(formula = red_delta ~ N_species_dose, data = all_apo)
summary(lm_apo_2)

#posthocs
emm_apo_N_species_dose=emmeans(lm_apo_2, specs=pairwise ~ N_species_dose)
summary(emm_apo_N_species_dose)
# nothing really going on


# Summarize by temp and N species dose so we can visualize
sum_N_species_dose_temp_nitrate <- summarySE(all_apo, measurevar = "red_delta", groupvars = c("temp","N_species_dose"))
sum_N_species_dose_temp_nitrate$N_species_dose <- factor(sum_N_species_dose_temp_nitrate$N_species_dose, levels=c("N_0", "N_1.5", "N_5","N_18"))
# Visualize
gg_N_species_dose_temp_nitrate<-ggplot(data = sum_N_species_dose_temp_nitrate,
       aes(x = N_species_dose,
           y = red_delta, col=temp)) +
    geom_point() +
    geom_errorbar(aes(ymin=red_delta-se, ymax=red_delta+se), width=0.1, size = 1) +
    #scale_color_manual(values = c("black", "darkgreen")) +
    ggtitle ("APO CORALS nitrate rgb - Delta Red channel value") +
    labs(x = "nitrate dose", 
         y = expression(paste("Delta Red channel value")), 
         caption = "data represent mean +/- SEM" ) +
    scale_x_discrete("nitrate dose", labels=c(N_0="Control", N_1.5="1.5uM", N_5="5uM", N_18="18uM"))+
    scale_color_manual("Temperature",labels=c("20C","30C"), values=c("blue", "red"))
gg_N_species_dose_temp_nitrate

# generating ptemp and pdose:
summary(aov_temp<-aov(red_delta ~ temp, data=all_apo))
Anova(aov_temp, type="III")
summary(emmeans(aov_temp, specs=pairwise ~ temp))

#ptemp=0.9495

summary(aov_temp<-aov(red_delta ~ N_species_dose, data=all_apo))
Anova(aov_temp, type="III")
summary(emmeans(aov_temp, specs=pairwise ~ N_species_dose))

#pdose=0.3758
summary(aov_temp<-aov(red_percent_change ~ N_species_dose*temp, data=all_apo))
Anova(aov_temp, type="III")
summary(emmeans(aov_temp, specs=pairwise ~ N_species_dose*temp))

```

#Percent change models
```{r PERCENT CHANGE Model selection }
#were not going to look at genetic ID so let's do an lm

#stepAIC is from the MASS package
fullModel = lm(red_percent_change ~   N_species_dose + temp + sym_state  + N_species_dose*temp + N_species_dose*sym_state + temp*sym_state, data= rgb_all_nitrate.data) # model with all variables and possible combinations

nullModel = lm(red_percent_change ~  1, data= rgb_all_nitrate.data) # model with the intercept only

summary(stepAIC(nullModel, # start with a model containing no variables
                direction = 'forward', # run forward selection
                scope = list(upper = fullModel, # the maximum to consider is a model with all variables
                             lower = nullModel), # the minimum to consider is a model with no variables
                trace = 1)) # do not show the step-by-step process of model selection

summary(fullModel)
#model it selected for:
lm_rgb_1 <- lm(formula = red_percent_change ~1, data = rgb_all_nitrate.data)
summary(lm_rgb_1)

#lets check out some other models
lm_rgb_2 <- lm(formula = red_percent_change ~ sym_state + temp + N_species_dose, data = rgb_all_nitrate.data)
summary(lm_rgb_2)
#nothing going on
lm_rgb_3 <- lm(formula = red_percent_change ~ sym_state + temp , data = rgb_all_nitrate.data)
summary(lm_rgb_3)
#nothing going on
#WINNER OUT OF ALL COMBINATIONS
lm_rgb_4 <- lm(formula = red_percent_change ~ sym_state + N_species_dose, data = rgb_all_nitrate.data)
summary(lm_rgb_4)
#nothing going on
lm_rgb_5 <- lm(formula = red_percent_change ~  temp + N_species_dose, data = rgb_all_nitrate.data)
summary(lm_rgb_5)

AIC(lm_rgb_1, lm_rgb_2, lm_rgb_3, lm_rgb_4, lm_rgb_5)

#linear model 1 is the winner here, nothing going on overall


plot_model(lm_rgb_1, type="diag") #data fitness looks decent
r2(lm_rgb_1)

```

```{r PERCENT CHANGE SYM linear model}
#stepAIC is from the MASS package
fullModel = lm(red_percent_change ~   N_species_dose + temp  + N_species_dose*temp, data= all_sym) # model with all 9 variables and possible combinations

nullModel = lm(red_percent_change ~  1, data= all_sym) # model with the intercept only

summary(stepAIC(nullModel, # start with a model containing no variables
                direction = 'forward', # run forward selection
                scope = list(upper = fullModel, # the maximum to consider is a model with all variables
                             lower = nullModel), # the minimum to consider is a model with no variables
                trace = 1)) # do not show the step-by-step process of model selection

summary(fullModel)
# it only selected for:
lm_sym_1 <- lm(red_percent_change ~  1, data= all_sym)

#lets see if we add the N_species_dose  what happens
lm_sym_2 <- lm(red_percent_change ~  N_species_dose + temp, data= all_sym)
summary(lm_sym_2)
#WINNER


AIC(lm_sym_1, lm_sym_2)

emm_sym_rgb_N_species_dose_temp=emmeans(lm_sym_2, specs=pairwise ~ N_species_dose*temp)
summary(emm_sym_rgb_N_species_dose_temp)

#really no effect of dose or sym state

#graph sym only by N species dose and temperature

# Summarize by temp and N species dose so we can visualize
sum_N_species_dose_temp_nitrate <- summarySE(all_sym, measurevar = "red_percent_change", groupvars = c("temp","N_species_dose"))
sum_N_species_dose_temp_nitrate$N_species_dose <- factor(sum_N_species_dose_temp_nitrate$N_species_dose, levels=c("N_0", "N_1.5", "N_5","N_18"))
# Visualize
gg_N_species_dose_temp_nitrate<-ggplot(data = sum_N_species_dose_temp_nitrate,
       aes(x = N_species_dose,
           y = red_percent_change, col=temp)) +
    geom_point() +
    geom_errorbar(aes(ymin=red_percent_change-se, ymax=red_percent_change+se), width=0.1, size = 1) +
    #scale_color_manual(values = c("black", "darkgreen")) +
    ggtitle ("SYM CORALS nitrate rgb - % Change in R channel value") +
    labs(x = "nitrate dose", 
         y = expression(paste("% Change in R channel value")), 
         caption = "data represent mean +/- SEM" ) +
    scale_x_discrete("nitrate dose", labels=c(N_0="Control", N_1.5="1.5uM", N_5="5uM", N_18="18uM"))+
    scale_color_manual("Temperature",labels=c("20C","30C"), values=c("blue", "red"))
gg_N_species_dose_temp_nitrate


# generating ptemp and pdose:
summary(aov_temp<-aov(red_percent_change ~ temp, data=all_sym))
Anova(aov_temp, type="III")
summary(emmeans(aov_temp, specs=pairwise ~ temp))

#ptemp=0.312

summary(aov_temp<-aov(red_percent_change ~ N_species_dose, data=all_sym))
Anova(aov_temp, type="III")
summary(emmeans(aov_temp, specs=pairwise ~ N_species_dose))

#pdose=0.415
  
#food for funsies
summary(aov_food<-aov(red_percent_change ~ food, data=all_sym))
Anova(aov_food, type="III")

#pfood=0.484

#food doesnt seem to matter at all
  
```

```{r PERCENT CHANGE APO linear model}
#stepAIC is from the MASS package
fullModel = lm(red_percent_change ~   N_species_dose + temp  + N_species_dose*temp, data= all_apo) # model with all 9 variables and possible combinations

nullModel = lm(red_percent_change ~  1, data= all_apo) # model with the intercept only

summary(stepAIC(nullModel, # start with a model containing no variables
                direction = 'forward', # run forward selection
                scope = list(upper = fullModel, # the maximum to consider is a model with all variables
                             lower = nullModel), # the minimum to consider is a model with no variables
                trace = 1)) # do not show the step-by-step process of model selection

summary(fullModel)
#selected for -
lm_apo_1 <- lm(formula = red_percent_change ~ 1, data = all_apo)
summary(lm_apo_1)

lm_apo_2 <- lm(formula = red_percent_change ~ N_species_dose, data = all_apo)
summary(lm_apo_2)

#posthocs
emm_apo_N_species_dose=emmeans(lm_apo_2, specs=pairwise ~ N_species_dose)
summary(emm_apo_N_species_dose)
# nothing really going on


# Summarize by temp and N species dose so we can visualize
sum_N_species_dose_temp_nitrate <- summarySE(all_apo, measurevar = "red_percent_change", groupvars = c("temp","N_species_dose"))
sum_N_species_dose_temp_nitrate$N_species_dose <- factor(sum_N_species_dose_temp_nitrate$N_species_dose, levels=c("N_0", "N_1.5", "N_5","N_18"))
# Visualize
gg_N_species_dose_temp_nitrate<-ggplot(data = sum_N_species_dose_temp_nitrate,
       aes(x = N_species_dose,
           y = red_percent_change, col=temp)) +
    geom_point() +
    geom_errorbar(aes(ymin=red_percent_change-se, ymax=red_percent_change+se), width=0.1, size = 1) +
    #scale_color_manual(values = c("black", "darkgreen")) +
    ggtitle ("APO CORALS nitrate rgb - Change in Red channel value") +
    labs(x = "nitrate dose", 
         y = expression(paste("Change in Red channel value")), 
         caption = "data represent mean +/- SEM" ) +
    scale_x_discrete("nitrate dose", labels=c(N_0="Control", N_1.5="1.5uM", N_5="5uM", N_18="18uM"))+
    scale_color_manual("Temperature",labels=c("20C","30C"), values=c("blue", "red"))
gg_N_species_dose_temp_nitrate

# generating ptemp and pdose:
summary(aov_temp<-aov(red_percent_change ~ temp, data=all_apo))
Anova(aov_temp, type="III")
summary(emmeans(aov_temp, specs=pairwise ~ temp))

#ptemp=0.797

summary(aov_temp<-aov(red_percent_change ~ N_species_dose, data=all_apo))
Anova(aov_temp, type="III")
summary(emmeans(aov_temp, specs=pairwise ~ N_species_dose))

#pdose=0.04


```




```{r Day 11 models}
#Day 11 is normally distributed so let's take a look at its model, since red delta wasnt as informative as we'd like
full.model_red_day11_nitrate <- lmer(red_day11~  N_species_dose + temp + food + sym_state + N_species_dose*temp + N_species_dose*food + N_species_dose*sym_state + temp*food + temp*sym_state + food*sym_state +  (1|col_num) + (1|exp_num) , data= rgb_all_nitrate.data)
summary(full.model_red_day11_nitrate )
print(step.model<- step(full.model_red_day11_nitrate ))


# DAY 11 IS MUCH MORE INFORMATIVE THAN DELTA! LET'S MOVE FORWARD WITH THIS

# Model it suggests:
mm_1_day11_nitrate <- lmer(red_day11 ~ N_species_dose + temp + sym_state + (1 | col_num) + temp*sym_state, data=rgb_all_nitrate.data)
summary(mm_1_day11_nitrate)


# Posthocs
emm_day11_N_species_dose=emmeans(mm_1_day11_nitrate, specs=pairwise ~ N_species_dose)
summary(emm_day11_N_species_dose)
# N_0 - N_1.5  -0.02346 0.00933 410  -2.514  0.0592
#  N_0 - N_18    0.00104 0.00945 422   0.111  0.9995
#  N_0 - N_5    -0.00153 0.00942 419  -0.162  0.9985
#  N_1.5 - N_18  0.02450 0.00945 417   2.592  0.0484 ** Significant
#  N_1.5 - N_5   0.02193 0.00941 414   2.331  0.0927
#  N_18 - N_5   -0.00257 0.00926 404  -0.278  0.9925

#Sym state
emm_day11_sym_state=emmeans(mm_1_day11_nitrate, specs=pairwise ~ sym_state)
summary(emm_day11_sym_state)
#0.02, SIGNIFICANT!

# N dose * sym state
emm_day11_sym_state_dose=emmeans(mm_1_day11_nitrate, specs=pairwise ~ sym_state*N_species_dose)
summary(emm_day11_sym_state_dose)
 # contrast          estimate      SE  df t.ratio p.value
 # A N_0 - S N_1.5   -0.04227 0.01262 463  -3.348  0.0197
 # S N_1.5 - A N_18   0.04332 0.01293 469   3.350  0.0196
 # S N_1.5 - A N_5    0.04075 0.01287 468   3.167  0.0348


```


```{r Exploratory t tests}
t.test(all_20$red_delta, all_30$red_delta) #no difference

t.test(all_fed$red_delta, all_starved$red_delta) #no difference

t.test(all_sym$red_delta, all_apo$red_delta) #no difference
```

# VISUALIZATIONS
```{r Prepping for visualizations}
rgb_all_nitrate.data$N_species_dose <- factor(rgb_all_nitrate.data$N_species_dose, levels=c("N_0", "N_1.5", "N_5","N_18"))
rgb_all_nitrate.data$N_species_dose<-as.character(rgb_all_nitrate.data$N_species_dose)
rgb_all_nitrate.data$sym_state<-as.character(rgb_all_nitrate.data$sym_state)
rgb_all_nitrate.data$temp <- as.character(rgb_all_nitrate.data$temp)
```


```{r Symbiotic State - red_delta}
#overall apo vs. sym
t.test(all_apo$rgb_avg_day11, all_sym$rgb_avg_day11)


rgb_treatmeans_apovsym <- summarySE(rgb_all_nitrate.data, measurevar=c("red_delta"),groupvars =c("sym_state"), na.rm=TRUE)

#NITRATE ONLY 
# plot, treatment x axis colored by site data figure
gg_rgb_plot_apovsym <- ggplot(rgb_treatmeans_apovsym, aes(x = sym_state, y= c(red_delta), color = sym_state))+
  theme_bw()+
  geom_point(size = 3, position = position_dodge(width=0.3))+
  geom_smooth(aes(group=sym_state), position = position_dodge(width=0.3), size = 0.5, method='lm', se = FALSE)+
 # geom_jitter(aes(), size=1.2, alpha=0.9)+
  geom_line(aes(group = sym_state), size = 0.5, linetype="dashed", position = position_dodge(width=0.3))+
  geom_errorbar(aes(x = sym_state, ymax = red_delta+se, ymin = red_delta-se), width = .2, position = position_dodge(width=0.3)) +
  #scale_color_manual(name = "Treatment",
                    #labels = c("Control 30C Fed","Control 30C Starved","nitrate High 30C Fed", "nitrate High 30C Starved","test"),
                    # values = c("orchid1","darkorchid1","royalblue","skyblue","black","gray","brown"))+
 ylab("Change in Red channel value Pre vs. Post-experiment")+
  ggtitle("Change in Red channel value Sym vs. Apo")+
 labs(caption = "data represent mean +/- SEM")+
  scale_x_discrete("Symboitic State", labels=c(A="Aposymbiotic", S="Symbiotic"))+ #relabels the x axis to the values in quotations
    scale_color_manual("Symboitic State", labels=c(A="Aposymbiotic", S="Symbiotic"), values=c("gray", "brown")) #gives you the colors for each point on the graph
gg_rgb_plot_apovsym

# Summarize by temp and N species dose so we can visualize
sum_N_species_dose_sym_state_nitrate <- summarySE(rgb_all_nitrate.data, measurevar = "red_delta", groupvars = c("sym_state","N_species_dose"))
sum_N_species_dose_sym_state_nitrate$N_species_dose <- factor(sum_N_species_dose_sym_state_nitrate$N_species_dose, levels=c("N_0", "N_1.5", "N_5","N_18"))
# Visualize
gg_N_species_dose_sym_state_nitrate<-ggplot(data = sum_N_species_dose_sym_state_nitrate,
       aes(x = N_species_dose,
           y = red_delta, colour=sym_state)) +
    geom_point() +
    geom_errorbar(aes(ymin=red_delta-se, ymax=red_delta+se), width=0.1, size = 1) +
    #scale_color_manual(values = c("black", "darkgreen")) +
    ggtitle ("Nitrate - Change in Red channel value by sym state and dose") +
    
   # scale_x_discrete(labels=c("20C","30C"))+
    labs(x = "Nitrate dose", 
         y = expression(paste("Change in Photosynthetic Efficiency Red channel value")), 
         caption = "data represent mean +/- SEM" ) +
    scale_x_discrete("Nitrate dose", labels=c(CNTRL_0="Control", N_1.5="1.5uM", N_5="5uM", N_18="18uM"))+
    scale_color_manual("Sym State", labels=c("Aposymbiotic","Symbiotic"), values=c("gray", "brown"))
gg_N_species_dose_sym_state_nitrate
# Summarize by food and sym state so we can visualize
sum_food_sym_state_nitrate <- summarySE(rgb_all_nitrate.data, measurevar = "red_delta", groupvars = c("sym_state","food"))
# Visualize
gg_food_sym_state_nitrate<-ggplot(data = sum_food_sym_state_nitrate,
       aes(x = sym_state,
           y = red_delta, col=food)) + #use fill here or the legends will be really hard to work with
    geom_point() +
    geom_errorbar(aes(ymin=red_delta-se, ymax=red_delta+se), width=0.1, size = 1) +
    ggtitle ("rgb delta Red channel value Sym vs. Apo at various nitrate doses") +
   #scale_fill_manual(name="Feeding Regime", labels=c('Fed', 'Starved'))+
 # scale_fill_manual(values=c("brown", "darkgray"))+
    labs(x = "Symbiotic state", 
         y = expression(paste("Change in Photosynthetic Efficiency Red channel value")), 
         caption = "data represent mean +/- SEM" ) +
      scale_x_discrete(name="Symboitic state", labels=c("A"="Aposymbiotic", "S"="Symbiotic")) +
  # scale_fill_manual(values=c("brown", "darkgray"))
 scale_color_manual(values=c("orange", "black"))
gg_food_sym_state_nitrate 

 
# WITHOUT CONTROLS #
# plot, treatment x axis colored by site data figure
rgb_treatmeans_apovsym <- summarySE(no_controls, measurevar=c("red_delta"),groupvars =c("sym_state"), na.rm=TRUE)
gg_rgb_plot_apovsym <- ggplot(rgb_treatmeans_apovsym, aes(x = sym_state, y= c(red_delta), color = sym_state))+
  theme_bw()+
  geom_point(size = 3, position = position_dodge(width=0.3))+
  geom_smooth(aes(group=sym_state), position = position_dodge(width=0.3), size = 0.5, method='lm', se = FALSE)+
 # geom_jitter(aes(), size=1.2, alpha=0.9)+
  geom_line(aes(group = sym_state), size = 0.5, linetype="dashed", position = position_dodge(width=0.3))+
  geom_errorbar(aes(x = sym_state, ymax = red_delta+se, ymin = red_delta-se), width = .2, position = position_dodge(width=0.3)) +
  #scale_color_manual(name = "Treatment",
                    #labels = c("Control 30C Fed","Control 30C Starved","nitrate High 30C Fed", "nitrate High 30C Starved","test"),
                    # values = c("orchid1","darkorchid1","royalblue","skyblue","black","gray","brown"))+
 ylab("Change in Photosynthetic Efficiency Red channel value")+
  ggtitle("No Controls rgb delta Red channel value Sym vs. Apo")+
 labs(caption = "data represent mean +/- SEM, p=")+
  scale_x_discrete("Symboitic State", labels=c(A="Aposymbiotic", S="Symbiotic"))+ #relabels the x axis to the values in quotations
    scale_color_manual("Symboitic State", labels=c(A="Aposymbiotic", S="Symbiotic"), values=c("gray", "brown")) #gives you the colors for each point on the graph
gg_rgb_plot_apovsym
# Stats on this:
full.model_nitrate_no_controls <- lmer(red_delta~  N_species_dose + temp + food + sym_state + N_species_dose*temp + N_species_dose*food + N_species_dose*sym_state + temp*food + temp*sym_state + food*sym_state +  (1|col_num) + (1|exp_num) , data= no_controls)
summary(full.model_nitrate_no_controls)
print(step.model<- step(full.model_nitrate_no_controls))
# Model we will use to check this out:
mm_1_no_controls <- lmer(red_day11 ~ sym_state, data=no_controls)
summary(mm_1_no_controls)
# Posthocs
emm_no_controls_sym_state=emmeans(mm_1_no_controls, specs=pairwise ~ sym_state)
summary(emm_no_controls_sym_state)


# Summarize by food and sym state so we can visualize
sum_food_sym_state_nitrate <- summarySE(no_controls, measurevar = "red_delta", groupvars = c("sym_state","food"))
# Visualize
gg_food_sym_state_nitrate<-ggplot(data = sum_food_sym_state_nitrate,
       aes(x = sym_state,
           y = red_delta, col=food)) + #use fill here or the legends will be really hard to work with
    geom_point() +
    geom_errorbar(aes(ymin=red_delta-se, ymax=red_delta+se), width=0.1, size = 1) +
    ggtitle ("No Controls rgb delta Red channel value Sym vs. Apo at various nitrate doses") +
   #scale_fill_manual(name="Feeding Regime", labels=c('Fed', 'Starved'))+
 # scale_fill_manual(values=c("brown", "darkgray"))+
    labs(x = "Symbiotic state", 
         y = expression(paste("Change in Photosynthetic Efficiency Red channel value")), 
         caption = "data represent mean +/- SEM" ) +
      scale_x_discrete(name="Symboitic state", labels=c("A"="Aposymbiotic", "S"="Symbiotic")) +
  # scale_fill_manual(values=c("brown", "darkgray"))
 scale_color_manual(values=c("orange", "black"))
gg_food_sym_state_nitrate #seems obvious that food doesnt matter

```

```{r Symbiotic State - red_day11 - Do we really want to do this? Potentially not because of course sym is going to be different than Apo}
#overall apo vs. sym
t.test(all_apo$rgb_avg_day11, all_sym$rgb_avg_day11)


rgb_treatmeans_apovsym <- summarySE(rgb_all_nitrate.data, measurevar=c("red_day11"),groupvars =c("sym_state"), na.rm=TRUE)

#NITRATE ONLY 
# plot, treatment x axis colored by site data figure
gg_rgb_plot_apovsym <- ggplot(rgb_treatmeans_apovsym, aes(x = sym_state, y= c(red_day11), color = sym_state))+
  theme_bw()+
  geom_point(size = 3, position = position_dodge(width=0.3))+
  geom_smooth(aes(group=sym_state), position = position_dodge(width=0.3), size = 0.5, method='lm', se = FALSE)+
 # geom_jitter(aes(), size=1.2, alpha=0.9)+
  geom_line(aes(group = sym_state), size = 0.5, linetype="dashed", position = position_dodge(width=0.3))+
  geom_errorbar(aes(x = sym_state, ymax = red_day11+se, ymin = red_day11-se), width = .2, position = position_dodge(width=0.3)) +
  #scale_color_manual(name = "Treatment",
                    #labels = c("Control 30C Fed","Control 30C Starved","nitrate High 30C Fed", "nitrate High 30C Starved","test"),
                    # values = c("orchid1","darkorchid1","royalblue","skyblue","black","gray","brown"))+
 ylab("Day 11 Red channel value ")+
  ggtitle("Day 11 Red channel value Sym vs. Apo")+
 labs(caption = "data represent mean +/- SEM")+
  scale_x_discrete("Symboitic State", labels=c(A="Aposymbiotic", S="Symbiotic"))+ #relabels the x axis to the values in quotations
    scale_color_manual("Symboitic State", labels=c(A="Aposymbiotic", S="Symbiotic"), values=c("gray", "brown")) #gives you the colors for each point on the graph
gg_rgb_plot_apovsym

# Summarize by temp and N species dose so we can visualize
sum_N_species_dose_sym_state_nitrate <- summarySE(rgb_all_nitrate.data, measurevar = "red_day11", groupvars = c("sym_state","N_species_dose"))
sum_N_species_dose_sym_state_nitrate$N_species_dose <- factor(sum_N_species_dose_sym_state_nitrate$N_species_dose, levels=c("N_0", "N_1.5", "N_5","N_18"))
# Visualize
gg_N_species_dose_sym_state_nitrate<-ggplot(data = sum_N_species_dose_sym_state_nitrate,
       aes(x = N_species_dose,
           y = red_day11, colour=sym_state)) +
    geom_point() +
    geom_errorbar(aes(ymin=red_day11-se, ymax=red_day11+se), width=0.1, size = 1) +
    #scale_color_manual(values = c("black", "darkgreen")) +
    ggtitle ("Nitrate - Day 11 Red channel value by sym state and dose") +
    
   # scale_x_discrete(labels=c("20C","30C"))+
    labs(x = "Nitrate dose", 
         y = expression(paste("Day 11 Photosynthetic Efficiency Red channel value")), 
         caption = "data represent mean +/- SEM" ) +
    scale_x_discrete("Nitrate dose", labels=c(CNTRL_0="Control", N_1.5="1.5uM", N_5="5uM", N_18="18uM"))+
    scale_color_manual("Sym State", labels=c("Aposymbiotic","Symbiotic"), values=c("gray", "brown"))
gg_N_species_dose_sym_state_nitrate
# Summarize by food and sym state so we can visualize
sum_food_sym_state_nitrate <- summarySE(rgb_all_nitrate.data, measurevar = "red_day11", groupvars = c("sym_state","food"))
# Visualize
gg_food_sym_state_nitrate<-ggplot(data = sum_food_sym_state_nitrate,
       aes(x = sym_state,
           y = red_day11, col=food)) + #use fill here or the legends will be really hard to work with
    geom_point() +
    geom_errorbar(aes(ymin=red_day11-se, ymax=red_day11+se), width=0.1, size = 1) +
    ggtitle ("rgb delta Red channel value Sym vs. Apo at various nitrate doses") +
   #scale_fill_manual(name="Feeding Regime", labels=c('Fed', 'Starved'))+
 # scale_fill_manual(values=c("brown", "darkgray"))+
    labs(x = "Symbiotic state", 
         y = expression(paste("Day 11 Photosynthetic Efficiency Red channel value")), 
         caption = "data represent mean +/- SEM" ) +
      scale_x_discrete(name="Symboitic state", labels=c("A"="Aposymbiotic", "S"="Symbiotic")) +
  # scale_fill_manual(values=c("brown", "darkgray"))
 scale_color_manual(values=c("orange", "black"))
gg_food_sym_state_nitrate 

 
# WITHOUT CONTROLS #
# plot, treatment x axis colored by site data figure
rgb_treatmeans_apovsym <- summarySE(no_controls, measurevar=c("red_day11"),groupvars =c("sym_state"), na.rm=TRUE)
gg_rgb_plot_apovsym <- ggplot(rgb_treatmeans_apovsym, aes(x = sym_state, y= c(red_day11), color = sym_state))+
  theme_bw()+
  geom_point(size = 3, position = position_dodge(width=0.3))+
  geom_smooth(aes(group=sym_state), position = position_dodge(width=0.3), size = 0.5, method='lm', se = FALSE)+
 # geom_jitter(aes(), size=1.2, alpha=0.9)+
  geom_line(aes(group = sym_state), size = 0.5, linetype="dashed", position = position_dodge(width=0.3))+
  geom_errorbar(aes(x = sym_state, ymax = red_day11+se, ymin = red_day11-se), width = .2, position = position_dodge(width=0.3)) +
  #scale_color_manual(name = "Treatment",
                    #labels = c("Control 30C Fed","Control 30C Starved","nitrate High 30C Fed", "nitrate High 30C Starved","test"),
                    # values = c("orchid1","darkorchid1","royalblue","skyblue","black","gray","brown"))+
 ylab("Day 11 Photosynthetic Efficiency Red channel value")+
  ggtitle("No Controls rgb delta Red channel value Sym vs. Apo")+
 labs(caption = "data represent mean +/- SEM, p=")+
  scale_x_discrete("Symboitic State", labels=c(A="Aposymbiotic", S="Symbiotic"))+ #relabels the x axis to the values in quotations
    scale_color_manual("Symboitic State", labels=c(A="Aposymbiotic", S="Symbiotic"), values=c("gray", "brown")) #gives you the colors for each point on the graph
gg_rgb_plot_apovsym


# Summarize by food and sym state so we can visualize
sum_food_sym_state_nitrate <- summarySE(no_controls, measurevar = "red_day11", groupvars = c("sym_state","food"))
# Visualize
gg_food_sym_state_nitrate<-ggplot(data = sum_food_sym_state_nitrate,
       aes(x = sym_state,
           y = red_day11, col=food)) + #use fill here or the legends will be really hard to work with
    geom_point() +
    geom_errorbar(aes(ymin=red_day11-se, ymax=red_day11+se), width=0.1, size = 1) +
    ggtitle ("No Controls rgb delta Red channel value Sym vs. Apo at various nitrate doses") +
   #scale_fill_manual(name="Feeding Regime", labels=c('Fed', 'Starved'))+
 # scale_fill_manual(values=c("brown", "darkgray"))+
    labs(x = "Symbiotic state", 
         y = expression(paste("Day 11 Photosynthetic Efficiency Red channel value")), 
         caption = "data represent mean +/- SEM" ) +
      scale_x_discrete(name="Symboitic state", labels=c("A"="Aposymbiotic", "S"="Symbiotic")) +
  # scale_fill_manual(values=c("brown", "darkgray"))
 scale_color_manual(values=c("orange", "black"))
gg_food_sym_state_nitrate #seems obvious that food doesnt matter

```


```{r rgb delta hot vs. ambient overall}

# Temp on its own doesnt seem to matter but sym and apo are driving the models so much we will separate them below
rgb_treatmeans_20vs30 <- summarySE(rgb_all_nitrate.data, measurevar=c("red_delta"),groupvars =c("temp"), na.rm=TRUE)

t.test(rgb_all_nitrate.data_simplified_controls$temp=="20", rgb_all_nitrate.data_simplified_controls$temp=="30")

# Summarize by temperature so we can visualize
sum_temp_nitrate <- summarySE(rgb_all_nitrate.data, measurevar = "red_delta", groupvars = c("temp"))
# Visualize
gg_temp_nitrate<-ggplot(data = sum_temp_nitrate,
       aes(x = temp,
           y = red_delta, col=temp)) +
    geom_point() +
    geom_errorbar(aes(ymin=red_delta-se, ymax=red_delta+se), width=0.1, size = 1) +
    #scale_color_manual(values = c("black", "darkgreen")) +
    ggtitle ("Nitrate rgb Delta Temperature summary") +
  theme(legend.position="none")+
    labs(x = "Temperature", 
         y = expression(paste("Delta Red channel value")), 
         caption = "data represent mean +/- SEM" ) +
    scale_x_discrete("Temperature", labels=c("20"="Control 20C", "30"="Elevated 30C")) +
    scale_color_manual("Temperature",labels=c("20C", "30C"), values=c("blue", "red"))
gg_temp_nitrate

#Let's try this on data without controls
rgb_treatmeans_20vs30 <- summarySE(no_controls, measurevar=c("red_delta"),groupvars =c("temp"), na.rm=TRUE)
# Summarize by temperature so we can visualize
sum_temp_nitrate <- summarySE(rgb_all_nitrate.data, measurevar = "red_delta", groupvars = c("temp"))
# Visualize
gg_temp_nitrate<-ggplot(data = sum_temp_nitrate,
       aes(x = temp,
           y = red_delta, col=temp)) +
    geom_point() +
    geom_errorbar(aes(ymin=red_delta-se, ymax=red_delta+se), width=0.1, size = 1) +
    #scale_color_manual(values = c("black", "darkgreen")) +
    ggtitle ("No controls Nitrate rgb Delta Temperature summary") +
  theme(legend.position="none")+
    labs(x = "Temperature", 
         y = expression(paste("Delta Red channel value")), 
         caption = "data represent mean +/- SEM" ) +
    scale_x_discrete("Temperature", labels=c("20"="Control 20C", "30"="Elevated 30C")) +
    scale_color_manual("Temperature",labels=c("20C", "30C"), values=c("blue", "red"))
gg_temp_nitrate

#summarize by temp and sym state with and without controls
rgb_treatmeans_temp_sym <- summarySE(rgb_all_nitrate.data, measurevar=c("red_delta"),groupvars =c("temp", "sym_state"), na.rm=TRUE)
# Visualize
gg_rgb_treatmeans_temp_sym<-ggplot(data = rgb_treatmeans_temp_sym,
       aes(x = sym_state,
           y = red_delta, col=temp)) +
    geom_point() +
    geom_errorbar(aes(ymin=red_delta-se, ymax=red_delta+se), width=0.1, size = 1) +
    #scale_color_manual(values = c("black", "darkgreen")) +
    ggtitle ("Nitrate Red Delta sym state Temperature summary") +
  theme(legend.position="none")+
    labs(x = "Temperature", 
         y = expression(paste("Delta Red channel value")), 
         caption = "data represent mean +/- SEM" ) +
    scale_x_discrete("Sym State", labels=c("A"="Apo", "S"="Sym")) +
    scale_color_manual("Temp",labels=c("20", "30"), values=c("blue", "red"))
gg_rgb_treatmeans_temp_sym
#Let's try this on data without controls
rgb_treatmeans_temp_sym <- summarySE(no_controls, measurevar=c("red_delta"),groupvars =c("temp", "sym_state"), na.rm=TRUE)
# Visualize
gg_rgb_treatmeans_temp_sym<-ggplot(data = rgb_treatmeans_temp_sym,
       aes(x = sym_state,
           y = red_delta, col=temp)) +
    geom_point() +
    geom_errorbar(aes(ymin=red_delta-se, ymax=red_delta+se), width=0.1, size = 1) +
    #scale_color_manual(values = c("black", "darkgreen")) +
    ggtitle ("No controls Nitrate Red Delta sym state Temperature summary") +
  theme(legend.position="none")+
    labs(x = "Temperature", 
         y = expression(paste("Delta Red channel value")), 
         caption = "data represent mean +/- SEM" ) +
    scale_x_discrete("Sym State", labels=c("A"="Apo", "S"="Sym")) +
    scale_color_manual("Temp",labels=c("20", "30"), values=c("blue", "red"))
gg_rgb_treatmeans_temp_sym

# Summarize by temp and N species dose so we can visualize
sum_N_species_dose_temp_nitrate <- summarySE(rgb_all_nitrate.data, measurevar = "red_delta", groupvars = c("temp","N_species_dose"))
# Visualize
gg_N_species_dose_temp_nitrate<-ggplot(data = sum_N_species_dose_temp_nitrate,
       aes(x = N_species_dose,
           y = red_delta, col=temp)) +
    geom_point() +
    geom_errorbar(aes(ymin=red_delta-se, ymax=red_delta+se), width=0.1, size = 1) +
    #scale_color_manual(values = c("black", "darkgreen")) +
    ggtitle ("Nitrate Red Delta Dose and Temperature summary") +
    labs(x = "Nitrate dose", 
         y = expression(paste("R channel delta")), 
         caption = "data represent mean +/- SEM" ) +
    scale_x_discrete("Nitrate dose", labels=c(CNTRL_0="Control", N_1.5="1.5uM", N_5="5uM", N_18="18uM"))+
    scale_color_manual("Temperature",labels=c("20C","30C"), values=c("blue", "red"))
gg_N_species_dose_temp_nitrate

# Separate by sym state - temp x N species dose

# Sym corals
sum_N_species_dose_temp_nitrate_sym <- summarySE(all_sym, measurevar = "red_delta", groupvars = c("temp","N_species_dose"))
# Visualize
gg_N_species_dose_temp_nitrate_sym<-ggplot(data = sum_N_species_dose_temp_nitrate_sym,
       aes(x = N_species_dose,
           y = red_delta, col=temp)) +
    geom_point() +
    geom_errorbar(aes(ymin=red_delta-se, ymax=red_delta+se), width=0.1, size = 1) +
    #scale_color_manual(values = c("black", "darkgreen")) +
    ggtitle ("Symbiotic Corals - Nitrate Red Delta Dose and Temperature summary") +
    labs(x = "Nitrate dose", 
         y = expression(paste("Delta Red channel value")), 
         caption = "data represent mean +/- SEM" ) +
    scale_x_discrete("Nitrate dose", labels=c(CNTRL_0="Control", N_1.5="1.5uM", N_5="5uM", N_18="18uM"))+
    scale_color_manual("Temperature",labels=c("20C","30C"), values=c("blue", "red"))
gg_N_species_dose_temp_nitrate_sym

#sym linear model
full.model_delta_sym <- lmer(red_delta ~  N_species_dose + temp + food + N_species_dose*temp + N_species_dose*food + temp*food +  (1|col_num) , data= all_sym)
summary(full.model_delta_sym)
print(step.model<- step(full.model_delta_sym))
mm_1_sym <- lmer(red_delta ~  N_species_dose + temp + (1|col_num) , data= all_sym)
summary(mm_1_sym)
emm_1=emmeans(mm_1_sym, specs=pairwise ~ N_species_dose*temp)
summary(emm_1)


# apo corals
sum_N_species_dose_temp_nitrate_apo <- summarySE(all_apo, measurevar = "red_delta", groupvars = c("temp","N_species_dose"))
# Visualize
gg_N_species_dose_temp_nitrate_apo<-ggplot(data = sum_N_species_dose_temp_nitrate_apo,
       aes(x = N_species_dose,
           y = red_delta, col=temp)) +
    geom_point() +
    geom_errorbar(aes(ymin=red_delta-se, ymax=red_delta+se), width=0.1, size = 1) +
    #scale_color_manual(values = c("black", "darkgreen")) +
    ggtitle ("Aposymbiotic Corals - Nitrate rgb Delta Dose and Temperature summary") +
    labs(x = "Nitrate dose", 
         y = expression(paste("Delta Red channel value")), 
         caption = "data represent mean +/- SEM" ) +
    scale_x_discrete("Nitrate dose", labels=c(CNTRL_0="Control", N_1.5="1.5uM", N_5="5uM", N_18="18uM"))+
    scale_color_manual("Temperature",labels=c("20C","30C"), values=c("blue", "red"))
gg_N_species_dose_temp_nitrate_apo

#apo linear model
full.model_delta_apo <- lmer(red_delta ~  N_species_dose + temp + food + N_species_dose*temp + N_species_dose*food + temp*food +  (1|col_num) , data= all_apo)
summary(full.model_delta_apo)
print(step.model<- step(full.model_delta_apo))
mm_1_apo <- lmer(red_delta ~  N_species_dose + temp + (1|col_num) , data= all_apo)
summary(mm_1_apo)
emm_1=emmeans(mm_1_apo, specs=pairwise ~ N_species_dose*temp)
summary(emm_1)
```

```{r N species dose graphs}
#Make N species dose a factor and give it levels so it will display in this order
rgb_all_nitrate.data$N_species_dose <- factor(rgb_all_nitrate.data$N_species_dose, levels=c("CNTRL_0", "N_1.5", "N_5","N_18"))

#Make everything else a character so they graph nicely 
rgb_all_nitrate.data$treat_ID_full<-as.character(rgb_all_nitrate.data$treat_ID_full)
rgb_all_nitrate.data$temp <- as.character(rgb_all_nitrate.data$temp)

# Summarize by N_species_dose so we can visualize
sum_N_species_dose_nitrate <- summarySE(rgb_all_nitrate.data, measurevar = "red_delta", groupvars = c("N_species_dose"))
# Visualize
gg_N_species_dose_nitrate<-ggplot(data = sum_N_species_dose_nitrate,
       aes(x = N_species_dose,
           y = red_delta, col=N_species_dose)) +
    geom_point() +
    geom_errorbar(aes(ymin=red_delta-se, ymax=red_delta+se), width=0.1, size = 1) +
    #scale_color_manual(values = c("black", "darkgreen")) +
    ggtitle ("Nitrate - Red channel change N Species Dose summary") +
   theme(legend.position="none")+
    labs(x = "\n", 
         y = expression(paste("Change in Photosynthetic Efficiency Red channel value")), 
         caption = "data represent mean +/- SEM" ) +
    scale_x_discrete("Nitrate dose", labels=c(CNTRL_0="Control", N_1.5="1.5uM", N_5="5uM", N_18="18uM"))+
    scale_color_manual(labels=labels, values=c("blue", "#9DCE9D","#359C35","darkgreen","black"))
gg_N_species_dose_nitrate

# Summarize by N_species_dose at rgb day 11 so we can visualize
sum_N_species_dose_nitrate_day11 <- summarySE(rgb_all_nitrate.data, measurevar = "rgb_avg_day11", groupvars = c("N_species_dose"))
# Visualize
gg_N_species_dose_nitrate_day11<-ggplot(data = sum_N_species_dose_nitrate_day11,
       aes(x = N_species_dose,
           y = rgb_avg_day11, col=N_species_dose)) +
    geom_point() +
    geom_errorbar(aes(ymin=rgb_avg_day11-se, ymax=rgb_avg_day11+se), width=0.1, size = 1) +
    #scale_color_manual(values = c("black", "darkgreen")) +
    ggtitle ("Nitrate - N Species Dose summary") +
   theme(legend.position="none")+
    labs(x = "\n", 
         y = expression(paste("Day 11 Photosynthetic Efficiency Red channel value")), 
         caption = "data represent mean +/- SEM" ) +
    scale_x_discrete("Nitrate dose", labels=c(CNTRL_0="Control", N_1.5="1.5uM", N_5="5uM", N_18="18uM"))+
    scale_color_manual(labels=labels, values=c("blue", "#9DCE9D","#359C35","darkgreen","black"))
gg_N_species_dose_nitrate_day11

#Jitter day 11 data
gg_N_species_dose_nitrate_day11_jitter<-ggplot(data = rgb_all_nitrate.data,
       aes(x = N_species_dose,
           y = rgb_avg_day11, col=N_species_dose)) +
    geom_boxplot() + 
   geom_jitter() +
    #scale_color_manual(values = c("black", "darkgreen")) +
    ggtitle ("Nitrate - N Species Dose summary") +
   theme(legend.position="none")+
    labs(x = "\n", 
         y = expression(paste("Day 11 Photosynthetic Efficiency Red channel value")), 
         caption = "data represent mean +/- SEM" ) +
    scale_x_discrete("Nitrate dose", labels=c(CNTRL_0="Control", N_1.5="1.5uM", N_5="5uM", N_18="18uM"))+
    scale_color_manual(labels=labels, values=c("blue", "#9DCE9D","#359C35","darkgreen","black"))
gg_N_species_dose_nitrate_day11_jitter



```

```{r}

```



