---
title: "Narragansett Water Quality"
author: "CFI"
date: "2024-06-28"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r Install required packages}
require("knitr")

#install.packages("lmerTest")
library("lmerTest")
#install.packages("Matrix")
library("Matrix")
#install.packages("lme4")
library("lme4")
#install.packages("emmeans")
library("emmeans")
#install.packages("pbkrtest")
library("pbkrtest")
library("tidyverse")
library(tidyverse)
library("performance")
#install.packages("see")
library("see")
#install.packages("ggrepel")
library("ggrepel")
#install.packages("sjPlot") #for visualizing linear models
library(sjPlot)
#install.packages("MASS")
library(MASS)
#install.packages("glmmTMB") # for visualizing model checks
library(glmmTMB)
#install.packages("relaimpo") #for quantifying the effects of predictor variables
library(relaimpo)
#install.packages("outliers") #for checking out whether a data point is an outlier
library(outliers)
library(Rmisc)
#install.packages("ggeffects")
library(ggeffects)
library(forestmodel)

#turn off scientific notation
options(scipen=999)

#let dplyr print a bunch of numbers
options(dplyr.print_max = 1e9)
options(max.print = 10000)   

```


```{r}
narragansett_water_qual.data <- read.csv("/Users/carolineianniello/Astrangia Ecotox/Data/Narragansett_water_qual_2014_2022_QCed_8_22_24.csv", header=TRUE, sep=",",stringsAsFactors = FALSE)

#I think we just want upper, and stations:
#2 which is Conimicut point
#5 Which is the GSO dock
#8 which is Jamestown
# Also categorize by season

#Add months
narragansett_water_qual.data <- narragansett_water_qual.data  %>% mutate(sample_month = case_when(
   month== 1 ~ "January",
   month==2 ~ "February",
   month==3 ~ "March",
   month==4 ~ "April",
   month==5 ~ "May",
   month==6 ~  "June",
   month==7 ~  "July",
   month==8 ~  "August",
   month==9 ~  "September",
   month==10 ~ "October",
   month==11 ~ "November",
   month==12 ~ "December"
)
)


#Add season
narragansett_water_qual.data <- narragansett_water_qual.data  %>% mutate(season = case_when(
    sample_month=="January" | sample_month=="February" | sample_month=="March" ~ "Winter" , #need two equal signs
      sample_month=="April" | sample_month=="May" | sample_month=="June" ~ "Spring" ,
    sample_month=="July" | sample_month=="August" | sample_month=="September" ~ "Summer" ,
    sample_month=="October" | sample_month=="November" | sample_month=="December" ~ "Fall" 
  )
)

#Filter
narragansett_water_qual.data$station <- as.numeric(narragansett_water_qual.data$station)

narragansett_water_qual.data <- narragansett_water_qual.data %>%
  filter(station == 2 | station == 8 ) %>%
  filter(year >= 2018) %>%
  filter(depth=="surface")

#Recategorize by season
narragansett_water_qual.data <- narragansett_water_qual.data  %>% mutate(location = case_when(
    station==2  ~ "Conimicut Point" , #need two equal signs
    station==8  ~ "Jamestown" 
  )
)


#now we have all depths, let's visualize
```

```{r}
narragansett_water_qual.data$season <- factor(narragansett_water_qual.data$season, levels=c("Winter","Spring","Summer","Fall"))
narragansett_water_qual.data$location <- factor(narragansett_water_qual.data$location, levels=c("Conimicut Point","GSO Dock","Jamestown"))

narragansett_water_qual.data<-narragansett_water_qual.data %>% 
  mutate(sample_year=as.factor(year)) %>%
  mutate(sample_month=factor(month, levels=c("January","February","March","April","May","June","July","August","September","October","November","December")))

narragansett_water_qual.data$nitrate.uml <- as.numeric(narragansett_water_qual.data$nitrate.uml)
hist(narragansett_water_qual.data$nitrate.uml)

# NITRATE
#Summarize by location, nitrate, season
sum_wq_narra_nitrate <- summarySE(narragansett_water_qual.data, measurevar = c("nitrate.uml"), groupvars = c("location", "season"))
gg_sum_wq_narra_nitrate <-ggplot(data = sum_wq_narra_nitrate ,
       aes(x = season,
           y = nitrate.uml, col=location)) +
    geom_point(size=4) +
    geom_errorbar(aes(ymin=nitrate.uml-se, ymax=nitrate.uml+se), width=0.25, linewidth=0.8) +
    ggtitle ("Nitrate Averages Across Years in Narragansett Bay, 2019-2021") +
    theme(legend.position = "right",
          legend.title = element_text(size=12),
          axis.title = element_text(size = 10),
          legend.background = element_blank(),
          panel.grid.major = element_blank(), 
          panel.grid.minor = element_blank(),
          axis.text = element_text(size = 12)) +
   # ylim(-10, 8) +
   ##scale_x_discrete("Nitrate Level", labels=c("0-6uM","6-10uM","10-20uM","10uM"))+
    labs(x = "Season", 
         y = expression(paste("Nitrate uM")), 
         caption = "data represent mean +/- SEM" ) 
       # theme(legend.position="none")+
    #scale_color_manual("Temperature", labels=c("20°C","30°C"), values=c("dodgerblue", "darkred"))
gg_sum_wq_narra_nitrate

#By month
sum_month_year_wq_narra_nitrate <- summarySE(narragansett_water_qual.data, measurevar = c("nitrate.uml"), groupvars = c("location", "month","year"), na.rm=T)
sum_month_year_wq_narra_nitrate$year <- as.factor(sum_month_year_wq_narra_nitrate$year)
sum_month_year_wq_narra_nitrate$month <-as.factor(sum_month_year_wq_narra_nitrate$month)

gg_sum_month_year_wq_narra_nitrate <-ggplot(data = sum_month_year_wq_narra_nitrate ,
       aes(x = month,
           y = nitrate.uml, col=year, shape=location, group=interaction(year,location))) +
    geom_point(size=3) +
 geom_line(linetype="dotted", size=.7)+
    geom_errorbar(aes(ymin=nitrate.uml-se, ymax=nitrate.uml+se), width=0.25, linewidth=0.8) +
    ggtitle ("Surface Nitrate Averages Across Years in Narragansett Bay, 2018-2022") +
    theme(legend.position = "right",
          legend.title = element_text(size=12),
          axis.title = element_text(size = 10),
          legend.background = element_blank(),
          panel.grid.major = element_blank(), 
          panel.grid.minor = element_blank(),
          axis.text = element_text(size = 10)) +
    ylim(0, 20) +
   scale_x_discrete(labels=c("January","February","March","April", "May","June","July","August","September","October","November","December"))+
    labs(x = "Month", 
         y = expression(paste("Nitrate uM")), 
         caption = "data represent mean +/- SEM" ) 
         #  scale_color_manual("Location", values=c("#EC407A", "#43A047", "#00BCD4")) 
#scale_shape_discrete("Year", values=c(1,2,3,4,5,6,7,8))
gg_sum_month_year_wq_narra_nitrate

```

```{r TEMPERATURE}
sum_month_year_wq_narra_temp <- summarySE(narragansett_water_qual.data, measurevar = c("temperature.celsius"), groupvars = c("location", "month","year"), na.rm=T)
sum_month_year_wq_narra_temp$year <- as.factor(sum_month_year_wq_narra_temp$year)
sum_month_year_wq_narra_temp$month <-as.factor(sum_month_year_wq_narra_temp$month)

gg_sum_month_year_wq_narra_temp <-ggplot(data = sum_month_year_wq_narra_temp ,
       aes(x = month,
           y = temperature.celsius, col=year, shape=location, group=interaction(year,location))) +
    geom_point(size=3) +
 geom_line(linetype="  dotted")+
    geom_errorbar(aes(ymin=temperature.celsius-se, ymax=temperature.celsius+se), width=0.25, linewidth=0.8) +
    ggtitle ("Surface Temperature Averages Across Years in Narragansett Bay, 2018-2022") +
    theme(legend.position = "right",
          legend.title = element_text(size=12),
          axis.title = element_text(size = 10),
          legend.background = element_blank(),
          panel.grid.major = element_blank(), 
          panel.grid.minor = element_blank(),
          axis.text = element_text(size = 10)) +
  #  ylim(0, 20) +
   scale_x_discrete(labels=c("January","February","March","April", "May","June","July","August","September","October","November","December"))+
    labs(x = "Month", 
         y = expression(paste("Temperature °C")), 
         caption = "data represent mean +/- SEM" ) 
         #  scale_color_manual("Location", values=c("#EC407A", "#43A047", "#00BCD4")) 
#scale_shape_discrete("Year", values=c(1,2,3,4,5,6,7,8))
gg_sum_month_year_wq_narra_temp
```

```{r}
#Mean summertime temperature 

narragansett_water_qual.data_SUMMER <- narragansett_water_qual.data %>%
  filter(season=="Summer")
summer_summary_temp  <- summarySE(narragansett_water_qual.data_SUMMER, measurevar = c("temperature.celsius"), na.rm=T)
```

