---
title: "PAM_COMBINED"
author: "CFI"
date: "2024-06-24"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r Install required packages}
require("knitr")

#install.packages("lmerTest")
library("lmerTest")
#install.packages("Matrix")
library("Matrix")
#install.packages("lme4")
library("lme4")
#install.packages("emmeans")
library("emmeans")
#install.packages("pbkrtest")
library("pbkrtest")
library("tidyverse")
library(tidyverse)
library("performance")
#install.packages("see")
library("see")
#install.packages("ggrepel")
library("ggrepel")
#install.packages("sjPlot") #for visualizing linear models
library(sjPlot)
#install.packages("MASS")
library(MASS)
#install.packages("glmmTMB") # for visualizing model checks
library(glmmTMB)
#install.packages("relaimpo") #for quantifying the effects of predictor variables
library(relaimpo)
#install.packages("outliers") #for checking out whether a data point is an outlier
library(outliers)
library(Rmisc)
#install.packages("ggeffects")
library(ggeffects)
library(forestmodel)

#turn off scientific notation
options(scipen=999)

#let dplyr print a bunch of numbers
options(dplyr.print_max = 1e9)
options(max.print = 10000)   

```


```{r Set working directory and upload data}
 
# #Create a NEW column for nitrate with new categories
# 
# PAM_preprocess.data <- PAM_preprocess.data %>%
#   mutate(NO3_category = case_when(
#    NO3_mean_observed < 6  ~ "Low" , #need two equal signs
#      NO3_mean_observed >= 6 ~ "Elevated" 
#    )
# )
# 
# 
# 
# #any single datapoint that was over 4 times disparate of mean or median from rest of treatment was discarded
# 

# ^ did all that pre-processing then confirmed duplicates in excel spreadhseet. Now we can just read the csv

#QCed and all dead HAVE BEEN deleted, all IDs agree between PAM, PAM, and survival --6.26.24

PAM_all.data<- read.csv("/Users/carolineianniello/Astrangia Ecotox/Data/PAM_dead_deleted_combined_NO3categorized_6_26_24.csv", header=TRUE, sep=",",stringsAsFactors = FALSE)


count(PAM_all.data$NO3_category)
#188 elevated observations
#741 low observations

PAM_all.data$NO3_category <- factor(PAM_all.data$NO3_category, levels=c("Low", "Elevated"))
PAM_all.data$sym_state<- as.factor(PAM_all.data$sym_state)
PAM_all.data$food<- as.factor(PAM_all.data$food)
PAM_all.data$temp<- as.factor(PAM_all.data$temp)

```

```{r Difference between PAM and survival-- SORTED}
# #add survival data to see what observations are missing
# survival_all.data<- read.csv("C:/Users/carol/OneDrive/Documents/PhD Boston University 2019-/Astrangia_nutrient_stressors_Rotjan_lab/Data/Survival_06_26_24.csv", header=TRUE, sep=",",stringsAsFactors = FALSE)
# 
# in_survival_not_PAM <- survival_all.data %>% 
#       filter(!survival_all.data$beetag_exprun %in% PAM_all.data$beetag_exprun) #PAMs not in survival
# notinPAM_butinsurvival <- data.frame(count(in_survival_not_PAM$beetag_exprun))
# #For df1 values not in df2
# 
# in_PAM_not_survival <- PAM_all.data %>% 
#       filter(!PAM_all.data$beetag_exprun %in% survival_all.data$beetag_exprun) #survivals not in PAM
# notinsurvival_PAM <- data.frame(count(in_PAM_not_survival$beetag_exprun))
# 
# 
# write.csv(notinPAM_butinsurvival, "C:/Users/carol/OneDrive/Documents/PhD Boston University 2019-/Astrangia_nutrient_stressors_Rotjan_lab/Data/notinPAM_butinsurvival.csv")
# 
# write.csv(notinsurvival_PAM, "C:/Users/carol/OneDrive/Documents/PhD Boston University 2019-/Astrangia_nutrient_stressors_Rotjan_lab/Data/notinsurvival_PAM.csv")



```

```{r Generating subsets to work with}


#SUBSET - 20C
PAM_20 <- PAM_all.data %>%
  filter(temp==20)
#SUBSET - 30C
PAM_30 <- PAM_all.data %>%
  filter(temp==30)






```

```{r T tests}
#selected t tests

#Nitrate category
t.test(PAM_delta ~ NO3_category, data= PAM_all.data)
#no diff
t.test(PAM_delta ~ NO3_category, data= PAM_20)
#no diff
t.test(PAM_delta ~ NO3_category, data= PAM_30)
#no diff

#Sym state
t.test(PAM_delta ~ sym_state, data= PAM_all.data)
#Syms lost more PAM_delta
t.test(PAM_delta ~ sym_state, data= PAM_20)
#Syms lost more PAM_delta
t.test(PAM_delta ~ sym_state, data= PAM_30)
#Syms lost more PAM_delta


#Food
t.test(PAM_delta ~ food, data= PAM_all.data)
#no diff
t.test(PAM_delta ~ food, data= PAM_20)
#no diff
t.test(PAM_delta ~ food, data= PAM_30)
#no diff


#Temp
t.test(PAM_delta ~ temp, data= PAM_all.data)
#no diff


#Nothing seems to matter! Slay
```

```{r ANOVAs to match graphs}
hist(PAM_all.data$PAM_avg_day11) #nice and normal

#Now an ANOVA on sym state, temp, and NO3_category 
anova_PAM_delta <- aov(PAM_delta ~ sym_state*temp*NO3_category, data=PAM_all.data)
summary(anova_PAM_delta )
#ptemp = 0.0146
TukeyHSD(anova_PAM )

hist(PAM_all.data$PAM_avg_day11) #eh not great kinda skewed but let's go with it
anova_PAM_avg_day11 <- aov(PAM_avg_day11~ sym_state*temp*NO3_category, data=PAM_all.data)
summary(anova_PAM_avg_day11 )
#ptemp = 0.0146
TukeyHSD(anova_PAM )

```


#For Manuscript


#PAM day 1 v 11

```{r}

#Summarize all treatments by SYM STATE and temp
sum_day1_temp_sym <- summarySE(PAM_all.data, measurevar = c("PAM_avg_day1"), groupvars = c("sym_state", "temp", "NO3_category"))
sum_day1_temp_sym$day <- 1
sum_day1_temp_sym$PAM_avg <- sum_day1_temp_sym$PAM_avg_day1

sum_day11_temp_sym <- summarySE(PAM_all.data, measurevar = c("PAM_avg_day11"), groupvars = c("sym_state", "temp", "NO3_category"))
sum_day11_temp_sym$day <- 11
sum_day11_temp_sym$PAM_avg <- sum_day11_temp_sym$PAM_avg_day11


PAM_day1_11_summary <- full_join(sum_day1_temp_sym, sum_day11_temp_sym)
PAM_day1_11_summary$day <- as.factor(PAM_day1_11_summary$day)

PAM_day1_11_summary_LOW <- subset(PAM_day1_11_summary, PAM_day1_11_summary$NO3_category=="Low")

PAM_day1_11_summary_ELEVATED <- subset(PAM_day1_11_summary, PAM_day1_11_summary$NO3_category=="Elevated")

# Visualize AMBIENT
gg_LOW <-ggplot(data = PAM_day1_11_summary_LOW,
       aes(x = day,
           y = PAM_avg, col=temp, shape=sym_state, group=interaction(sym_state, temp))) +
    geom_point(size=4, position=position_dodge(width=0.2)) +
    geom_errorbar(aes(ymin=PAM_avg-se, ymax=PAM_avg+se), width=0.25, linewidth=0.8, position=position_dodge(width=0.2)) +
  geom_line(linewidth=1, position=position_dodge(width=0.2), linetype="dotted")+
    ggtitle ("PAM AMBIENT N Delta By Temp Sym State") +
    theme(legend.position = "right",
           legend.text = element_text(size=13),
          legend.title = element_text(size=15),
          axis.title = element_text(size = 14),
          legend.background = element_blank(),
          panel.grid.major = element_blank(), 
          panel.grid.minor = element_blank(),
          axis.text = element_text(size = 12)) +
    #ylim(-0.18,0.15) +
 scale_x_discrete("Day", labels=c("1", "11"))+
    labs(x = "Day", 
         y = expression(paste("Mean Fv/Fm")), 
         caption = "data represent mean +/- SEM" ) +
       # theme(legend.position="none")+
  scale_shape_discrete("Symbiotic state", labels=c("Aposymbiotic","Symbiotic")) +
    scale_color_manual("Temperature", labels=c("20°C","29°C"), values=c("dodgerblue", "darkred")) +
  theme(aspect.ratio = 1.5)
gg_LOW


# Visualize AMBIENT
gg_ELEVATED <-ggplot(data = PAM_day1_11_summary_ELEVATED,
       aes(x = day,
           y = PAM_avg, col=temp, shape=sym_state, group=interaction(sym_state, temp))) +
    geom_point(size=4, position=position_dodge(width=0.2)) +
    geom_errorbar(aes(ymin=PAM_avg-se, ymax=PAM_avg+se), width=0.25, linewidth=0.8, position=position_dodge(width=0.2)) +
  geom_line(linewidth=1, position=position_dodge(width=0.2), linetype="dotted")+
    ggtitle ("PAM AMBIENT N Delta By Temp Sym State") +
    theme(legend.position = "right",
           legend.text = element_text(size=13),
          legend.title = element_text(size=15),
          axis.title = element_text(size = 14),
          legend.background = element_blank(),
          panel.grid.major = element_blank(), 
          panel.grid.minor = element_blank(),
          axis.text = element_text(size = 12)) +
    #ylim(-0.18,0.15) +
 scale_x_discrete("Day", labels=c("1", "11"))+
    labs(x = "Day", 
         y = expression(paste("Mean Fv/Fm")), 
         caption = "data represent mean +/- SEM" ) +
       # theme(legend.position="none")+
  scale_shape_discrete("Symbiotic state", labels=c("Aposymbiotic","Symbiotic")) +
    scale_color_manual("Temperature", labels=c("20°C","29°C"), values=c("dodgerblue", "darkred")) +
  theme(aspect.ratio = 1.5)
gg_ELEVATED

```



# PAM delta 


```{r}

#Summarize all treatments by SYM STATE and temp
sum_sym_temp <- summarySE(PAM_all.data, measurevar = "PAM_delta", groupvars = c("sym_state", "temp", "NO3_category"))
# Visualize
gg_sym_temp <-ggplot(data = sum_sym_temp,
       aes(x = NO3_category,
           y = PAM_delta, col=temp, shape=sym_state)) +
    geom_point(size=4) +
    geom_errorbar(aes(ymin=PAM_delta-se, ymax=PAM_delta+se), width=0.25, linewidth=0.8) +
    ggtitle ("PAM Delta By Treatment, Temp, and Sym State") +
    theme(legend.position = "right",
           legend.text = element_text(size=13),
          legend.title = element_text(size=15),
          axis.title = element_text(size = 14),
          legend.background = element_blank(),
          panel.grid.major = element_blank(), 
          panel.grid.minor = element_blank(),
          axis.text = element_text(size = 12)) +
    ylim(-0.18,0.15) +
  scale_x_discrete("Treatment", labels=c("Elevated","Low "))+
    labs(x = "Treatment", 
         y = expression(paste("Delta Fv/Fm")), 
         caption = "data represent mean +/- SEM" ) +
       # theme(legend.position="none")+
  scale_shape_discrete("Symbiotic state", labels=c("Aposymbiotic","Symbiotic")) +
    scale_color_manual("Temperature", labels=c("20°C","29°C"), values=c("dodgerblue", "darkred"))
gg_sym_temp

#Summarize all treatments by FOOD and temp
sum_food_temp <- summarySE(PAM_all.data, measurevar = "PAM_delta", groupvars = c("food", "temp", "NO3_category"))
# Visualize
gg_food_temp <-ggplot(data = sum_food_temp,
       aes(x = NO3_category,
           y = PAM_delta, col=temp, shape=food)) +
    geom_point(size=4) +
    geom_errorbar(aes(ymin=PAM_delta-se, ymax=PAM_delta+se), width=0.25, linewidth=0.8) +
    ggtitle ("PAM Delta By Treatment, Temp, and Food") +
    theme(legend.position = "right",
           legend.text = element_text(size=13),
          legend.title = element_text(size=15),
          axis.title = element_text(size = 14),
          legend.background = element_blank(),
          panel.grid.major = element_blank(), 
          panel.grid.minor = element_blank(),
          axis.text = element_text(size = 12)) +
       ylim(-0.18,0.15) +
  scale_x_discrete("Treatment", labels=c("Elevated","Low"))+
    labs(x = "Treatment", 
         y = expression(paste("Delta Fv/Fm")), 
         caption = "data represent mean +/- SEM" ) +
       # theme(legend.position="none")+
  scale_shape_manual("Feeding treatment", labels=c("Fed","Starved"), values=c(18,8)) +
    scale_color_manual("Temperature", labels=c("20°C","29°C"), values=c("dodgerblue", "darkred"))
gg_food_temp
```




```{r PAM Day 11 visuals}
sum_sym_temp_nitrate_PAM_day11 <- summarySE(PAM_all.data, measurevar = "PAM_avg_day11", groupvars = c("sym_state", "temp", "NO3_category"))
# Visualize
gg_sum_sym_temp_nitrate_PAM_day11<-ggplot(data = sum_sym_temp_nitrate_PAM_day11 ,
       aes(x = NO3_category,
           y = PAM_avg_day11, col=temp, shape=sym_state)) +
    geom_point(size=4) +
    geom_errorbar(aes(ymin=PAM_avg_day11-se, ymax=PAM_avg_day11+se), width=0.25, linewidth=0.8) +
    ggtitle ("Day 11 Photosynthetic Efficiency Value by Sym State and Temp") +
    theme(legend.position = "right",
          legend.title = element_text(size=12),
          axis.title = element_text(size = 10),
          legend.background = element_blank(),
          panel.grid.major = element_blank(), 
          panel.grid.minor = element_blank(),
          axis.text = element_text(size = 12)) +
   ##scale_x_discrete("Nitrate Level", labels=c("0-6uM","6-10uM","10-20uM","10uM"))+
    labs(x = "Nitrate Dose", 
         y = expression(paste("Fv/Fm")), 
         caption = "data represent mean +/- SEM" ) +
       # theme(legend.position="none")+
  scale_shape_discrete("Symbiotic state", labels=c("Aposymbiotic","Symbiotic")) +
    scale_color_manual("Temperature", labels=c("20°C","29°C"), values=c("dodgerblue", "darkred"))

gg_sum_sym_temp_nitrate_PAM_day11

```


