---
title: "respirometry_COMBINED"
author: "CFI"
date: "2024-06-21"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r Install required packages}
require("knitr")

#install.packages("lmerTest")
library("lmerTest")
#install.packages("Matrix")
library("Matrix")
#install.packages("lme4")
library("lme4")
#install.packages("emmeans")
library("emmeans")
#install.packages("pbkrtest")
library("pbkrtest")
library("tidyverse")
library(tidyverse)
library("performance")
#install.packages("see")
library("see")
#install.packages("ggrepel")
library("ggrepel")
#install.packages("sjPlot") #for visualizing linear models
library(sjPlot)
#install.packages("MASS")
library(MASS)
#install.packages("glmmTMB") # for visualizing model checks
library(glmmTMB)
#install.packages("relaimpo") #for quantifying the effects of predictor variables
library(relaimpo)
#install.packages("outliers") #for checking out whether a data point is an outlier
library(outliers)
library(Rmisc)
#install.packages("ggeffects")
library(ggeffects)
library(forestmodel)

#turn off scientific notation
options(scipen=999)

#let dplyr print a bunch of numbers
options(dplyr.print_max = 1e9)
options(max.print = 10000)   

```


```{r Set working directory and upload data - nitrate DATA ONLY}
resp_all.data <- read.csv("C:/Users/carol/OneDrive/Documents/PhD Boston University 2019-/Astrangia_nutrient_stressors_Rotjan_lab/Data/RESP_ALL_cleaned_dead_and_broken_outlierG28Y65_deleted_SA_CORR_observed_N_A_6_21_24.csv", header=TRUE, sep=",",stringsAsFactors = FALSE)


#Create a NEW column for nitrate with new categories

resp_all.data <- resp_all.data  %>%
  mutate(NO3_category = case_when(
   NO3_mean_observed <=6  ~ "Low" , #need two equal signs
     NO3_mean_observed > 6 & NO3_mean_observed <=10 ~ "Medium",
    NO3_mean_observed > 10 ~ "High" 
   )
)

count(resp_all.data$NO3_category)
#76 high observations
#65 medium observations
#580 low observations


```


#For Manuscript
```{r}

# # ENTIRE DATASET
# Resp rate by sym state by dose
# Summarize by sym state so we can visualize
resp_all.data$NO3_category <- factor(resp_all.data$NO3_category, levels=c("Low","Medium",))
resp_all.data$sym_state<- as.factor(resp_all.data$sym_state)
sum_sym_state_nitrate <- summarySE(resp_all.data, measurevar = "abs_resp_rate_SA_corr", groupvars = c("sym_state", "NO3_category"))
# Visualize
gg_sym_state_nitrate<-ggplot(data = sum_sym_state_nitrate,
       aes(x = NO3_category,
           y = abs_resp_rate_SA_corr, col=sym_state)) +
    geom_point() +
    geom_errorbar(aes(ymin=abs_resp_rate_SA_corr-se, ymax=abs_resp_rate_SA_corr+se), width=0.35, size = 1) +
    ggtitle ("nitrate - Sym state by Dose") +
    theme(legend.position = "right",
          legend.title = element_text(size=12),
          axis.title = element_text(size = 10),
          legend.background = element_blank(),
          panel.grid.major = element_blank(), 
          panel.grid.minor = element_blank(),
          axis.text = element_text(size = 12)) +
     ylim(0.05, 0.16) +
   ##scale_x_discrete("Nitrate Level", labels=c("0-6uM","6-10uM","10-20uM","10uM"))+
    labs(x = "nitrate Dose", 
         y = expression(paste("Absolute Rate O2 Consumption (umol*min"^"-1"~"*cm"^"2"~")")), 
         caption = "data represent mean +/- SEM" ) +
       # theme(legend.position="none")+
  scale_color_manual("Symbiotic state", labels=c("Aposymbiotic","Symbiotic"), values=c("gray", "brown"))
gg_sym_state_nitrate

#lets t test low vs high
hist(log(resp_all.data$abs_resp_rate_SA_corr))
#looks beauty when you log it
subset_low_high <- subset(resp_all.data, NO3_category== "Low" | NO3_category== "High")
t.test(log(abs_resp_rate_SA_corr) ~ NO3_category, data=subset_low_high, paired=F) #SIGNIFICANTTTTTT FAAAK YEAH


t.test(NO3_uM ~ food, data= water_qual_bigelow_all, paired=F)


# # NO E COLI AT 20C
resp_NOEC_20C <- resp_all.data %>%
  filter(e_coli_plate==0 & temp==20)
#resp_NOEC_20C$NO3_category <- factor(resp_NOEC_20C$NO3_category, levels=c(0,5,7.5,10))
resp_NOEC_20C$sym_state<- as.factor(resp_NOEC_20C$sym_state)
sum_nitrate_NOEC_20C<- summarySE(resp_NOEC_20C, measurevar = "abs_resp_rate_SA_corr", groupvars = c("sym_state", "NO3_category"))
# Visualize
gg_nitrate_NOEC_20C <-ggplot(data = sum_nitrate_NOEC_20C,
       aes(x = NO3_category,
           y = abs_resp_rate_SA_corr, col=sym_state)) +
    geom_point() +
    geom_errorbar(aes(ymin=abs_resp_rate_SA_corr-se, ymax=abs_resp_rate_SA_corr+se), width=0.35, size = 1) +
    ggtitle ("nitrate NO E. Coli 20C - Sym state by Dose") +
    theme(legend.position = "right",
          legend.title = element_text(size=12),
          axis.title = element_text(size = 10),
          legend.background = element_blank(),
          panel.grid.major = element_blank(), 
          panel.grid.minor = element_blank(),
          axis.text = element_text(size = 12)) +
   ##scale_x_discrete("Nitrate Level", labels=c("0-6uM","6-10uM","10-20uM","10uM"))+
    labs(x = "nitrate Dose", 
         y = expression(paste("Absolute Rate O2 Consumption (umol*min"^"-1"~"*cm"^"2"~")")), 
         caption = "data represent mean +/- SEM" ) +
  ylim(0.05, 0.145) +
       # theme(legend.position="none")+
  scale_color_manual("Symbiotic state", labels=c("Aposymbiotic","Symbiotic"), values=c("gray", "brown"))
gg_nitrate_NOEC_20C

# # E COLI AT 20C
resp_EC_20C <- resp_all.data %>%
  filter(e_coli_plate==1 & temp==20)
resp_EC_20C$sym_state<- as.factor(resp_EC_20C$sym_state)
sum_nitrate_EC_20C<- summarySE(resp_EC_20C, measurevar = "abs_resp_rate_SA_corr", groupvars = c("sym_state", "NO3_category"))
# Visualize
gg_nitrate_EC_20C <-ggplot(data = sum_nitrate_EC_20C,
       aes(x = NO3_category,
           y = abs_resp_rate_SA_corr, col=sym_state)) +
    geom_point() +
    geom_errorbar(aes(ymin=abs_resp_rate_SA_corr-se, ymax=abs_resp_rate_SA_corr+se), width=0.35, size = 1) +
    ggtitle ("nitrate E. Coli 20C - Sym state by Dose") +
    theme(legend.position = "right",
          legend.title = element_text(size=12),
          axis.title = element_text(size = 10),
          legend.background = element_blank(),
          panel.grid.major = element_blank(), 
          panel.grid.minor = element_blank(),
          axis.text = element_text(size = 12)) +
   #scale_x_discrete("Nitrate Level", labels=c("0-6uM","6-10uM","10-20uM","10uM"))+
    labs(x = "nitrate Dose", 
         y = expression(paste("Absolute Rate O2 Consumption (umol*min"^"-1"~"*cm"^"2"~")")), 
         caption = "data represent mean +/- SEM" ) +
   ylim(0.05, 0.35) +
       # theme(legend.position="none")+
  scale_color_manual("Symbiotic state", labels=c("Aposymbiotic","Symbiotic"), values=c("gray", "brown"))
gg_nitrate_EC_20C

# # NO E COLI AT 30C
resp_NOEC_30C <- resp_all.data %>%
  filter(e_coli_plate==0 & temp==30)
resp_NOEC_30C$sym_state<- as.factor(resp_NOEC_30C$sym_state)
sum_nitrate_NOEC_30C<- summarySE(resp_NOEC_30C, measurevar = "abs_resp_rate_SA_corr", groupvars = c("sym_state", "NO3_category"))
# Visualize
gg_nitrate_NOEC_30C <-ggplot(data = sum_nitrate_NOEC_30C,
       aes(x = NO3_category,
           y = abs_resp_rate_SA_corr, col=sym_state)) +
    geom_point() +
    geom_errorbar(aes(ymin=abs_resp_rate_SA_corr-se, ymax=abs_resp_rate_SA_corr+se), width=0.35, size = 1) +
    ggtitle ("nitrate NO E. Coli 30C - Sym state by Dose") +
    theme(legend.position = "right",
          legend.title = element_text(size=12),
          axis.title = element_text(size = 10),
          legend.background = element_blank(),
          panel.grid.major = element_blank(), 
          panel.grid.minor = element_blank(),
          axis.text = element_text(size = 12)) +
   #scale_x_discrete("Nitrate Level", labels=c("0-6uM","6-10uM","10-20uM","10uM"))+
    labs(x = "nitrate Dose", 
         y = expression(paste("Absolute Rate O2 Consumption (umol*min"^"-1"~"*cm"^"2"~")")), 
         caption = "data represent mean +/- SEM" ) +
 ylim(0.05, 0.145) +
       # theme(legend.position="none")+
  scale_color_manual("Symbiotic state", labels=c("Aposymbiotic","Symbiotic"), values=c("gray", "brown"))
gg_nitrate_NOEC_30C

# # E COLI AT 30C
resp_EC_30C <- resp_all.data %>%
  filter(e_coli_plate==1 & temp==30)
resp_EC_30C$sym_state<- as.factor(resp_EC_30C$sym_state)
sum_nitrate_EC_30C<- summarySE(resp_EC_30C, measurevar = "abs_resp_rate_SA_corr", groupvars = c("sym_state", "NO3_category"))
# Visualize
gg_nitrate_EC_30C <-ggplot(data = sum_nitrate_EC_30C,
       aes(x = NO3_category,
           y = abs_resp_rate_SA_corr, col=sym_state)) +
    geom_point() +
    geom_errorbar(aes(ymin=abs_resp_rate_SA_corr-se, ymax=abs_resp_rate_SA_corr+se), width=0.35, size = 1) +
    ggtitle ("nitrate E. Coli 30C - Sym state by Dose") +
    theme(legend.position = "right",
          legend.title = element_text(size=12),
          axis.title = element_text(size = 10),
          legend.background = element_blank(),
          panel.grid.major = element_blank(), 
          panel.grid.minor = element_blank(),
          axis.text = element_text(size = 12)) +
   #scale_x_discrete("Nitrate Level", labels=c("0-6uM","6-10uM","10-20uM","10uM"))+
    labs(x = "nitrate Dose", 
         y = expression(paste("Absolute Rate O2 Consumption (umol*min"^"-1"~"*cm"^"2"~")")), 
         caption = "data represent mean +/- SEM" ) +
    ylim(0.05, 0.2) +
       # theme(legend.position="none")+
  scale_color_manual("Symbiotic state", labels=c("Aposymbiotic","Symbiotic"), values=c("gray", "brown"))
gg_nitrate_EC_30C


# # By temperature
resp_NOEC <- resp_all.data %>%
  filter(e_coli_plate==0)
resp_NOEC$sym_state<- as.factor(resp_NOEC$sym_state)
resp_NOEC$temp<- as.factor(resp_NOEC$temp)
sum_nitrate_NOEC<- summarySE(resp_NOEC, measurevar = "abs_resp_rate_SA_corr", groupvars = c("NO3_category", "temp"))
# Visualize
gg_nitrate_NOEC <-ggplot(data = sum_nitrate_NOEC,
       aes(x = NO3_category,
           y = abs_resp_rate_SA_corr, col=temp)) +
    geom_point() +
    geom_errorbar(aes(ymin=abs_resp_rate_SA_corr-se, ymax=abs_resp_rate_SA_corr+se), width=0.35, size = 1) +
    ggtitle ("nitrate NO E. Coli - Temperature by Dose") +
    theme(legend.position = "right",
          legend.title = element_text(size=12),
          axis.title = element_text(size = 10),
          legend.background = element_blank(),
          panel.grid.major = element_blank(), 
          panel.grid.minor = element_blank(),
          axis.text = element_text(size = 12)) +
   #scale_x_discrete("Nitrate Level", labels=c("0-6uM","6-10uM","10-20uM","10uM"))+
    labs(x = "nitrate Dose", 
         y = expression(paste("Absolute Rate O2 Consumption (umol*min"^"-1"~"*cm"^"2"~")")), 
         caption = "data represent mean +/- SEM" ) +
       # theme(legend.position="none")+
      ylim(0.05, 0.145) +
  scale_color_manual("Temperature", labels=c("20°C","30°C"), values=c("dodgerblue", "red3"))
gg_nitrate_NOEC 

# # By temp with E. coli
resp_EC <- resp_all.data %>%
  filter(e_coli_plate==1)
#resp_EC$NO3_category <- factor(resp_EC$NO3_category, levels=c(0,5,7.5,10))
resp_EC$sym_state<- as.factor(resp_EC$sym_state)
resp_EC$temp<- as.factor(resp_EC$temp)
sum_nitrate_EC<- summarySE(resp_EC, measurevar = "abs_resp_rate_SA_corr", groupvars = c("NO3_category", "temp"))
# Visualize
gg_nitrate_EC <-ggplot(data = sum_nitrate_EC,
       aes(x = NO3_category,
           y = abs_resp_rate_SA_corr, col=temp)) +
    geom_point() +
    geom_errorbar(aes(ymin=abs_resp_rate_SA_corr-se, ymax=abs_resp_rate_SA_corr+se), width=0.35, size = 1) +
    ggtitle ("nitrate E. Coli - Temperature by Dose") +
    theme(legend.position = "right",
          legend.title = element_text(size=12),
          axis.title = element_text(size = 10),
          legend.background = element_blank(),
          panel.grid.major = element_blank(), 
          panel.grid.minor = element_blank(),
          axis.text = element_text(size = 12)) +
   #scale_x_discrete("Nitrate Level", labels=c("0-6uM","6-10uM","10-20uM","10uM"))+
    labs(x = "nitrate Dose", 
         y = expression(paste("Absolute Rate O2 Consumption (umol*min"^"-1"~"*cm"^"2"~")")), 
         caption = "data represent mean +/- SEM" ) +
       # theme(legend.position="none")+
      ylim(0.05, 0.3) +
  scale_color_manual("Temperature", labels=c("20°C","30°C"), values=c("dodgerblue", "red3"))
gg_nitrate_EC 


############# ADDING FEEDING STATE AS A SHAPE
# # NO E COLI AT 20C
sum_nitrate_NOEC_20C_food <- summarySE(resp_NOEC_20C, measurevar = "abs_resp_rate_SA_corr", groupvars = c("sym_state", "NO3_category", "food"))
# Visualize
gg_nitrate_NOEC_20C_food <-ggplot(data = sum_nitrate_NOEC_20C_food,
       aes(x = NO3_category,
           y = abs_resp_rate_SA_corr, col=sym_state, shape=food)) +
    geom_point(size=5, position=position_dodge(width=0.5)) +
    geom_errorbar(aes(ymin=abs_resp_rate_SA_corr-se, ymax=abs_resp_rate_SA_corr+se), width=0.35, size = 1, position=position_dodge(width=0.5)) +
    ggtitle ("nitrate NO E. Coli 20C - Sym state by Dose") +
    theme(legend.position = "right",
          legend.title = element_text(size=12),
          axis.title = element_text(size = 10),
          legend.background = element_blank(),
          panel.grid.major = element_blank(), 
          panel.grid.minor = element_blank(),
          axis.text = element_text(size = 12)) +
   #scale_x_discrete("Nitrate Level", labels=c("0-6uM","6-10uM","10-20uM","10uM"))+
    labs(x = "nitrate Dose", 
         y = expression(paste("Absolute Rate O2 Consumption (umol*min"^"-1"~"*cm"^"2"~")")), 
         caption = "data represent mean +/- SEM" ) +
   ylim(0.04, 0.165) +
       # theme(legend.position="none")+
  scale_color_manual("Symbiotic state", labels=c("Aposymbiotic","Symbiotic"), values=c("gray", "brown"))+
scale_shape_discrete(labels=c("Fed","Starved"),name="Nutritional State")
gg_nitrate_NOEC_20C_food

# # E COLI AT 20C
sum_nitrate_EC_20C_food<- summarySE(resp_EC_20C, measurevar = "abs_resp_rate_SA_corr", groupvars = c("sym_state", "NO3_category","food"))
# Visualize
gg_nitrate_EC_20C_food <-ggplot(data = sum_nitrate_EC_20C_food,
       aes(x = NO3_category,
           y = abs_resp_rate_SA_corr, col=sym_state, shape=food)) +
   geom_point(size=5, position=position_dodge(width=0.5)) +
    geom_errorbar(aes(ymin=abs_resp_rate_SA_corr-se, ymax=abs_resp_rate_SA_corr+se), width=0.35, size = 1, position=position_dodge(width=0.5)) +
    ggtitle ("nitrate E. Coli 20C - Sym state by Dose") +
    theme(legend.position = "right",
          legend.title = element_text(size=12),
          axis.title = element_text(size = 10),
          legend.background = element_blank(),
          panel.grid.major = element_blank(), 
          panel.grid.minor = element_blank(),
          axis.text = element_text(size = 12)) +
   #scale_x_discrete("Nitrate Level", labels=c("0-6uM","6-10uM","10-20uM","10uM"))+
    labs(x = "nitrate Dose", 
         y = expression(paste("Absolute Rate O2 Consumption (umol*min"^"-1"~"*cm"^"2"~")")), 
         caption = "data represent mean +/- SEM" ) +
 ylim(0.04, 0.165) +
       # theme(legend.position="none")+
  scale_color_manual("Symbiotic state", labels=c("Aposymbiotic","Symbiotic"), values=c("gray", "brown"))+
scale_shape_discrete(labels=c("Fed","Starved"),name="Nutritional State")
gg_nitrate_EC_20C_food

# # NO E COLI AT 30C
sum_nitrate_NOEC_30C_food<- summarySE(resp_NOEC_30C, measurevar = "abs_resp_rate_SA_corr", groupvars = c("sym_state", "NO3_category","food"))
# Visualize
gg_nitrate_NOEC_30C_food <-ggplot(data = sum_nitrate_NOEC_30C_food,
       aes(x = NO3_category,
           y = abs_resp_rate_SA_corr, col=sym_state, shape=food)) +
   geom_point(size=5, position=position_dodge(width=0.5)) +
    geom_errorbar(aes(ymin=abs_resp_rate_SA_corr-se, ymax=abs_resp_rate_SA_corr+se), width=0.35, size = 1, position=position_dodge(width=0.5)) +
    ggtitle ("nitrate NO E. Coli 30C - Sym state by Dose") +
    theme(legend.position = "right",
          legend.title = element_text(size=12),
          axis.title = element_text(size = 10),
          legend.background = element_blank(),
          panel.grid.major = element_blank(), 
          panel.grid.minor = element_blank(),
          axis.text = element_text(size = 12)) +
   #scale_x_discrete("Nitrate Level", labels=c("0-6uM","6-10uM","10-20uM","10uM"))+
    labs(x = "nitrate Dose", 
         y = expression(paste("Absolute Rate O2 Consumption (umol*min"^"-1"~"*cm"^"2"~")")), 
         caption = "data represent mean +/- SEM" ) +
 ylim(0.04, 0.165) +
       # theme(legend.position="none")+
  scale_color_manual("Symbiotic state", labels=c("Aposymbiotic","Symbiotic"), values=c("gray", "brown"))+
scale_shape_discrete(labels=c("Fed","Starved"),name="Nutritional State")
gg_nitrate_NOEC_30C_food

# # E COLI AT 30C
sum_nitrate_EC_30C_food<- summarySE(resp_EC_30C, measurevar = "abs_resp_rate_SA_corr", groupvars = c("sym_state", "NO3_category", "food"))
# Visualize
gg_nitrate_EC_30C_food <-ggplot(data = sum_nitrate_EC_30C_food,
       aes(x = NO3_category,
           y = abs_resp_rate_SA_corr, col=sym_state, shape=food)) +
    geom_point(size=5, position=position_dodge(width=0.5)) +
    geom_errorbar(aes(ymin=abs_resp_rate_SA_corr-se, ymax=abs_resp_rate_SA_corr+se), width=0.35, size = 1, position=position_dodge(width=0.5)) +
    ggtitle ("nitrate E. Coli 30C - Sym state by Dose") +
    theme(legend.position = "right",
          legend.title = element_text(size=12),
          axis.title = element_text(size = 10),
          legend.background = element_blank(),
          panel.grid.major = element_blank(), 
          panel.grid.minor = element_blank(),
          axis.text = element_text(size = 12)) +
   #scale_x_discrete("Nitrate Level", labels=c("0-6uM","6-10uM","10-20uM","10uM"))+
    labs(x = "nitrate Dose", 
         y = expression(paste("Absolute Rate O2 Consumption (umol*min"^"-1"~"*cm"^"2"~")")), 
         caption = "data represent mean +/- SEM" ) +
 ylim(0.04, 0.165) +
       # theme(legend.position="none")+
  scale_color_manual("Symbiotic state", labels=c("Aposymbiotic","Symbiotic"), values=c("gray", "brown"))+
scale_shape_discrete(labels=c("Fed","Starved"),name="Nutritional State")
gg_nitrate_EC_30C_food

# # By temperature
sum_nitrate_NOEC_food<- summarySE(resp_NOEC, measurevar = "abs_resp_rate_SA_corr", groupvars = c("NO3_category", "temp", "food"))
# Visualize
gg_nitrate_NOEC_food <-ggplot(data = sum_nitrate_NOEC_food,
       aes(x = NO3_category,
           y = abs_resp_rate_SA_corr, col=temp, shape=food)) +
    geom_point(size=5, position=position_dodge(width=0.5)) +
    geom_errorbar(aes(ymin=abs_resp_rate_SA_corr-se, ymax=abs_resp_rate_SA_corr+se), width=0.35, size = 1, position=position_dodge(width=0.5)) +
    ggtitle ("nitrate NO E. Coli - Temperature by Dose") +
    theme(legend.position = "right",
          legend.title = element_text(size=12),
          axis.title = element_text(size = 10),
          legend.background = element_blank(),
          panel.grid.major = element_blank(), 
          panel.grid.minor = element_blank(),
          axis.text = element_text(size = 12)) +
   #scale_x_discrete("Nitrate Level", labels=c("0-6uM","6-10uM","10-20uM","10uM"))+
    labs(x = "nitrate Dose", 
         y = expression(paste("Absolute Rate O2 Consumption (umol*min"^"-1"~"*cm"^"2"~")")), 
         caption = "data represent mean +/- SEM" ) +
  scale_shape_discrete(labels=c("Fed","Starved"),name="Nutritional State") +
       # theme(legend.position="none")+
   ylim(0.04, 0.165) +
  scale_color_manual("Temperature", labels=c("20°C","30°C"), values=c("dodgerblue", "red3"))
gg_nitrate_NOEC_food

# # By temp with E. coli
sum_nitrate_EC_food<- summarySE(resp_EC, measurevar = "abs_resp_rate_SA_corr", groupvars = c("NO3_category", "temp","food"))
# Visualize
gg_nitrate_EC <-ggplot(data = sum_nitrate_EC_food,
       aes(x = NO3_category,
           y = abs_resp_rate_SA_corr, col=temp, shape=food)) +
    geom_point(size=5, position=position_dodge(width=0.5)) +
    geom_errorbar(aes(ymin=abs_resp_rate_SA_corr-se, ymax=abs_resp_rate_SA_corr+se), width=0.35, size = 1, position=position_dodge(width=0.5)) +
    ggtitle ("nitrate E. Coli - Temperature by Dose") +
    theme(legend.position = "right",
          legend.title = element_text(size=12),
          axis.title = element_text(size = 10),
          legend.background = element_blank(),
          panel.grid.major = element_blank(), 
          panel.grid.minor = element_blank(),
          axis.text = element_text(size = 12)) +
   #scale_x_discrete("Nitrate Level", labels=c("0-6uM","6-10uM","10-20uM","10uM"))+
    labs(x = "nitrate Dose", 
         y = expression(paste("Absolute Rate O2 Consumption (umol*min"^"-1"~"*cm"^"2"~")")), 
         caption = "data represent mean +/- SEM" ) +
       # theme(legend.position="none")+
      ylim(0.04, 0.165) +
  scale_shape_discrete(labels=c("Fed","Starved"),name="Nutritional State") +
  scale_color_manual("Temperature", labels=c("20°C","30°C"), values=c("dodgerblue", "red3"))
gg_nitrate_EC 
```

