---
title: "RGB_COMBINED"
author: "CFI"
date: "2024-06-24"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r Install required packages}
require("knitr")

#install.packages("lmerTest")
library("lmerTest")
#install.packages("Matrix")
library("Matrix")
#install.packages("lme4")
library("lme4")
#install.packages("emmeans")
library("emmeans")
#install.packages("pbkrtest")
library("pbkrtest")
library("tidyverse")
library(tidyverse)
library("performance")
#install.packages("see")
library("see")
#install.packages("ggrepel")
library("ggrepel")
#install.packages("sjPlot") #for visualizing linear models
library(sjPlot)
#install.packages("MASS")
library(MASS)
#install.packages("glmmTMB") # for visualizing model checks
library(glmmTMB)
#install.packages("relaimpo") #for quantifying the effects of predictor variables
library(relaimpo)
#install.packages("outliers") #for checking out whether a data point is an outlier
library(outliers)
library(Rmisc)
#install.packages("ggeffects")
library(ggeffects)
library(forestmodel)

#turn off scientific notation
options(scipen=999)

#let dplyr print a bunch of numbers
options(dplyr.print_max = 1e9)
options(max.print = 10000)   

```




```{r Set working directory and upload data - nitrate DATA ONLY}
# RGB_preprocess.data <- read.csv("C:/Users/carol/OneDrive/Documents/PhD Boston University 2019-/Astrangia_nutrient_stressors_Rotjan_lab/Data/RGB_ALL_Recomputted_dead_deleted_5_19_24.csv", header=TRUE, sep=",",stringsAsFactors = FALSE)
# 
# 
# #Create a NEW column for nitrate with new categories
# 
# RGB_preprocess.data <- RGB_preprocess.data %>%
#   mutate(NO3_category = case_when(
#    NO3_mean_observed < 6  ~ "Low" , #need two equal signs
#      NO3_mean_observed >= 6 ~ "Elevated" 
#    )
# )
# 
# 
# 
# #any single datapoint that was over 4 times disparate of mean or median from rest of treatment was discarded
#
# ^ did all that pre-processing then confirmed duplicates in excel spreadhseet. Now we can just read the csv

#QCed and all dead HAVE BEEN deleted, all IDs agree between RGB, RGB, and survival --6.26.24
RGB_all.data<- read.csv("/Users/carolineianniello/Astrangia_Ecotox/Data/RGB_recomputed_dead_deleted_combined_NO3categorized_6_26_24.csv", header=TRUE, sep=",",stringsAsFactors = FALSE)

count(RGB_all.data$NO3_category)
#188 elevated observations
#741 low observations





```

```{r Difference between RGB and survival - SORTED}
# #add survival data to see what observations are missing
# survival_all.data<- read.csv("C:/Users/carol/OneDrive/Documents/PhD Boston University 2019-/Astrangia_nutrient_stressors_Rotjan_lab/Data/Survival_06_26_24.csv", header=TRUE, sep=",",stringsAsFactors = FALSE)
# 
# 
# in_survival_not_RGB <- survival_all.data %>% 
#       filter(!survival_all.data$beetag_exprun %in% RGB_all.data$beetag_exprun) #RGBs not in survival
# notinRGB_butinsurvival <- data.frame(count(in_survival_not_RGB$beetag_exprun))
# #For df1 values not in df2
# 
# in_RGB_not_survival <- RGB_all.data %>% 
#       filter(!RGB_all.data$beetag_exprun %in% survival_all.data$beetag_exprun) #survivals not in RGB
# notinsurvival_RGB <- data.frame(count(in_RGB_not_survival$beetag_exprun))
# 
# 
# write.csv(notinRGB_butinsurvival, "C:/Users/carol/OneDrive/Documents/PhD Boston University 2019-/Astrangia_nutrient_stressors_Rotjan_lab/Data/notinRGB_butinsurvival.csv")
# 
# write.csv(notinsurvival_RGB, "C:/Users/carol/OneDrive/Documents/PhD Boston University 2019-/Astrangia_nutrient_stressors_Rotjan_lab/Data/notinsurvival_RGB.csv")
```

```{r Generating subsets to work with}

RGB_all.data$NO3_category <- factor(RGB_all.data$NO3_category, levels=c("Low", "Elevated"))
RGB_all.data$sym_state<- as.factor(RGB_all.data$sym_state)
RGB_all.data$food<- as.factor(RGB_all.data$food)
RGB_all.data$temp<- as.factor(RGB_all.data$temp)
#SUBSET - 20C
RGB_20 <- RGB_all.data %>%
  filter(temp==20)
#SUBSET - 30C
RGB_30 <- RGB_all.data %>%
  filter(temp==30)






```

```{r T tests}
#selected t tests

#Nitrate category
t.test(red_delta ~ NO3_category, data= RGB_all.data)
#no diff
t.test(red_delta ~ NO3_category, data= RGB_20)
#no diff
t.test(red_delta ~ NO3_category, data= RGB_30)
#no diff

#Sym state
t.test(red_delta ~ sym_state, data= RGB_all.data)
#no diff
t.test(red_delta ~ sym_state, data= RGB_20)
#no diff
t.test(red_delta ~ sym_state, data= RGB_30)
#no diff


#Food
t.test(red_delta ~ food, data= RGB_all.data)
#no diff
t.test(red_delta ~ food, data= RGB_20)
#no diff
t.test(red_delta ~ food, data= RGB_30)
#no diff


#Temp
t.test(red_delta ~ temp, data= RGB_all.data)
#corals in 30C overall gained, corals in 20C overall lost (makes sense re: sym phys)


#Nothing seems to matter! Slay
```

```{r ANOVAs to match graphs}
hist(RGB_all.data$red_delta) #nice and normal

#Now an ANOVA on sym state, temp, and NO3_category 
anova_RGB <- aov(red_delta ~ sym_state*temp*NO3_category, data=RGB_all.data)
summary(anova_RGB )
#ptemp = 0.0146
TukeyHSD(anova_RGB )


```


#For Manuscript
```{r}

#Summarize all treatments by SYM STATE and temp
# SYM STAAAATE
sum_day1_temp_sym <- summarySE(RGB_all.data, measurevar = c("red_day1"), groupvars = c("sym_state", "temp", "NO3_category"))
sum_day1_temp_sym$day <- 1
sum_day1_temp_sym$red <- sum_day1_temp_sym$red_day1

sum_day11_temp_sym <- summarySE(RGB_all.data, measurevar = c("red_day11"), groupvars = c("sym_state", "temp", "NO3_category"))
sum_day11_temp_sym$day <- 11
sum_day11_temp_sym$red <- sum_day11_temp_sym$red_day11


RGB_day1_11_summary <- full_join(sum_day1_temp_sym, sum_day11_temp_sym)
RGB_day1_11_summary$day <- as.factor(RGB_day1_11_summary$day)
RGB_day1_11_summary$day_NO3 <- paste(RGB_day1_11_summary$NO3_category, RGB_day1_11_summary$day, sep="_")

RGB_day1_11_summary_BACKGROUND <- subset(RGB_day1_11_summary, RGB_day1_11_summary$NO3_category=="Low")

RGB_day1_11_summary_ELEVATED <- subset(RGB_day1_11_summary, RGB_day1_11_summary$NO3_category=="Elevated")

#FOOOOD
sum_day1_temp_food <- summarySE(RGB_all.data, measurevar = c("red_day1"), groupvars = c("food", "temp", "NO3_category"))
sum_day1_temp_food$day <- 1
sum_day1_temp_food$red <- sum_day1_temp_food$red_day1

sum_day11_temp_food <- summarySE(RGB_all.data, measurevar = c("red_day11"), groupvars = c("food", "temp", "NO3_category"))
sum_day11_temp_food$day <- 11
sum_day11_temp_food$red <- sum_day11_temp_food$red_day11


RGB_day1_11_summary_food <- full_join(sum_day1_temp_food, sum_day11_temp_food)
RGB_day1_11_summary_food$day <- as.factor(RGB_day1_11_summary_food$day)
RGB_day1_11_summary_food$day_NO3 <- paste(RGB_day1_11_summary_food$NO3_category, RGB_day1_11_summary_food$day, sep="_")

RGB_day1_11_summary_BACKGROUND <- subset(RGB_day1_11_summary_food, RGB_day1_11_summary_food$NO3_category=="Low")

RGB_day1_11_summary_ELEVATED <- subset(RGB_day1_11_summary_food, RGB_day1_11_summary_food$NO3_category=="Elevated")
```

```{r Separating symbiotic and aposymbiotic}

#subset just apo from RGB_day1_11_summary
RGB_day1_11_summary_APO <- RGB_day1_11_summary %>% 
filter(sym_state=="A")

RGB_day1_11_summary_APO$temp <-as.factor(RGB_day1_11_summary_APO$temp)
RGB_day1_11_summary_APO$NO3_category <-as.factor(RGB_day1_11_summary_APO$NO3_category)

gg_apo_RGB <- ggplot(data = RGB_day1_11_summary_APO,
                           aes(x = day_NO3,
                               y = red, col = temp, shape = sym_state, group = interaction(temp, NO3_category))) +  # Group by sym_state, temp, and NO3_category
  geom_point(size = 4.5, position = position_dodge(width = 0.45)) +
  geom_errorbar(aes(ymin = red - se, ymax = red + se), width = 0.455, linewidth = 0.8, position = position_dodge(width = 0.45)) +  # Keep solid error bars
  geom_line(aes(linetype = "Dotted line"), linewidth = 1, position = position_dodge(width = 0.45)) +  # Dotted lines and include in the legend
  geom_vline(xintercept = 2.5, color = "black", linetype = "solid", size = 1) +  # Black line separating NO3 categories
  theme_classic() +
  theme(legend.position = "none",  # Remove legend from the first plot
        axis.title.x = element_blank(),  # Remove x-axis label from top plot
        axis.text.x = element_blank(),  # Remove x-axis text from top plot
        axis.ticks.x = element_blank(), # Remove x-axis ticks from top plot
        axis.title = element_text(size = 18),
        axis.text = element_text(size = 18, hjust = 1),
        axis.title.y = element_blank(),
        text = element_text(family = "serif", size = 20)) +
  ylim(125,170) +
  scale_color_manual("Temperature", labels = c("20°C", "29°C"), values = c("dodgerblue", "darkred")) +
  scale_linetype_manual(" ", values = "dotted", labels=c("Change over time")) +  # Set dotted line in the legend
  theme(aspect.ratio = 0.75)

gg_apo_RGB

#subset just sym from RGB_day1_11_summary
RGB_day1_11_summary_sym <- RGB_day1_11_summary %>% 
filter(sym_state=="S")
RGB_day1_11_summary_sym$temp <-as.factor(RGB_day1_11_summary_sym$temp)
RGB_day1_11_summary_sym$NO3_category <-as.factor(RGB_day1_11_summary_sym$NO3_category)


gg_sym_RGB <- ggplot(data = RGB_day1_11_summary_sym,
                           aes(x = day_NO3,
                               y = red, col = temp, shape = sym_state, group = interaction(temp, NO3_category))) +  # Group by sym_state, temp, and NO3_category
  geom_point(shape=17, size = 4.5, position = position_dodge(width = 0.45)) +
  geom_errorbar(aes(ymin = red - se, ymax = red + se), width = 0.455, linewidth = 0.8, position = position_dodge(width = 0.45)) +  # Keep solid error bars
  geom_line(aes(linetype = "Dotted line"), linewidth = 1, position = position_dodge(width = 0.45)) +  # Dotted lines and include in the legend
  geom_vline(xintercept = 2.5, color = "black", linetype = "solid", size = 1) +  # Black line separating NO3 categories
  theme_classic() +
  theme(legend.position = "none",  # Remove legend from the first plot
        axis.title = element_text(size = 18),
        axis.text = element_text(size = 18, hjust = 1),
        axis.title.y = element_blank(),
        text = element_text(family = "serif", size = 20)) +
   scale_x_discrete("Day", labels = c("1", "11", "1", "11")) +
 ylim(125,170) +
  scale_color_manual("Temperature", labels = c("20°C", "29°C"), values = c("dodgerblue", "darkred")) +
  scale_linetype_manual(" ", values = "dotted", labels=c("Change over time")) +  # Set dotted line in the legend
  theme(aspect.ratio = 0.75)

gg_sym_RGB


# Combine the two plots with space in between
gg_RGB_apo_sym <- gg_apo_RGB / plot_spacer() / gg_sym_RGB  +  # Add plot_spacer() between the plots
  plot_layout(guides = "collect", heights = c(1, 0.1, 1)) &  # Adjust the height of the spacer
  theme(legend.position = "right")  # Keep legend on the right

# Display the combined plot
gg_RGB_apo_sym

# Save the plot
ggsave(file="Figures/gg_RGB_apo_sym.svg", plot=gg_RGB_apo_sym, device='svg')
ggsave(file="Figures/gg_RGB_apo_sym.png", plot=gg_RGB_apo_sym)
```




```{r Sym state AND feeding DUAL}

RGB_day1_11_summary$temp <- as.factor(RGB_day1_11_summary$temp)

gg_sym_state_RGB <- ggplot(data = RGB_day1_11_summary,
                           aes(x = day_NO3,
                               y = red, col = temp, shape = sym_state, group = interaction(sym_state, temp, NO3_category))) +  # Group by sym_state, temp, and NO3_category
  geom_point(size = 4.5, position = position_dodge(width = 0.45)) +
  geom_errorbar(aes(ymin = red - se, ymax = red + se), width = 0.455, linewidth = 0.8, position = position_dodge(width = 0.45)) +  # Keep solid error bars
  geom_line(aes(linetype = "Dotted line"), linewidth = 1, position = position_dodge(width = 0.45)) +  # Dotted lines and include in the legend
  geom_vline(xintercept = 2.5, color = "black", linetype = "solid", size = 1) +  # Black line separating NO3 categories
  theme_classic() +
  theme(legend.position = "none",  # Remove legend from the first plot
        axis.title.x = element_blank(),  # Remove x-axis label from top plot
        axis.text.x = element_blank(),  # Remove x-axis text from top plot
        axis.ticks.x = element_blank(), # Remove x-axis ticks from top plot
        axis.title = element_text(size = 18),
        axis.text = element_text(size = 18, hjust = 1),
        axis.title.y = element_blank(),
        text = element_text(family = "serif", size = 20)) +
 ylim(125, 170) +
  scale_shape_discrete("Symbiotic state", labels = c("Aposymbiotic", "Symbiotic")) +
  scale_color_manual("Temperature", labels = c("20°C", "29°C"), values = c("dodgerblue", "darkred")) +
  scale_linetype_manual(" ", values = "dotted", labels=c("Change over time")) +  # Set dotted line in the legend
  theme(aspect.ratio = 0.75)

gg_sym_state_RGB

RGB_day1_11_summary_food$temp <- as.factor(RGB_day1_11_summary_food$temp)
gg_food_RGB <- ggplot(data = RGB_day1_11_summary_food,
                      aes(x = day_NO3,
                          y = red, col = temp, shape = food, group = interaction(food, temp, NO3_category))) +  # Group by food, temp, and NO3_category
  geom_point(aes(fill=temp),size = 4.5, position = position_dodge(width = 0.45)) +
  geom_errorbar(aes(ymin = red - se, ymax = red + se), width = 0.455, linewidth = 0.8, position = position_dodge(width = 0.45)) +  # Keep solid error bars
  geom_line(aes(linetype = "Dotted line"), linewidth = 1, position = position_dodge(width = 0.45)) +  # Dotted lines and include in the legend
  geom_vline(xintercept = 2.5, color = "black", linetype = "solid", size = 1) +  # Black line separating NO3 categories
  theme_classic() +
  theme(legend.position = "right",  # Keep legend in second plot
        axis.title.x = element_blank(),
        axis.title.y = element_blank(),  # Remove y-axis label from bottom plot
        axis.text = element_text(size = 18),
        axis.text.x = element_text(size = 18, vjust = -1),
        text = element_text(family = "serif", size = 20)) +
 ylim(125, 170) +
  scale_x_discrete("Day", labels = c("1", "11", "1", "11")) +
  labs(x = "Day",
       y = expression(paste("Mean Fv/Fm"))) +
  scale_shape_manual("Feeding treatment", labels = c("Fed", "Starved"), values = c(15, 25)) +
  scale_color_manual("Temperature", labels = c("20°C", "29°C"), values = c("dodgerblue", "darkred")) +
  scale_fill_manual(values = c("dodgerblue", "darkred")) +
  scale_linetype_manual(" ", values = "dotted", labels=c("Change over time")) +  # Set dotted line in the legend
  theme(aspect.ratio = 0.75)

gg_food_RGB


# Combine the two plots with space in between
gg_RGB_DELTA <- gg_sym_state_RGB / plot_spacer() / gg_food_RGB +  # Add plot_spacer() between the plots
  plot_layout(guides = "collect", heights = c(1, 0.1, 1)) &  # Adjust the height of the spacer
  theme(legend.position = "right")  # Keep legend on the right

# Display the combined plot
gg_RGB_DELTA

# Save the plot
ggsave(file="Figures/gg_RGB_DELTA.svg", plot=gg_RGB_DELTA, device='svg')
ggsave(file="Figures/gg_RGB_DELTA.png", plot=gg_RGB_DELTA)





```


