---
title: "Survival - Kaplan Meier"
author: "CFI"
date: "2024-06-12"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r Loading all necessary packages}

#install.packages("dplyr")
#compare with and without predictor
library("lme4")
#install.packages("lmerTest")
library("lmerTest")
#install.packages("emmeans")
library("emmeans")
#install.packages("pbkrtest")
library("pbkrtest")
#reshape melts our datasets in the way we want
library("reshape2")
library("dplyr")
library("plyr")
library("tidyverse")
library("Rmisc")
library("ggplot2")
#multiple response variables 
#check model with performance package
  #model tools R markdown
  #check for colinearity
  #r squared figures
#install.packages("performance")
#install.packages(c("rlang", "ggplot2", "performance", "dplyr", "ggrepel", "see"), dependencies = TRUE)
library("performance")
#install.packages("see")
library("see")
#install.packages("ggrepel")
library("ggrepel")
#install.packages("sjPlot") #for visualizing linear models
library(sjPlot)
library(MASS)
library(car)
library(outliers)
#gg effects
library(ggpubr)
#install.packages("ggpmisc")
library("ggpmisc")
library(devtools)
source_gist("524eade46135f6348140") #for the stat_smooth_func()
#install.packages("survival")
library(survival)
#install.packages("glmnet")
library(glmnet)
#install.packages("survminer")
library(survminer)


#increase the number of results it will show
options(max.print=1000000)
```



```{r upload data}
survival_all.data <- read.csv("/Users/carolineianniello/Astrangia_Ecotox/Data/Survival_06_26_24.csv", header=TRUE, sep=",",stringsAsFactors = FALSE)

# #Create a NEW column for nitrate with new categories

survival_all.data <- survival_all.data %>%
   mutate(NO3_category = case_when(
    NO3_mean_observed < 6  ~ "Background" , #need two equal signs
      NO3_mean_observed >= 6 ~ "Elevated" 
    )
 )

#make a table of deaths at end of experiment
#number alive v number dead in each treatment
#Treatment
survival_all.data$treatment <- paste(survival_all.data$NO3_category, survival_all.data$temp, survival_all.data$sym_state, survival_all.data$food,sep="_")

survival_all.data_fortable <- survival_all.data %>%
  group_by(treatment,  survival_day12)%>%
  tally()


total_n <- survival_all.data %>%
  group_by(treatment)%>%
  tally()
```

```{r Pivot long to get each row have a survival for each coral}

#long data to deal with repeated measures
survival_all.data <- survival_all.data %>%
  pivot_longer(
    cols = starts_with("survival_day"),
    names_to = "Day",
    values_to = "Death"
  )

#change Day to either 1-12
survival_all.data <- survival_all.data %>% mutate(Day = case_when(
    Day=="survival_day1" ~ 1 , 
    Day=="survival_day2" ~ 2 , 
    Day=="survival_day3" ~ 3 , 
    Day=="survival_day4" ~ 4 , 
    Day=="survival_day5" ~ 5 , 
    Day=="survival_day6" ~ 6 , 
    Day=="survival_day7" ~ 7 , 
    Day=="survival_day8" ~ 8 , 
    Day=="survival_day9" ~ 9 , 
    Day=="survival_day10" ~ 10 , 
    Day=="survival_day11" ~ 11 , 
    Day=="survival_day12" ~ 12))

#Treatment
survival_all.data$treatment <- paste(survival_all.data$NO3_category, survival_all.data$temp, survival_all.data$sym_state, survival_all.data$food,sep="_")

#make treatment a factor
survival_all.data$treatment<-as.factor(survival_all.data$treatment)
levels(survival_all.data$treatment)

```

```{r Survival Model}
#make things the right type
survival_all.data$temp <- as.factor(survival_all.data$temp)
survival_all.data$NO3_category <- as.factor(survival_all.data$NO3_category)
survival_all.data$food <- as.factor(survival_all.data$food)
survival_all.data$sym_state <- as.factor(survival_all.data$sym_state)

# Create a survival model to assess mortality over time by treatment with modeling data

km_fit <- survfit(Surv(Day, Death) ~ NO3_category + sym_state + temp + food, data = survival_all.data)
summary(km_fit)

#plot(km_fit, xlab = "Time", ylab = "Survival Probability", main = "Kaplan-Meier Survival Curve")

treat.mod <- coxph(Surv(Day, Death) ~ NO3_category + sym_state + temp + food, data=survival_all.data, control = coxph.control(iter.max = 1000))
# Summarize the model 
summary(treat.mod)

treat.mod_all <- coxph(Surv(Day, Death) ~ NO3_category + sym_state + temp + food + NO3_category*sym_state + NO3_category*temp + NO3_category*food + sym_state*temp + sym_state*food, data=survival_all.data)
# Summarize the model 
summary(treat.mod_all)
survival_all.data$treatment <- as.factor(survival_all.data$treatment)
levels_treatID <- data.frame(levels(survival_all.data$treatment))



```

```{r Visualizations}

#reorder factor labels first

# function to make some FANCY labels

label_treatments <- function(labels0){
  
  L_label_pieces <- str_split(labels0,pattern = "_")
  
  labels1 <- map_chr(L_label_pieces,function(v_label_piece){
    
    v_label_piece[2] <- paste0(v_label_piece[2],"°C")
    v_label_piece[3] <- switch(v_label_piece[3],A = "Apo",S = "Sym")
    v_label_piece[4] <- switch(v_label_piece[4],F = "Fed",S = "Starved")
    
    return(paste(v_label_piece,collapse = " "))
    
  })
  
  return(labels1)
}

# Plot kaplan meier survival function with ggplot
all_survfit <- survfit(Surv(Day, Death) ~ treatment, data = survival_all.data)
summary(all_survfit)


library(RColorBrewer)
#display.brewer.all()
library(viridis)

gg_survival <- ggsurvplot(all_survfit, # survival function
                conf.int = FALSE, # remove confidence intervals
                pval = FALSE, # do not include p value on plot
                surv.scale = "default", # or %
                legend.labs= c("Background nitrate 20°C Aposymbiotic Fed, n=90","Background nitrate 20°C Aposymbiotic Starved, n=105", "Background nitrate 20°C Symbiotic Fed, n=90", "Background nitrate 20°C Symboitic Starved, n=105", "Background nitrate 29°C Aposymbiotic Fed, n=107", "Background nitrate 29°C Aposymbiotic Starved, n=75","Background nitrate 29°C Symbiotic Fed, n=106","Background nitrate 29°C Symbiotic Starved, n=74", "Elevated nitrate 20°C Aposymbiotic Fed, n=30", "Elevated nitrate 20°C Aposymbiotic Starved, n=15", "Elevated nitrate 20°C Symbiotic Fed, n=30" , "Elevated nitrate 20°C Symbiotic Starved, n=15", "Elevated nitrate 29°C Aposymbiotic Fed, n=15", "Elevated nitrate 29°C Aposymbiotic Starved, n=43", "Elevated nitrate 29°C Symbiotic Fed, n=15", "Elevated nitrate 29°C Symbiotic Starved, n=45"),
                legend = c(0.3, 0.48), font.legend = 18, legend.title ="Treatment", # legend parameters 
                xlab = "Day", xlim = c(0, 12), break.x.by = 1, font.x = 18, # x axis parameters
                ylim = c(0.4,1), font.y= 18, # y axis parameters
                font.tickslab = 18,
                censor.size = 8,
           ggtheme = theme_classic2(base_family = "Times New Roman"),
           font.family = "Times New Roman",
           palette = c(
"#DB4DD6", "#9F3EEA", "#7238F0", "#0909C8", "#2949FF", "#29B0FF", "#55C2CE", "#24FFE2", "#46DD4D", "#A5FF1F", "#FFE91F", "#FEB601", "#E37A02", "#C44303", "#A51C03","#6D4C41"


))
gg_survival

ggsave(file="Figures/gg_survival.svg", print(gg_survival), device='svg')
ggsave(file="Figures/gg_survival.png", print(gg_survival))




```

```{r}
all_deaths <- survival_all.data %>%
  filter(Death==1)

all_death_table <- data.frame(count(all_deaths$treatment))

all_deaths_day12 <- survival_all.data %>%
  filter(Death==1 & Day==12)

all_death_table_day12 <- data.frame(count(all_deaths_day12$treatment))


#Now lets do a binomial regression JUST on day 5
survival_all.data_WIDE <- read.csv("C:/Users/carol/OneDrive/Documents/PhD Boston University 2019-/Astrangia_nutrient_stressors_Rotjan_lab/Data/Survival_06_12_24_for_logistic.csv", header=TRUE, sep=",",stringsAsFactors = FALSE)
survival_all.data_WIDE<- survival_all.data_WIDE %>%
  filter(N_species=="A")

survival_all.data_WIDE$temp <- as.factor(survival_all.data_WIDE$temp)
survival_all.data_WIDE$NO3_category <- as.numeric(survival_all.data_WIDE$NO3_category)
survival_all.data_WIDE$food <- as.factor(survival_all.data_WIDE$food)
survival_all.data_WIDE$sym_state <- as.factor(survival_all.data_WIDE$sym_state)
binoimal_survival_GLM <- glmer(survival_day12 ~ NO3_category + sym_state + temp + food + (1|beetag_exprun), family=binomial(link='logit'), data=survival_all.data_WIDE) #not havin it, theres only one death

```
