---
title: "PAM data AMMONIUM: last updated 12/9/22 C. Fleming"
output: html_notebook
editor_options: 
  chunk_output_type: inline
---

# AMMONIUM ONLY
```{r Loading all necessary packages}
# library("knitr")
# require("knitr")
# opts_knit$set(root.dir = "C:/Users/carol/Documents/PhD Boston University 2019-/Chapter_2_Ecotox/Summer_2022_N_Ecotox")
# setwd("C:/Users/carol/Documents/PhD Boston University 2019-/Chapter_2_Ecotox/Summer_2022_N_Ecotox")
# getwd()
#install.packages("dplyr")
#compare with and without predictor
library("lme4")
#install.packages("lmerTest")
library("lmerTest")
#install.packages("emmeans")
library("emmeans")
#install.packages("pbkrtest")
library("pbkrtest")
#reshape melts our datasets in the way we want
library("reshape2")
library("dplyr")
library("plyr")
library("tidyverse")
library("Rmisc")
library("ggplot2")
#multiple response variables 
#check model with performance package
  #model tools R markdown
  #check for colinearity
  #r squared figures
#install.packages("performance")
#install.packages(c("rlang", "ggplot2", "performance", "dplyr", "ggrepel", "see"), dependencies = TRUE)
library("performance")
#install.packages("see")
library("see")
#install.packages("ggrepel")
library("ggrepel")
#install.packages("sjPlot") #for visualizing linear models
library(sjPlot)
library(MASS)
library(car)
library(outliers)
#gg effects
library(ggpubr)
#install.packages("ggpmisc")
library("ggpmisc")
library(devtools)
source_gist("524eade46135f6348140") #for the stat_smooth_func()


#increase the number of results it will show
options(max.print=1000000)
```


```{r Inputting data & making sure everything is organized correctly}
pam_all_ammonium.data <- read.csv("PAM_ammonium_only_4_19_23_dead_deleted_random_controls.csv", header=TRUE, sep=",",stringsAsFactors = FALSE)

pam_all_ammonium.data <- na.omit(pam_all_ammonium.data)


#changing some column names
pam_all_ammonium.data<-subset(pam_all_ammonium.data, select = -c(temp))
#renaming columns in base R because dplyr is freaking out
colnames(pam_all_ammonium.data)[colnames(pam_all_ammonium.data) == "sym_state"] ="sym_state_full"
colnames(pam_all_ammonium.data)[colnames(pam_all_ammonium.data) == "sym_state.1"] ="sym_state"
colnames(pam_all_ammonium.data)[colnames(pam_all_ammonium.data) == "temp.1"] ="temp"

#Setting everything I need as factors for linear model and stats
pam_all_ammonium.data$N_species<-as.factor(pam_all_ammonium.data$N_species)
pam_all_ammonium.data$N_dose<-as.factor(pam_all_ammonium.data$N_dose)
pam_all_ammonium.data$N_species_dose<-as.factor(pam_all_ammonium.data$N_species_dose)
pam_all_ammonium.data$temp<-as.factor(pam_all_ammonium.data$temp)
pam_all_ammonium.data$food<-as.factor(pam_all_ammonium.data$food)
pam_all_ammonium.data$sym_state<-as.character(pam_all_ammonium.data$sym_state)
pam_all_ammonium.data$food_sym_state<-as.factor(pam_all_ammonium.data$food_sym_state)
pam_all_ammonium.data$N_species_dose <- factor(pam_all_ammonium.data$N_species_dose, levels=c("CNTRL_0", "A_5", "A_7.5","A_10"))
pam_all_ammonium.data$control_or_nutrient<-as.factor(pam_all_ammonium.data$control_or_nutrient)
pam_all_ammonium.data$log_pam_percent_change<-as.numeric(pam_all_ammonium.data$log_pam_percent_change)
summary(pam_all_ammonium.data$temp)
pam_all_ammonium.data$pam_percent_change<-as.numeric(pam_all_ammonium.data$pam_percent_change)
summary(pam_all_ammonium.data$temp)

#lets check for normality in pam_delta
hist(pam_all_ammonium.data$PAM_delta)
qqnorm(pam_all_ammonium.data$PAM_delta)
#looks fine, lets proceed

#lets check for normality in log_pam_percent_change
hist(pam_all_ammonium.data$log_pam_percent_change)
qqnorm(pam_all_ammonium.data$log_pam_percent_change, main = NULL)
# UGGO! Need to natural log
pam_all_ammonium.data$log_log_pam_percent_change <- log(abs(pam_all_ammonium.data$log_pam_percent_change))
#change the one with negative infinity to 0
pam_all_ammonium.data[pam_all_ammonium.data$log_log_pam_percent_change=="-Inf", "log_log_pam_percent_change"] <- 0 #yay that worked! That was messing up all of our linear models
#now lets take a look at the logged data
hist(pam_all_ammonium.data$log_log_pam_percent_change)

hist(pam_all_ammonium.data$PAM_avg_day1) # eh
qqnorm(pam_all_ammonium.data$PAM_avg_day1, main = NULL)

hist(pam_all_ammonium.data$PAM_avg_day11) # eh
qqnorm(pam_all_ammonium.data$PAM_avg_day11, main = NULL)





```

```{r lets explore whats happening with the outliers}


#now visualize
gg_outliers_check<-
  ggplot(pam_all_ammonium.data, aes(x=N_species_dose, y=PAM_delta)) +
  geom_boxplot(width=0.8) +
  geom_jitter(width=0.15, alpha=0.9) + #this overlays the raw data 
  ylab("PAM delta")+
  xlab("N dose")+
  theme(legend.position="none", plot.title = element_text(size = 9)) +
  theme(axis.text.x = element_text(angle=90, vjust=.5, hjust=1))+ #this makes the x axis labels up and down instead of side to side to prevent overlapping
 annotate("text", x = Inf, y = Inf, label = paste("  "), vjust = 1, hjust = 1, size=3)+
  ggtitle("PAM delta by dose - Ammonium")
gg_outliers_check

gg_delta_outliers_check<-
  ggplot(pam_all_ammonium.data, aes(x=N_species_dose, y=pam_percent_change, col=sym_state)) +
  geom_boxplot(width=0.8, outlier.shape = NA) +
  geom_jitter(width=0.15, alpha=0.9) + #this overlays the raw data 
  ylab("PAM percent change")+
  xlab("N dose")+
  theme(legend.position="none", plot.title = element_text(size = 9)) +
  theme(axis.text.x = element_text(angle=90, vjust=.5, hjust=1))+ #this makes the x axis labels up and down instead of side to side to prevent overlapping
 annotate("text", x = Inf, y = Inf, label = paste("  "), vjust = 1, hjust = 1, size=3)+
      scale_color_manual("Sym State",labels=c("Apo","Sym"), values=c("darkgray", "brown"))+
  ggtitle("PAM percent change - Ammonium")
gg_delta_outliers_check

gg_delta_outliers_check<-
  ggplot(pam_all_ammonium.data, aes(x=N_species_dose, y=PAM_delta, col=sym_state)) +
  geom_boxplot(width=0.8, outlier.shape = NA) +
  geom_jitter(width=0.15, alpha=0.9) + #this overlays the raw data 
  ylab("PAM percent change")+
  xlab("N dose")+
  theme(legend.position="none", plot.title = element_text(size = 9)) +
  theme(axis.text.x = element_text(angle=90, vjust=.5, hjust=1))+ #this makes the x axis labels up and down instead of side to side to prevent overlapping
 annotate("text", x = Inf, y = Inf, label = paste("  "), vjust = 1, hjust = 1, size=3)+
      scale_color_manual("Sym State",labels=c("Apo","Sym"), values=c("darkgray", "brown"))+
  ggtitle("PAM delta - Ammonium")
gg_delta_outliers_check


```


```{r Basic list of subsets}
# all aposymbiotic
all_apo<-subset(pam_all_ammonium.data, pam_all_ammonium.data$sym_state=="A")
# all symbiotic
all_sym<-subset(pam_all_ammonium.data, pam_all_ammonium.data$sym_state=="S")
# all fed
all_fed<-subset(pam_all_ammonium.data, pam_all_ammonium.data$food=="F")
# all starved
all_starved<-subset(pam_all_ammonium.data, pam_all_ammonium.data$food=="S")
# all 20C
all_20<-subset(pam_all_ammonium.data, pam_all_ammonium.data$temp=="20")
# all 30C
all_30<-subset(pam_all_ammonium.data, pam_all_ammonium.data$temp=="30")

#without controls
no_controls <- subset(pam_all_ammonium.data, pam_all_ammonium.data$N_dose!=0)
```
#DELTA visuals (no transformation)

```{r delta visuals}
#delta graph by dose by sym state
pam_treatmeans_apovsym <- summarySE(pam_all_ammonium.data, measurevar = "PAM_delta", groupvars = c("sym_state","N_species_dose"))
pam_treatmeans_apovsym$N_species_dose <- factor(pam_treatmeans_apovsym$N_species_dose, levels=c("CNTRL_0", "A_5", "A_7.5","A_10")) 
gg_pam_plot_apovsym <- ggplot(pam_treatmeans_apovsym, aes(x = N_species_dose, y= c(PAM_delta), color = sym_state))+
   geom_jitter(data= pam_all_ammonium.data, aes(x=N_species_dose, y=PAM_delta, color=sym_state), alpha=0.3) +
  geom_point() +
  geom_errorbar(aes(x = N_species_dose, ymax = PAM_delta+se, ymin = PAM_delta-se), size=1, width = .4) +
 ylab("Change in Fv/Fm")+
  ggtitle("ammonium Δ Fv/Fm")+
  scale_x_discrete("Dose", labels=c(A="Aposymbiotic", S="Symbiotic"))+ #relabels the x axis to the values in quotations
    scale_color_manual("Sym state", labels=c(A="Aposymbiotic", S="Symbiotic"), values=c("gray38", "brown")) #gives you the colors for each point on the graph
gg_pam_plot_apovsym

pam_all_treats <- summarySE(pam_all_ammonium.data, measurevar = "PAM_delta", groupvars = c("treat_ID_without_food"))
gg_pam_all_treats <- ggplot(pam_all_treats, 
      aes(x = treat_ID_without_food, y= c(PAM_delta), 
      color = treat_ID_without_food))+
      geom_jitter(data= pam_all_ammonium.data, aes(x=treat_ID_without_food,
      y=PAM_delta, color=sym_state), alpha=0.3) +
      geom_point() +
      geom_errorbar(aes(x = treat_ID_without_food, ymax = PAM_delta+se,
      ymin = PAM_delta-se), size=1, width = .4) +
      ylab("Change in Fv/Fm")+
      ggtitle("ammonium Δ Fv/Fm")+
      scale_x_discrete("Dose", labels=c(A="Aposymbiotic", S="Symbiotic")) + 
  theme(axis.text.x = element_text(angle=90, vjust=.5, hjust=1)) #this makes the x axis labels up and down instead of side to side to prevent overlapping
gg_pam_all_treats




```

#DELTA models
```{r lmer delta model selection 7.5.23}

full.model <- lmer(PAM_delta ~  N_species_dose + temp + food + sym_state + + N_species_dose*temp + N_species_dose*food + N_species_dose*sym_state + temp*food + temp*sym_state  + food*sym_state +  (1|col_num) + (1|exp_num) , data= pam_all_ammonium.data)
print(step.model<- step(full.model))

#model it selected for;

ammonium_delta_model <- lmer(PAM_delta ~ temp + sym_state + N_species_dose + (1 | col_num) + (1 | exp_num) + temp:sym_state, data= pam_all_ammonium.data)

summary(ammonium_delta_model)
plot_model(ammonium_delta_model, type="diag")
#Model actually looks decent! Let's go with this one

summary(emmeans(ammonium_delta_model, specs=pairwise ~ N_species_dose*temp*sym_state))



```


#PERCENT CHANGE MODELS
```{r PERCENT CHANGE Model selection }
#were not going to look at genetic ID so let's do an lm

#testing experiment number as random
lm_test <- lmer(log_pam_percent_change ~ temp + (1|exp_num), data=pam_all_ammonium.data)
r2(lm_test)
#doesnt impact it , its okay to leave out for now

#stepAIC is from the MASS package
fullModel = lm(log_pam_percent_change ~   N_species_dose + temp + sym_state  + N_species_dose*temp + N_species_dose*sym_state + temp*sym_state, data= pam_all_ammonium.data) # model with all 9 variables and possible combinations

nullModel = lm(log_pam_percent_change ~  1, data= pam_all_ammonium.data) # model with the intercept only

summary(stepAIC(nullModel, # start with a model containing no variables
                direction = 'forward', # run forward selection
                scope = list(upper = fullModel, # the maximum to consider is a model with all variables
                             lower = nullModel), # the minimum to consider is a model with no variables
                trace = 1)) # do not show the step-by-step process of model selection

summary(fullModel)
#model it selected for:
lm_pam_1 <- lm(formula = log_pam_percent_change ~ temp, data = pam_all_ammonium.data)
summary(lm_pam_1)
#WINNER

#lets check out some other models
lm_pam_2 <- lm(formula = log_pam_percent_change ~ temp + sym_state + temp*sym_state, data = pam_all_ammonium.data)
summary(lm_pam_2)

lm_pam_3 <- lm(formula = log_pam_percent_change ~ temp + N_species_dose, data = pam_all_ammonium.data)
summary(lm_pam_3)
#nothing really going on with dose

AIC(lm_pam_1, lm_pam_2)

#Temperature seems to be driving this model, lets go with model #1

#posthocs
summary(emmeans(lm_pam_1, pairwise ~ temp))
#0.01

plot_model(lm_pam_1, type="diag") #data fitness looks decent
r2(lm_pam_1)

# Summarize by temp and N species dose so we can visualize
sum_sym_state_temp_ammonium <- summarySE(pam_all_ammonium.data, measurevar = "pam_percent_change", groupvars = c("temp","sym_state"))
# Visualize
gg_sym_state_temp_ammonium<-ggplot(data = sum_sym_state_temp_ammonium,
       aes(x = sym_state,
           y = pam_percent_change, col=temp)) +
    geom_point() +
    geom_errorbar(aes(ymin=pam_percent_change-se, ymax=pam_percent_change+se), width=0.1, size = 1) +
    #scale_color_manual(values = c("black", "darkgreen")) +
    ggtitle ("Ammonium PAM - % Change Fv/Fm") +
    labs(x = "ammonium dose", 
         y = expression(paste("% Change Fv/Fm")), 
         caption = "data represent mean +/- SEM" ) +
    scale_x_discrete("Symbiotic state", labels=c(CNTRL_0="Control", N_1.5="1.5uM", N_5="5uM", N_18="18uM"))+
    scale_color_manual("Temperature",labels=c("20C","30C"), values=c("blue", "red"))
gg_sym_state_temp_ammonium

# generating ptemp and pdose:
summary(aov_temp<-aov(log_pam_percent_change ~ temp, data=pam_all_ammonium.data))
Anova(aov_temp, type="III")
summary(emmeans(aov_temp, specs=pairwise ~ temp))

#ptemp=0.0.01

summary(aov_temp<-aov(log_pam_percent_change ~ N_species_dose, data=pam_all_ammonium.data))
Anova(aov_temp, type="III")
summary(emmeans(aov_temp, specs=pairwise ~ N_species_dose))

#pdose=0.36

# Summarize by temp 
sum_temp_ammonium <- summarySE(pam_all_ammonium.data, measurevar = "pam_percent_change", groupvars = c("temp"))

# Visualize
gg_sum_temp_ammonium<-ggplot(data = sum_temp_ammonium,
       aes(x = temp,
           y = pam_percent_change, col=temp)) +
    geom_point() +
    geom_errorbar(aes(ymin=pam_percent_change-se, ymax=pam_percent_change+se), width=0.1, size = 1) +
    #scale_color_manual(values = c("black", "darkgreen")) +
    ggtitle ("Ammonium PAM - % Change Fv/Fm") +
    labs(x = "Temperature", 
         y = expression(paste("% Change Fv/Fm")), 
         caption = "data represent mean +/- SEM" ) +
    scale_x_discrete("Temperature", labels=c(CNTRL_0="Control", N_1.5="1.5uM", N_5="5uM", N_18="18uM"))+
    scale_color_manual("Temperature",labels=c("20C","30C"), values=c("blue", "red"))
gg_sum_temp_ammonium

summary(aov_temp<-aov(log_pam_percent_change ~ control_or_nutrient, data=pam_all_ammonium.data))
Anova(aov_temp, type="III")
#pnutrient= 0.7742

```

```{r SYM linear model}
#stepAIC is from the MASS package
fullModel = lm(log_pam_percent_change ~   N_species_dose + temp  + N_species_dose*temp, data= all_sym) # model with all 9 variables and possible combinations

nullModel = lm(log_pam_percent_change ~  1, data= all_sym) # model with the intercept only

summary(stepAIC(nullModel, # start with a model containing no variables
                direction = 'forward', # run forward selection
                scope = list(upper = fullModel, # the maximum to consider is a model with all variables
                             lower = nullModel), # the minimum to consider is a model with no variables
                trace = 1)) # do not show the step-by-step process of model selection

summary(fullModel)
# it only selected for:
lm_sym_1 <- lm(log_pam_percent_change ~  1, data= all_sym)
summary(lm_sym_1)

#lets see if we add the N_species_dose what happens
lm_sym_2 <- lm(log_pam_percent_change ~  N_species_dose, data= all_sym)
summary(lm_sym_2)
summary(emmeans(lm_sym_2, specs=pairwise ~ N_species_dose))
# temp * N species dose out
lm_sym_3 <- lm(log_pam_percent_change ~  temp + N_species_dose, data= all_sym)
summary(lm_sym_3)
# nothing really going on

AIC(lm_sym_1, lm_sym_2)

emm_sym_pam_N_species_dose_temp=emmeans(lm_sym_3, specs=pairwise ~ temp)
summary(emm_sym_pam_N_species_dose_temp)


#really no effect of dose

#graph sym only by N species dose and temperature

# Summarize by temp and N species dose so we can visualize
sum_N_species_dose_temp_ammonium <- summarySE(all_sym, measurevar = "log_pam_percent_change", groupvars = c("temp","N_species_dose"))
sum_N_species_dose_temp_ammonium$N_species_dose <- factor(sum_N_species_dose_temp_ammonium$N_species_dose, levels=c("CNTRL_0", "A_5", "A_7.5","A_10"))
# Visualize
gg_N_species_dose_temp_ammonium<-ggplot(data = sum_N_species_dose_temp_ammonium,
       aes(x = N_species_dose,
           y = log_pam_percent_change, col=temp)) +
    geom_point() +
    geom_errorbar(aes(ymin=log_pam_percent_change-se, ymax=log_pam_percent_change+se), width=0.1, size = 1) +
    #scale_color_manual(values = c("black", "darkgreen")) +
    ggtitle ("SYM CORALS ammonium PAM - % Change Fv/Fm") +
    labs(x = "ammonium dose", 
         y = expression(paste("% Change Fv/Fm")), 
         caption = "data represent mean +/- SEM" ) +
    scale_x_discrete("ammonium dose", labels=c(CNTRL_0="Control", N_1.5="1.5uM", N_5="5uM", N_18="18uM"))+
    scale_color_manual("Temperature",labels=c("20C","30C"), values=c("blue", "red"))
gg_N_species_dose_temp_ammonium



# generating ptemp and pdose:
summary(aov_temp<-aov(log_pam_percent_change ~ temp, data=all_sym))
Anova(aov_temp, type="III")
summary(emmeans(aov_temp, specs=pairwise ~ temp))

#ptemp=0.221

summary(aov_temp<-aov(log_pam_percent_change ~ N_species_dose, data=all_sym))
Anova(aov_temp, type="III")
summary(emmeans(aov_temp, specs=pairwise ~ N_species_dose))

#pdose=0.455

#ptemp * pdose
summary(aov_temp<-aov(log_pam_percent_change ~ N_species_dose*temp, data=all_sym))
Anova(aov_temp, type="III")
summary(emmeans(aov_temp, specs=pairwise ~ N_species_dose))


summary(aov_temp<-aov(log_pam_percent_change ~ control_or_nutrient, data=all_sym))
Anova(aov_temp, type="III")
#pnutrient= 0.7742
  
#food for funsies
summary(aov_food<-aov(log_pam_percent_change ~ food, data=all_sym))
Anova(aov_food, type="III")

#pfood=0.99

#food doesnt seem to matter at all
  
```

```{r APO linear model}
#stepAIC is from the MASS package
fullModel = lm(log_pam_percent_change ~ N_species_dose + temp  + N_species_dose*temp, data= all_apo) # model with all 9 variables and possible combinations

nullModel = lm(log_pam_percent_change ~  1, data= all_apo) # model with the intercept only

summary(stepAIC(nullModel, # start with a model containing no variables
                direction = 'forward', # run forward selection
                scope = list(upper = fullModel, # the maximum to consider is a model with all variables
                             lower = nullModel), # the minimum to consider is a model with no variables
                trace = 1)) # do not show the step-by-step process of model selection

summary(fullModel)

#selected for...
lm_apo_1 <- lm(log_pam_percent_change ~  temp, data= all_apo)
summary(lm_apo_1)

#lets see if we add the N_species_dose * temp what happens
lm_apo_2 <- lm(log_pam_percent_change ~  N_species_dose+temp + N_species_dose*temp, data= all_apo)
summary(lm_apo_2)
#temp is the only thing driving it really


AIC(lm_apo_1, lm_apo_2) #1 is the clear winner here-- AIC is a lot lower

#posthocs
emm_apo_temp=emmeans(lm_apo_1, specs=pairwise ~ temp)
summary(emm_apo_temp) #0.0159



# Summarize by temp and N species dose so we can visualize
sum_N_species_dose_temp_ammonium <- summarySE(all_apo, measurevar = "log_pam_percent_change", groupvars = c("temp","N_species_dose"))
sum_N_species_dose_temp_ammonium$N_species_dose <- factor(sum_N_species_dose_temp_ammonium$N_species_dose, levels=c("CNTRL_0", "A_5", "A_7.5","A_10"))
# Visualize
gg_N_species_dose_temp_ammonium<-ggplot(data = sum_N_species_dose_temp_ammonium,
       aes(x = N_species_dose,
           y = log_pam_percent_change, col=temp)) +
    geom_point() +
    geom_errorbar(aes(ymin=log_pam_percent_change-se, ymax=log_pam_percent_change+se), width=0.1, size = 1) +
    #scale_color_manual(values = c("black", "darkgreen")) +
    ggtitle ("APO CORALS ammonium PAM - % Change Fv/Fm") +
    labs(x = "ammonium dose", 
         y = expression(paste("% Change Fv/Fm")), 
         caption = "data represent mean +/- SEM" ) +
    scale_x_discrete("ammonium dose", labels=c(CNTRL_0="Control", N_1.5="1.5uM", N_5="5uM", N_18="18uM"))+
    scale_color_manual("Temperature",labels=c("20C","30C"), values=c("blue", "red"))
gg_N_species_dose_temp_ammonium

# generating ptemp and pdose:
summary(aov_temp<-aov(log_pam_percent_change ~ temp, data=all_apo))
Anova(aov_temp, type="III")
summary(emmeans(aov_temp, specs=pairwise ~ temp))

#ptemp=0.015

summary(aov_temp<-aov(log_pam_percent_change ~ N_species_dose, data=all_apo))
Anova(aov_temp, type="III")
summary(emmeans(aov_temp, specs=pairwise ~ N_species_dose))

#pdose=0.5352

summary(aov_temp<-aov(log_pam_percent_change ~ N_species_dose*temp, data=all_apo))
Anova(aov_temp, type="III")
summary(emmeans(aov_temp, specs=pairwise ~ N_species_dose*temp))

#pinteraction= 0.81

summary(aov_temp<-aov(log_pam_percent_change ~ control_or_nutrient, data=all_apo))
Anova(aov_temp, type="III")
#pnutrient= 0.81

#summarize by temp
sum_temp_ammonium <- summarySE(all_apo, measurevar = "log_pam_percent_change", groupvars = c("temp"))

# Visualize
gg_temp_ammonium<-ggplot(data = sum_temp_ammonium,
       aes(x =temp,
           y = log_pam_percent_change, col=temp)) +
    geom_point() +
    geom_errorbar(aes(ymin=log_pam_percent_change-se, ymax=log_pam_percent_change+se), width=0.1, size = 1) +
    #scale_color_manual(values = c("black", "darkgreen")) +
    ggtitle ("APO CORALS ammonium PAM - % Change Fv/Fm") +
    labs(x = "ammonium dose", 
         y = expression(paste("% Change Fv/Fm")), 
         caption = "data represent mean +/- SEM" ) +
    scale_x_discrete("Temperature", labels=c(CNTRL_0="Control", N_1.5="1.5uM", N_5="5uM", N_18="18uM"))+
    scale_color_manual("Temperature",labels=c("20C","30C"), values=c("blue", "red"))
gg_temp_ammonium


```



```{r Nutrient or control linear model CHALK TALK}

#sym full model -- not including genetic data

fullModel = lm(log_pam_percent_change ~   N_species_dose + temp + food +  N_species_dose*temp + N_species_dose*food  + temp*food, data= all_sym) # model with all 9 variables and possible combinations

nullModel = lm(log_pam_percent_change ~  1, data= all_sym) # model with the intercept only

summary(stepAIC(nullModel, # start with a model containing no variables
                direction = 'forward', # run forward selection
                scope = list(upper = fullModel, # the maximum to consider is a model with all variables
                             lower = nullModel), # the minimum to consider is a model with no variables
                trace = 1)) # do not show the step-by-step process of model selection


mm_sym<- lm(log_pam_percent_change ~  N_species_dose, data= all_sym)
summary(full.model_sym)

emm_sym=emmeans(mm_sym , specs=pairwise ~ N_species_dose)
summary(emm_sym)

summary(aov_sym<-aov(log_pam_percent_change ~ N_species_dose, data=all_sym))
TukeyHSD(aov_sym, "N_species_dose")



all_sym$N_species_dose <- factor(all_sym$N_species_dose, levels=c("CNTRL_0", "A_5", "A_7.5","A_10"))
#now plot sym corals by N species dose
# Summarize by N_species_dose so we can visualize
sum_sym_N_species_dose_ammonium <- summarySE(all_sym, measurevar = "log_pam_percent_change", groupvars = c("N_species_dose"))
# Visualize
gg_sym_N_species_dose_ammonium<-ggplot(data = sum_sym_N_species_dose_ammonium,
       aes(x = N_species_dose,
           y = log_pam_percent_change, col=N_species_dose)) +
    geom_point(size = 4) +
   theme(
  axis.text.x = element_text(size = 22),
   axis.title.x = element_text(size = 30),
  axis.text.y = element_text(size = 24),
   axis.title.y = element_text(size = 30)) +
 ylim(-.18, 0.015) +
    geom_errorbar(aes(ymin=log_pam_percent_change-se, ymax=log_pam_percent_change+se), width=0.3, size = 2) +
    #scale_color_manual(values = c("black", "darkgreen")) +
  #  ggtitle ("ammonium - N Species Dose summary for sym corals") +
   theme(legend.position="none")+
    labs(x = "\n", 
         y = expression(paste("% Change Fv/Fm"))) +
    scale_x_discrete("Dose", labels=c(CNTRL_0="Control", A_5="Ambient", A_7.5="Intermediate", A_10="High"))+
    scale_color_manual(labels=labels, values=c("blue", "orchid1","blueviolet","purple4"))
gg_sym_N_species_dose_ammonium

# Summarize by N_species_dose so we can visualize
sum_sym_temp <- summarySE(all_sym, measurevar = "log_pam_percent_change", groupvars = c("temp", "control_or_nutrient"))
# Visualize
gg_sum_sym_temp<-ggplot(data = sum_sym_temp,
       aes(x =control_or_nutrient,
           y = log_pam_percent_change, col=temp)) +
    geom_point(size=4) +
   theme(
  axis.text.x = element_text(size = 22),
   axis.title.x = element_text(size = 30),
  axis.text.y = element_text(size = 24),
   axis.title.y = element_text(size = 28)) +
 ylim(-.2, 0.1) +
    geom_errorbar(aes(ymin=log_pam_percent_change-se, ymax=log_pam_percent_change+se), width=0.3, size = 2) +
    #scale_color_manual(values = c("black", "darkgreen")) +
  #  ggtitle ("Ammonium - N Species Dose summary for sym corals") +
   theme( legend.title = element_text(size=20), legend.text = element_text(size=20))+
    labs(x = "\n", 
         y = expression(paste("% Change Fv/Fm"))) +
     scale_color_manual(" Temperature ", labels=c("20C","30C"), values=c("blue", "darkred"))
gg_sum_sym_temp



full.model_pam_nutrient_or_control<- lmer(log_pam_percent_change ~  control_or_nutrient + temp + food + sym_state + control_or_nutrient*temp + control_or_nutrient*food + control_or_nutrient*sym_state + temp*food + temp*sym_state + food*sym_state +  (1|col_num) + (1|exp_num) , data= all_sym)
summary(full.model_pam_nutrient_or_control)
print(step.model<- step(full.model_pam_nutrient_or_control))

#CONTROL OR NUTRIENT -- not significant
mm_pam_control_or_nutrient <- lmer(log_pam_percent_change  ~ control_or_nutrient + temp + food + sym_state + (1 | col_num) + (1 | exp_num), data=pam_all_ammonium.data)
summary(mm_pam_control_or_nutrient)

emm_test=emmeans(mm_pam_control_or_nutrient , specs=pairwise ~ temp*control_or_nutrient)
summary(emm_test)

tab_model(mm_pam_control_or_nutrient)
```

`

```{r Subsetting by sym state with visualizations}
#We're interested to see how sym state drives reaction to dose and temperature seperately

#Symbiotic corals
full.model_pam_ammonium_sym <- lmer(log_pam_percent_change ~  N_species_dose + temp + food +  N_species_dose*temp + N_species_dose*food + temp*food + (1|col_num) + (1|exp_num) , data= all_sym)
summary(full.model_pam_ammonium_sym )
print(step.model<- step(full.model_pam_ammonium_sym ))
#lets just add N species dose and temperature cause thats what were interested in
summary(mm_ammonium_sym <- lmer(log_pam_percent_change ~  N_species_dose + temp + (1|col_num) + (1|exp_num) , data= all_sym))
#posthoc to see differences
emm_temp_dose_sym=emmeans(mm_ammonium_sym, specs=pairwise ~ temp*N_species_dose)
summary(emm_temp_dose_sym)
 # contrast                        estimate     SE  df t.ratio p.value
 # temp20 A_10 - temp30 A_10       -0.09736 0.0280 228  -3.473  0.0141 `
 # temp30 A_10 - temp20 A_7.5       0.15775 0.0479 217   3.294  0.0250
 # temp20 A_5 - temp30 A_5         -0.09736 0.0280 228  -3.473  0.0141 `
 # temp30 A_5 - temp20 A_7.5        0.15491 0.0477 212   3.248  0.0290 
 # temp20 A_7.5 - temp30 A_7.5     -0.09736 0.0280 228  -3.473  0.0141 `
 # temp20 A_7.5 - temp30 CNTRL_0   -0.16653 0.0476 210  -3.498  0.0131
 # temp20 CNTRL_0 - temp30 CNTRL_0 -0.09736 0.0280 228  -3.473  0.0141 `

#now plot
sum_temp_dose_ammonium_sym <- summarySE(all_sym, measurevar = "log_pam_percent_change", groupvars = c("temp", "N_species_dose"))
sum_temp_dose_ammonium_sym$N_species_dose <- factor(sum_temp_dose_ammonium_sym$N_species_dose, levels=c("CNTRL_0", "A_5", "A_7.5","A_10"))
gg_sum_temp_dose_ammonium_sym<-ggplot(data = sum_temp_dose_ammonium_sym,
       aes(x = N_species_dose,
           y = log_pam_percent_change, col=temp)) +
    geom_point() +
    geom_errorbar(aes(ymin=log_pam_percent_change-se, ymax=log_pam_percent_change+se), width=0.1, size = 1) +
    #scale_color_manual(values = c("black", "darkgreen")) +
    ggtitle ("Ammonium- Temperature and dose summary - Sym corals") +
  theme(legend.position="none")+
    labs(x = "Ammonium dose", 
         y = expression(paste("% Change Fv/Fm")), 
         caption = "data represent mean +/- SEM" ) +
      scale_x_discrete("Ammonium dose", labels=c(CNTRL_0="Control", A_5="5uM", A_7.5="7.5uM", A_10="10uM"))+
    scale_color_manual(labels=labels, values=c("blue", "red"))
gg_sum_temp_dose_ammonium_sym

#Aposymbiotic corals
full.model_pam_ammonium_apo <- lmer(log_pam_percent_change ~  N_species_dose + temp + food +  N_species_dose*temp + N_species_dose*food + temp*food + (1|col_num) + (1|exp_num) , data= all_apo)
summary(full.model_pam_ammonium_apo )
print(step.model<- step(full.model_pam_ammonium_apo ))
#lets just add N species dose and temperature cause thats what were interested in
summary(mm_ammonium_apo <- lmer(log_pam_percent_change ~  N_species_dose + temp + (1|col_num) + (1|exp_num) , data= all_apo))
#posthoc to see differences
emm_temp_dose_apo=emmeans(mm_ammonium_apo, specs=pairwise ~ temp*N_species_dose)
summary(emm_temp_dose_apo)
 # NO STAT DIFFERENCES!

#now plot
sum_temp_dose_ammonium_apo <- summarySE(all_apo, measurevar = "log_pam_percent_change", groupvars = c("temp", "N_species_dose"))
sum_temp_dose_ammonium_apo$N_species_dose <- factor(sum_temp_dose_ammonium_apo$N_species_dose, levels=c("CNTRL_0", "A_5", "A_7.5","A_10"))
gg_sum_temp_dose_ammonium_apo<-ggplot(data = sum_temp_dose_ammonium_apo,
       aes(x = N_species_dose,
           y = log_pam_percent_change, col=temp)) +
    geom_point() +
    geom_errorbar(aes(ymin=log_pam_percent_change-se, ymax=log_pam_percent_change+se), width=0.1, size = 1) +
    #scale_color_manual(values = c("black", "darkgreen")) +
    ggtitle ("Ammonium- Temperature and dose summary - Apo corals") +
  theme(legend.position="none")+
    labs(x = "Ammonium dose", 
         y = expression(paste("% Change Fv/Fm")), 
         caption = "data represent mean +/- SEM" ) +
      scale_x_discrete("Ammonium dose", labels=c(CNTRL_0="Control", A_5="5uM", A_7.5="7.5uM", A_10="10uM"))+
    scale_color_manual(labels=labels, values=c("blue", "red"))
gg_sum_temp_dose_ammonium_apo


```




# VISUALIZATIONS
```{r Prepping for visualizations}
pam_all_ammonium.data$N_species_dose <- factor(pam_all_ammonium.data$N_species_dose, levels=c("CNTRL_0", "A_5", "A_7.5","A_10"))
no_controls$N_species_dose <- factor(no_controls$N_species_dose, levels=c("CNTRL_0", "A_5", "A_7.5","A_10"))
pam_all_ammonium.data$N_species_dose<-as.character(pam_all_ammonium.data$N_species_dose)
pam_all_ammonium.data$sym_state<-as.character(pam_all_ammonium.data$sym_state)
pam_all_ammonium.data$temp <- as.character(pam_all_ammonium.data$temp)

```


```{r Symbiotic State - log_pam_percent_change}
# AMMONIUM ONLY

# plot, treatment x axis colored by site data figure
pam_treatmeans_apovsym <- summarySE(pam_all_ammonium.data, measurevar=c("log_pam_percent_change"),groupvars =c("sym_state"), na.rm=TRUE)
gg_pam_plot_apovsym <- ggplot(pam_treatmeans_apovsym, aes(x = sym_state, y= c(log_pam_percent_change), color = sym_state))+
  theme_bw()+
  geom_point(size = 3, position = position_dodge(width=0.3))+
  geom_smooth(aes(group=sym_state), position = position_dodge(width=0.3), size = 0.5, method='lm', se = FALSE)+
 # geom_jitter(aes(), size=1.2, alpha=0.9)+
  geom_line(aes(group = sym_state), size = 0.5, linetype="dashed", position = position_dodge(width=0.3))+
  geom_errorbar(aes(x = sym_state, ymax = log_pam_percent_change+se, ymin = log_pam_percent_change-se), width = .2, position = position_dodge(width=0.3)) +
  #scale_color_manual(name = "Treatment",
                    #labels = c("Control 30C Fed","Control 30C Starved","Ammonium High 30C Fed", "Ammonium High 30C Starved","test"),
                    # values = c("orchid1","darkorchid1","royalblue","skyblue","black","gray","brown"))+
 ylab("% Change Fv/Fm Pre vs. Post-experiment")+
  ggtitle("% Change Fv/Fm Sym vs. Apo - Ammonium")+
 labs(caption = "data represent mean +/- SEM, p=<0.0001***")+
  scale_x_discrete("Symboitic State", labels=c(A="Aposymbiotic", S="Symbiotic"))+ #relabels the x axis to the values in quotations
    scale_color_manual("Symboitic State", labels=c(A="Aposymbiotic", S="Symbiotic"), values=c("gray", "brown")) #gives you the colors for each point on the graph
gg_pam_plot_apovsym

# Summarize by temp and N species dose so we can visualize
sum_N_species_dose_sym_state_ammonium <- summarySE(pam_all_ammonium.data, measurevar = "log_pam_percent_change", groupvars = c("sym_state","N_species_dose"))
# Visualize
gg_N_species_dose_sym_state_ammonium<-ggplot(data = sum_N_species_dose_sym_state_ammonium,
       aes(x = N_species_dose,
           y = log_pam_percent_change, colour=sym_state)) +
    geom_point() +
    geom_errorbar(aes(ymin=log_pam_percent_change-se, ymax=log_pam_percent_change+se), width=0.1, size = 1) +
    #scale_color_manual(values = c("black", "darkgreen")) +
    ggtitle ("Ammonium - % Change Fv/Fm by sym state and dose") +
    
   # scale_x_discrete(labels=c("20C","30C"))+
    labs(x = "ammonium dose", 
         y = expression(paste("Change in Photosynthetic Efficiency Fv/Fm")), 
         caption = "data represent mean +/- SEM" ) +
    scale_x_discrete("ammonium dose", labels=c(CNTRL_0="Control", A_5="1.5uM", A_7.5="7.5um", A_10="10um"))+
    scale_color_manual("Sym State", labels=c("Aposymbiotic","Symbiotic"), values=c("gray", "brown"))
gg_N_species_dose_sym_state_ammonium
# Summarize by food and sym state so we can visualize
sum_food_sym_state_ammonium <- summarySE(pam_all_ammonium.data, measurevar = "log_pam_percent_change", groupvars = c("sym_state","food"))
# Visualize
gg_food_sym_state_ammonium<-ggplot(data = sum_food_sym_state_ammonium,
       aes(x = sym_state,
           y = log_pam_percent_change, col=food)) + #use fill here or the legends will be really hard to work with
    geom_point() +
    geom_errorbar(aes(ymin=log_pam_percent_change-se, ymax=log_pam_percent_change+se), width=0.1, size = 1) +
    ggtitle ("PERCENT CHANGE Fv/Fm Sym vs. Apo at Fed vs. Starved") +
   #scale_fill_manual(name="Feeding Regime", labels=c('Fed', 'Starved'))+
 # scale_fill_manual(values=c("brown", "darkgray"))+
    labs(x = "Symbiotic state", 
         y = expression(paste("Change in Photosynthetic Efficiency Fv/Fm")), 
         caption = "data represent mean +/- SEM" ) +
      scale_x_discrete(name="Symboitic state", labels=c("A"="Aposymbiotic", "S"="Symbiotic")) +
  # scale_fill_manual(values=c("brown", "darkgray"))
 scale_color_manual(values=c("orange", "black"))
gg_food_sym_state_ammonium 

 
# WITHOUT CONTROLS #
# plot, treatment x axis colored by site data figure
pam_treatmeans_apovsym <- summarySE(no_controls, measurevar=c("log_pam_percent_change"),groupvars =c("sym_state"), na.rm=TRUE)
gg_pam_plot_apovsym <- ggplot(pam_treatmeans_apovsym, aes(x = sym_state, y= c(log_pam_percent_change), color = sym_state))+
  theme_bw()+
  geom_point(size = 3, position = position_dodge(width=0.3))+
  geom_smooth(aes(group=sym_state), position = position_dodge(width=0.3), size = 0.5, method='lm', se = FALSE)+
 # geom_jitter(aes(), size=1.2, alpha=0.9)+
  geom_line(aes(group = sym_state), size = 0.5, linetype="dashed", position = position_dodge(width=0.3))+
  geom_errorbar(aes(x = sym_state, ymax = log_pam_percent_change+se, ymin = log_pam_percent_change-se), width = .2, position = position_dodge(width=0.3)) +
  #scale_color_manual(name = "Treatment",
                    #labels = c("Control 30C Fed","Control 30C Starved","Ammonium High 30C Fed", "Ammonium High 30C Starved","test"),
                    # values = c("orchid1","darkorchid1","royalblue","skyblue","black","gray","brown"))+
 ylab("Change in Photosynthetic Efficiency Fv/Fm")+
  ggtitle("No Controls PERCENT CHANGE Fv/Fm Sym vs. Apo - Ammonium")+
 labs(caption = "data represent mean +/- SEM, p=")+
  scale_x_discrete("Symboitic State", labels=c(A="Aposymbiotic", S="Symbiotic"))+ #relabels the x axis to the values in quotations
    scale_color_manual("Symboitic State", labels=c(A="Aposymbiotic", S="Symbiotic"), values=c("gray", "brown")) #gives you the colors for each point on the graph
gg_pam_plot_apovsym

# Summarize by food and sym state so we can visualize
sum_food_sym_state_ammonium <- summarySE(no_controls, measurevar = "log_pam_percent_change", groupvars = c("sym_state","food"))
# Visualize
gg_food_sym_state_ammonium<-ggplot(data = sum_food_sym_state_ammonium,
       aes(x = sym_state,
           y = log_pam_percent_change, col=food)) + #use fill here or the legends will be really hard to work with
    geom_point() +
    geom_errorbar(aes(ymin=log_pam_percent_change-se, ymax=log_pam_percent_change+se), width=0.1, size = 1) +
    ggtitle ("No Controls PERCENT CHANGE Fv/Fm Sym vs. Apo at various Ammonium doses") +
   #scale_fill_manual(name="Feeding Regime", labels=c('Fed', 'Starved'))+
 # scale_fill_manual(values=c("brown", "darkgray"))+
    labs(x = "Symbiotic state", 
         y = expression(paste("Change in Photosynthetic Efficiency Fv/Fm")), 
         caption = "data represent mean +/- SEM" ) +
      scale_x_discrete(name="Symboitic state", labels=c("A"="Aposymbiotic", "S"="Symbiotic")) +
  # scale_fill_manual(values=c("brown", "darkgray"))
 scale_color_manual(values=c("orange", "black"))
gg_food_sym_state_ammonium #seems obvious that food doesnt matter

```


```{r Symbiotic State - PAM_avg_day11 - TABLE THIS FOR NOW}
#overall apo vs. sym
t.test(all_apo$PAM_avg_day11, all_sym$PAM_avg_day11)


pam_treatmeans_apovsym <- summarySE(pam_all_ammonium.data, measurevar=c("PAM_avg_day11"),groupvars =c("sym_state"), na.rm=TRUE)

#ammonium ONLY 
# plot, treatment x axis colored by site data figure
gg_pam_plot_apovsym <- ggplot(pam_treatmeans_apovsym, aes(x = sym_state, y= c(PAM_avg_day11), color = sym_state))+
  theme_bw()+
  geom_point(size = 3, position = position_dodge(width=0.3))+
  geom_smooth(aes(group=sym_state), position = position_dodge(width=0.3), size = 0.5, method='lm', se = FALSE)+
 # geom_jitter(aes(), size=1.2, alpha=0.9)+
  geom_line(aes(group = sym_state), size = 0.5, linetype="dashed", position = position_dodge(width=0.3))+
  geom_errorbar(aes(x = sym_state, ymax = PAM_avg_day11+se, ymin = PAM_avg_day11-se), width = .2, position = position_dodge(width=0.3)) +
  #scale_color_manual(name = "Treatment",
                    #labels = c("Control 30C Fed","Control 30C Starved","Ammonium High 30C Fed", "Ammonium High 30C Starved","test"),
                    # values = c("orchid1","darkorchid1","royalblue","skyblue","black","gray","brown"))+
 ylab("Day 11 Fv/Fm")+
  ggtitle("Day 11 Fv/Fm Sym vs. Apo")+
 labs(caption = "data represent mean +/- SEM, p=")+
  scale_x_discrete("Symboitic State", labels=c(A="Aposymbiotic", S="Symbiotic"))+ #relabels the x axis to the values in quotations
    scale_color_manual("Symboitic State", labels=c(A="Aposymbiotic", S="Symbiotic"), values=c("gray", "brown")) #gives you the colors for each point on the graph
gg_pam_plot_apovsym

# Summarize by food and sym state so we can visualize
sum_food_sym_state_ammonium <- summarySE(pam_all_ammonium.data, measurevar = "PAM_avg_day11", groupvars = c("sym_state","food"))
# Visualize
gg_food_sym_state_ammonium<-ggplot(data = sum_food_sym_state_ammonium,
       aes(x = sym_state,
           y = PAM_avg_day11, col=food)) + #use fill here or the legends will be really hard to work with
    geom_point() +
    geom_errorbar(aes(ymin=PAM_avg_day11-se, ymax=PAM_avg_day11+se), width=0.1, size = 1) +
    ggtitle ("Day 11 Fv/Fm Sym vs. Apo at various ammonium doses") +
   #scale_fill_manual(name="Feeding Regime", labels=c('Fed', 'Starved'))+
 # scale_fill_manual(values=c("brown", "darkgray"))+
    labs(x = "Symbiotic state", 
         y = expression(paste("Day 11 Fv/Fm")), 
         caption = "data represent mean +/- SEM" ) +
      scale_x_discrete(name="Symboitic state", labels=c("A"="Aposymbiotic", "S"="Symbiotic")) +
  # scale_fill_manual(values=c("brown", "darkgray"))
 scale_color_manual(values=c("orange", "black"))
gg_food_sym_state_ammonium #seems obvious that food doesnt matter

# Summarize by temp and N species dose so we can visualize
sum_N_species_dose_sym_state_ammonium <- summarySE(pam_all_ammonium.data, measurevar = "PAM_avg_day11", groupvars = c("sym_state","N_species_dose"))
# Visualize
gg_N_species_dose_sym_state_ammonium<-ggplot(data = sum_N_species_dose_sym_state_ammonium,
       aes(x = N_species_dose,
           y = PAM_avg_day11, colour=sym_state)) +
    geom_point() +
    geom_errorbar(aes(ymin=PAM_avg_day11-se, ymax=PAM_avg_day11+se), width=0.1, size = 1) +
    #scale_color_manual(values = c("black", "darkgreen")) +
    ggtitle ("Day 11 Fv/Fm Sym state and N species dose") +
   # scale_x_discrete(labels=c("20C","30C"))+
    labs(x = "ammonium dose", 
         y = expression(paste("Day 11 Fv/Fm")), 
         caption = "data represent mean +/- SEM" ) +
    scale_x_discrete("ammonium dose", labels=c(CNTRL_0="Control", A_5="1.5uM", A_7.5="7.5um", A_10="10um"))+
    scale_color_manual("Sym State", labels=c("Aposymbiotic","Symbiotic"), values=c("gray", "brown"))
gg_N_species_dose_sym_state_ammonium


# WITHOUT CONTROLS #
# plot, treatment x axis colored by site data figure
pam_treatmeans_apovsym <- summarySE(no_controls, measurevar=c("PAM_avg_day11"),groupvars =c("sym_state"), na.rm=TRUE)
gg_pam_plot_apovsym <- ggplot(pam_treatmeans_apovsym, aes(x = sym_state, y= c(PAM_avg_day11), color = sym_state))+
  theme_bw()+
  geom_point(size = 3, position = position_dodge(width=0.3))+
  geom_smooth(aes(group=sym_state), position = position_dodge(width=0.3), size = 0.5, method='lm', se = FALSE)+
 # geom_jitter(aes(), size=1.2, alpha=0.9)+
  geom_line(aes(group = sym_state), size = 0.5, linetype="dashed", position = position_dodge(width=0.3))+
  geom_errorbar(aes(x = sym_state, ymax = PAM_avg_day11+se, ymin = PAM_avg_day11-se), width = .2, position = position_dodge(width=0.3)) +
  #scale_color_manual(name = "Treatment",
                    #labels = c("Control 30C Fed","Control 30C Starved","Ammonium High 30C Fed", "Ammonium High 30C Starved","test"),
                    # values = c("orchid1","darkorchid1","royalblue","skyblue","black","gray","brown"))+
 ylab("Day 11 Fv/Fm")+
  ggtitle("No Controls Day 11 Fv/Fm Sym vs. Apo")+
 labs(caption = "data represent mean +/- SEM, p=")+
  scale_x_discrete("Symboitic State", labels=c(A="Aposymbiotic", S="Symbiotic"))+ #relabels the x axis to the values in quotations
    scale_color_manual("Symboitic State", labels=c(A="Aposymbiotic", S="Symbiotic"), values=c("gray", "brown")) #gives you the colors for each point on the graph
gg_pam_plot_apovsym

# Summarize by food and sym state so we can visualize
sum_food_sym_state_ammonium <- summarySE(no_controls, measurevar = "PAM_avg_day11", groupvars = c("sym_state","food"))
# Visualize
gg_food_sym_state_ammonium<-ggplot(data = sum_food_sym_state_ammonium,
       aes(x = sym_state,
           y = PAM_avg_day11, col=food)) + #use fill here or the legends will be really hard to work with
    geom_point() +
    geom_errorbar(aes(ymin=PAM_avg_day11-se, ymax=PAM_avg_day11+se), width=0.1, size = 1) +
    ggtitle ("No Controls Day 11 Fv/Fm Sym vs. Apo at various ammonium doses") +
   #scale_fill_manual(name="Feeding Regime", labels=c('Fed', 'Starved'))+
 # scale_fill_manual(values=c("brown", "darkgray"))+
    labs(x = "Symbiotic state", 
         y = expression(paste("Day 11 Fv/Fm")), 
         caption = "data represent mean +/- SEM" ) +
      scale_x_discrete(name="Symboitic state", labels=c("A"="Aposymbiotic", "S"="Symbiotic")) +
  # scale_fill_manual(values=c("brown", "darkgray"))
 scale_color_manual(values=c("orange", "black"))
gg_food_sym_state_ammonium #seems obvious that food doesnt matter


```


```{r Fed vs. Starved - PERCENT CHANGE with and without controls}
#Don't think theres anything going on here

# PERCENT CHANGE Fed vs. starved WITH CONTROLS
pam_treatmeans_fedvstarved_delta <- summarySE(pam_all_ammonium.data, measurevar=c("log_pam_percent_change"),groupvars =c("food"), na.rm=TRUE)
# plot, treatment x axis colored by site data figure
pam_plot_fedvstarved_delta <-ggplot(pam_treatmeans_fedvstarved_delta, aes(x = food, y= c(log_pam_percent_change), color = food))+
  theme_bw()+
  geom_point(size = 3, position = position_dodge(width=0.3))+
  geom_smooth(aes(group=food), position = position_dodge(width=0.3), size = 0.5, method='lm', se = FALSE)+
 # geom_jitter(aes(), size=1.2, alpha=0.9)+
  geom_line(aes(group = food), size = 0.5, linetype="dashed", position = position_dodge(width=0.3))+
  geom_errorbar(aes(x = food, ymax = log_pam_percent_change+se, ymin = log_pam_percent_change-se), width = .2, position = position_dodge(width=0.3)) +
 ylab("PERCENT CHANGE Fv/Fm")+
    scale_color_manual("Feeding Regime", values=c("orange", "black")) +
  scale_x_discrete(name="Feeding regime", labels=c("F"="Fed", "S"="Starved")) +
  ggtitle("Fed vs. starved PERCENT CHANGE, Ammonium p=0.05")
pam_plot_fedvstarved_delta


# PERCENT CHANGE Fed vs. starved WITHOUT CONTROLS
pam_treatmeans_fedvstarved_delta <- summarySE(no_controls, measurevar=c("log_pam_percent_change"),groupvars =c("food"), na.rm=TRUE)
# plot, treatment x axis colored by site data figure
pam_plot_fedvstarved_delta <-ggplot(pam_treatmeans_fedvstarved_delta, aes(x = food, y= c(log_pam_percent_change), color = food))+
  theme_bw()+
  geom_point(size = 3, position = position_dodge(width=0.3))+
  geom_smooth(aes(group=food), position = position_dodge(width=0.3), size = 0.5, method='lm', se = FALSE)+
 # geom_jitter(aes(), size=1.2, alpha=0.9)+
  geom_line(aes(group = food), size = 0.5, linetype="dashed", position = position_dodge(width=0.3))+
  geom_errorbar(aes(x = food, ymax = log_pam_percent_change+se, ymin = log_pam_percent_change-se), width = .2, position = position_dodge(width=0.3)) +
 ylab("PERCENT CHANGE Fv/Fm")+
  scale_color_manual("Feeding Regime", values=c("orange", "black")) +
  scale_x_discrete(name="Feeding regime", labels=c("F"="Fed", "S"="Starved")) +
  ggtitle("No Controls - Fed vs. starved PERCENT CHANGE, Ammonium")
pam_plot_fedvstarved_delta

# Fed vs. Starved at different N doses
sum_food_dose_ammonium <- summarySE(pam_all_ammonium.data, measurevar = "log_pam_percent_change", groupvars = c("N_species_dose","food"))
# Visualize
gg_sum_food_dose_ammonium<-ggplot(data = sum_food_dose_ammonium,
       aes(x = N_species_dose,
           y = log_pam_percent_change, col=food)) + #use fill here or the legends will be really hard to work with
    geom_point() +
    geom_errorbar(aes(ymin=log_pam_percent_change-se, ymax=log_pam_percent_change+se), width=0.1, size = 1) +
    ggtitle ("PERCENT CHANGE Fed vs. starved at various doses of Ammonium") +
   #scale_fill_manual(name="Feeding Regime", labels=c('Fed', 'Starved'))+
 # scale_fill_manual(values=c("brown", "darkgray"))+
    labs(x = "Symbiotic state", 
         y = expression(paste("Day 11 Fv/Fm")), 
         caption = "data represent mean +/- SEM" ) +
  scale_x_discrete("ammonium dose", labels=c(CNTRL_0="Control", A_5="1.5uM", A_7.5="7.5um", A_10="10um"))+
 scale_color_manual("Food regime", labels=c("F"="Fed", "S"="Starved"),values=c("orange", "black"))
gg_sum_food_dose_ammonium #seems obvious that food doesnt matter
```

```{r PERCENT CHANGE Temperature graphs}

# Temp on its own doesnt seem to matter but sym and apo are driving the models so much we will separate them below
pam_treatmeans_20vs30 <- summarySE(pam_all_ammonium.data, measurevar=c("log_pam_percent_change"),groupvars =c("temp"), na.rm=TRUE)

t.test(pam_all_ammonium.data_simplified_controls$temp=="20", pam_all_ammonium.data_simplified_controls$temp=="30")

# Summarize by temperature so we can visualize
sum_temp_ammonium <- summarySE(pam_all_ammonium.data, measurevar = "log_pam_percent_change", groupvars = c("temp"))
# Visualize
gg_temp_ammonium<-ggplot(data = sum_temp_ammonium,
       aes(x = temp,
           y = log_pam_percent_change, col=temp)) +
    geom_point() +
    geom_errorbar(aes(ymin=log_pam_percent_change-se, ymax=log_pam_percent_change+se), width=0.1, size = 1) +
    #scale_color_manual(values = c("black", "darkgreen")) +
    ggtitle ("ammonium PERCENT CHANGE Temperature summary") +
  theme(legend.position="none")+
    labs(x = "Temperature", 
         y = expression(paste("Change in Photosynthetic Efficiency Fv/Fm")), 
         caption = "data represent mean +/- SEM" ) +
    scale_x_discrete("Temperature", labels=c("20"="Control 20C", "30"="Elevated 30C")) +
    scale_color_manual("Temperature",labels=c("20C", "30C"), values=c("blue", "red"))
gg_temp_ammonium

#Let's try this on data without controls
pam_treatmeans_20vs30 <- summarySE(no_controls, measurevar=c("log_pam_percent_change"),groupvars =c("temp"), na.rm=TRUE)
# Summarize by temperature so we can visualize
sum_temp_ammonium <- summarySE(pam_all_ammonium.data, measurevar = "log_pam_percent_change", groupvars = c("temp"))
# Visualize
gg_temp_ammonium<-ggplot(data = sum_temp_ammonium,
       aes(x = temp,
           y = log_pam_percent_change, col=temp)) +
    geom_point() +
    geom_errorbar(aes(ymin=log_pam_percent_change-se, ymax=log_pam_percent_change+se), width=0.1, size = 1) +
    #scale_color_manual(values = c("black", "darkgreen")) +
    ggtitle ("No controls ammonium PERCENT CHANGE Temperature summary") +
  theme(legend.position="none")+
    labs(x = "Temperature", 
         y = expression(paste("Change in Photosynthetic Efficiency Fv/Fm")), 
         caption = "data represent mean +/- SEM" ) +
    scale_x_discrete("Temperature", labels=c("20"="Control 20C", "30"="Elevated 30C")) +
    scale_color_manual("Temperature",labels=c("20C", "30C"), values=c("blue", "red"))
gg_temp_ammonium

#summarize by temp and sym state with and without controls
pam_treatmeans_temp_sym <- summarySE(pam_all_ammonium.data, measurevar=c("log_pam_percent_change"),groupvars =c("temp", "sym_state"), na.rm=TRUE)
# Visualize
gg_pam_treatmeans_temp_sym<-ggplot(data = pam_treatmeans_temp_sym,
       aes(x = sym_state,
           y = log_pam_percent_change, col=temp)) +
    geom_point() +
    geom_errorbar(aes(ymin=log_pam_percent_change-se, ymax=log_pam_percent_change+se), width=0.1, size = 1) +
    #scale_color_manual(values = c("black", "darkgreen")) +
    ggtitle ("ammonium PERCENT CHANGE sym state Temperature summary") +
  theme(legend.position="none")+
    labs(x = "Temperature", 
         y = expression(paste("Change in Photosynthetic Efficiency Fv/Fm")), 
         caption = "data represent mean +/- SEM" ) +
    scale_x_discrete("Sym State", labels=c("A"="Apo", "S"="Sym")) +
    scale_color_manual("Temp",labels=c("20", "30"), values=c("blue", "red"))
gg_pam_treatmeans_temp_sym
#Let's try this on data without controls
pam_treatmeans_temp_sym <- summarySE(no_controls, measurevar=c("log_pam_percent_change"),groupvars =c("temp", "sym_state"), na.rm=TRUE)
# Visualize
gg_pam_treatmeans_temp_sym<-ggplot(data = pam_treatmeans_temp_sym,
       aes(x = sym_state,
           y = log_pam_percent_change, col=temp)) +
    geom_point() +
    geom_errorbar(aes(ymin=log_pam_percent_change-se, ymax=log_pam_percent_change+se), width=0.1, size = 1) +
    #scale_color_manual(values = c("black", "darkgreen")) +
    ggtitle ("No controls ammonium PERCENT CHANGE sym state Temperature summary") +
  theme(legend.position="none")+
    labs(x = "Temperature", 
         y = expression(paste("Change in Photosynthetic Efficiency Fv/Fm")), 
         caption = "data represent mean +/- SEM" ) +
    scale_x_discrete("Sym State", labels=c("A"="Apo", "S"="Sym")) +
    scale_color_manual("Temp",labels=c("20", "30"), values=c("blue", "red"))
gg_pam_treatmeans_temp_sym

# Summarize by temp and N species dose so we can visualize
sum_N_species_dose_temp_ammonium <- summarySE(pam_all_ammonium.data, measurevar = "log_pam_percent_change", groupvars = c("temp","N_species_dose"))
sum_N_species_dose_temp_ammonium$N_species_dose <- factor(sum_N_species_dose_temp_ammonium$N_species_dose, levels=c("CNTRL_0", "A_5", "A_7.5","A_10"))
# Visualize
gg_N_species_dose_temp_ammonium<-ggplot(data = sum_N_species_dose_temp_ammonium,
       aes(x = N_species_dose,
           y = log_pam_percent_change, col=temp)) +
    geom_point() +
    geom_errorbar(aes(ymin=log_pam_percent_change-se, ymax=log_pam_percent_change+se), width=0.1, size = 1) +
    #scale_color_manual(values = c("black", "darkgreen")) +
    ggtitle ("Ammonium PERCENT CHANGE Dose and Temperature summary") +
    labs(x = "Ammonium dose", 
         y = expression(paste("Change in Photosynthetic Efficiency Fv/Fm")), 
         caption = "data represent mean +/- SEM" ) +
    scale_x_discrete("Ammonium dose", labels=c(CNTRL_0="Control", A_5="5uM", A_7.5="7.5um", A_10="10um"))+
    scale_color_manual("Temperature",labels=c("20C","30C"), values=c("blue", "red"))
gg_N_species_dose_temp_ammonium

# Separate by sym state - temp x N species dose

# Sym corals
sum_N_species_dose_temp_ammonium_sym <- summarySE(all_sym, measurevar = "log_pam_percent_change", groupvars = c("temp","N_species_dose"))
#its being a hoe and making me re order
sum_N_species_dose_temp_ammonium_sym$N_species_dose <- factor(sum_N_species_dose_temp_ammonium_sym$N_species_dose, levels=c("CNTRL_0", "A_5", "A_7.5","A_10"))

# Visualize
gg_N_species_dose_temp_ammonium_sym<-ggplot(data = sum_N_species_dose_temp_ammonium_sym,
       aes(x = N_species_dose,
           y = log_pam_percent_change, col=temp)) +
    geom_point() +
    geom_errorbar(aes(ymin=log_pam_percent_change-se, ymax=log_pam_percent_change+se), width=0.1, size = 1) +
    #scale_color_manual(values = c("black", "darkgreen")) +
    ggtitle ("Symbiotic Corals - Ammonium PERCENT CHANGE Dose and Temperature summary") +
    labs(x = "Ammonium dose", 
         y = expression(paste("Change in Photosynthetic Efficiency Fv/Fm")), 
         caption = "data represent mean +/- SEM" ) +
    scale_x_discrete("Ammonium dose", labels=c(CNTRL_0="Control", A_5="1.5uM", A_7.5="7.5um", A_10="10um"))+
    scale_color_manual("Temperature",labels=c("20C","30C"), values=c("blue", "red"))
gg_N_species_dose_temp_ammonium_sym


# apo corals
sum_N_species_dose_temp_ammonium_apo <- summarySE(all_apo, measurevar = "log_pam_percent_change", groupvars = c("temp","N_species_dose"))
sum_N_species_dose_temp_ammonium_apo$N_species_dose <- factor(sum_N_species_dose_temp_ammonium_apo$N_species_dose, levels=c("CNTRL_0", "A_5", "A_7.5","A_10"))
# Visualize
gg_N_species_dose_temp_ammonium_apo<-ggplot(data = sum_N_species_dose_temp_ammonium_apo,
       aes(x = N_species_dose,
           y = log_pam_percent_change, col=temp)) +
    geom_point() +
    geom_errorbar(aes(ymin=log_pam_percent_change-se, ymax=log_pam_percent_change+se), width=0.1, size = 1) +
    #scale_color_manual(values = c("black", "darkgreen")) +
    ggtitle ("Aposymbiotic Corals - Ammonium PERCENT CHANGE Dose and Temperature summary") +
    labs(x = "Ammonium dose", 
         y = expression(paste("Change in Photosynthetic Efficiency Fv/Fm")), 
         caption = "data represent mean +/- SEM" ) +
    scale_x_discrete("Ammonium dose", labels=c(CNTRL_0="Control", A_5="1.5uM", A_7.5="7.5um", A_10="10um"))+
    scale_color_manual("Temperature",labels=c("20C","30C"), values=c("blue", "red"))
gg_N_species_dose_temp_ammonium_apo
```

```{r N species dose graphs}
#Make N species dose a factor and give it levels so it will display in this order
pam_all_ammonium.data$N_species_dose <- factor(pam_all_ammonium.data$N_species_dose, levels=c("CNTRL_0", "A_5", "A_7.5","A_10"))

#Make everything else a character so they graph nicely 
pam_all_ammonium.data$treat_ID_full<-as.character(pam_all_ammonium.data$treat_ID_full)
pam_all_ammonium.data$temp <- as.character(pam_all_ammonium.data$temp)

# Summarize by N_species_dose so we can visualize
sum_N_species_dose_ammonium <- summarySE(pam_all_ammonium.data, measurevar = "log_pam_percent_change", groupvars = c("N_species_dose"))
# Visualize
gg_N_species_dose_ammonium<-ggplot(data = sum_N_species_dose_ammonium,
       aes(x = N_species_dose,
           y = log_pam_percent_change, col=N_species_dose)) +
    geom_point() +
   ylim(-0.078, 0.015) +
    geom_errorbar(aes(ymin=log_pam_percent_change-se, ymax=log_pam_percent_change+se), width=0.1, size = 1) +
    #scale_color_manual(values = c("black", "darkgreen")) +
    ggtitle ("Ammonium - PERCENT CHANGE N Species Dose summary") +
   theme(legend.position="none")+
    labs(x = "\n", 
         y = expression(paste("Change in Photosynthetic Efficiency Fv/Fm")), 
         caption = "data represent mean +/- SEM" ) +
    scale_x_discrete("Ammonium dose", labels=c(CNTRL_0="Control", A_5="Ambient", A_7.5="Intermediate", A_10="High"))+
    scale_color_manual(labels=labels, values=c("blue", "orchid1","blueviolet","purple4"))
gg_N_species_dose_ammonium




```

```{r Controls vs. Nutrient - CHALK TALK}

#I added a column called "control_or_nutrient"

# let's do temperature for control vs. nutrient

sum_temp_control_nutrient <- summarySE(pam_all_ammonium.data, measurevar = "log_pam_percent_change", groupvars = c("temp", "control_or_nutrient"))
gg_temp_ammonium<-ggplot(data = sum_temp_control_nutrient,
       aes(x = control_or_nutrient,
           y = log_pam_percent_change, col=temp)) +
    geom_point() +
    ylim(-0.08, 0.07) +
    geom_errorbar(aes(ymin=log_pam_percent_change-se, ymax=log_pam_percent_change+se), width=0.1, size = 1) +
    #scale_color_manual(values = c("black", "darkgreen")) +
    ggtitle ("ammonium with & without control - Temperature summary") +
    labs(x = " ", 
         y = expression(paste("% Change Fv/Fm")), 
         caption = "data represent mean +/- SEM" ) +
    scale_color_manual(" Temperature ", labels=c("20C","30C"), values=c("blue", "darkred"))
gg_temp_ammonium

#now let's do sym state for control vs. nutrient

sum_sym_state_control_nutrient <- summarySE(log_pam_percent_change_all_ammonium.data, measurevar = "log_pam_percent_change", groupvars = c("sym_state", "control_or_nutrient"))
gg_sym_state_ammonium<-ggplot(data = sum_sym_state_control_nutrient,
       aes(x = control_or_nutrient,
           y = log_pam_percent_change, col=sym_state)) +
    geom_point() +
    ylim(-0.0049, -0.0039) +
    geom_errorbar(aes(ymin=log_pam_percent_change-se, ymax=log_pam_percent_change+se), width=0.1, size = 1) +
    #scale_color_manual(values = c("black", "darkgreen")) +
    ggtitle ("ammonium with & without control - Sym state summary") +
    labs(x = " ", 
         y = expression(paste("Rate O2 Consumption (umol*min"^"-1"~"*g"^"-1"~")")), 
         caption = "data represent mean +/- SEM" ) +
    scale_color_manual(" Symbiotic State ", labels=c("Aposymbiotic","Symbiotic"), values=c("darkgray", "tan4"))
gg_sym_state_ammonium



# STATS STATS STATS
mm_log_pam_percent_change_control_v_nutrient <- lmer(log_pam_percent_change ~  temp + control_or_nutrient + (1 | col_num), data=pam_all_ammonium.data)
summary(mm_log_pam_percent_change_control_v_nutrient)

# Summarize by control_or_nutrient * e_coli
emm_control_v_nutrient=emmeans(mm_log_pam_percent_change_control_v_nutrient, specs=pairwise ~ control_or_nutrient*e_coli_plate)
summary(emm_control_v_nutrient)

# Summarize by control_or_nutrient * temp
emm_control_v_nutrient=emmeans(mm_log_pam_percent_change_control_v_nutrient, specs=pairwise ~ control_or_nutrient*temp)
summary(emm_control_v_nutrient)

# Summarize by control_or_nutrient * symbiotic state
emm_control_v_nutrient=emmeans(mm_log_pam_percent_change_control_v_nutrient, specs=pairwise ~ control_or_nutrient*sym_state)
summary(emm_control_v_nutrient)


```


