---
title: "Polyp Extension Score"
author: "CFI"
date: "2024-06-12"
output:
  pdf_document: default
  html_document: default
editor_options:
  chunk_output_type: console
  highlight: breezedark
---


```{r Loading all necessary packages }
#setwd("C:/Users/carol/OneDrive/Documents/PhD Boston University 2019-/Astrangia_nutrient_stressors_Rotjan_lab/Data/")
#setwd(dirname(getwd())) #need to add this!
library("knitr")
require("knitr")
#opts_knit$set(root.dir = "C:/Users/carol/OneDrive/Documents/PhD Boston University 2019-/Astrangia_nutrient_stressors_Rotjan_lab/Data/")
#setwd("C:/Users/carol/OneDrive/Documents/PhD Boston University 2019-/Astrangia_nutrient_stressors_Rotjan_lab/Data/")
#setwd(dirname(getwd())) 
#getwd()
#install.packages("dplyr")
#compare with and without predictor
library("lme4")
#install.packages("lmerTest")
library("lmerTest")
#install.packages("emmeans")
library("emmeans")
#install.packages("pbkrtest")
library("pbkrtest")
#reshape melts our datasets in the way we want
library("reshape2")
library("dplyr")
library("plyr")
library("tidyverse")
library("Rmisc")
library("ggplot2")
library("glmmTMB")
#multiple response variables 
#check model with performance package
  #model tools R markdown
  #check for colinearity
  #r squared figures
#install.packages("performance")
#install.packages(c("rlang", "ggplot2", "performance", "dplyr", "ggrepel", "see"), dependencies = TRUE)
library("performance")
#install.packages("see")
library("see")
#install.packages("ggrepel")
library("ggrepel")
#install.packages("sjPlot") #for visualizing linear models
library(sjPlot)
library(MASS)
library(car)
library(outliers)
#gg effects
library(ggpubr)
#install.packages("ggpmisc")
library("ggpmisc")
library(devtools)
source_gist("524eade46135f6348140") #for the stat_smooth_func()
#install.packages("DHARMA")
library(DHARMa)
#install.packages("ordinal")
library(ordinal)
#install.packages("cowplot")
library(cowplot)

#increase the number of results it will show
options(max.print=1000000)
```

```{r Inputting data & making sure everything is organized correctly}
#opts_knit$set(root.dir = "C:/Users/carol/OneDrive/Documents/PhD Boston University 2019-/Astrangia_nutrient_stressors_Rotjan_lab/Data/")
pes_all.data <- read.csv("/Users/carolineianniello/Astrangia_Ecotox/Data/PES_all_06_26_24_dead_NAs.csv", header=TRUE, sep=",",stringsAsFactors = FALSE)
#pes_data_WIDE <- read.csv("C:/Users/carol/OneDrive/Documents/PhD Boston University 2019-/Astrangia_nutrient_stressors_Rotjan_lab/Data/PES_all_06_12_24.csv", header=TRUE, sep=",",stringsAsFactors = FALSE)

#ALL DONE PRE PROCESSING, UPLOADING REFORMATTED DATA WITH NEW NITRATE CATEGORIES
# #long data to deal with PES repeated measures
# pes_all.data <- pes_all.data %>%
#   pivot_longer(
#     cols = starts_with("PES_day"),
#     names_to = "PES_day",
#     values_to = "PES_value"
#   )
# 
# #change PES_day to either 2, 6, or 10
# pes_all.data <- pes_all.data %>% mutate(PES_day = case_when(
#     PES_day=="PES_day2" ~ 2 , #need two equal signs
#     PES_day=="PES_day6" ~ 6 , #need two equal signs
#     PES_day=="PES_day10" ~ 10)) #need two equal signs
# 
# write.csv(pes_all.data, "C:/Users/carol/OneDrive/Documents/PhD Boston University 2019-/Astrangia_nutrient_stressors_Rotjan_lab/Data/pes_all.data.csv")

#Create a NEW column for nitrate with new categories
pes_all.data <- pes_all.data %>%
mutate(NO3_category = case_when(
NO3_mean_observed < 6  ~ "Low" , #need two equal signs
NO3_mean_observed >= 6 ~ "Elevated" 
 )
)

hist(pes_all.data$PES_value)

pes_all.data$treatment <- paste(pes_all.data$NO3_category,pes_all.data$temp, pes_all.data$food, pes_all.data$sym_state, sep="_")

pes_all.data$PES_value <- as.factor(pes_all.data$PES_value)
pes_all.data$PES_day <- as.numeric(pes_all.data$PES_day)
pes_all.data$NO3_category <- as.factor(pes_all.data$NO3_category)
pes_all.data$sym_state <- as.factor(pes_all.data$sym_state)
pes_all.data$temp <- as.factor(pes_all.data$temp)
pes_all.data$food <- as.factor(pes_all.data$food)


```

```{r}

#Checking that there is pretty good variation in scores -- it looks like there is
PES_stacked = pes_all.data %>%
  group_by(PES_value, PES_day, treatment) %>%
  dplyr::summarise(frequency = n()) 

#Plot it
ggplot(PES_stacked, aes(y = frequency, x = PES_day, fill = as.factor(PES_value))) + 
  geom_bar(stat = "identity", position = "fill") +
  facet_grid(. ~ treatment) + 
  scale_fill_brewer(palette = "Blues", direction=1) +
  labs(fill = "Behavioural Score") +
  theme_cowplot()
```


#We can proceed with an ordinal regression

```{r}

#using the ordinal package
clmm_PES_1 <- clmm(PES_value ~ PES_day + NO3_category + sym_state + temp + food + NO3_category*sym_state + NO3_category*food + NO3_category*temp + sym_state*temp + sym_state*food + food*temp +  (1|beetag_exprun), data = pes_all.data)


```


```{r generate a custom function to step AIC the clmm models - RUN ON THE SCC }
#THE FOLLOWING CODE IS COMPUTATIONALLY INTENSIVE AND WAS RUN FOR 12 hours with 1 core on the SCC

# setwd("~/")
# library("tidyverse")
# library(ordinal)
# 
# pes_all.data <- read.csv("PES_all_06_26_24_dead_NAs.csv", header=TRUE, sep=",",stringsAsFactors = FALSE)
# 
# 
# #Create a NEW column for nitrate with new categories
# pes_all.data <- pes_all.data %>%
#   mutate(NO3_category = case_when(
#     NO3_mean_observed < 6  ~ "Low" , #need two equal signs
#     NO3_mean_observed >= 6 ~ "Elevated" 
#   )
#   )
# 
# pes_all.data$PES_value <- as.factor(pes_all.data$PES_value)
# pes_all.data$PES_day <- as.numeric(pes_all.data$PES_day)
# pes_all.data$NO3_category <- as.factor(pes_all.data$NO3_category)
# pes_all.data$sym_state <- as.factor(pes_all.data$sym_state)
# pes_all.data$temp <- as.factor(pes_all.data$temp)
# pes_all.data$food <- as.factor(pes_all.data$food)
# 
# #################
# 
# step_clmm_custom <- function(data) {
#   library(ordinal)
#   
#   # Define the full formula terms
#   full_formula <- PES_value ~ PES_day + NO3_category + sym_state + temp + food +
#     NO3_category*sym_state + NO3_category*food + NO3_category*temp +
#     sym_state*temp + sym_state*food + food*temp
#   
#   full_terms <- attr(terms(full_formula), "term.labels")
#   
#   # Prepare for model selection
#   best_aic <- Inf
#   best_model <- NULL
#   model_results <- data.frame(Formula = character(), AIC = numeric(), stringsAsFactors = FALSE)
#   
#   # Loop over all combinations of the predictors and interactions
#   for (i in seq_along(full_terms)) {
#     comb <- combn(full_terms, i, simplify = FALSE)
#     for (j in seq_along(comb)) {
#       # Create the formula for the current combination
#       current_formula <- as.formula(paste("PES_value ~", paste(comb[[j]], collapse = " + "), "+ (1|beetag_exprun)", "+ (1|exp_num)"))
#       print(current_formula)
#       
#       # Fit the model
#       current_model <- clmm(current_formula, data = data)
#       
#       # Compute the AIC
#       current_aic <- AIC(current_model)
#       
#       # Store the formula and AIC
#       model_results <- rbind(model_results, data.frame(Formula = deparse(current_formula), AIC = current_aic))
#       
#       # Update the best model if the current one is better
#       if (current_aic < best_aic) {
#         best_aic <- current_aic
#         best_model <- current_model
#       }
#     }
#   }
#   
#   # Return the best model, its AIC, and all AICs
#   list(best_model = best_model, best_aic = best_aic, model_results = model_results)
# }
# 
# # Run the stepwise selection
# result <- step_clmm_custom(pes_all.data)
# 
# # Extract the best model, its AIC, and the AICs of all models
# best_model <- result$best_model
# best_aic <- result$best_aic
# model_aic_df <- result$model_results
# 
# # View the dataframe of all model formulas and their AICs
# saveRDS(best_model, "best_model.RDS")
# write.csv(best_aic, "best_aic.csv")
# write.csv(model_aic_df, "all_aic.csv")
```


```{r Model selection}
# REMINDER OF FULL MODEL
library(ordinal)
clmm_PES_KITCHEN_SINK <- clmm(PES_value ~ PES_day + NO3_category + sym_state + temp + food + NO3_category*sym_state + NO3_category*food + NO3_category*temp + sym_state*temp + sym_state*food + food*temp +  (1|beetag_exprun), data = pes_all.data)

#All these formulas had an AIC of 8809.427
clmm_PES_1 <- clmm(PES_value ~ PES_day + food + sym_state*temp +  (1|beetag_exprun), data = pes_all.data)
summary(clmm_PES_1)

clmm_PES_1_rand <- clmm(PES_value ~ PES_day + food + sym_state*temp +  (1|beetag_exprun) + (1|exp_num), data = pes_all.data)
summary(clmm_PES_1_rand)

AIC(clmm_PES_1, clmm_PES_1_rand)

clmm_PES_2 <- clmm(PES_value ~ PES_day + temp + food + sym_state*temp +  (1|beetag_exprun), data = pes_all.data)

clmm_PES_3 <- clmm(PES_value ~ PES_day + sym_state + food + sym_state*temp +  (1|beetag_exprun), data = pes_all.data)

clmm_PES_4 <- clmm(PES_value ~ PES_day + sym_state + food + temp + sym_state*temp +  (1|beetag_exprun), data = pes_all.data)


# WE SHOULD GO WITH MODEL 1, WHICH IS THE SIMPLEST MODEL (parsimony) 

summary(clmm_PES_1)


#PES DAY p= <0.001
#FOOD STARVED p= <0.001
#SYM STATE SYM p= 0.904
#TEMP 30 p=0.00149
#SYM STATE SYM * TEMP 30 p=0.059


emmeans(clmm_PES_1, specs=pairwise ~sym_state*temp)
#A temp20 - A temp30   0.4077 0.128 Inf   3.177  0.0081
# S temp20 - A temp30   0.3921 0.129 Inf   3.039  0.0127
#A temp30 - S temp30  -0.3264 0.127 Inf  -2.574  0.0493

```



```{r Visualizations of PES -- ALL DATA}

pes_all.data$PES_value<- as.numeric(pes_all.data$PES_value)

#Group by temp and sym state and then re-plot?
pes_all.data_gg <- pes_all.data
pes_all.data_gg$temp_sym <- paste(pes_all.data_gg$temp, "_", pes_all.data_gg$sym_state)
pes_all.data_gg$temp_sym <- as.factor(pes_all.data_gg$temp_sym)
#pes_all.data_gg$PES_day <- as.integer(pes_all.data_gg$PES_DAY)

#make a new column for Nitrate level and sym state
pes_all.data_gg$NO3_category_sym_state <- paste(pes_all.data_gg$NO3_category, pes_all.data_gg$sym_state, sep="_")

#sum by TEMPERATURE AND SYM STATE
sum_nitrate_4<- summarySE(pes_all.data_gg, measurevar = "PES_value", groupvars = c("NO3_category_sym_state", "PES_day", "temp"), na.rm=T)
gg_nitrate_PES_4 <-ggplot(data = sum_nitrate_4,
       aes(x = PES_day,
           y = PES_value, col=temp, shape=NO3_category_sym_state, group=interaction(NO3_category_sym_state, temp))) +
    geom_point(size = 4.5, position = position_dodge(width  = 0.85)) +
 geom_line(linewidth = 1, position = position_dodge(width = 0.85), linetype = "dotted") +
   geom_errorbar(aes(ymin=PES_value-se, ymax=PES_value+se), width = 1, linewidth = 0.8, position = position_dodge(width = 0.85)) +
    ggtitle ("Polyp Exension Score- Average by symbiotic state, temperature, and nitrate level") +
theme_classic() +
 theme(legend.position = "right",  
        axis.title.x = element_blank(),
        axis.title.y = element_blank(),  
       axis.text = element_text(size = 18),
       axis.text.x = element_text(size = 18, vjust=-1),
        text = element_text(family = "serif", size=20)) +
    labs(x = "Day of experiment", 
         y = expression(paste("Average Polyp Exension Score"))) +
       # theme(legend.position="none")+
   scale_color_manual("Temperature", labels=c("20°C","29°C"), values=c("dodgerblue", "darkred")) +
  scale_shape_manual("Treatment", labels=c("Elevated NO"[3]~"Apo", "Elevated NO"[3]~"Sym","Background NO"[3]~"Apo","Background NO"[3]~"Sym"), values=c(19, 17, 1, 2)) +
  ylim(2.8,4.5) +
  scale_x_continuous(expand = c(0, .2), limits = c(1,NA),breaks=seq(0,10,by=1)) + 
  scale_y_continuous(breaks=seq(2.75,4.25, by=0.25))


gg_nitrate_PES_4
ggsave(file="Figures/gg_nitrate_PES_4.svg", plot=gg_nitrate_PES_4, device='svg')
ggsave(file="Figures/gg_nitrate_PES_4.png", plot=gg_nitrate_PES_4)

```

```{r Visualizations of PES -- FED ONLY }

#subset JUST fed corals
pes_all.data_gg_FED <- pes_all.data_gg %>%
  filter(food=="F")

#sum by TEMPERATURE AND SYM STATE
sum_nitrate_FED<- summarySE(pes_all.data_gg_FED, measurevar = "PES_value", groupvars = c("NO3_category_sym_state", "PES_day", "temp"), na.rm=T)
gg_nitrate_PES_FED <-ggplot(data = sum_nitrate_FED,
       aes(x = PES_day,
           y = PES_value, col=temp, shape=NO3_category_sym_state, group=interaction(NO3_category_sym_state, temp))) +
    geom_point(size = 6, position = position_dodge(width  = 0.85)) +
 geom_line(linewidth = 1, position = position_dodge(width = 0.85), linetype = "dotted") +
   geom_errorbar(aes(ymin=PES_value-se, ymax=PES_value+se), width = 1.4, linewidth = 0.8, position = position_dodge(width = 0.85)) +
    ggtitle ("Polyp Exension Score for FED corals- Average by symbiotic state, temperature, and nitrate level") +
theme_classic() +
 theme(legend.position = "right",  
        axis.title.x = element_blank(),
        axis.title.y = element_blank(),  
       axis.text = element_text(size = 18),
       axis.text.x = element_text(size = 18, vjust=-1),
        text = element_text(family = "serif", size=20)) +
    labs(x = "Day of experiment", 
         y = expression(paste("Average Polyp Exension Score"))) +
       # theme(legend.position="none")+
   scale_color_manual("Temperature", labels=c("20°C","29°C"), values=c("dodgerblue", "darkred")) +
  scale_shape_manual("Treatment", labels=c("Elevated NO"[3]~"Apo", "Elevated NO"[3]~"Sym","Background NO"[3]~"Apo","Background NO"[3]~"Sym"), values=c(19, 17, 1, 2)) +
  scale_x_continuous(expand = c(0, .2), limits = c(1,NA),breaks=seq(0,10,by=1)) + 
  #scale_y_continuous(breaks=seq(2.75,4.75, by=0.25))
  ylim(2.5,4.5)


gg_nitrate_PES_FED
ggsave(file="Figures/gg_nitrate_PES_FED.svg", plot=gg_nitrate_PES_FED, device='svg')
ggsave(file="Figures/gg_nitrate_PES_FED.png", plot=gg_nitrate_PES_FED)

```

```{r visualizations of PES -- STARVED only}

#subset JUST STARVED corals
pes_all.data_gg_STARVED <- pes_all.data_gg %>%
  filter(food=="S")

#sum by TEMPERATURE AND SYM STATE
sum_nitrate_STARVED<- summarySE(pes_all.data_gg_STARVED, measurevar = "PES_value", groupvars = c("NO3_category_sym_state", "PES_day", "temp"), na.rm=T)
gg_nitrate_PES_STARVED <-ggplot(data = sum_nitrate_STARVED,
       aes(x = PES_day,
           y = PES_value, col=temp, shape=NO3_category_sym_state, group=interaction(NO3_category_sym_state, temp))) +
    geom_point(size = 4.5, position = position_dodge(width  = 0.85)) +
 geom_line(linewidth = 1, position = position_dodge(width = 0.85), linetype = "dotted") +
   geom_errorbar(aes(ymin=PES_value-se, ymax=PES_value+se), width = 1, linewidth = 0.8, position = position_dodge(width = 0.85)) +
    ggtitle ("Polyp Exension Score for STARVED corals- Average by symbiotic state, temperature, and nitrate level") +
theme_classic() +
 theme(legend.position = "right",  
        axis.title.x = element_blank(),
        axis.title.y = element_blank(),  
       axis.text = element_text(size = 18),
       axis.text.x = element_text(size = 18, vjust=-1),
        text = element_text(family = "serif", size=20)) +
    labs(x = "Day of experiment", 
         y = expression(paste("Average Polyp Exension Score"))) +
       # theme(legend.position="none")+
   scale_color_manual("Temperature", labels=c("20°C","29°C"), values=c("dodgerblue", "darkred")) +
  scale_shape_manual("Treatment", labels=c("Elevated NO"[3]~"Apo", "Elevated NO"[3]~"Sym","Background NO"[3]~"Apo","Background NO"[3]~"Sym"), values=c(19, 17, 1, 2)) +
  scale_x_continuous(expand = c(0, .2), limits = c(1,NA),breaks=seq(0,10,by=1)) + 
  ylim(2.5,4.5)
  #scale_y_continuous(breaks=seq(2.75,4.75, by=0.25))


gg_nitrate_PES_STARVED
ggsave(file="Figures/gg_nitrate_PES_STARVED.svg", plot=gg_nitrate_PES_STARVED, device='svg')
ggsave(file="Figures/gg_nitrate_PES_STARVED.png", plot=gg_nitrate_PES_STARVED)

```
```

