---
title: "Water quality of jars - data from Bigelow labs"
output: html_notebook
editor_options: 
  chunk_output_type: inline
---

```{r add packages}
library("lme4")
#install.packages("lmerTest")
library("lmerTest")
#install.packages("emmeans")
library("emmeans")
#install.packages("pbkrtest")
library("pbkrtest")
#reshape melts our datasets in the way we want
library("reshape2")
library("dplyr")
library("plyr")
library("tidyverse")
library("Rmisc")
library("ggplot2")
#multiple response variables 
#check model with performance package
  #model tools R markdown
  #check for colinearity
  #r squared figures
#install.packages("performance")
#install.packages(c("rlang", "ggplot2", "performance", "dplyr", "ggrepel", "see"), dependencies = TRUE)
library("performance")
#install.packages("see")
library("see")
#install.packages("ggrepel")
library("ggrepel")
#install.packages("sjPlot") #for visualizing linear models
library(sjPlot)
library(car)
#gg effects

#increase the number of results it will show
options(max.print=1000000)
```


```{r upload data }
#upload data
water_qual_bigelow_3A <- read.csv("bigelow_water_quality_3A_run.csv", header=TRUE, sep=",",stringsAsFactors = FALSE)
water_qual_bigelow_3A$treatment_ID<-as.factor(water_qual_bigelow_3A$treatment_ID)
water_qual_bigelow_3A$temp<-as.factor(water_qual_bigelow_3A$temp)

```

```{r visualizations - nitrate}

#lets try those tidy skills
water_qual_graph <- water_qual_bigelow_3A %>% 
  select("treatment_ID","NO3_INTENDED", "NO3_uM", "temp") %>% 
pivot_longer(-c(treatment_ID, temp), names_to = "variable", values_to = "value")

gg_intended_v_actual_nit <- ggplot(water_qual_graph, aes(treatment_ID, value, colour = variable, shape=temp)) + 
  scale_color_manual(values=c("black","dodgerblue")) +
  geom_point() +
  labs(color="Condition") +
  ylab("Nitrate level (uM)")+
  xlab("Treatment ID")+
  theme(axis.text.x = element_text(angle=90, vjust=.5, hjust=1)) + #this makes the x axis labels up and down instead of side to side to prevent overlapping
  ylab("Nitrate level (uM)")+
  xlab("Treatment ID")+
  ggtitle("Nitrate Levels -- Intended vs. measured")
gg_intended_v_actual_nit

```

```{r visualizations - Ammonium}
#lets try those tidy skills
water_qual_graph <- water_qual_bigelow_3A %>% 
  select("treatment_ID","NH4_INTENDED", "NH4_uM", "temp") %>% 
pivot_longer(-c(treatment_ID, temp), names_to = "variable", values_to = "value")

gg_intended_v_actual_amm <- ggplot(water_qual_graph, aes(treatment_ID, value, colour = variable, shape=temp)) + 
  scale_color_manual(values=c("black","forestgreen")) +
  geom_point() +
  labs(color="Condition") +
  ylab("Nitrate level (uM)")+
  xlab("Treatment ID")+
  theme(axis.text.x = element_text(angle=90, vjust=.5, hjust=1)) + #this makes the x axis labels up and down instead of side to side to prevent overlapping
  ylab("Nitrate level (uM)")+
  xlab("Treatment ID")+
  ggtitle("Ammonium Levels -- Intended vs. measured")
gg_intended_v_actual_amm
```

